### ISSUE TITLE
Protobuf compiler in j2objc v2.1.1 generates code with references to enum values missing from jar

### ISSUE THREAD

**Issue by safetydank** [google/j2objc#1000]
With input protobuf definition `sample.proto`:

```
syntax = "proto2";

package protobuf;

option optimize_for = LITE_RUNTIME;

message Handshake {
    required string version = 1;
    optional string android_app_version = 101;
    optional string ios_app_version = 102;
}
```

I run the protobuf compiler using `$J2OBJC/j2objc_protoc --java_out=java --j2objc_out=objc sample.proto`

The generated Java code includes references to enum values `GET_MEMOIZED_IS_INITIALIZED` and `SET_MEMOIZED_IS_INITIALIZED` for type `com.google.protobuf.GeneratedMessageLite.MethodToInvoke` that are missing in `$J2OBJC/lib/protobuf_runtime.jar` (verified missing using JD-GUI). This causes errors when using `j2objc` to translate Java source files with references to the generated protobuf Java code.

**Comment by tomball** [comment]
The "optimize for LITE_RUNTIME" option [no longer supports reflective methods in the Java protobuf runtime](https://github.com/protocolbuffers/protobuf/issues/4314). That support is now available in a separate libprotobuf-lite.jar, but there isn't a j2objc equivalent to that runtime. I recommend you remove that option from your proto file.

**Comment by safetydank** [comment]
Thanks for looking into this.
