### ISSUE TITLE
translated exceptions

### ISSUE THREAD

**Issue by gaborvass** [google/j2objc#1001]
Hi,
Maybe it would be great to mention the differences between exception concepts in Java and Objective-C.
In Cocoa exceptions mean something really bad happened and the application will terminate, meaning `__strong` variables won't be released, which could cause memory leaks.

More info:
http://clang.llvm.org/docs/AutomaticReferenceCounting.html#exceptions

Thanks,
Gabor

**Comment by FD-** [comment]
It's mentioned here: https://developers.google.com/j2objc/guides/memory-management

**Comment by gaborvass** [comment]
Missed it, sorry!
