### ISSUE TITLE
Getting file descriptor from Socket

### ISSUE THREAD

**Issue by FD-** [google/j2objc#1002]
While trying to fix an issue with my SSLSocketFactory implementation (#998), it would be great to have a way to get the actual file descriptor (the int, not the Java object wrapping it) from a Socket.
Initially, I thought I'd just use reflection, but it seems like it's disabled in the precompiled version of j2objc. Is there any other way to access the file descriptor (from a Swift subclass of a Java function)?

**Comment by antonio-cortes-perez** [comment]
I added the following two imports to the bridging header:
#import "java/net/Socket.h"
#import "java/io/FileDescriptor.h"

And this code builds successfully:
    let socket = JavaNetSocket()
    let descriptor = socket.getFileDescriptor$()!;
    let i = descriptor.getInt$();

I hope this helps.

**Comment by FD-** [comment]
Perfect, thanks so much!
