### ISSUE TITLE
Build script seems to look for the iOS SDK by the wrong folder name.

### ISSUE THREAD

**Issue by jacques-gasselin** [google/j2objc#1003]
When running 'make dist' on High Sierra the build scripts try to reference SDK versions by locations that don't exist.

2 Issues:

1. In /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/ it looks for iPhoneOS11.2.sdk, which should just be called iPhoneOS.sdk.

2. In /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/
it looks for iPhoneSimulator11.2.sdk, which should just be called iPhoneSimulator.sdk.

The workaround is simple enough, just symlink the locations, but it does seem like a bug in the build script.

**Comment by tomball** [comment]
The script in question is [scripts/sysroot_path.sh](https://github.com/google/j2objc/blob/master/scripts/sysroot_path.sh), and something is strange here since it uses Xcode's xcrun command to locate the path. Would you please run this terminal command on your system and post the results?
```
xcrun -sdk iphoneos --show-sdk-path
```
This should be the same as what sysroot_path.sh returns. If it is and you aren't able to build, you may need to reinstall Xcode.

**Comment by jacques-gasselin** [comment]
It outputs /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.4.sdk
which is the same as the sysroot_path.sh script outputs.

Still when I compile it looks for 11.2

**Comment by tomball** [comment]
Run `env` to see if your environment has SDKROOT or CONFIGURATION_BUILD_DIR defined. [make/common.mk](https://github.com/google/j2objc/blob/master/make/common.mk#L88) uses those environment variables to save the sysroot_path script result, but won't be run if CONFIGURATION_BUILD_DIR is set. If either are, run `unset SDKROOT CONFIGURATION_BUILD_DIR` to clear them. If they aren't, try running this command to run in a clean environment:
```
env -i PATH=$PATH HOME=$HOME JAVA_HOME=`/usr/libexec/java_home -v 1.8` make dist
```

**Comment by tomball** [comment]
[Cleaned up sysroot_path.sh script.](https://github.com/google/j2objc/commit/5ce55d559776e5874cf9f476a0a2b9fed019b5e3) If you are still having problems, please attach a log after building with the above env command.

**Comment by jacques-gasselin** [comment]
Thanks.
