### ISSUE TITLE
Add TYPE_USE to WeakOuter

### ISSUE THREAD

**Issue by FD-** [google/j2objc#1004]
Is there any particular reason why the WeakOuter annotation cannot be placed on fields?
AFAICT, code like this creates a reference cycle that would be fixed by that annotation:

```
class OkCache {
  final OkInternalCache internalCache = new OkInternalCache() {
    @Override public OkResponse get(OkRequest request) throws IOException {
      return OkCache.this.get(request);
    }
  }
  .
  .
  .
}
```

**Comment by antonio-cortes-perez** [comment]
The ideal syntax would be:
final OkInternalCache internalCache = new **@WeakOuter** OkInternalCache() {...}

But it is not currently supported by J2ObjC. Quote from this post:
https://j2objc.blogspot.com/2017/01/breaking-retain-cycles-with-weak-and.html

> Promote anonymous classes to inner classes. Since Java 8, it is possible to create anonymous instances with type annotations. For example: Runnable r = new @Foo Runnable() { … }; For the time being, though, J2ObjC’s @WeakOuter still needs to be backward compatible with Java 7. This means you have to promote your anonymous classes to inner classes, so you can add @WeakOuter to them.

**Comment by antonio-cortes-perez** [comment]
After a bit a research and testing, I found out that there are libraries that are using WeakOuter and that need to be Java 7 compatible. Adding TYPE_USE to WeakOuter will break these libraries. Please follow the recommendation in the previous comment.

**Comment by FD-** [comment]
I see. Thanks for the explanation!
