### ISSUE TITLE
Reintroduce support for the -processor flag

### ISSUE THREAD

**Issue by omerp** [google/j2objc#1010]
The -processor flag was [previously supported](https://github.com/google/j2objc/issues/574) by J2ObjC, and seems to have been implemented using a JDT pre-processing step, that was since [deprecated](https://github.com/omerp/j2objc/commit/bc5dbad02372242e4286f6633f1b12f3d08f9977), even though CLI documentation still seems to support it.

I've attempted to re-implemented support for it using the existing javac-based pre-processing step, would love to get your feedback on it! (would attach a PR shortly)

**Comment by omerp** [comment]
PR: #1011

**Comment by tomball** [comment]
Right, it's just a bug and not a deprecated feature. No one previously noticed because most annotation processor jars have a ServiceLoader definition.

**Comment by tomball** [comment]
As you probably noticed, all j2objc does is forward annotation flags to its
Java compiler front-end. That used to be the JDT, which was more
complicated and buggy. Now we're using javac, and when converting
accidentally missed this flag.

**Comment by omerp** [comment]
This is now fixed in master
