### ISSUE TITLE
Setting SO_NOSIGPIPE for all sockets

### ISSUE THREAD

**Issue by FD-** [google/j2objc#1012]
I'm regularly seeing my app crash due to a SIGPIPE signal. Apparently, this signal is sent when an application tries to send to an already closed socket.

Interestingly, the same code doesn't produce this signal on Android, so I guess the Android JVM somehow silently handles them. Thus, I'm suggesting to handle the signal in j2objc as well, so that code ported with j2objc doesn't produce unexpected crashes.

It seems like there are two ways to deal with these signals:

- Globally ignore them using
    `signal(SIGPIPE, SIG_IGN)`

- Setting the SO_NOSIGPIPE option on every socket

While I'm currently working around the problem using the global solution, I'm wondering whether j2objc shouldn't already set the SO_NOSIGPIPE flag on its sockets by default. Alternatively, I'm wondering how Android handles these signals, and whether that solution can be integrated into j2objc.

Please let me hear your thoughts on the issue!

**Comment by tomball** [comment]
Fixed in latest source.
