### ISSUE TITLE
SSLSocket dealloc throws exception

### ISSUE THREAD

**Issue by FD-** [google/j2objc#1016]
I've found a problem with j2objc's SSLSocket implementation. This time, luckily, it should be easy to fix:

In the current implementation, it's possible that the dealloc method throws an exception. This is due to the call to `tearDownContext` (which checks the ssl status and can throw an exception) [here](https://github.com/google/j2objc/blob/f3f34591e1aec4a80de7dd31228f73a3a23d6d46/jre_emul/Classes/com/google/j2objc/net/ssl/IosSslSocket.m#L216).

I guess the best solution would be to add a boolean parameter to tearDownContext that determines whether the checkStatus method should be called.

Please let me know what you think!

**Comment by antonio-cortes-perez** [comment]
Good point! I think it should be enough to remove the call to checkStatus in tearDownContext. A "best-effort" approach should be OK given that we are already disposing the context.

**Comment by tomball** [comment]
+1

**Comment by antonio-cortes-perez** [comment]
Fixed in latest source.
