### ISSUE TITLE
Missing armv7 symbols

### ISSUE THREAD

**Issue by mkudrnac** [google/j2objc#1018]
In new version of j2objc - 2.3 there is in change log:
```Removed obsolete 32-bit library architectures.```

So when linking I got this error:
```ld: symbol(s) not found for architecture armv7```
JRE.framework
JSR305.framework

Is this thing intentional?
Because this would drop support for a few devices which I would like to support - see attachment.

Thank you.

![jkze4](https://user-images.githubusercontent.com/12230741/49877165-1be46c80-fe25-11e8-99fa-921ebd9660d6.png)

**Comment by tomball** [comment]
That's correct, but we only removed armv7 support from the default distribution builds (they were getting too big). You can still create your own build that includes them with the [J2OBJC_ARCHS environment variable](https://github.com/google/j2objc/blob/master/make/common.mk#L67):
```
$ git clone https://github.com/google/j2objc.git
$ cd j2objc
# This is the old J2OBJC_ARCHS list. You can speed up the build by including just the builds you use:
$ export J2OBJC_ARCHS="iphone simulator macosx iphone64 watchv7k watch64 watchsimulator simulator64"
$ make -j8 all_dist
```
Generally speaking, the release builds are intended for developers who want to evaluate j2objc. Developers who release apps (or plan to) are strongly encouraged to download and build the j2objc project. This gives them the source code to debug and support their apps, and allows them to patch in new bug fixes their apps need as soon as they're pushed.

**Comment by mkudrnac** [comment]
Thank you. Can you please update the documentation? 
For example here? - https://developers.google.com/j2objc/guides/building-j2objc

**Comment by tomball** [comment]
Good idea, will do so later today.

**Comment by tomball** [comment]
Done: https://developers.google.com/j2objc/guides/building-j2objc#building_processor_architectures

**Comment by adil-hussain-84** [comment]
A suggestion: how about offering two separate zips for download in the Releases page: a “64-bit iOS architectures only” one for those who want a small download for evaluation purposes and an “all iOS architectures” one for those who don’t mind a larger download? Or does this complicate the release process?
