### ISSUE TITLE
Wrong version of protobuff_runtime.jar in J2ObjC 2.3 (cannot compile)

### ISSUE THREAD

**Issue by sarsonj** [google/j2objc#1019]
Hi,

it looks like that there is older version (3.3) of protobuff runtime, than protobuff compiler itself (3.5.1). When used I got compilation errors like:

 symbol: method setUnknownFieldsProto3(UnknownFieldSet)
/Users/sarsonj/Documents/work/ios/ttmonitor-common/protobuf/genjava/pb/Pb.java:28721: error: cannot find symbol
              if (!parseUnknownFieldProto3(
                   ^

After using JAR from protobuff 3.5.1, it works.

Thanks,

Jindrich

**Comment by antonio-cortes-perez** [comment]
Fixed in 2.3.1.
