### ISSUE TITLE
Static Integer value as new byte array length does not unbox correctly.

### ISSUE THREAD

**Issue by thesquaregroot** [google/j2objc#1031]
Given the following class:

    public class ArrayInit {
        private static Integer SIZE = 32;

        public byte[] createArray() {
            return new byte[SIZE];
        }
    }

And then running the following test case (after exposing the class to a Swift environment):

        let array = create_ArrayInit_init()
        print(array!.createArray()!.length())

The printed value is not what is expected (32) and is instead seemingly random values (e.g. 1896188416).  Sometimes it's even negative, resulting in:

    caught "JavaLangNegativeArraySizeException", "java.lang.NegativeArraySizeException"

Our assumption is that `JavaLangInteger` is not correctly being converted to a primitive integer in this context and instead we're seeing the memory location or something similar.

Changing the type of `SIZE` to a primitive `int` seems to be a valid work-around:

     private static int SIZE = 32;

**Comment by tomball** [comment]
Good catch, great test case! We should be able to fix this quickly.

**Comment by tomball** [comment]
You can see the problem by examining ArrayInit.m:
```
static JavaLangInteger *ArrayInit_SIZE;
...
return [IOSByteArray arrayWithLength:ArrayInit_SIZE];
```
The second line should be: `return [IOSByteArray arrayWithLength:[ArrayInit_SIZE intValue]];`

**Comment by antonio-cortes-perez** [comment]
Fixed in latest source code.
