### ISSUE TITLE
BSD currency is define in iOS sdk

### ISSUE THREAD

**Issue by losharik** [google/j2objc#1037]
Hello. When using the --swift-friendly flag, the currency is converted to property with the BSD name, but in iOS sdk there is already a define with the same name in header file param.h.

**Comment by antonio-cortes-perez** [comment]
Hi, you have a couple of options.
1) --swift-friendly = --static-accessor-methods --nullability --class-properties
You could try by only using --static-accessor-methods --nullability

2) If you want the benefits of class properties, you could add BSD to the list of reserved names. The property will be named BSD_. If you are using the released distribution, you can update the reserved names by updating this file 
com/google/devtools/j2objc/reserved_names.txt
in 
path_to_j2objc/lib/j2objc.jar

Here is an example of listing the file:
$  jar -tf lib/j2objc.jar | grep reserved
com/google/devtools/j2objc/reserved_names.txt

Let us know if the second option works for you and we will consider adding BSD to reserved_names.txt in the next release.

**Comment by losharik** [comment]
Second options is perfect worked.

**Comment by losharik** [comment]
> Hi, you have a couple of options.
> 
> 1. --swift-friendly = --static-accessor-methods --nullability --class-properties
>    You could try by only using --static-accessor-methods --nullability
> 2. If you want the benefits of class properties, you could add BSD to the list of reserved names. The property will be named BSD_. If you are using the released distribution, you can update the reserved names by updating this file
>    com/google/devtools/j2objc/reserved_names.txt
>    in
>    path_to_j2objc/lib/j2objc.jar
> 
> Here is an example of listing the file:
> $ jar -tf lib/j2objc.jar | grep reserved
> com/google/devtools/j2objc/reserved_names.txt
> 
> Let us know if the second option works for you and we will consider adding BSD to reserved_names.txt in the next release.

Second options is perfect worked.

**Comment by losharik** [comment]
There is also define EMPTY in the header utmpx.h
