### ISSUE TITLE
getResponseMessage of HttpURLConnection returns incorrect custom http status text

### ISSUE THREAD

**Issue by CruorVult** [google/j2objc#1039]
When server responses with custom http status text like "_401 Invalid user name or password_.", the method returns standard message "_Unauthorized_" for 401 status code, after translating to objective c.

Here an example:

[HttpURLConnection-getResponseMessage.zip](https://github.com/google/j2objc/files/3141311/HttpURLConnection-getResponseMessage.zip)

**Comment by tomball** [comment]
How is the server sending a custom http status text? The raw HTTP response doesn't have anything similar to what you describe:
```
$ curl -i --raw https://en-sales-mobile-demo.bpmonline.com/0/DataService/json/SyncReply/SelectQuery
HTTP/2 401
content-type: text/html
server: Microsoft-IIS/10.0
x-powered-by: ASP.NET
x-frame-options: SAMEORIGIN
x-content-type-options: nosniff
date: Fri, 03 May 2019 21:18:35 GMT
content-length: 1293

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
<title>401 - Unauthorized: Access is denied due to invalid credentials.</title>
<style type="text/css">
<!--
body{margin:0;font-size:.7em;font-family:Verdana, Arial, Helvetica, sans-serif;background:#EEEEEE;}
fieldset{padding:0 15px 10px 15px;}
h1{font-size:2.4em;margin:0;color:#FFF;}
h2{font-size:1.7em;margin:0;color:#CC0000;}
h3{font-size:1.2em;margin:10px 0 0 0;color:#000000;}
#header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:"trebuchet MS", Verdana, sans-serif;color:#FFF;
background-color:#555555;}
#content{margin:0 0 0 2%;position:relative;}
.content-container{background:#FFF;width:96%;margin-top:8px;padding:10px;position:relative;}
-->
</style>
</head>
<body>
<div id="header"><h1>Server Error</h1></div>
<div id="content">
 <div class="content-container"><fieldset>
  <h2>401 - Unauthorized: Access is denied due to invalid credentials.</h2>
  <h3>You do not have permission to view this directory or page using the credentials that you supplied.</h3>
 </fieldset></div>
</div>
</body>
</html>
```
What's weird is that your example shows the message you expect when run in Java, but nowhere in the OpenJDK source is the text "Invalid user name or password.", either. Do you have any idea where this text is from? I'm not familiar with HTTP/2.

**Comment by CruorVult** [comment]
To change http status text in response on the server we use [HttpResponse.StatusDescription](https://docs.microsoft.com/en-us/dotnet/api/system.web.httpresponse.statusdescription?view=netframework-4.8).

According to the specification of HTTP it calls [Reason Phrase](https://www.w3.org/Protocols/rfc2616/rfc2616-sec6.html#sec6.1.1) 

> The reason phrases listed here are only recommendations -- they MAY be replaced by local equivalents without affecting the protocol.

**Comment by tomball** [comment]
I'm confused. First, HttpResponse is a .NET class. Second, there's no such phrase in the raw response text I posted above -- regardless of what platform your server uses, the HTTP response should show that phrase in the results, right?

**Comment by CruorVult** [comment]
HttpResponse.StatusDescription it is an example how to set individual reason phrase "Invalid user name or password." instead of "Unauthorized" for 401 status on server response. It is answer for question:
> How is the server sending a custom http status text?

To get this response using curl please set version of http 1.1 and required headers:

```
$ curl -i --raw --http1.1 -H "X-Requested-With: XMLHttpRequest" -H "Authorization: Cookie" https://en-sales-mobile-demo.bpmonline.com/0/DataService/json/SyncReply/SelectQuery
HTTP/1.1 401 Invalid user name or password.
Content-Type: text/html
Server: Microsoft-IIS/10.0
X-Powered-By: ASP.NET
X-Frame-Options: SAMEORIGIN
X-Content-Type-Options: nosniff
Date: Sun, 05 May 2019 09:56:48 GMT
Content-Length: 1293

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
<title>401 - Unauthorized: Access is denied due to invalid credentials.</title>
<style type="text/css">
<!--
body{margin:0;font-size:.7em;font-family:Verdana, Arial, Helvetica, sans-serif;background:#EEEEEE;}
fieldset{padding:0 15px 10px 15px;} 
h1{font-size:2.4em;margin:0;color:#FFF;}
h2{font-size:1.7em;margin:0;color:#CC0000;} 
h3{font-size:1.2em;margin:10px 0 0 0;color:#000000;} 
#header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:"trebuchet MS", Verdana, sans-serif;color:#FFF;
background-color:#555555;}
#content{margin:0 0 0 2%;position:relative;}
.content-container{background:#FFF;width:96%;margin-top:8px;padding:10px;position:relative;}
-->
</style>
</head>
<body>
<div id="header"><h1>Server Error</h1></div>
<div id="content">
 <div class="content-container"><fieldset>
  <h2>401 - Unauthorized: Access is denied due to invalid credentials.</h2>
  <h3>You do not have permission to view this directory or page using the credentials that you supplied.</h3>
 </fieldset></div>
</div>
</body>
</html>
```

**Comment by tomball** [comment]
Thanks for your patience (compiler guys are rarely networking experts :-). So the real issue is that IosHttpUrlConnection doesn't copy optional message text from the HTTP/1.1 header into its status response header. I see where JRE code does that, so it should be a straightforward fix.

**Comment by tomball** [comment]
Bad news: iOS (NSURLConnection) doesn't provide access to the Reason Phrase from an HTTP status line ([StackOverflow #1](https://stackoverflow.com/questions/6372047/can-i-access-reason-phrase-from-the-http-status-line-in-nshttpurlresponse), [#2](https://stackoverflow.com/questions/21859791/ios-obj-c-get-http-status-code-response-message-reason-phrase?rq=1)), nor the raw response header. [IosHttpUrlConnection therefore recreates the status line](https://github.com/google/j2objc/blob/master/jre_emul/Classes/com/google/j2objc/net/IosHttpURLConnection.java#L611) you're seeing using [the recommended reason phrases from RFC 2616](https://www.w3.org/Protocols/rfc2616/rfc2616-sec6.html). It's the best we can do, given this iOS API limitation.

NSHTTPURLResponse does return all headers, though, so they're available to Java classes on Android or iOS. Therefor, an alternative approach you can try is to define a custom response header with the status text.

**Comment by CruorVult** [comment]
Thank you Tom!
I'm not surprised that apple developers ignoring some w3 standards :)
