### ISSUE TITLE
GetPrimitiveArrayCritical bug with IOSLongArray

### ISSUE THREAD

**Issue by jgartman** [google/j2objc#1041]
I think I've run into a bug while trying to use `GetPrimitiveArrayCritical` with an IOSLongArray.  I've created a small example app that should reproduce the issue, please let me know if you have any difficulty building or running it.

https://github.com/jgartman/IOSLongArrayIssue

Basically the example consists of a small Java class that creates an int and a long array and then passes them to a native function:
```
class TestClass{

	public void testFunc(){
		int [] intArray = {1234};
		long [] longArray = {1234L};

		nativeTestFunc(intArray, longArray);
	}

	private static native void nativeTestFunc(int [] intArray, long[] longArray);
}
```

The native function then uses `GetPrimitiveArrayCritical` to get a pointer to the arrays:
```
#include "jni.h"

#ifdef __cplusplus
extern "C" {
#endif
    
    void Java_TestClass_nativeTestFunc(JNIEnv *_env_, jclass _cls_, jarray intArray, jarray longArray){
        jboolean intArrayIsCopy;
        jint* intArrayPtr = (jint*)_env_->GetPrimitiveArrayCritical(intArray,&intArrayIsCopy);
        jboolean longArrayIsCopy;
        jlong* longArrayPtr = (jlong*)_env_->GetPrimitiveArrayCritical(longArray, &longArrayIsCopy);
        
        int integer = intArrayPtr[0];
        long long_ = longArrayPtr[0];
    }
    
#ifdef __cplusplus
}
#endif
```
The problem I'm having is that with the translated code the values in the long array appear to be incorrect.  In the screenshot below the int has a value of 1234 which matches what it was set to originally in Java while the long has value 529989643264

<img width="1440" alt="Screen Shot 2019-05-06 at 9 25 36 AM" src="https://user-images.githubusercontent.com/12043806/57266508-358f8600-704a-11e9-9f12-47b64dc15869.png">

It looks like the underlying cause of this might possibly be related to the cast to IOSByteArray that occurs [here](https://github.com/google/j2objc/blob/master/jre_emul/Classes/jni.m#L192).  The cast assumes that the buffer for all primitive arrays is at the same offset from the objects base address.  However, in this example the IOSLongArray has it's buffer offset by 16 bytes whereas it's only at 12 bytes for the IOSIntArray:

<img width="1440" alt="Screen Shot 2019-05-06 at 9 24 17 AM" src="https://user-images.githubusercontent.com/12043806/57266691-10e7de00-704b-11e9-9ada-ed22a5a79118.png">

Please let me know if there is any additional information you need or if you are unable to reproduce this issue on your end.

Thanks.

**Comment by tomball** [comment]
Thanks for your detailed test and analysis. I think you're right about it being an alignment issue, especially since this code was written before 64bit was the default.

I think adding a buffer property to IOSPrimitiveArray which is implemented by each subclass should address this, as it will return the correct address without GetPrimitiveArrayCritical needing to know what the array type is. Sound reasonable?

**Comment by jgartman** [comment]
@tomball Thanks so much for your quick response, that sounds great to me.

**Comment by tomball** [comment]
It's an alignment issue: long and double array buffer addresses are 16 bytes from the object address, while the other array types are 12 bytes.

**Comment by jgartman** [comment]
Thanks @tomball, I just tried out a version with your fix and I can't reproduce the bug anymore.  Great project and I really appreciate the support on this issue.

**Comment by tomball** [comment]
Thanks for verifying the fix.
