### ISSUE TITLE
Out of memory when translate to Objective C code

### ISSUE THREAD

**Issue by tranleduy2000** [google/j2objc#1042]
Since Java and Objective C have different memory management, I have memory problem when translate to Objective C code. The code works perfectly in JVM, it only cost 100MB when running but it cost **3.85GB** when running on iOS devices 

I am going to describe about it:
Now let's write a simple Java code, it demonstrates for the program need a lot of memory to execute.
```Java
package com.example.myapplication;

public class Foo {

    public void bar() {

        for (int i = 0; i < 100000; i++) {
            int[] fooBar = new int[10000];

            // avoid compiler warning
            fooBar[1] = 0;
            System.out.println(fooBar[1]);
        }

    }
}

```

Open Android profiler with sample Android app below:
```Java
package com.example.myapplication;

import android.os.Bundle;
import android.support.v7.app.AppCompatActivity;

public class MainActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        new Thread(new Runnable() {
            @Override
            public void run() {
                new Foo().bar();

                try {
                    Thread.sleep(1000 * 60);
                } catch (Exception e) {
                    e.printStackTrace();
                }
                System.out.println("Completed");
            }
        }).start();
    }
}

```

![image](https://user-images.githubusercontent.com/19369448/57567593-f2e0fb80-7405-11e9-8e83-98b113d1320e.png)

The image below shows that memory usage do not increase too much because Java's garbage collector clean the memory of array `fooBar` immediately after complete one iteration of for loop (no variable references to `fooBar`)

Now I translate this Java code to ObjC and run it in iOS simulator

```ObjectiveC
// ...

@implementation ComExampleMyapplicationFoo

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ComExampleMyapplicationFoo_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (void)bar {
  for (jint i = 0; i < 100000; i++) {
    IOSIntArray *fooBar = [IOSIntArray arrayWithLength:10000];
    *IOSIntArray_GetRef(fooBar, 1) = 0;
    [((JavaIoPrintStream *) nil_chk(JreLoadStatic(JavaLangSystem, out))) printlnWithInt:IOSIntArray_Get(fooBar, 1)];
  }
}
@end
// ...
```

```Swift
import UIKit

class ViewController: UIViewController {

    override func viewDidLoad() {
        super.viewDidLoad()
       
        DispatchQueue(label: "abc").async {
            ComExampleMyapplicationFoo().bar();
            
            usleep(1000000 * 30)
        }
    }

}
```

Open the profiler
![image](https://user-images.githubusercontent.com/19369448/57567676-28d2af80-7407-11e9-9827-24a32886ea9e.png)

We can see the memory usage increase too much (over 3.8GB). This problem occurs because the memory management of Objective C only releases object when exit `async` block (the generated code didn't use ARC, so it will create autorelease object). In general, objects in the autorelease pool are released at the end of an iteration of the main runloop. 

I found a solution that can help avoid this problem: manual using NSAutoreleasePool

Let's refactor the code
```ObjC
- (void)bar {
    for (jint i = 0; i < 100000; i++) {
        
        NSAutoreleasePool *pool = [[NSAutoreleasePool alloc] init];
        
        IOSIntArray *fooBar = [IOSIntArray arrayWithLength:10000];
        *IOSIntArray_GetRef(fooBar, 1) = 0;
        [((JavaIoPrintStream *) nil_chk(JreLoadStatic(JavaLangSystem, out))) printlnWithInt:IOSIntArray_Get(fooBar, 1)];
        
        [pool drain];
        
    }
}
```

Now rerun the application
![image](https://user-images.githubusercontent.com/19369448/57567772-83b8d680-7408-11e9-962f-b09003488aca.png)

Reference: https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/MemoryMgmt/Articles/mmAutoreleasePools.html

**Comment by antonio-cortes-perez** [comment]
Thanks for the detailed analysis. The J2ObjC annotation AutoreleasePool is provided exactly for this type of scenarios.
https://github.com/google/j2objc/blob/master/annotations/src/main/java/com/google/j2objc/annotations/AutoreleasePool.java

**Comment by danieldickison** [comment]
You’ll want to read through https://developers.google.com/j2objc/guides/memory-management

**Comment by tranleduy2000** [comment]
I didn't notice that j2objc support @Autoreleasepool annotation. Thanks for your support.
