### ISSUE TITLE
Undefined symbols for architecture arm64

### ISSUE THREAD

**Issue by vaqichowdhri** [google/j2objc#1049]
I am getting below error on my mac machine during executing "xcodebuild" command from mac terminal.

Before executing xcodebuild command i had set "linker flags" in xcconfig file, using below command:
echo 'OTHER_LDFLAGS = $(inherited)' > temp.xcconfig

**xcodebuild command:**
xcodebuild -workspace /Users/vvm/.jenkins/workspace/mic_retail_mobile_demo_PR-8-RE6PN2ZNJTX2E53GBKRXKYL2PER6CDNR7SXQSPH3PNLI3YNVFCJQ/iOSApp/XcodeProject/VMAppWithKonylib/VMAppWithKonylib.xcworkspace -scheme KRelease -xcconfig temp.xcconfig -destination generic/platform=iOS build

**Error**
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_AFHTTPResponseSerializer", referenced from:
      objc-class-ref in Nucleus(NCAPIManager.o)
  "_OBJC_CLASS_$_AFJSONResponseSerializer", referenced from:
      objc-class-ref in Nucleus(NCSessionManager.o)
      objc-class-ref in Nucleus(NCAPIManager.o)
  "_OBJC_METACLASS_$_AFHTTPSessionManager", referenced from:
      _OBJC_METACLASS_$_NCSessionManager in Nucleus(NCSessionManager.o)
  "_GMVDetectorTypeBarcode", referenced from:
      -[scannerFFI startScannerOperation:] in scannerFFI-E496C92780711593.o
  "_OBJC_CLASS_$_AFHTTPSessionManager", referenced from:
      _OBJC_CLASS_$_NCSessionManager in Nucleus(NCSessionManager.o)
  "_OBJC_CLASS_$_MTLModel", referenced from:
      _OBJC_CLASS_$_NCGenericModel in Nucleus(NCGenericModel.o)
  "_OBJC_METACLASS_$_MTLModel", referenced from:
      _OBJC_METACLASS_$_NCGenericModel in Nucleus(NCGenericModel.o)
  "_OBJC_CLASS_$_MTLJSONAdapter", referenced from:
      objc-class-ref in Nucleus(NCContent.o)
      objc-class-ref in Nucleus(NCContentManager.o)
      objc-class-ref in Nucleus(NCAPIManager.o)
      objc-class-ref in Nucleus(NCSignal.o)
  "_GMVDetectorBarcodeFormats", referenced from:
      -[scannerFFI startScannerOperation:] in scannerFFI-E496C92780711593.o
  "_GMVDetectorImageOrientation", referenced from:
      -[scannerFFI captureOutput:didOutputSampleBuffer:fromConnection:] in scannerFFI-E496C92780711593.o
  "_OBJC_CLASS_$_GMVDetector", referenced from:
      objc-class-ref in scannerFFI-E496C92780711593.o
  "_OBJC_CLASS_$_AFJSONRequestSerializer", referenced from:
      objc-class-ref in Nucleus(NCSessionManager.o)
  "_OBJC_CLASS_$_GMVUtility", referenced from:
      objc-class-ref in scannerFFI-E496C92780711593.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Can someone help me up with this issue, as am unaware how to resolve it.

**Comment by antonio-cortes-perez** [comment]
Are the generated classes part of your Xcode build? Note that J2ObjC converts Java source to Objective-C source. Then you have to include the generated classes when building the application.
Please check https://developers.google.com/j2objc/guides/using-j2objc-with-xcode
