### ISSUE TITLE
Xcode 11 does not build

### ISSUE THREAD

**Issue by PorterHoskins** [google/j2objc#1053]
I am trying to get JRE built from Xcode 11. I am running into this issue when I run `make frameworks`:

```
/Developer/j2objc-2.4/jre_emul/build_result/Classes/java/io/ObjectStreamClass.m:510:14: error: too many arguments to
      function call, expected 0, have 2
  return imp(newInstance, sel);
         ~~~ ^~~~~~~~~~~~~~~~
1 error generated.
```

The JRE builds fine if ran with Xcode 10 command line tools.

**Comment by SpencerBaker** [comment]
I'm having the same issue.

**Comment by antonio-cortes-perez** [comment]
This is fixed in the latest source. The specific commit is
https://github.com/google/j2objc/commit/896730452717b4c48d36d455a89057edcb2163dc
