### ISSUE TITLE
Feature Request: XCFramework distributable 

### ISSUE THREAD

**Issue by PorterHoskins** [google/j2objc#1055]
With Xcode 11, `xcodebuild` provides the `-create-xcframework` command. This packages multiple framework architectures into one distributable. This feature replaces fat-frameworks and Xcode 11 is able to provide the correct framework file based on the architecture being ran. 

A xcframework of the JRE.framework would allow all the architectures (iOS, iOS Simulator, tvOS, tvOS Simulator, MacOS, and one day iOS (UIKitForMac)) to be released as one `.xcframework` file.

**Comment by tomball** [comment]
This should address #1094.

**Comment by tomball** [comment]
Implemented in commit [cc8095a](https://github.com/google/j2objc/commit/cc8095a3ac6e7216c5d9f0dd4ad84b537ca92228) -- thanks for the suggestion.
