### ISSUE TITLE
docs: slight typo in Xcode Build Rules page

### ISSUE THREAD

**Issue by treitter** [google/j2objc#1057]
Hi,

I just noticed that, on the [Xcode Build Rules page](https://developers.google.com/j2objc/guides/xcode-build-rules), there's a typo in "Adding a J2ObjC Build Rule", steps 7 and 8. They mention `${DERIVED_FILES_DIR}` but the actual variable seems to be `${DERIVED_FILE_DIR}` (no S).

**Comment by tomball** [comment]
Thanks for the report, but both are currently set in Xcode 10.2:
```
$ xcodebuild -project JreEmulation.xcodeproj -target "jre_emul" -showBuildSettings | grep DERIVED_FILE
    DERIVED_FILES_DIR = /Users/tball/Library/Developer/Xcode/DerivedData/JreEmulation-cthpmgsdlulotqcwbtuzpoqsoerz/Build/Intermediates.noindex/JreEmulation.build/Release-iphoneos/jre_emul.build/DerivedSources
    DERIVED_FILE_DIR = /Users/tball/Library/Developer/Xcode/DerivedData/JreEmulation-cthpmgsdlulotqcwbtuzpoqsoerz/Build/Intermediates.noindex/JreEmulation.build/Release-iphoneos/jre_emul.build/DerivedSources
```
Has that changed in Xcode 11? I don't care which build setting is documented, as long as Apple doesn't remove it.

**Comment by treitter** [comment]
Not sure - I've apparently got xcodebuild 10.2 as well and don't want to upgrade it while I'm in the middle of the trickiest part of my port through j2objc :)

**Comment by tomball** [comment]
Doc updated and pushed to server today.
