### ISSUE TITLE
Translation the annotation with keyword

### ISSUE THREAD

**Issue by ChGen** [google/j2objc#1062]
I've tried to translate some Java code with j2objc 2.5, which includes Swagger annotations (io.swagger:swagger-annotations:1.5.17) and got an issue:
The annotation code fragment is:

```
package io.swagger.annotations;
//.....
public @interface ApiKeyAuthDefinition {
//...
    ApiKeyLocation in();
//....
}
```

which produces:

```
id<IoSwaggerAnnotationsApiKeyAuthDefinition> create_IoSwaggerAnnotationsApiKeyAuthDefinition(NSString *description__, IoSwaggerAnnotationsApiKeyAuthDefinition_ApiKeyLocation *inArg, NSString *key, NSString *name) {
  IoSwaggerAnnotationsApiKeyAuthDefinition *self = AUTORELEASE([[IoSwaggerAnnotationsApiKeyAuthDefinition alloc] init]);
  self->description___ = RETAIN_(description__);
  self->in_ = RETAIN_(in);
  self->key_ = RETAIN_(key);
  self->name_ = RETAIN_(name);
  return self;
}
```

In the function body of the resulting code `inArg` called `in`, which is an error, and also a reserved keywork in objc, so I get build error in XCode.

**Comment by antonio-cortes-perez** [comment]
Thanks for reporting this bug! I was able to reproduce it. I'll take a look at it.

**Comment by antonio-cortes-perez** [comment]
Fixed in latest source code. Please clone the repo and build the distribution (https://developers.google.com/j2objc/guides/building-j2objc).
