### ISSUE TITLE
Add new java.nio classes introduced in Android Oreo (26)

### ISSUE THREAD

**Issue by KirillovDenis** [google/j2objc#1064]
Attempt to translate a class that uses the `java.nio.channels.AsynchronousFileChannel` nd `java.nio.channels.CompletionHandler` fails with:

```
Main.java:1: error: cannot find symbol
import java.nio.channels.AsynchronousFileChannel;
symbol:   class AsynchronousFileChannel
location: package java.nio.channels

Main.java:2: error: cannot find symbol
import java.nio.channels.CompletionHandler;
symbol:   class CompletionHandler
location: package java.nio.channels
```

I have seen [J2OBJC Reference](https://developers.google.com/j2objc/javadoc/jre/reference/java/nio/channels/package-summary). It seems to be a JRE Emulation limitation. Will support for these classes `java.nio.channels.AsynchronousFileChannel, java.nio.channels.CompletionHandler` be added?

**Comment by tomball** [comment]
The J2ObjC JRE emulation library is heavily based on the Nougot (version 25) release of [Android's libcore library](https://android.googlesource.com/platform/libcore/), and the classes you mention were added to its Oreo (version 26) release. We're in the process now of upgrading to Oreo, and so plan on adding the new API soon.

**Comment by tomball** [comment]
Added `java.nio.file`, `java.nio.file.attribute` and `java.nio.file.spi` to [j2objc-2.7 release](https://github.com/google/j2objc/releases/tag/2.7). Sorry for closing this issue so late.
