### ISSUE TITLE
arm64e support

### ISSUE THREAD

**Issue by shradda02** [google/j2objc#1065]
I have j2objc integrated into my project and now I am trying to add arm64e support to my app. While doing this I found that j2objc (even the latest release) is not built with arm64e architecture. 
lipo -info frameworks/JRE.framework/JRE 
Architectures in the fat file: frameworks/JRE.framework/JRE are: x86_64 arm64 
lipo -info lib/libxalan.a 
Architectures in the fat file: lib/libxalan.a are: x86_64 arm64 
Due to this my build seems to have problems on adding arm64e support. Do you have any guidelines on how to add arm64e support with j2objc? Thanks!
ld: warning: ignoring file j2objc-2.5/lib/libxalan.a, missing required architecture arm64e in file j2objc-2.5/lib/libxalan.a (5 slices)

**Comment by antonio-cortes-perez** [comment]
Take a look at the section "Building Processor Architectures" in https://developers.google.com/j2objc/guides/building-j2objc

**Comment by tomball** [comment]
The "Building Processor Architectures" section refers to 32-bit slices that are defined in j2objc's build, but are not included in the distribution build. arm64e is a new architecture introduced in iOS 12, so we need to add support for it.

**Comment by tomball** [comment]
FYI, Apple wants you to test with arm64e, but doesn't distribute apps with it yet:

> App Store Connect and Testflight don’t yet accept submissions with an arm64e slice. Xcode removes this slice from your app bundle when you upload it.

[https://developer.apple.com/documentation/security/preparing_your_app_to_work_with_pointer_authentication](https://developer.apple.com/documentation/security/preparing_your_app_to_work_with_pointer_authentication?language=objc)

**Comment by tomball** [comment]
Fixed in [9ae8634](https://github.com/google/j2objc/commit/9ae8634293e77ae057c24e51d93826eb691be8d2), just not closed then.
