### ISSUE TITLE
Feature request: AddressSanitizer compatibilty

### ISSUE THREAD

**Issue by jgartman** [google/j2objc#1085]
I have AddressSanitizer enabled in the debug configuration of my app.  Since updating to j2objc2.5 from 2.0.5 the app crashes constantly in debug mode with the following exception : `'NSInvalidArgumentException', reason: '*** +[NSString stringWithUTF8String:]: NULL cString'`
```
Last Exception Backtrace:
0   CoreFoundation                	0x184312d8c __exceptionPreprocess + 228
1   libobjc.A.dylib               	0x1834cc5ec objc_exception_throw + 55
2   CoreFoundation                	0x184312c6c +[NSException raise:format:] + 115
3   Foundation                    	0x184c4c0a0 +[NSString stringWithUTF8String:] + 91
4   TestApp                        	0x10654a73c __ClassForJavaName_block_invoke + 147
5   libdispatch.dylib             	0x183c04a60 _dispatch_client_callout + 15
6   libdispatch.dylib             	0x183c37364 dispatch_once_f$VARIANT$armv81 + 59
7   TestApp                        	0x106548858 ClassForJavaName + 1239
8   TestApp                        	0x106548228 IOSClass_forName_ + 127
9   TestApp                        	0x105dd88f4 -[JavaLangSystemClassLoader loadClassWithNSString:withBoolean:] + 43
```
Steps to reproduce crash:
1) Create a Java source file and use the ObjectiveCName annotation to define a non-default name for the translated class.
2) Call a function that will call into the class loader (I happened to be using `CertificateFactory factory = CertificateFactory.getInstance("X.509");` but I'm sure there are many).
2) Run translation
3) Enable AddressSanatizer in the apps scheme.
4) Build and run the app.

I think the root of the problem is that having AddressSanitizer enabled causes empty lines to be inserted in the `__j2obc_aliases` section of the app binary.

Without AddressSanitizer enabled:
```
Joshs-MacBook-Pro:~ joshgartman$ xcrun objdump -s /path/to/test/app/TestApp.app/TestApp  --section=__j2objc_aliases

/path/to/test/app/TestApp.app/TestApp:	
	file format Mach-O arm64

Contents of section __j2objc_aliases:
 1020b15b8 a0c7ea00 01000000 20c8ea00 01000000  ........ .......
 1020b15c8 5e16fc00 01000000 6e16fc00 01000000  ^.......n.......
 1020b15d8 9e1bfc00 01000000 b21bfc00 01000000  ................
 1020b15e8 c31bfc00 01000000 d41bfc00 01000000  ................
 1020b15f8 1b97f000 01000000 0a1cfc00 01000000  ................
 1020b1608 6a65f700 01000000 ba1efc00 01000000  je..............
```

With AddressSanitizer enabled:
```
Joshs-MacBook-Pro:~ joshgartman$ xcrun objdump -s /path/to/test/app/TestApp.app/TestApp  --section=__j2objc_aliases


/path/to/test/app/TestApp.app/TestApp:
	file format Mach-O arm64

Contents of section __j2objc_aliases:
 1020b15e0 80c7ea00 01000000 00c8ea00 01000000  ................
 1020b15f0 00000000 00000000 00000000 00000000  ................
 1020b1600 00000000 00000000 00000000 00000000  ................
 1020b1610 00000000 00000000 00000000 00000000  ................
 1020b1620 5316fc00 01000000 6316fc00 01000000  S.......c.......
 1020b1630 931bfc00 01000000 a71bfc00 01000000  ................
 1020b1640 b81bfc00 01000000 c91bfc00 01000000  ................
 1020b1650 1097f000 01000000 ff1bfc00 01000000  ................
 1020b1660 5f65f700 01000000 af1efc00 01000000  _e..............
```

When the dictionary mapping from Java names to ObjC names is constructed https://github.com/google/j2objc/blob/master/jre_emul/Classes/IOSClass.m#L546, the lines of zeros are treated as null pointers and the crash occurs.  

I tried adding the attribute `__attribute__((no_sanitize("address")))` to the macro that creates the Java to ObjC name mappings https://github.com/google/j2objc/blob/master/jre_emul/Classes/J2ObjC_source.h#L95 and that seemed to fix the issue.  I'd be happy to open a PR if that's an acceptable solution.

Thanks.

**Comment by tomball** [comment]
Thanks for investigating this so thoroughly, and yes, please open a PR if you have the time. I can certainly copy your solution, but would rather that credit for the change is given to the person who did the work!

**Comment by tomball** [comment]
Thanks @jgartman for reporting this issue and providing the fix.

**Comment by jgartman** [comment]
Thanks @tomball
