### ISSUE TITLE
Mac Catalyst Support II

### ISSUE THREAD

**Issue by kangert** [google/j2objc#1095]
Thank you for your quick reply on:
https://github.com/google/j2objc/issues/1094#issue-499947538

However Catalyst would probably need a special version of the library:
`../lib/macosx/libjre_emul.a(ErrnoException.o), building for Mac Catalyst, but linking in object file built for macOS, file '/Users/admin/Documents/Workspaces/j2objc/lib/macosx/libjre_emul.a' for architecture x86_64`

**Comment by tomball** [comment]
Duplicate of reopened #1094. There's no need to refile a closed issue when adding new information, just reopen it (if you can't for some reason, we certainly will).
