### ISSUE TITLE
Example for calling iOS code from Java code translated to objc

### ISSUE THREAD

**Issue by ekuleshov** [google/j2objc#1106]
Looking for an example how to call iOS code (if at all possible) from the Java code translated into objc.

I can look into generating some kind of stubs to make the Java compiler happy about iOS api. But not sure how those api calls would look like after translation to objc.

**Comment by tomball** [comment]
Discussions/questions normally go to [StackOverflow](https://stackoverflow.com/questions/tagged/j2objc), but the short answer is documented in [Writing Native Methods](https://stackoverflow.com/questions/tagged/j2objc). While you can write short methods by embedding them with OCNI, the benefit of using JNI is that often the same native code can be used on Android and iOS. You'll find some examples [here](https://github.com/google/j2objc/tree/master/jre_emul/android/platform/libcore/ojluni/src/main/native).

**Comment by ekuleshov** [comment]
I apologize on using a wrong place for this. Though I felt this question is also a potential request for enhancement.

The "native methods" feature is basically providing a way to embed objc code  into Java or in other words - write more objc code. But I'm looking for the opposite - write less objc code and have iOS frameworks bridged/mapped with translated objc code.

I'd like to write something like this in Java:

```
public class MainController extends UIViewController //
		implements UITableViewDataSource, UITableViewDelegate, UISearchBarDelegate {
   ...
}
```

and that need to become objc code like:

```
#import <UIKit/UIKit.h>

@interface MainController : UIViewController <
		UITableViewDataSource, UITableViewDelegate, UISearchBarDelegate> {
  ...
}

```

**Comment by antonio-cortes-perez** [comment]
This sounds like a duplicate of https://github.com/google/j2objc/issues/1026

**Comment by ekuleshov** [comment]
Not really. Instead of putting objc code snippets in comments in the java code, I'l like to be able to write in my java code stuff like this:

```
UIView picker = UIView.alloc().initWithFrame(new CGRectMake(0, 0, SCREEN_WIDTH, 260));
picker.setBackgroundColor(UIColor.whiteColor());
```
so it would translate to objc like this:

```
UIView *picker = [[UIView alloc] initWithFrame:CGRectMake(0, 0, SCREEN_WIDTH, 260)];
picker.backgroundColor = [UIColor whiteColor];

```
