### ISSUE TITLE
Cookies are not set in default cookie handler during the redirection (HttpURLConnection in iOS)

### ISSUE THREAD

**Issue by kluverua** [google/j2objc#1117]
Problem:
In the iOS implementation of the HttpURLConnection class cookies are not set in default cookie handler during the redirection (in Android everything works fine).

To test this problem here is a test service https://damp-dawn-68572.herokuapp.com with method "redirect".
It sets cookie 'some_cookie=42' and redirects to method "getcook" which returns a list of cookies that came to it.
Server **Node.js** source code:
```
const express = require('express')
express().get('/getcook', (req, res) => {
	const cookie = req.headers.cookie || "";
	return res.send('Request cookies: ' + cookie.split('; '));
}).get('/redirect', (req, res) => {
	res.cookie('some_cookie', 42);
	return res.redirect('/getcook');
}).listen(5000);
```
Here is sample **JAVA** code to reproduce:

```
import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.net.CookieHandler;
import java.net.CookiePolicy;
import java.net.HttpURLConnection;
import java.net.URL;

class Main {

    public static void main(String[] args) {
        try {
            CookieHandler.setDefault(new java.net.CookieManager(null, CookiePolicy.ACCEPT_ALL));
            URL url = new URL("https://damp-dawn-68572.herokuapp.com/redirect");
            HttpURLConnection connection = (HttpURLConnection) url.openConnection();
            connection.connect();
            int code = connection.getResponseCode();
            BufferedReader br =	new BufferedReader(new InputStreamReader(connection.getInputStream()));
            StringBuilder sb = new StringBuilder();
            String output;
            while ((output = br.readLine()) != null) {
                sb.append(output);
            }
            String body = sb.toString();
            System.out.print(code);
            System.out.print(body); //Here I expect to see string "Request cookies: some_cookie=42"
            connection.disconnect();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
```

And as result translated to iOS code is "Request cookies: "
I think cookie are not set during any intermediate redirects in iOS implementation.

**Comment by tomball** [comment]
This is due to [a known iOS bug](https://forums.developer.apple.com/thread/43818). The workaround is straightforward: in IosHttpURLConnection, copy the cookies from the redirect response to the outgoing request (PR #1120).

**Comment by tomball** [comment]
Fixed in current source.

**Comment by kluverua** [comment]
> workaround is straightforward: in IosHttpURLConnection, copy the cookies from the redirect response to the outgoing request (PR #1120).

The workaround does not work when new request will be proceed using HttpURLConnection.
Problem is that method "put" of default CookieHandler does not call for each redirect, and cookies are not set to cookie store.

**Comment by FD-** [comment]
IMHO, IosHttpURLConnection will never exactly replicate the way how the HTTP stack works in Java, because it builds on iOS's native HTTP stack. However, you can always use OkHttp in a j2objc project (https://github.com/FD-/OkHttp-j2objc should get you started), which also includes an implementation of HttpURLConnection.

**Comment by j2objc-copybara** [comment]
Well, this issue had a great test case for the developer’s app need, and my
change addressed it. 100% compatibility was never claimed; as you note, the
JRE and iOS have very different network stacks, and apps that have critical
networking requirements have been implementing them natively.

Since you sound like you have a deep understanding of HTTP and HTTPS
protocol, please consider contributing improvements to the project. I’m
especially interested in your OkHttp use, since my limited understanding is
that it requires secure sockets. We’d switch to OkHttp in a heartbeat if
its tests all passed, as that would provide full Android compatibility.

**Comment by tomball** [comment]
Please submit new issues with tests that demonstrate the problem clearly
like this issue’s author did (ideally, with an analysis of what our code is
doing wrong). Compiler engineers are rarely networking experts (we
certainly aren’t), so that’s the best way to improve HTTP support.

**Comment by kluverua** [comment]
Sure! I will provide a new test case that shows an error (in a new issue).
P.S. You should roll back your commit
https://github.com/google/j2objc/commit/b67ca8f9e083b7a554d8d878efa5d9f743e0f962
because the value in the “Set-Cookie” property of the server response does not always have the correct format that is suitable for the “Cookie” in request

**Comment by tomball** [comment]
Any suggestions on how to fix it? "does not always have the correct format" doesn't describe the problem well.

**Comment by tomball** [comment]
FYI, there are not any initial cookies from iOS in a redirected request (that's the existing iOS bug), so nothing gets overwritten and why I thought it would be okay to replace the header. The only difference I see in the cookie and set-cookie specs is that set-cookie has an expires attribute -- is that what needs to be stripped?

**Comment by kluverua** [comment]
Response cookies may contain lots parameters:
<cookie-name>=<cookie-value>; Domain=<domain-value>; Secure; HttpOnly; Expires='';.......
Parameters is separated by ('; ')
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie

But request cookies should be a list of name-value pairs in the form of <cookie-name>=<cookie-value>. Pairs in the list are separated by a semicolon and a space ('; ') 
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cookie


**Example**
Response
Set-Cookie: cook1=1; Domain=somecompany.co.uk

Current behavior in request cookie will be:
Cookie: cook1=1; Domain=somecompany.co.uk
*The server interprets "Domain" as new cookie name

But should be:
Cookie: cook1=1;

**Comment by kluverua** [comment]
I have one solution in which we leave all the manipulations with the cookies to iOS.
But this solution does not take into account the case when cookie is expired, in that case we does not need to send it to server
```
NSDictionary *responseHeaders = [response allHeaderFields];
NSArray *cookies = [NSHTTPCookie cookiesWithResponseHeaderFields:responseHeaders forURL:[response URL]];
if (cookies != nil && [cookies count] > 0) {
    NSDictionary *headers = [NSHTTPCookie requestHeaderFieldsWithCookies:cookies];
    [nextRequest setAllHTTPHeaderFields:headers];
}
```

**Comment by tomball** [comment]
Thanks for the suggestion, I'll give it a try. I'll also see if java.net.HttpCookie may help here, as it has a parse() method that could be used with the Set-Cookie string.

**Comment by kluverua** [comment]
is there is opportunity to call java code here?
something like this (pseudo code):

_CookieHandler cookieHandler = CookieHandler.getDefault();
if (cookieHandler != null) {
      try {
        cookieHandler.put(uri, **[response allHeaderFields]**);
        **[nextRequest setAllHTTPHeaderFields**:cookieHandler.get(uri, **[request allHeaderFields]**);];
..._

if that available we no need to do anything

**Comment by kluverua** [comment]
i create new issue with test case https://github.com/google/j2objc/issues/1128

**Comment by tomball** [comment]
Absolutely -- after transpilation, it's all pure Objective C. :-)

Native ObjC can directly invoke Java methods, while Java calling ObjC needs to be done with the latter in a native method (so javac can compile it first). Although it's a little hidden, we have a java.util.Map wrapper for NSDictionary ([NSDictionaryMap](https://github.com/google/j2objc/blob/master/jre_emul/Classes/NSDictionaryMap.h)), so the allHeaderFields result is easily wrapped and used by transpiled Java.

**Comment by tomball** [comment]
Posting your repository and notes is very helpful -- thanks!.
