### ISSUE TITLE
Can not refer methods with array from Swift

### ISSUE THREAD

**Issue by robotan0921** [google/j2objc#1179]
I tried to use static library of Objective-c files generated by j2objc from Swift application.
But, I can not use methods with array parameters of its static library.

This is error message; 
'Value of type 'ComExampleLibSampleClass' has no member 'start''.

My code is below.
java:
`public void start(float[] position) {}`

generated objc header:
`- (void)startWithFloatArray:(IOSFloatArray *)position;`

---
In case of non-array parameter, it can be referred.
swift:
`sampleClass?.start(with: jfloat(10))`

java:
`public void start(float position) {}`

generated objc header:
`- (void)startWithFloat:(jfloat)position;`

**Comment by tomball** [comment]
The Swift importer doesn't know how to infer an array type from an Objective C signature. I recommend you instead pass in a List.

**Comment by robotan0921** [comment]
Thank you for your advice.
I understood that this is an issue of swift-objc bridging, not j2objc.
