### ISSUE TITLE
Undefined symbols for architecture arm64

### ISSUE THREAD

**Issue by ViorelOnica** [google/j2objc#1192]
Hello,

Command line javac gives me a few warnings, but XCode shows them as errors. However, the .m and .h files are generated so I copied those files in XCode, added the headers in include directory but I'm receiving the error in the picture below when I try to build.

<img width="968" alt="Screenshot 2020-01-29 at 17 01 01" src="https://user-images.githubusercontent.com/27728770/73368385-853d6e00-42b9-11ea-93c2-2cf41cdebad7.png">

**Comment by tomball** [comment]
Please use Stackoverflow.com in the future, as GitHub Issues are normally for bug reports and enhancement requests (like your request that we add java.nio.file support).

That said, it looks like the .o file was built for a different architecture than arm64. To check this, use "lipo -info <path>", which will give you a result like this (non-fat file just means the .o file is not a static library):
```
$ lipo -info ~/tmp/JUnit4Test.o
Non-fat file: /Users/tball/tmp/JUnit4Test.o is architecture: x86_64
```
If SerialComAdapter.o's architecture isn't arm64, then it needs to be built for arm64. If it is, open the .m and look for the missing symbols -- the files that j2objc generates are 100% pure Objective C sources that depend on the Foundation framework, just as if some iOS developer wrote them by hand.
