### ISSUE TITLE
I hope some of the Demo and stable development of translation tools and tool use

### ISSUE THREAD

**Issue by superLiuYiPeng** [google/j2objc#1232]
In j2objc the translation process, and without a stable translations help tool, in the gradle translation plug-in stops maintenance, is a good translation projects, please, or items now have some demo or too little information on the Internet,

**Comment by tomball** [comment]
Please use a different project, as this project is not meeting your needs. 

j2objc is a software engineering tool that works with [j2cl](https://github.com/google/j2cl) to build very-large projects with separate platform-independent, shared code. It is not the right tool for smaller apps, as the build overhead outweighs any benefits.
