### ISSUE TITLE
Allow setting of iOS Deployment target version for jre_emul [moved]

### ISSUE THREAD

**Issue by kstanger** [google/j2objc#124]
This is [Issue 124](https://code.google.com/p/j2objc/issues/detail?id=124) moved from a Google Code project.
Added on 2012-12-20T10:44:58.000Z by [schro...@gmail.com](http://code.google.comhttps://code.google.com/u/105508117981345972216/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Medium

**Comment by tomball** [comment]
Implemented.
