### ISSUE TITLE
'IOSClass.h' file not found

### ISSUE THREAD

**Issue by jiangyubao** [google/j2objc#1252]
I user flutter to create a plugin that dependency on j2objc, and here is my podspec:

` s.ios.vendored_frameworks = 'frameworks/JRE.xcframework'
  s.vendored_frameworks = 'JRE.xcframework'`
and I also copy the JRE.xcframework to frameworks directory too.

but when I run flutter build ios to build flutter example project, it can't work, and here is the error message:

`Error output from Xcode build:
↳
    ** BUILD FAILED **

Xcode's output:
↳
    /Users/jiangyb/Documents/eclipse_workspace/flutter_workspace/flutter_hyble/ios/Classes/com/itou/osgi/scc/share/fmt/impl/
    SportteryHalfFullScanerPaperFiller.m:6:10: fatal error: 'IOSClass.h' file not found
    #include "IOSClass.h"
             ^~~~~~~~~~~~
    1 error generated.
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description`

Does anyboy success to add j2objc to flutter plugins?

**Comment by tomball** [comment]
Stop filing issues for questions, especially after you ask the same question on j2objc-discuss. Issues are for bug reports and enhancement requests.
