### ISSUE TITLE
Convert Types service to injectable implementation [moved]

### ISSUE THREAD

**Issue by kstanger** [google/j2objc#134]
This is [Issue 134](https://code.google.com/p/j2objc/issues/detail?id=134) moved from a Google Code project.
Added on 2013-01-10T04:18:44.000Z by [r.w.linc...@gmail.com](http://code.google.comhttps://code.google.com/u/111080856793152167233/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Low

**Comment by tomball** [comment]
Implemented in latest source.
