### ISSUE TITLE
j2ObjC ProtoBuff implementation wrongly encodes / decodes repeated enums

### ISSUE THREAD

**Issue by sarsonj** [google/j2objc#1362]
I have this simple protobuff definition:

```proto
package comm;
option java_package = "pb";
option java_outer_classname = "PbComm";

syntax = "proto3";
enum TestEnum {
    ZERO = 0;
    ONE = 1;
    TWO = 2;
}

message TestRepeated {
    repeated TestEnum test = 1;
}
```

In java code, I just add few of TestEnums into TestRepeated message:
```java
        PbComm.TestRepeated.Builder test = PbComm.TestRepeated.newBuilder();
        test.addTest(PbComm.TestEnum.ZERO);
        test.addTest(PbComm.TestEnum.ONE);
        test.addTest(PbComm.TestEnum.TWO);


        System.out.println(test.build()); // debug print of message
        System.out.println(BaseEncoding.base64().encode(test.build().toByteArray())); // message encoded in base64 (to be able to use easily it in raw encoder)

```

Now first print shows correctly message with 3 repeated fields:
```
test: ZERO
test: ONE
test: TWO
```
Second print shows base64 encoded message, in my case it is: ```CgMAAQI=```

When you try to raw decode this message, it didn't encode it as 3 variants, but as one string. When running same code on Java / Android, the base64 encoded string processed some raw decoded shows correctly 3 variants.

See screenshot, how is this message decoded:

<img width="473" alt="Screenshot 2020-07-02 17 24 37" src="https://user-images.githubusercontent.com/925756/86377690-f1693700-bc88-11ea-91d7-982ba901f6c1.png">

**Comment by sarsonj** [comment]
For info - result from same code on Android - base64 message is ```CAAIAQgC``` and result from raw decoder looks more nicer:

<img width="400" alt="Screenshot 2020-07-02 18 39 49" src="https://user-images.githubusercontent.com/925756/86387504-90932c00-bc93-11ea-999a-af71cf415317.png">

**Comment by tomball** [comment]
I think you may have found a bug in Android's protobuf library, as I get CgMAAQI= building this with the latest Java protobuf runtime on Maven Central. Attached are my copies of your sources ([sources.zip](https://github.com/google/j2objc/files/4867150/sources.zip)); the only changes I made were to move the proto3 declaration to the top of the proto file, and added a printout of the byte array (I like that better than Base64 for debugging):

```
$ mkdir build_result
$ ~/homebrew/bin/protoc --java_out=:build_result pbcomm.proto
$ javac -d build_result -classpath ../../jars/protobuf-java-3.12.2.jar:../../jars/guava-24.0-jre.jar \
    RepeatedEnumTest.java build_result/pb/PbComm.java
$ java -classpath build_result:../../jars/protobuf-java-3.12.2.jar:../../jars/guava-24.0-jre.jar RepeatedEnumTest

debug print:
test: ZERO
test: ONE
test: TWO

base64: CgMAAQI=
bytes: [10, 3, 0, 1, 2]
```
With the j2objc protoc plugin and runtime, the same results are printed:
```
$ ~/j2objc-2.6/j2objc_protoc --j2objc_out=:build_result pbcomm.proto
$ j2objc -d build_result -classpath build_result:/Users/tball/j2objc-2.6/lib/protobuf_runtime.jar:/Users/tball/j2objc-2.6/lib/guava-25.1-jre.jar RepeatedEnumTest.java
$ j2objcc -Ibuild_result -I/Users/tball/j2objc-2.6/include/guava -lguava -lprotobuf_runtime build_result/RepeatedEnumTest.m build_result/pb/PbComm.m
$ ./a.out RepeatedEnumTest

debug print:
test: ZERO
test: ONE
test: TWO

base64: CgMAAQI=
bytes: [10, 3, 0, 1, 2]
```

**Comment by sarsonj** [comment]
Thanks. We are using lite version of protobuf on Android. This is not what we choose, but unfortunately Google libs like Crashlytics are using it and it is not possible to use lite and full in one project because of class duplications.

We will update this ticket when we will find solution (we have to find it, it is critical for us).

**Comment by sarsonj** [comment]
Hi,

so we resolved it. According to protobuf3 spec, the repeated fields are encoded as "packed repeated fields". However, the live version of protobuf library don't respect this. Also, j2objc (and probably full java version) don't decode unpacked repeated fields (I don't know, if this is bug or not - in protobuf docs is written, that "In proto3, repeated fields of scalar numeric types use packed encoding by default.", not that non packed fields are not supported).

The fix is to declare repeated field as packed. So that updated definition:
```proto
package comm;
option java_package = "pb";
option java_outer_classname = "PbComm";

syntax = "proto3";
enum TestEnum {
    ZERO = 0;
    ONE = 1;
    TWO = 2;
}

message TestRepeated {
    repeated TestEnum test = 1 [packed=true];
}
```
is now encoded same using j2objc protobuf and android protobuf.

@tomball thanks to showing me the right direction!

**Comment by tomball** [comment]
What happens if you specify proto2 syntax instead of adding the packed attribute? Although the j2objc protoc plugin doesn't check which syntax is specified (I need to fix that), it only supports proto2 because that's all the Objective C native proto runtime did. 

We'd also like to move j2objc to only supporting proto-lite, for the same reason the Android team did: the app size is smaller (both the generated proto classes and the runtime), and faster due to no reflection support (I think it also transfers fewer bytes because of that, but haven't tested that). The original protobuf design was for inter-server data transfer, not with mobile devices. Especially for smaller, slower devices the lite runtime can make a big difference.
