### ISSUE TITLE
file.getAbsolutePath() returns different paths with make or not

### ISSUE THREAD

**Issue by albertomisail** [google/j2objc#1439]
This makes MacOSXPathTest pass when `run-single-test` is used but not when `make test` is used

**Comment by tomball** [comment]
The underlying issue is that the test compares the absolute path strings from java.io.File and java.nio.file.Path, and the File code is from Apache Harmony, while Path is the latest libcore version. Updating File should resolve this, which I hope to get to next week.

**Comment by tomball** [comment]
It turns out to be a bad test somewhere (tracking it down), which is causing System.getProperty("user.dir") to change to a temporary directory, but not setting it back when the test completes.
