### ISSUE TITLE
Package prefix support should use prefixes in generated file names. [moved]

### ISSUE THREAD

**Issue by kstanger** [google/j2objc#144]
This is [Issue 144](https://code.google.com/p/j2objc/issues/detail?id=144) moved from a Google Code project.
Added on 2013-02-09T19:48:23.000Z by [tball@google.com](http://code.google.comhttps://code.google.com/u/tball@google.com/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Medium

**Comment by tomball** [comment]
Implementing this feature would break many build systems, which depend on matching input to output file names.

**Comment by adil-hussain-84** [comment]
That's a shame :-( Would have been great if the prefix applied to the file name as well as the class name.

**Comment by tomball** [comment]
That drives build systems crazy, as most of them depend upon the relative output name being the relative input name with a different prefix.
