### ISSUE TITLE
Undefined symbols for architecture arm64 > Symbol: _OBJC_CLASS_$_HKCDADocumentSample > Referenced from: __OBJC_$_CATEGORY_HKCDADocumentSample_$_serialization in HealthData.o

### ISSUE THREAD

**Issue by anusebastian** [google/j2objc#1503]
Trying to build an iOS app which is originally (built in Unity) through gitLab using CI.
Added new package for HealthKit  and endedup with error "Undefined symbols for architecture arm64 > Symbol: _OBJC_CLASS_$_HKCDADocumentSample > Referenced from: __OBJC_$_CATEGORY_HKCDADocumentSample_$_serialization in HealthData.o" while building the app. tried deleting cache pods and DerivedData .But no luck.

Thanks in Advance

**Comment by tomball** [comment]
Unity is unrelated to j2objc, and those symbols aren't generated by j2objc.
