### ISSUE TITLE
JDK not supported. Please set JAVA_HOME to JDK 1.8 or 11. I need help

### ISSUE THREAD

**Issue by gazyy1** [google/j2objc#1519]
![1606097137657](https://user-images.githubusercontent.com/34432682/99930558-7403a780-2d8c-11eb-814a-9daabda0a29f.jpg)
![1606097142818](https://user-images.githubusercontent.com/34432682/99930564-782fc500-2d8c-11eb-9f6a-68b16e415bb0.jpg)
![1606097147532](https://user-images.githubusercontent.com/34432682/99930566-7960f200-2d8c-11eb-863a-61fa8dde18f7.jpg)
@ #1515 @tomball

**Comment by Seasonswag** [comment]
还是不行啊,老哥.你呢

**Comment by tomball** [comment]
It's just a simple version test, so you can delete the whole block from line 58 through line 69.

Also, be sure to edit the same script you are actually running. Wherever path your j2objc command in Xcode has, edit that file. Editing the "j2objc.sh" script in the source base, but running the "j2objc" script in a distribution build won't fix the problem.

**Comment by Seasonswag** [comment]
> It's just a simple version test, so you can delete the whole block from line 58 through line 69.
> 
> 这只是一个简单的版本测试，因此您可以从第58行到第69行删除整个块。
> 
> Also, be sure to edit the same script you are actually running. Wherever path your j2objc command in Xcode has, edit that file. Editing the "j2objc.sh" script in the source base, but running the "j2objc" script in a distribution build won't fix the problem.
> 
> 另外，一定要编辑实际运行的脚本。无论你在 Xcode 的 j2objc 命令的路径是什么，编辑这个文件。在源代码库中编辑“ j2objc.sh”脚本，但是在分发版构建中运行“ j2objc”脚本并不能解决这个问题。

谢谢你,我尝试过,但是出现了另一个错误 : /Users/Season/Downloads/j2objc-master/dist/j2objc: /Library/Internet: No such file or directory ,the last line in j2objc.sh

**Comment by gazyy1** [comment]
> Lines 47-56 set which `java` command to use. It depends either upon using a OpenJDK or Oracle Java distribution, which you aren't, or else whatever JAVA_HOME is set to. To test whether you have JAVA_HOME set correctly by running `$JAVA_HOME/bin/java -version`, which should give you the same version as just running `java -version`. If not, figure out the top-level directory of your Java distribution, then run `export JAVA_HOME=`your-path.
> 
> There isn't a `/Library/Internet` path on Macs, instead it's `/Library/Internet Plug-Ins`. Because `Plug-Ins` was stripped off, it suggests that your PATH or JAVA_HOME environment variables are incorrectly set. Whenever you set an environment variable to a path with a space in it, the path has to be surrounded with quotes. Also, don't use the Java installed in `/Library/Internet Plug-Ins/JavaAppletPlugin.plugin`, as that path is only for Java browser applets.

I'm really sorry to bother you again, but I still haven't solved what you said
![1606291795951](https://user-images.githubusercontent.com/34432682/100200038-08ab0880-2f39-11eb-8d54-b711206ce914.jpg)
![1606291800637](https://user-images.githubusercontent.com/34432682/100200048-0ba5f900-2f39-11eb-9b78-b204ea55b53d.jpg)

**Comment by gazyy1** [comment]
> 还是不行啊,老哥.你呢

不管用 血崩好几天了

**Comment by gazyy1** [comment]
I tried to skip this judgment, but another error will be reported. I don't know where to generate the file and how to modify it.
![1606296745811](https://user-images.githubusercontent.com/34432682/100208984-4bbea900-2f44-11eb-9185-60485fbb33f3.jpg)
![1606296751352](https://user-images.githubusercontent.com/34432682/100208995-4eb99980-2f44-11eb-964d-18435f6bc0a1.jpg)

**Comment by Seasonswag** [comment]
> > 还是不行啊,老哥.你呢
> 
> 不管用 血崩好几天了

完事了,暴力解决,把JAVA_HOME设好,把j2objc.sh里直接JAVA=JAVA_HOME路径/bin/java 👌

**Comment by gazyy1** [comment]
> > > 还是不行啊,老哥.你呢
> > 
> > 
> > 不管用 血崩好几天了
> 
> 完事了,暴力解决,把JAVA_HOME设好,把j2objc.sh里直接JAVA=JAVA_HOME路径/bin/java 👌

靠谱兄弟 成了
