### ISSUE TITLE
#error "Status must not be compiled with ARC (-fobjc-arc)"

### ISSUE THREAD

**Issue by forkdog** [google/j2objc#1545]
version: 2.7
I tried to turn off arc, to run successfully. But I want to keep it open, and I don't know how to solve it.
`#include "J2ObjC_source.h"
#include "Status.h"
#include "java/lang/System.h"

#if __has_feature(objc_arc)
#error "Status must not be compiled with ARC (-fobjc-arc)"
#endif

#line 1 "/Volumes/myDisk/aReader/aReader/Java/Status.java"

#line 20
@implementation OrgJ2objcStatus

J2OBJC_IGNORE_DESIGNATED_BEGIN

#line 20
- (instancetype)init {
  OrgJ2objcStatus_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

#line 22
+ (NSString *)hello {
  return OrgJ2objcStatus_hello();
}

+ (NSString *)sayHello {
  return OrgJ2objcStatus_sayHello();
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x9, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x9, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(hello);
  methods[2].selector = @selector(sayHello);
  #pragma clang diagnostic pop
  static const J2ObjcClassInfo _OrgJ2objcStatus = { "Status", "org.j2objc", NULL, methods, NULL, 7, 0x1, 3, 0, -1, -1, -1, -1, -1 };
  return &_OrgJ2objcStatus;
}

@end

#line 20
void OrgJ2objcStatus_init(OrgJ2objcStatus *self) {
  NSObject_init(self);
}

#line 20
OrgJ2objcStatus *new_OrgJ2objcStatus_init() {
  J2OBJC_NEW_IMPL(OrgJ2objcStatus, init)
}

#line 20
OrgJ2objcStatus *create_OrgJ2objcStatus_init() {
  J2OBJC_CREATE_IMPL(OrgJ2objcStatus, init)
}

#line 22
NSString *OrgJ2objcStatus_hello() {
  OrgJ2objcStatus_initialize();
  
#line 23
  return JreStrcat("$$", @"Hello from ", JavaLangSystem_getPropertyWithNSString_(@"os.name"));
}

#line 26
NSString *OrgJ2objcStatus_sayHello() {
  OrgJ2objcStatus_initialize();
  
#line 27
  return @"Hello world !";
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgJ2objcStatus)`

**Comment by tomball** [comment]
That #error line is generated because j2objc's default is to generate code that uses reference counting, not ARC. To generate ARC code, run j2objc with the `-use-ARC` flag. This will also change the #error test to say the generated .m file "... must be compiled with ARC (-fobjc-arc)".
