### ISSUE TITLE
XCombineJars generates incomplete header paths with packages that have underscores

### ISSUE THREAD

**Issue by gregkerzhner** [google/j2objc#1556]
Greetings @tomball! 

J2ObjC is producing incomplete header paths when the XCombineJars option is enabled (and this option is always enabled with Bazel - https://github.com/bazelbuild/bazel/blob/f49c1df24df99df97153e02940d7e97202f7b87e/src/main/java/com/google/devtools/build/lib/rules/objc/J2ObjcConfiguration.java#L44
)

  This issue starts in version 2.2, and is introduced by this commit - https://github.com/google/j2objc/commit/08308ec278ae08c18e35dd0efe8c1162c30dc0fe.

The issue can be seen in the attached zip file, which contains 3 java classes.  One of the classes `BachUpsertCatalogObjectsRequest.java` imports another class `CatalogModifier.java`.

In version 2.1, when I run j2objc (on java 8) via the command:

`./j2objc  com/squareup/protos/connect/v2/merchant_catalog/resources/CatalogModifier.java com/squareup/protos/connect/v2/merchant_catalog/service/BatchUpsertCatalogObjectsRequest.java com/squareup/wiremocks/ProtoAdapter.java -d output -XcombineJars`

The generated `BachUpsertCatalogObjectsRequest.m` file imports `CatalogModifier.h` with the full path with the line
`#include "com/squareup/protos/connect/v2/merchant_catalog/resources/CatalogModifier.h"`

In version 2.2, running the same command, produces an include statement that does not have the full path:
`#include "CatalogModifier.h"`

Interestingly, other imports, such as the import for `BachUpsertCatalogObjectsRequest.m`.s own header file (`BachUpsertCatalogObjectsRequest.h`) correctly generate the full path in both versions 2.1 and 2.2.

I believe this issue https://github.com/google/j2objc/issues/1030 may also be related.  Thank you in advance for your time! 

[j2objc-bug.zip](https://github.com/google/j2objc/files/5934555/j2objc-bug.zip)

**Comment by tomball** [comment]
What's weird is that the full path is defined in CatalogModifier.m, just not in BatchUpsertCatalogObjectsRequest.m. Investigating...

**Comment by tomball** [comment]
The underlying issue is that [JavacParser.packageName()](https://github.com/google/j2objc/blob/master/translator/src/main/java/com/google/devtools/j2objc/javac/JavacParser.java#L361) wasn't allowing underscores in the package name.

**Comment by tomball** [comment]
Thanks for the clear test!
