### ISSUE TITLE
failureaccess.jar should be added to dist libs

### ISSUE THREAD

**Issue by sarsonj** [google/j2objc#1569]
It looks like that Guava 30.0 (maybe older one as well) has external dependency to failureaccess.jar. It would be nice to add this jar to dist folder after j2objc compilation to have everything together to convert Java sources.

**Comment by tomball** [comment]
[Contributions](https://developers.google.com/j2objc/guides/how-to-contribute) cheerfully accepted. ;-)

**Comment by sarsonj** [comment]
Ok, pull request #1571.

**Comment by tomball** [comment]
Thanks for your contribution.
