### ISSUE TITLE
Make fails when building from path with spaces [moved]

### ISSUE THREAD

**Issue by kstanger** [google/j2objc#159]
This is [Issue 159](https://code.google.com/p/j2objc/issues/detail?id=159) moved from a Google Code project.
Added on 2013-03-26T08:37:23.000Z by [sj1...@gmail.com](http://code.google.comhttps://code.google.com/u/114182909067816580108/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium

**Comment by tomball** [comment]
Should be fixed in latest release.
