### ISSUE TITLE
Matcher succeeds in Java but errors out in transpiled objc code

### ISSUE THREAD

**Issue by abbyThompson** [google/j2objc#1603]
There is a discrepancy between the behavior of `Matcher` in Java code v. the transpiled objc code. When the following code is run in Java, the `group` call is successful and returns `bar`. However, when the code is transpiled to objc and run, the `group` call errors out with the following: `java.lang.IllegalArgumentException: No capturing group in the pattern with the name foo (JavaLangIllegalArgumentException)`.

```
public static void main(String args[]) 
{ 
 final Pattern demoPattern = Pattern.compile("^(\\?foo=(?<foo>.+))?$");

 final String demoText = "?foo=bar";
 final Matcher m = demoPattern.matcher(demoText);
 if (!m.matches()) {
  System.out.println("Test Failed!");
  return;
 }
 final String foo = m.group("foo");
    System.out.println("Test Succeeded! foo is: " + foo); 
} 
```
[Full gist](https://gist.github.com/abbyThompson/ab7894b797e29ddc6313e09fdd7c8016)

**Comment by tomball** [comment]
Great test, should be straightforward to fix.

**Comment by tomball** [comment]
Maybe not so easy, as I tracked this down to what may be a problem in the [ICU](http://site.icu-project.org/) library in iOS. Named capture groups are supposed to be [supported in ICU](http://site.icu-project.org/design/regular-expressions/named-capture-groups) from version 55, which released in IOS a few years ago. I'll double-check that we're setting up the native regex instance correctly.

**Comment by abbyThompson** [comment]
@tomball thanks for the update!

**Comment by tomball** [comment]
Fixed: the native regex code was calling an ICU function with a string when it expected an array of UChars. Thanks for reporting this!

To get this change, do a git pull of this repository and then [build it](https://developers.google.com/j2objc/guides/building-j2objc).

**Comment by abbyThompson** [comment]
Thanks so much for the speedy fix @tomball !

**Comment by tomball** [comment]
BTW, if your team has a released iOS app that uses J2ObjC, we'll happily add it to [our list](https://developers.google.com/j2objc/guides/projects-that-use-j2objc). It's free marketing!
