### ISSUE TITLE
Early release

### ISSUE THREAD

**Issue by hkjels** [google/j2objc#1613]
Version 2.7 is not compatible with M1 Mac's, but `HEAD` seems stable and works. Would it be feasible to cut an early release with just the fixes that are already in place?

**Comment by tomball** [comment]
Good idea. We don't have a fixed schedule, but instead release a
distribution bundle whenever there has been enough change to justify it.
Adding M1 support seems like a big enough "chunk." :-)

One issue we've hit recently, which a new release makes worse, is that
GitHub has a maximum binary size we can upload, and we've had to rework the
bundle so it will fit (those XCFrameworks take a lot of space). One
experiment that looks promising is to run Proguard on the j2objc and
cycle_finder jars. Assuming that reduces the bundle size enough, it'll
likely take a week or so to update the build, its docs, and test the new
bundle.

**Comment by hkjels** [comment]
Sounds challenging. I'll cross fingers for Proguard yielding the required reductions and looking forward to the release. Thanks for the quick reply!

**Comment by tomball** [comment]
FYI, there's no magic to a release bundle, it's just a convenience for new j2objc users. To make your own at any time, clone the j2objc repository, install protocol buffers (`brew install protobuf` is easiest), then run [scripts/build_distribution.sh](https://github.com/google/j2objc/blob/master/scripts/build_distribution.sh).
