### ISSUE TITLE
Build script doesn't delete /tmp/jre_emul [moved]

### ISSUE THREAD

**Issue by kstanger** [google/j2objc#163]
This is [Issue 163](https://code.google.com/p/j2objc/issues/detail?id=163) moved from a Google Code project.
Added on 2013-04-03T11:18:09.000Z by [sj1...@gmail.com](http://code.google.comhttps://code.google.com/u/114182909067816580108/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium

**Comment by tomball** [comment]
Fixed.
