### ISSUE TITLE
Equals and hashcode overridden by default implementation for subclasses of subclasses of Number

### ISSUE THREAD

**Issue by jack-nolan** [google/j2objc#1645]
In 3a8c31b681d3731203ebdc60bf76b49f7f3eec94, a check was added to add `equals` and `hashcode` to subclasses of `Number` if they are not declared by the subclass. But if a subclass of `Number` overrides `equals` and `hashcode`, and a subclass of that subclass does not override `equals` and `hashcode`, the defualt implementation of `equals` and `hashcode` is still added to the subclass of the subclass. It seems like a good fix to this would be to only add the `equals` and `hashcode` to direct subclasses of `Number`.

##### Java
```
public class ClassA extends Number {
  private final int value;

  public ClassA(int value) {
    this.value = value;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o)
      return true;
    if (!(o instanceof ClassA))
      return false;
    ClassA classA = (ClassA)o;
    return Objects.equals(value, classA.value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(value);
  }

  public class ClassB extends ClassA {
    public ClassB(int value) {
      super(value);
    }
  }
  ...
}
```
##### Transpiled equals and hashcode for ClassB
```
- (jboolean)isEqual:(id)obj {
  return self == obj;
}

- (NSUInteger)hash {
  return (NSUInteger)self;
}
```
When transpiled, ClassA uses the transpiled `equals` and `hashcode`. In ClassB they are overriden by default implementations instead of inheriting from ClassA.

The following evaluates to true in Java, but false when transpiled.
```
Objects.equals(new ClassB(1), new ClassB(1));
```

**Comment by tomball** [comment]
Fixed in [6c979b8](6c979b8dea4236b3a0d3c062dbee59172afd6a54).
