### ISSUE TITLE
Support of Mac Catalyst on Apple Silicon

### ISSUE THREAD

**Issue by kangert** [google/j2objc#1698]
J2ObjC frameworks now support Apple Silicon (macOS ARM64) in the latest j2objc version, but that doesn't seem to be the case for Mac Catalyst.  

**... building for Mac Catalyst-arm64 but attempting to link with file built for Mac Catalyst-x86_64**

**Comment by tomball** [comment]
I don't have access to any M1 hardware so far (as you can imagine, there's a huge demand within Google engineering for it, and our tiny project is way down the priority list). We've therefore relied on pull requests from developers like yourself, such as PR #1685. [Here is the contributing doc](https://developers.google.com/j2objc/guides/how-to-contribute), in case you can help.

**Comment by kangert** [comment]
Unfortunately, I'm in the same situation regarding this - but since in my case it's a small project, I would leave it in the hands of M1 users in TestFlight - I understand that in the case of j2objc, personal experience is needed :). So I can only wish you to receive this toy as soon as possible :).

**Comment by tomball** [comment]
Thanks! I may try to convince my wife I need a personal M1 Mac Mini, but it
will be a tough sell after 13 years of Google paying for my equipment. 🙂

**Comment by hohteri** [comment]
Sorry to jump here but Mac catalyst is built for arm64 with the PR #1685 

`MacBook-Pro-13:j2objc hohteri$ lipo -info dist/lib/maccatalyst/libjre_emul.a 
Architectures in the fat file: dist/lib/maccatalyst/libjre_emul.a are: x86_64 arm64`

`MacBook-Pro-13:j2objc hohteri$ ls -l dist/frameworks/JRE.xcframework/
Headers/                      Versions/                     ios-arm64_x86_64-maccatalyst/ macos-arm64_x86_64/           watchos-i386-simulator/       
Info.plist                    ios-arm64/                    ios-arm64_x86_64-simulator/   watchos-arm64_32/ `

The binary distribution of j2objc 2.8 does not contain these builds, so you need to build it yourself.

**Comment by kangert** [comment]
Quite an interesting service:
https://www.scaleway.com/en/hello-m1/

**Comment by hohteri** [comment]
@tomball @kangert I’d assume this issue can be closed since the PR has been merged?

**Comment by tomball** [comment]
Yes, AFAIK this closes the issue. I still don't have an M1/M2 to verify it, though. :-(
