### ISSUE TITLE
Float precision loss 

### ISSUE THREAD

**Issue by rammuralidhar** [google/j2objc#1700]
When ever we do:
[JavaLangFloat valueOfWithNSString:"0.5"] 
I inspect the float generated in XCode. The NSNumber behind float is 0.5

[JavaLangFloat valueOfWithNSString:"0.3"] 
I inspect the float generated in XCode. The NSNumber behind float is 0.3000002

The floats are losing precision. Is this expected behavior

**Comment by tomball** [comment]
j2objc uses the same floating point support as Android and OpenJDK: [sun.misc.FloatingDecimal](https://github.com/google/j2objc/blob/master/jre_emul/android/platform/libcore/ojluni/src/main/java/sun/misc/FloatingDecimal.java). This ensures that **Java** parsing behaves the same across platforms. That doesn't mean it's identical to how NSNumber defines floating point, as there are subtle differences. 

If you need the Java definition of floating point, use java.lang.Float and Double; but if you need the iOS definition, use NSNumber.
