### ISSUE TITLE
Multiple setters created for static variables [moved]

### ISSUE THREAD

**Issue by kstanger** [google/j2objc#175]
This is [Issue 175](https://code.google.com/p/j2objc/issues/detail?id=175) moved from a Google Code project.
Added on 2013-05-06T15:13:49.000Z by [mbastr...@gmail.com](http://code.google.comhttps://code.google.com/u/116154106651256276405/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium

**Comment by tomball** [comment]
Fixed.
