### ISSUE TITLE
Google GSON library translates, but unable to successfully use it

### ISSUE THREAD

**Issue by sardarasmita** [google/j2objc#1750]
I am trying to get Gson through j2objc such that I can use it for my iOS swift framework. I am using J2ObjC 2.8 and GSON 2.8.5. and all the classes are translating correctly. However, while running the tests, I cannot successfully convert the data using GSON as the function throws the error. For every Gson function I use I get the error **java.lang.ArrayStoreException: attempt to add object of type java.util.Formatter$FixedString to array with type java.util.Formatter$FormatString (JavaLangArrayStoreException)**

**Comment by tomball** [comment]
I downloaded the GSON 2.8.5 source.zip, unzipped it, ran Maven to generate a Java source file, then ran:
```
$ mvn test   # generates GsonBuildConfig.java
$ j2objc -classpath ~/j2objc/dist/lib/j2objc_junit.jar -d build_output \
    -sourcepath src/main/java:src/test/java:target/generated-sources/java-templates \
    `find src/main/java src/test/java -name '*.java'`
     target/generated-sources/java-templates/com/google/gson/internal/GsonBuildConfig.java
$ j2objcc -o unit-tests -ljre_emul -ljunit -Ibuild_output `find build_output -name '*.m'` -ObjC
$ ./unit-tests org.junit.runner.JUnitCore com.google.gson.GsonTest
JUnit version 4.13.1
..
Time: 0.002

OK (2 tests)
```
(Unfortunately, GSON doesn't have any Suite classes defined, so each test needs to be run separately.)

I searched the GSON source for any references to either ArrayStoreException or Formatter, but there aren't any. 

Please attach a short test class that demonstrates this problem.

**Comment by sardarasmita** [comment]
### This is the converted objc code

```
- (ComModel *)getAuthorizationSessionDataWithComAuthRequest:(ComAuthRequest *)authorizationSessionRequest {
  ComModel *response = nil;
  ComGoogleGsonGson *diagData = new_ComGoogleGsonGson_init();
  response = new_ComModel_init();
  [response setVinWithNSString:[((ComAuthRequest *) nil_chk(authorizationSessionRequest)) getVin]];
  [response setBodyWithNSString:[authorizationSessionRequest getBody]];
  [response setDtcsWithNSString:[diagData toJsonWithId:[authorizationSessionRequest getDtcs]]];
  return response;
}
```

### This is the function that calls the above function  which is in swift

```
    func checkGson() -> ComDtcModel{
        let authRequest = ComAuthRequest()
        authRequest?.setVinWith("vin")
        authRequest?.setBodyWith("body")
        let dtc = ComRequest()
        dtc?.setNameWith("name")
        dtc?.setDescriptionWith("description")
        dtc?.setEcuNameWith("ecu")
        let listArr = JavaUtilListImpl().convertArraytoJavaUtilList(list: [dtc!])
        authRequest?.setDtcsWith(listArr)
        let response = ComAuthService().getAuthorizationSessionData(with: authRequest)
        return response ?? ComDtcModel()
    }
}
```

### Below is the test case

 ```
func testGson(){
        let response = Service().checkGson()
        XCTAssertNotNil(response)
 }
```

### ERROR: 
**java.lang.ArrayStoreException: attempt to add object of type java.util.Formatter$FixedString to array with type java.util.Formatter$FormatString (JavaLangArrayStoreException)**

**Comment by tomball** [comment]
I need a self-contained test, not fragments from your app. Here's what I could disassemble:
```
import com.google.gson.Gson;
import java.util.Arrays;
import java.util.List;

public class GsonTest {

  static class ComRequest {
    private String name;
    private String description;
    private String ecuName;

    public String getName() { return name; }
    public void setName(String name) { this.name = name; }
    public String getDescription() { return description; }
    public void setDescription(String description) { this.description = description; }
    public String getEcuName() { return ecuName; }
    public void setEcuName(String ecuName) { this.ecuName = ecuName; }


  }

  public static void main(String... args) {
    ComRequest dtc = new ComRequest();
    dtc.setName("name");
    dtc.setDescription("description");
    dtc.setEcuName("ecu");
    List<ComRequest> listArr = Arrays.asList(dtc);
    Gson gson = new Gson();
    String json = gson.toJson(listArr);
    System.out.println(json);
  }
}
```
This runs the same with Java and natively:
```
tball@tball-macbookpro:tmp$ javac -classpath ~/Downloads/gson-2.8.5.jar GsonTest.java
tball@tball-macbookpro:tmp$ java -classpath ~/Downloads/gson-2.8.5.jar:. GsonTest
[{"name":"name","description":"description","ecuName":"ecu"}]
tball@tball-macbookpro:tmp$ j2objc -classpath ~/Downloads/gson-2.8.5.jar GsonTest.java
tball@tball-macbookpro:tmp$ j2objcc -o gson-test -I. -I ~/src/gson/build_output -L ~/src/gson/build_output -lgson GsonTest.m
tball@tball-macbookpro:tmp$ ./gson-test GsonTest
[{"name":"name","ecuName":"ecu","description":"description"}]
```
Perhaps the issue is with `JavaUtilListImpl().convertArraytoJavaUtilList(list: [dtc!])`, which appears to be a utility method of yours (though `List<ComRequest> listArr = Arrays.asList(dtc);` seems simpler and more type-safe).

Another thing to consider is not using GSON, if all you're using it for is for diagnostics. The J2ObjC distribution includes Android's [org.json library](https://developers.google.com/j2objc/javadoc/android/reference/org/json/package-summary), which is simpler to use.

Regardless, I can't proceed without a failing Java test, as j2objc is a Java compiler and runtime. Please reopen if you can attach such a test, so we have something to investigate and use to verify the issue has been fixed.

**Comment by sardarasmita** [comment]
Java Code 

```
public class Request {
    private String name;
    private String description;

    public void setName(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    
    public String getDescription() {
        return description;
    }    
}
```

```
public class AService {
	public String getGsonString(Request request) {
		Gson gson = new Gson();
		return gson.toJson(request);
	}
}

```
I am using the converted code of the above code to run the test case in the swift project
```
func testGsonString(){
        let request = ComRequest()
        request?.setNameWith("name")
        request?.setDescriptionWith("description")
        let response = ComAService().getGsonString(with: request!)
        XCTAssertNotNil(response)
    }

```
While running the above code, **The ComAService().getGsonString(with: request!)** throws error

I have used j2objc-maven-plugin 1.1.4 for conversion and gson  2.8.5.

<img width="1743" alt="Screenshot 2021-08-24 at 3 54 31 PM" src="https://user-images.githubusercontent.com/89202330/130604735-578ae5d5-ce31-4386-8c4f-22251c606b19.png">

<img width="1527" alt="Screenshot 2021-08-24 at 4 04 44 PM" src="https://user-images.githubusercontent.com/89202330/130604697-9a487673-8692-47f4-888a-6d5652e337bf.png">
