### ISSUE TITLE
Unable to convert log4j-1.2.17

### ISSUE THREAD

**Issue by dreemz17** [google/j2objc#1771]
Trying to convert log4j-1.2.17 conversion on Mac, it just hangs and doesn't do anything.

Logs:
org/apache/log4j/helpers/DateLayout.java org/apache/log4j/helpers/ThreadLocalMap.java org/apache/log4j/helpers/BoundedFIFO.java org/apache/log4j/ProvisionNode.java org/apache/log4j/BasicConfigurator.java org/apache/log4j/HTMLLayout.java org/apache/log4j/Priority.java
[INFO] translating /log4j/src/main/java/org/apache/log4j/or/RendererMap.java
[INFO] translating /log4j/src/main/java/org/apache/log4j/helpers/UtilLoggingLevel.java
[INFO] translating /log4j/src/main/java/org/apache/log4j/spi/OptionHandler.java
[INFO] translating /log4j/src/main/java/org/apache/log4j/or/ThreadGroupRenderer.java
[INFO] translating /log4j/src/main/java/org/apache/log4j/pattern/NamePatternConverter.java
[INFO] translating /log4j/src/main/java/org/apache/log4j/helpers/DateLayout.java
[INFO] translating /log4j/src/main/java/org/apache/log4j/pattern/PatternParser.java
[INFO] translating /log4j/src/main/java/org/apache/log4j/xml/Log4jEntityResolver.java
[INFO] translating /log4j/src/main/java/org/apache/log4j/pattern/FullLocationPatternConverter.java
[INFO] translating /log4j/src/main/java/org/apache/log4j/xml/SAXErrorHandler.java
....
....
....

**Comment by tomball** [comment]
I'm not sure why it's hanging on your system, but perhaps you need to run the [latest version, 2.8](https://github.com/google/j2objc/releases/tag/2.8), or with a distribution built from the latest source. I'm able to build with either of these, but (and this is important) just those log4j packages that depend on the [JRE packages that are supported by j2objc](https://developers.google.com/j2objc/javadoc/jre/reference). These packages have unsupported dependencies:

- `org.apache.log4j.chainsaw`, `org.apache.log4j.lfs`: `java.awt`, `javax.swing`
- `org.apache.log4j.jms`: `javax.jms`
- `org.apache.log4j.jmx`: `javax.management`
- `org.apache.log4j.net`: `javax.mail`

To verify the other packages build, I unzipped the log47-1.2.17-sources.jar, then ran:
```
$ ~/j2objc-2.8/j2objc -d build `find org -name '*.java' |egrep -v '(chainsaw|lf5|jmx|jms|net)'`
$ echo $?
0
```

The find command lists all Java source files, and the egrep command filters out those packages which won't build.
