### ISSUE TITLE
make truth_dist fails

### ISSUE THREAD

**Issue by YummyTastyCode** [google/j2objc#1806]
make dist fails.
This is the call stack.
compiling <path>/j2objc/testing/truth/build_result/objc/com/google/common/truth/ExpectFailure.m
<path>/j2objc/testing/truth/build_result/objc/com/google/common/truth/ExpectFailure.m:94:17: error: method 'applyWithOrgJunitRunnersModelStatement:withOrgJunitRunnerDescription:' in protocol 'OrgJunitRulesTestRule' not implemented [-Werror,-Wprotocol]
@implementation ComGoogleCommonTruthExpectFailure
                ^
../../dist/include/org/junit/rules/TestRule.h:24:1: note: method 'applyWithOrgJunitRunnersModelStatement:withOrgJunitRunnerDescription:' declared here
- (OrgJunitRunnersModelStatement *)applyWithOrgJunitRunnersModelStatement:(OrgJunitRunnersModelStatement *)base
^
1 error generated.
make[1]: *** [<path>/j2objc/testing/truth/build_result/objs-iphone64/com/google/common/truth/ExpectFailure.o] Error 1
make: *** [truth_dist] Error 2

It seems the problem is about
  @Override
  @GwtIncompatible("org.junit.rules.TestRule")
  public Statement apply(final Statement base, Description description) {
    checkNotNull(base);
    checkNotNull(description);
    return new Statement() {
      @Override
      public void evaluate() throws Throwable {
        enterRuleContext();
        try {
          base.evaluate();
        } finally {
          leaveRuleContext();
        }
        ensureFailureCaught();
      }
    };
  }

inside ExpectFailure.java

I've just removed
@GwtIncompatible("org.junit.rules.TestRule")
It has been compiled successfully.
I have no idea how to fix it by PR.

**Comment by tomball** [comment]
Cannot duplicate with current source base. 

This should only happen if the j2objc `--strip-gwt-incompatible` flag is set, which will cause the `apply()` method to be then be stripped (otherwise, @GwtIncompatible annotations are ignored). If you need to use this flag in your project, you can either remove the @GwtIncompatible line as you did, or split your j2objc command so that the sources requiring the flag are built separately.

**Comment by tomball** [comment]
In particular, don't build the j2objc project with this flag.
