### ISSUE TITLE
Transfer transcoded objc files to another project

### ISSUE THREAD

**Issue by nickkhodcts** [google/j2objc#1809]
Hi,
I experience a problem with transfer of transcoded java files to another project.
I would like to use transcoded files in a separate static lib. So I moved all the created .h and .m files from DerivedData to another project, but It also requires multiple java dependencies.
Is there any way to resolve this?

**Comment by tomball** [comment]
All Java dependencies need to be translated as well, which usually are jars
you specified with the -classpath argument. iOS doesn't support code from
external sources at runtime, so all classes have to be included in the iOS
app.
