### ISSUE TITLE
Conversion of JavaUtilConcurrentAtomicAtomicReference into Array can't find array methods

### ISSUE THREAD

**Issue by dreemz17** [google/j2objc#1815]
After the conversion of an array of Atomic reference converted to type JavaUtilConcurrentAtomicAtomicReference* in Objective C, not able to call array methods like length, etc in Objective C.
Java code : AtomicReference<String[]> names -> JavaUtilConcurrentAtomicAtomicReference* names
On executing [names length] getting error [JavaUtilConcurrentAtomicAtomicReference length]: unrecognized selector

**Comment by dreemz17** [comment]
found solution

**Comment by tomball** [comment]
Please leave a description of your solution. Even if it was an "oops" moment on your part, it will help other developers who may find this issue during a project search.

**Comment by dreemz17** [comment]
Use the get and set function to fetch a value from the JavaUtilConcurrentAtomicAtomicReference refernce.
