### ISSUE TITLE
java.lang.ArrayStoreException: source of type IOSByteArray is not an array

### ISSUE THREAD

**Issue by gianlucabertani** [google/j2objc#1827]
We are experiencing a strange crash due to an uncaught Java exception in an application which includes both code transpiled with J2ObjC _AND_ an external framework transpiled with J2ObjC. The local code and the library have been transpiled with the same version of J2ObjC, which is version 2.7.

The exception is thrown at the beginning of a custom thread started by the external library. Being in the library, we have no access to the original Java code. What we know for sure is that the same library used in the same application, but excluding the local transpiled code and J2ObjC static libraries, works correctly and throws no exception.

The exception stack trace is as follows:
```
2021-12-28 17:42:39.313040+0100 ######[34201:1972018] *** Terminating app due to uncaught exception 'JavaLangArrayStoreException', reason: 'java.lang.ArrayStoreException: source of type IOSByteArray is not an array'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff20422fba __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007fff20193ff5 objc_exception_throw + 48
	2   ########################            0x00000001125fc6b7 +[JavaLangSystem nanoTime] + 0
	3   ########################            0x00000001125a446d -[JavaIoByteArrayInputStream readWithByteArray:withInt:withInt:] + 141
	4   ########################            0x00000001125a15e3 -[JavaIoBufferedInputStream readWithByteArray:withInt:withInt:] + 150
	5   ########################            0x00000001126fe789 -[JavaUtilProperties_LineReader readLine] + 178
	6   ########################            0x00000001126fbf8b JavaUtilProperties_loadLineReaderWithJavaUtilProperties_LineReader_withJavaUtilProperties_KeyValueLoader_ + 102
	7   ########################            0x0000000112793d84 -[JavaUtilLoggingLogManager readConfigurationWithJavaIoInputStream:] + 151
	8   ########################            0x0000000112793600 -[JavaUtilLoggingLogManager readConfiguration] + 532
	9   ########################            0x0000000112792a83 JavaUtilLoggingLogManager_checkConfiguration + 34
	10  ########################            0x0000000112792a1b JavaUtilLoggingLogManager_readPrimordialConfiguration + 65
	11  ########################            0x0000000112795c05 -[JavaUtilLoggingLogManager_1 run] + 94
	12  ########################            0x000000011279292a JavaUtilLoggingLogManager_ensureLogManagerInitialized + 226
	13  ########################            0x00000001127929ad JavaUtilLoggingLogManager_getLogManager + 31
	14  ########################            0x0000000112798da4 JavaUtilLoggingLogger_demandLoggerWithNSString_withNSString_withIOSClass_ + 39
	15  ########################            0x0000000112600d3e -[JavaLangThread_SystemUncaughtExceptionHandler uncaughtExceptionWithJavaLangThread:withJavaLangThrowable:] + 40
	16  ########################            0x00000001125fe05b start_routine + 127
	17  libsystem_pthread.dylib             0x00007fff6034a4f4 _pthread_start + 125
	18  libsystem_pthread.dylib             0x00007fff6034600f thread_start + 15
)
libc++abi: terminating with uncaught exception of type JavaLangArrayStoreException
*** Terminating app due to uncaught exception 'JavaLangArrayStoreException', reason: 'java.lang.ArrayStoreException: source of type IOSByteArray is not an array'
```

Any suggestion on what could be the cause or how to solve this?

**Comment by gianlucabertani** [comment]
After some more inspection, that stack trace seems to present a _double_ exception, i.e. an exception thrown while handling an exception.

The original exception in unknown, but is caught and handled by this `SystemUncaughtExceptionHandler`, which is implemented in the [jre_emul Thread.java source](https://github.com/google/j2objc/blob/master/jre_emul/Classes/java/lang/Thread.java). This system exception handler tries to log the exception using `java.logging`.

While logging, a secondary exception of type `java.lang.ArrayStoreException` is thrown and this is what is shown in the stack trace.

So, it seems there's some kind of error in the `SystemUncaughtExceptionHandler` that at least prevents the original uncaught exception to be logged.

**Comment by gianlucabertani** [comment]
Ok, solved by myself.

The problem here is the external framework carries on all the static libraries from J2ObjC. So there's no need to add the typical [build settings for J2ObjC](https://developers.google.com/j2objc/guides/xcode-build-rules) in the project, i.e. `Framework Search Path` and `Library Search Path` must be left empty, while `Header Search Path` must still be set.

Once removed the settings for framework and library search paths, the project still built successfully and the crash disappeared.

Hope this may be of help to anyone incurring in the same error.

**Comment by gianlucabertani** [comment]
To be more precise:
* _IF_ your project makes use of J2ObjC transpiled code 
* _AND_ has a dependency from an external library which in turn makes use of J2ObjC transpiled code
* _THEN_ set the project Build Settings as follows:
  * `Other Linker Flags`: leave empty, i.e. DON'T ADD `-ljre_emul` etc.
  * `User-Defined Settings`: ADD `J2OBJC_HOME` as specified in [Xcode Build Rules](https://developers.google.com/j2objc/guides/xcode-build-rules)
  * `Framework Search Paths`: leave empty, i.e. DON'T ADD `${J2OBJC_HOME}/frameworks`
  * `Library Search Paths`: leave empty, i.e. DON'T ADD `${J2OBJC_HOME}/lib`
  * `Header Search Paths`: ADD `${J2OBJC_HOME}/include` as specified in [Xcode Build Rules](https://developers.google.com/j2objc/guides/xcode-build-rules)

The project will build successfully thanks to the J2ObjC includes on the search path, and will link successfully thanks to all the symbols already present in the external library.

**Comment by tomball** [comment]
Thanks for posting the solution to this. It looked like duplicate runtimes
were referenced, but from just looking at the stack trace it wasn’t obvious
how that happened.
