### ISSUE TITLE
Building for arm64 device, arm64 simulator and x86_64 simulator

### ISSUE THREAD

**Issue by mungler** [google/j2objc#1828]
Hi,

We're in the midst of trying to update our j2objc library to XCFramework, and are hoping to be able to run our app natively on the arm64 Simulator on M1 Macs. I'm trying to build j2objc from source (latest master as of today - commit f119c4274dde21785dc8d96bef52f3dc3a15ecac).

I ran the following:

```
J2OBJC_ARCHS="iphone64 simulator64" make -j8 frameworks
```

However, no matter if i build on my M1 Air or my Intel iMac, this results in XCFrameworks with only arm64 binaries:

```
rory@Eddie ~/W/j/d/frameworks (master)> ls JRE.xcframework/
Headers			Versions		ios-arm64-simulator
Info.plist		ios-arm64
rory@Eddie ~/W/j/d/frameworks (master)> file JRE.xcframework/ios-arm64-simulator/libjre_emul.a 
JRE.xcframework/ios-arm64-simulator/libjre_emul.a: Mach-O universal binary with 1 architecture: [arm64:current ar archive]
JRE.xcframework/ios-arm64-simulator/libjre_emul.a (for architecture arm64):	current ar archive
rory@Eddie ~/W/j/d/frameworks (master)> file JRE.xcframework/ios-arm64/libjre_emul.a 
JRE.xcframework/ios-arm64/libjre_emul.a: Mach-O universal binary with 1 architecture: [arm64:current ar archive]
JRE.xcframework/ios-arm64/libjre_emul.a (for architecture arm64):	current ar archive
rory@Eddie ~/W/j/d/frameworks (master)> 
```

I first did the build on my M1 so I thought it was just picking up on the local CPU arch, but I repeated on my intel iMac and got the same result.

Our own library build (including j2objc-converted Java code) generates an XCFramework with a fat-binary for Simulator:

```
rory@Hactar ~/W/l/b/LibASW-iOS.xcframework> ls
Info.plist			ios-arm64_x86_64-simulator
ios-arm64
... etc
```

though admittedly this is largely built 'by hand' in our build script.

Am I doing something wrong? My goal is to use JRE.xcframework in our app, along with our own library, and have it run natively on both Intel and Apple Silicon Macs.

**Comment by tomball** [comment]
I think the problem is that you didn't include the M1 archs you wanted in J2OBJC_ARCHS: macosx64 and possibly, maccatalyst64. These are automatically included if J2OBJC_ARCHS isn't defined in [make/common.mk:103](https://github.com/google/j2objc/blob/master/make/common.mk#L103).

Please reopen if this isn't the issue. I don't have access to an M1 system, but will try to find one to reproduce this.
