### ISSUE TITLE
Support translating Java methods with method-mapped signatures [moved]

### ISSUE THREAD

**Issue by kstanger** [google/j2objc#185]
This is [Issue 185](https://code.google.com/p/j2objc/issues/detail?id=185) moved from a Google Code project.
Added on 2013-06-03T14:53:23.000Z by [halfs...@gmail.com](http://code.google.comhttps://code.google.com/u/115309617626404951068/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Medium

**Comment by tomball** [comment]
Should be fixed using ObjectiveCName annotation.
