### ISSUE TITLE
Python scripts fail on MacOS 12.3, need to be updated to python3

### ISSUE THREAD

**Issue by sgammon** [google/j2objc#1851]
Hey Google / esteemed j2objc authors,

I'm excited to try j2objc, but I am running into issues following the build guide. On the [_Building J2ObjC_](https://developers.google.com/j2objc/guides/building-j2objc#building_j2objc_2) step, it refers to `make` commands such as `make dist`, and so forth... and I also saw a suggestion to build a distribution via `scripts/build_distribution.sh`.

I've tried all of these routes, but no matter what I do, I arrive at:

```
building jre_emul.jar
building jre_emul-src.jar
make[1]: ../scripts/gen_java_source_jar.py: No such file or directory
make[1]: *** [/Users/sam/Workspace/j2objc/jre_emul/build_result/jre_emul-src.jar] Error 1
```

I've tried on `master` latest, I've tried at `2.8`, and so on. Surely there's something obvious I'm missing here? `PROTOBUF_ROOT_DIR` is defined, so is `JAVA_HOME`. I'm running on Zulu JDK 11. Protobuf version is `3.19.4`, at latest.

**Comment by sgammon** [comment]
note: I would use the distribution release, which works great, but I am not able to run the simulator with a toy app that depends on ObjC generated by j2objc. I get:

```
ld: warning: directory not found for option '-F/Users/sam/Libraries/j2objc/latest/frameworks'
ld: in /Users/sam/Libraries/j2objc/latest/lib/libjre_emul.a(IOSClass.o), building for iOS Simulator, but linking in object file built for iOS, for architecture arm64
```

As I understand it, the distributions no longer contain the full set of symbols, so this makes sense. Thus I set about building j2objc at trunk, but ran into this issue.

FWIW I am an advanced user of Bazel and if there's an easy way to accomplish this via Bazel, I'm happy to go that route.

**Comment by sgammon** [comment]
@tomball any ideas?

**Comment by tomball** [comment]
You just upgraded to MacOS 12.3, right? Apple decided to stop distributing /usr/bin/python (Python 2.7), so the 12.3 upgrade removed it from your system. Feel free to share any feelings you have about that decision with them. ;-)

Unfortunately, one can't always just run 2.7 Python scripts using /usr/bin/python3, as the two major versions aren't compatible. So doing so fixes `scripts/gen_java_source_jar.py`, but as the build continues, `scripts/gen_resource_source.py` fails with a Python TypeError. If you have any Python experience, consider fixing it (it looks straightforward) and [submitting a pull request to contribute your fix](https://developers.google.com/j2objc/guides/how-to-contribute).

A workaround that avoids changing these scripts is to [install Python 2.7 using HomeBrew](https://docs.python-guide.org/starting/install/osx/), then add a softlink so /usr/bin/python points to your HomeBrew python binary (the default is /usr/local/bin).

I should be able to update the scripts next week, if no one beats me to it with a pull request.

**Comment by sgammon** [comment]
@tomball thanks for the quick reply! that makes sense and yes that is, well, apple-esque. i tried to follow your guide here but still got stuck. i'm familiar with python and happy to submit a PR over the weekend, i suspect you will begin hearing about this a lot (this is a new machine, not an update 😉)

the brew guide doesn't seem to work anymore, i'm not sure why. maybe it's because i'm on M1? running
```
brew install python@2
```

gave me
```
➜  j2objc git:(master) brew install python@2 
Warning: No available formula with the name "python@2". Did you mean ipython, bpython, jython or cython?
==> Searching for similarly named formulae...
These similarly named formulae were found:
ipython                                            bpython                                            jython                                             cython
To install one of them, run (for example):
  brew install ipython
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching taps on GitHub...
Error: No formulae found in taps.
```

womp womp. so i installed [macpython 2.7.18 via `python.org`](https://www.python.org/downloads/release/python-2718/). back in `j2objc`, i ran `make clean` and then `make dist`, which gave me:
```
building jre_emul.jar
building jre_emul-src.jar
make[1]: ../scripts/gen_java_source_jar.py: No such file or directory
make[1]: *** [/Users/sam/Workspace/j2objc/jre_emul/build_result/jre_emul-src.jar] Error 1
make: *** [jre_emul_jars_dist] Error 2
```

same as before. to check sanity, i ran:
```
➜  j2objc git:(master) which python
/usr/local/bin/python
➜  j2objc git:(master) python --version
Python 2.7.18
➜  j2objc git:(master) which python2
/usr/local/bin/python2
➜  j2objc git:(master) which python2.7
/usr/local/bin/python2.7
```

which seems to cover all the options the `Makefile` might be looking for. is there an alias it needs beyond what's present above, or could something else be wrong?

**Comment by tomball** [comment]
You're almost there: run "sudo ln -s /usr/local/bin/python /usr/bin/python"
to create a soft link for scripts that invoke /usr/bin/python directly,
like these scripts do.
