### ISSUE TITLE
Can't build in Simulator on m1? Need arm64 architecture

### ISSUE THREAD

**Issue by bryan1anderson** [google/j2objc#1933]
Is there a way to build this out for simulator on m1? I can't figure out how to get the correct slice for simulator arm 64 architecture for our XCFramework

**Comment by ferencIOS** [comment]
@bryan1anderson 

I solved this way:

**STEP 1** (j2objc proj)
```
git clone https://github.com/google/j2objc.git
cd j2objc
git checkout 4adbb2ddc7c542431902ee14e77256ba7808923d
```
**STEP 2** (java)
Then from Oracle took the [jdk-11.0.17_macos-aarch64_bin.dmg](https://download.oracle.com/otn/java/jdk/11.0.17%2B10/8bd089539add49a9b99e2f27eb0c4329/jdk-11.0.17_macos-aarch64_bin.dmg), install it!

Open your bash/zsh file and put 
```
export JAVA_HOME=`/usr/libexec/java_home -v 11`
```

**STEP 3** (protobuf)
Update the command line and install `protobuf` as the [j2objc guide](https://developers.google.com/j2objc/guides/building-j2objc#install_protobuf) said

**STEP 4** (xcframeworks)
Run
```
make dist
```
you will find this path `dist/frameworks`

**STEP 5** (optional)
In case of error run:
```
make clean
```
and then retry **STEP 4**

I did it on my m1 macOS 13.0.1 (22A400)

**Comment by waelsaad** [comment]
Hi, I am trying to compile j2objc on M3 Max. I have done all steps but when I do make dist I keep getting :-

`Building j2objc annotations
mvn -q generate-resources dependency:sources
make[1]: mvn: No such file or directory`

**Comment by tomball** [comment]
I updated the [Building J2ObjC](https://developers.google.com/j2objc/guides/building-j2objc) page, which should address some of your issues. The [scripts/build_distribution.sh script](https://github.com/google/j2objc/blob/master/scripts/build_distribution.sh) now builds successfully on a M3 MBP(minus a couple of JRE test failures).

The Apple Silicon machines require the arm64 and simulator64 architectures, which weren't available when the last binary release was made. We now recommend that everyone build from the latest source. Although for most open-source projects that's risky, at Google all our apps are built internally from HEAD, and every change is code-reviewed and triggers a continuous integration build of those apps before it's committed.
