### ISSUE TITLE
Obj-C Lightweight Generics support not working as expected?

### ISSUE THREAD

**Issue by mungler** [google/j2objc#1947]
Further to the discussion here: https://groups.google.com/g/j2objc-discuss/c/bkR6wleBjXE

I converted a file Monkey.java, containing the following snippet, using the new --objc-generics flag:

```java
public class Monkey {
	public String[] sounds;
	
	public Monkey(String[] sounds) {
		this.sounds = sounds;
	}
	
	public void doSomething(Monkey[] monkeyArray) {
		System.out.println("do something with the array");
	}
	
	public void speak() {
		if (this.sounds.length > 0) {
			System.out.println(this.sounds[0]);
		} else {
			System.out.println("generic monkey sound");
		}
	}
	
	public void sort(int[] numbers) {
		System.out.println("received " + numbers.length + " numbers to sort");
	}
	
	public static void main(String[] args) {
		Monkey m = new Monkey(args);
		
		m.speak();
		
		m.sort(new int[] { 2, 5, 8, 0, 99});
	}
	
}
```

And the resulting .m file looks like this:

```objc
//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/rory/Monkey.java
//

#include "IOSObjectArray.h"
#include "IOSPrimitiveArray.h"
#include "J2ObjC_source.h"
#include "Monkey.h"
#include "java/io/PrintStream.h"
#include "java/lang/System.h"

#if __has_feature(objc_arc)
#error "Monkey must not be compiled with ARC (-fobjc-arc)"
#endif

@implementation Monkey

- (instancetype)initWithNSStringArray:(IOSObjectArray *)sounds {
  Monkey_initWithNSStringArray_(self, sounds);
  return self;
}

- (void)doSomethingWithMonkeyArray:(IOSObjectArray *)monkeyArray {
  [((JavaIoPrintStream *) nil_chk(JreLoadStatic(JavaLangSystem, out))) printlnWithNSString:@"do something with the array"];
}

- (void)speak {
  if (((IOSObjectArray *) nil_chk(self->sounds_))->size_ > 0) {
    [((JavaIoPrintStream *) nil_chk(JreLoadStatic(JavaLangSystem, out))) printlnWithNSString:IOSObjectArray_Get(self->sounds_, 0)];
  }
  else {
    [((JavaIoPrintStream *) nil_chk(JreLoadStatic(JavaLangSystem, out))) printlnWithNSString:@"generic monkey sound"];
  }
}

- (void)sortWithIntArray:(IOSIntArray *)numbers {
  [((JavaIoPrintStream *) nil_chk(JreLoadStatic(JavaLangSystem, out))) printlnWithNSString:JreStrcat("$I$", @"received ", ((IOSIntArray *) nil_chk(numbers))->size_, @" numbers to sort")];
}

+ (void)mainWithNSStringArray:(IOSObjectArray *)args {
  Monkey_mainWithNSStringArray_(args);
}

- (void)dealloc {
  RELEASE_(sounds_);
  [super dealloc];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 1, 2, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 3, 4, -1, -1, -1, -1 },
    { NULL, "V", 0x9, 5, 0, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(initWithNSStringArray:);
  methods[1].selector = @selector(doSomethingWithMonkeyArray:);
  methods[2].selector = @selector(speak);
  methods[3].selector = @selector(sortWithIntArray:);
  methods[4].selector = @selector(mainWithNSStringArray:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "sounds_", "[LNSString;", .constantValue.asLong = 0, 0x1, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "[LNSString;", "doSomething", "[LMonkey;", "sort", "[I", "main" };
  static const J2ObjcClassInfo _Monkey = { "Monkey", NULL, ptrTable, methods, fields, 7, 0x1, 5, 1, -1, -1, -1, -1, -1 };
  return &_Monkey;
}

@end

void Monkey_initWithNSStringArray_(Monkey *self, IOSObjectArray *sounds) {
  NSObject_init(self);
  JreStrongAssign(&self->sounds_, sounds);
}

Monkey *new_Monkey_initWithNSStringArray_(IOSObjectArray *sounds) {
  J2OBJC_NEW_IMPL(Monkey, initWithNSStringArray_, sounds)
}

Monkey *create_Monkey_initWithNSStringArray_(IOSObjectArray *sounds) {
  J2OBJC_CREATE_IMPL(Monkey, initWithNSStringArray_, sounds)
}

void Monkey_mainWithNSStringArray_(IOSObjectArray *args) {
  Monkey_initialize();
  Monkey *m = create_Monkey_initWithNSStringArray_(args);
  [m speak];
  [m sortWithIntArray:[IOSIntArray arrayWithInts:(jint[]){ 2, 5, 8, 0, 99 } count:5]];
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(Monkey)

```

Notably, I expected the `sounds` argument to the constructor to be declared as `IOSObjectArray<NSString*>` or similar, and the `monkeyArray` argument to `doSomethingWithMonkeyArray` to be `IOSObjectArray<Monkey*>`.

My assumption was that all I needed to do to get this to work is compile the distribution using latest git source and invoke the converter with the `--objc-generics` flag - but perhaps i'm missing a step?

Thanks in advance.

**Comment by mungler** [comment]
Stupid question.... just looking at the original commit which added support for generics... IOSObjectArray.h changed to include the ObjectType stuff, but there was no corresponding change to IOSObjectArray.m, which continues to use `id`. Is changing the header only sufficient, here? I sort of expected the implementation would need to change too, but i'm not an Obj-C developer, only a dabbler :)

**Comment by tomball** [comment]
Your assumptions are right. The engineer who worked on this feature (now moved on) assumed that lightweight generics should only be generated in headers, and explicitly left the non-generic references in generated impl (.m) files. My plan this week is to revert the code that makes this distinction so generic declarations and references are made everywhere, and then see what, if anything, needs to be adjusted.

FWIW, any interested developers are encouraged to code-review [the project's pull-requests](https://github.com/google/j2objc/pulls) when they're created. Even if a pull request get merged before feedback is posted, it's still read and considered. My recommendation for translator pull requests is to check for any unit test changes, as most of them pipe Java snippets through the translator and verify the Objective-C output. It's therefore easy to verify whether generated code matches your expectations, and send feedback if it doesn't.

For what it's worth, this process can work both ways. If we aren't responding quickly enough to a new feature or bug report, public engineers are welcome to [contribute a pull request](https://developers.google.com/j2objc/guides/how-to-contribute). We give external contributions the same code review rigor we do our internal ones, so even if a developer isn't sure whether their PR is correct, it starts a conversation.

**Comment by mungler** [comment]
Hi Tom, thanks for getting back. In fact I commented on here about the change being only to the header, but I then read this article which seems to suggest using `id` in the `.m` file is correct:

https://medium.com/ios-os-x-development/generics-in-objective-c-8f54c9cfbce7

But as I say, i'm not an Obj-C developer so I don't know for sure.

Good to know about the PRs - i'm happy to review and comment where I can, thanks.

**Comment by tomball** [comment]
That's basically the information we were following, and unfortunately,
Apple doesn't have any better docs and the Foundation framework source
isn't available. If "id" is required, then our generation probably needs to
introduce casts where necessary.

**Comment by mungler** [comment]
Seems that might be the case, yes.

Let me know if I can be of any help!

**Comment by tomball** [comment]
Monkey.java now translates correctly (or as correctly as we understand how ObjC generics should be generated), and jre_emul and its tests (over 4,000 source files) build and pass, so I'm closing this issue.

If you have further problems with this feature, please file a new bug with a test demonstrating the issue, like you did here. Thanks for your patience!

**Comment by mungler** [comment]
Superb, thanks @tomball will check it out 👍
