### ISSUE TITLE
No 2.x release available for j2objc-annotations on Maven central

### ISSUE THREAD

**Issue by sandeepk-veritas** [google/j2objc#1987]
The last release for j2objc-annotations is 1.3 on Maven central. 

2.x seems to be now main release that is regularly maintained, but no release is available for it on Maven central.

1.3 is getting highlighted as EOL in the scanner, so will it be possible to release 2.x on Maven? We make use of Guava a lot and it has dependency on j2objc-annotations. They cannot upgrade because no new release is available on Maven central.

**Comment by tomball** [comment]
Why do you need this? Guava's pom.xml uses 1.3, and builds successfully. We don't synchronize the j2objc and j2objc-annotations releases, since the annotations rarely change.

**Comment by sandeepk-veritas** [comment]
j2objc-annotations version 1.3 is getting detected as EOL by many security scanners.
It was released in 2017 i.e. almost 7 yrs now. Hence we are getting questions regarding around this component. We are getting questions from customers around use of EOL components.
Guava is using j2objc-annotations as dependency, and we make use of Guava extensively. Guava cannot upgrade its dependencies if no new versions are available.

**Comment by sandeepk-veritas** [comment]
@tomball any further thoughts on this?

**Comment by tomball** [comment]
What "security scanners"? We've heard nothing about this component's EOL status. BTW, you always have the option of forking and submitting your own Maven component, companies do that all the time.

**Comment by sandeepk-veritas** [comment]
We are using Synopsys Blackduck Hub. 

Forking is not a good option here as Guava is very well known component. If Guava gets the latest version of j2objc-annotations, then it would benefit a larger community.

**Comment by tomball** [comment]
https://central.sonatype.dev/artifact/com.google.j2objc/j2objc-annotations/2.8

**Comment by sandeepk-veritas** [comment]
Thanks a lot @tomball

**Comment by hazendaz** [comment]
And just like that, bots already sending alerts on the update.  Thanks for releasing it!
