### ISSUE TITLE
Can't build frameworks

### ISSUE THREAD

**Issue by NullIsOne** [google/j2objc#2005]
Hello.
I'm trying to build a lightweight `JRE.xcframeworks` with next command
`J2OBJC_ARCHS="iphone64 simulator64 simulator" make -j8 frameworks`
but have a problems.

I tried on master b7d135ebb12af564fab15232dbdfaa9a0a9940d6 and got
```
building j2objc jar
src/main/java/com/google/devtools/j2objc/util/ExternalAnnotations.java:25: error: package org.checkerframework.afu.scenelib.el does not exist
import org.checkerframework.afu.scenelib.el.AScene;
...
src/main/java/com/google/devtools/j2objc/javac/MethodTranslator.java:998: error: method does not override or implement a method from a supertype
  @Override
  ^
Note: src/main/java/com/google/devtools/j2objc/pipeline/InputFilePreprocessor.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
56 errors
make[1]: *** [/Users/korobeinikov/Documents/GitHub/j2objc/translator/build_result/j2objc.jar] Error 1
make: *** [translator] Error 2
```

I tried on tag 2.8 960e8a5b4d586a0ec43b74dac7230aed1e13c103 and got
```
Locale: ru_RU.UTF-8
Darwin dev-macmini-korobeinikov.local 22.1.0 Darwin Kernel Version 22.1.0: Sun Oct 9 20:14:54 PDT 2022; root:xnu-8792.41.9~2/RELEASE_X86_64 x86_64
Xcode 14.2 Build version 14C18
Apple clang version 14.0.0 (clang-1400.0.29.202)
Target: x86_64-apple-darwin22.1.0
Thread model: posix
InstalledDir: /Applications/Xcode-14.2.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

Environment:
HOME=/Users/korobeinikov
J2OBJC_2_5_HOME=/Users/korobeinikov/.j2objc-env/versions/2.5
J2OBJC_2_8_HOME=/Users/korobeinikov/.j2objc-env/versions/2.8
J2OBJC_ARCHS=iphone64 simulator64 simulator
JAVA_HOME=/Users/korobeinikov/Library/Java/JavaVirtualMachines/corretto-1.8.0_352/Contents/Home
LANG=ru_RU.UTF-8
LC_ALL=en_US.UTF-8
LOGNAME=korobeinikov
LaunchInstanceID=82BECCEC-B304-46BC-9FA2-252FE82FB1C2
MAKEFLAGS= --jobserver-fds=3,4 -j
MAKELEVEL=1
MAVEN_HOME=/Users/korobeinikov/Library/apache-maven-3.8.3
MFLAGS=- --jobserver-fds=3,4 -j
PATH=/Users/korobeinikov/Library/apache-maven-3.8.3/bin:/usr/local/bin:/usr/local/sbin:/Users/korobeinikov/.rbenv/shims:/Library/Frameworks/Python.framework/Versions/3.11/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/korobeinikov/.j2objc-env/libexec:/Users/korobeinikov/.j2objc-env/libexec
PWD=/Users/korobeinikov/documents/github/j2objc
RBENV_SHELL=zsh
SDKMAN_CANDIDATES_API=https://api.sdkman.io/2
SDKMAN_CANDIDATES_DIR=/Users/korobeinikov/.sdkman/candidates
SDKMAN_DIR=/Users/korobeinikov/.sdkman
SDKMAN_PLATFORM=darwinx64
SDKMAN_VERSION=5.13.0
SECURITYSESSIONID=186a4
SHELL=/bin/zsh
SHLVL=2
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.CGQYOC8RC9/Listeners
TERM=xterm-256color
TERM_PROGRAM=Apple_Terminal
TERM_PROGRAM_VERSION=447
TERM_SESSION_ID=476F12CA-0D2B-48CA-A089-11F7D733FBC5
TMPDIR=/var/folders/t1/mr6gg1155s15m80mktnlw_2r0000gp/T/
USER=korobeinikov
XPC_FLAGS=0x0
XPC_SERVICE_NAME=0

building j2objc jar
building jre_emul.jar
building jre_emul-src.jar
make[1]: ../scripts/gen_java_source_jar.py: No such file or directory
make[1]: *** [/Users/korobeinikov/Documents/GitHub/j2objc/jre_emul/build_result/jre_emul-src.jar] Error 1
make[1]: *** Waiting for unfinished jobs....
building json.jar
Note: src/main/java/com/google/devtools/j2objc/pipeline/InputFilePreprocessor.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
make: *** [jre_emul_jars_dist] Error 2
```
Looks like 2.8 is can't build anymore, isn't it?
I found relevant issue #1851 

So, is there any stable and buildable sources for MacOS 13?
Or maybe I missed something? 
Help me please.

**Comment by NullIsOne** [comment]
I forked repository and tried to upgrade all `py` scripts to python3, but looks like is not enough.
60829a76abcd2bc1ff49faaffafd153fe19ba837

Now I got next error in generated objective-c code.
```
compiling /Users/korobeinikov/Documents/GitHub/j2objc/jre_emul/build_result/Classes/java/math/MathContext.m
/Users/korobeinikov/Documents/GitHub/j2objc/jre_emul/build_result/Classes/java/lang/reflect/Proxy.m:255:10: error: cast to smaller integer type 'jint' (aka 'int') from 'JavaLangReflectProxy *' [-Werror,-Wpointer-to-int-cast]
  return (jint)self;
         ^~~~~~~~~~
1 error generated.
compiling /Users/korobeinikov/Documents/GitHub/j2objc/jre_emul/build_result/Classes/java/math/RoundingMode.m
make[1]: *** [/Users/korobeinikov/Documents/GitHub/j2objc/jre_emul/build_result/objs-simulator64/java/lang/reflect/Proxy.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [jre_emul_dist] Error 2
```

**Comment by tomball** [comment]
You're right that Java 11 is needed now, so I should update the "building j2objc" doc.

What does "clang --version" show on your system? I'm able to build successfully, and show "Apple clang version 14.0.0 (clang-1400.0.29.202)" from Xcode 14.1. If you are running a newer version of Xcode, Apple may have added `-Wpointer-to-int-cast` to its default warnings set (I can never keep up, since it seems to change with each release).

The cast in Proxy.m is "okay", but now that pointers are 64-bit, rounding down an address to 32-bits isn't the best hash. It's interesting that almost the same code doesn't get a warning in `System.identityHashCode()`, so clang's warnings aren't perfect. I'll update `System.identityHashCode()` to avoid this warning, and have `Proxy.proxy_hashCode()` call `System.identityHashCode()` instead. That way the hash function is in correct and in one place.

Would you mind making a pull request of your python changes? We instead install Homebrew's python to keep 2.7 around (it's needed for other in-house scripts), but the project doesn't need to depend upon it any more.

**Comment by NullIsOne** [comment]
Here my output of `clang`

```
clang --version
Apple clang version 14.0.0 (clang-1400.0.29.202)
Target: x86_64-apple-darwin22.1.0
Thread model: posix
InstalledDir: /Applications/Xcode-14.2.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```
Looks like it's same as yours.

Of course I could make a PR, but I want to compile j2objc successfully first :-)

**Comment by NullIsOne** [comment]
Thank you. 
With your changes for System.identityHashCode and one more fix of some unused variables in java sources (268a91922fe7a831b3722446bbee3774b2530047) I successfully built `dist` but without frameworks
![Снимок экрана 2023-01-21 в 16 20 02](https://user-images.githubusercontent.com/28707156/213866567-9ed08f93-2ac6-44cb-be21-6df8566057b8.png)

For some reason next line in main `Makefile` didn't launched.
When I tried to start from `cd jre_emul && $(MAKE) framework` manually I got next error

```
building JRE framework
xcodebuild -create-xcframework -output ../dist/frameworks/JRE.xcframework -library /Users/korobeinikov/Documents/GitHub/j2objc/jre_emul/build_result/objs-iphone64/libjre_emul.a -library /Users/korobeinikov/Documents/GitHub/j2objc/jre_emul/build_result/objs-simulator/libjre_emul.a -library /Users/korobeinikov/Documents/GitHub/j2objc/jre_emul/build_result/objs-simulator64/libjre_emul.a
Both 'ios-i386-simulator' and 'ios-x86_64-simulator' represent two equivalent library definitions.
make[1]: *** [../dist/frameworks/JRE.xcframework] Error 70
make: *** [frameworks] Error 2
```

**Comment by tomball** [comment]
I think the right fix here is to not build the simulator architecture anymore (just build the simulator64), as we now only build a 32bit arch for watchOS. According to [iOS Ref](https://iosref.com/ios-usage), that would drop support from devices that can't update to iOS 11, released in 2017.

I'll remove simulator and ios-i386-simulator support from the make/ files, while you update your build to be "J2OBJC_ARCHS="iphone64 simulator64" make -j8 frameworks". Let me know if the 386 simulator is still needed.

**Comment by tomball** [comment]
[Does i386 simulator target relavant or used anymore?](https://developer.apple.com/forums/thread/90648)

**Comment by NullIsOne** [comment]
You're right.
We don't need i386.

The thing I want to achieve is to make `xcframework` which contains `ios-x86_64-simulator` and `ios-arm64-simulator` to get rid of `EXCLUDED_ARHC` hack in our hosted app.

Now with 
`J2OBJC_ARCHS="iphone64 simulator64" make -j8 framework`
I got xcframework
![Снимок экрана 2023-01-23 в 14 15 32](https://user-images.githubusercontent.com/28707156/214015011-18f1d517-9d2f-496b-8a39-ee2af22fe7e3.png)

I will try to add `arm64_simulator` using approach from this issue https://issuetracker.google.com/issues/206669748?pli=1

I'm not sure if I can automate this and update scripts..
Will check manually first.

**Comment by NullIsOne** [comment]
Finally I did it.
You can look at my [preview release](https://github.com/NullIsOne/j2objc/releases/tag/preview) with description and [diff with original 2.8](https://github.com/NullIsOne/j2objc/compare/2.8...preview ).

I will test this on my project first.
At least I can build it with recompiled JRE linked.

**Comment by NullIsOne** [comment]
After all I was able to build from master too.
Here archives attached. https://github.com/NullIsOne/j2objc/releases/tag/latest
Closing. 
Thank you for all your help.
