### ISSUE TITLE
Code generated for String.format(Locale locale, String format, Object... args) call won't compile [moved]

### ISSUE THREAD

**Issue by kstanger** [google/j2objc#201]
This is [Issue 201](https://code.google.com/p/j2objc/issues/detail?id=201) moved from a Google Code project.
Added on 2013-06-29T20:54:05.000Z by [schro...@gmail.com](http://code.google.comhttps://code.google.com/u/105508117981345972216/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium

**Comment by tomball** [comment]
Lost test code when issue was moved to GitHub. Please open new issue if it's still a problem.
