### ISSUE TITLE
Variables that Differ only by a Captial are not Differentiated [moved]

### ISSUE THREAD

**Issue by kstanger** [google/j2objc#204]
This is [Issue 204](https://code.google.com/p/j2objc/issues/detail?id=204) moved from a Google Code project.
Added on 2013-07-04T01:41:01.000Z by [thomaswp...@gmail.com](http://code.google.comhttps://code.google.com/u/113015469821020246797/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium

**Comment by tomball** [comment]
Verified j2objc now successfully translates classes with variables that match a case-insensitive comparison.
