### ISSUE TITLE
-no-package-directories option not working

### ISSUE THREAD

**Issue by davidmoore1** [google/j2objc#2057]
I have been building with j2objc 2.8 until now.  Today I created a fork and built a dist from the next to the last checkout (git checkout 4adbb2ddc7c542431902ee14e77256ba7808923d).  In the image below, the left hand file is the java file being processed, the shot in the middle is what was generated today using the updated j2objc.  The file on the right is the same file as it was processed by j2objc 2.8.  
![Screenshot 2023-04-03 at 6 18 26 PM](https://user-images.githubusercontent.com/6209188/229670399-4f332009-c041-490f-b8ef-d410d375465f.png)
This is the build command in xcode used to call j2objc to produce the file.  

"${J2OBJC_HOME}/j2objc" --swift-friendly -d ${GENERATED_FILES_DIR} -classpath ${J2OBJC_HOME}/lib/json.jar -sourcepath "${JAVA_SOURCE_PATH}" --no-package-directories --prefixes "${SRCROOT}/AppLibCommon/prefixes.properties" -use-arc -g ${INPUT_FILE_PATH};

While the files are still placed in one directory as they were in j2objc 2.8, the includes generated now referencing other files in the library include the entire path within the original java hierarchy instead of just the name of the include file in quotes as it was previously.

**Comment by kuldar-daniel** [comment]
Ran across the same thing. Has there been any movement on this issue?

**Comment by kuldar-daniel** [comment]
> @kuldar-daniel I believe I still see the problem with the commit being rolled back, which was listed as the solution. Is it working correctly for you?
I went to latest commit from master and it built and works correctly from there.

**Comment by davidmoore1** [comment]
Agreed
