### ISSUE TITLE
Ability to disable property generation for non-public membors [moved]

### ISSUE THREAD

**Issue by kstanger** [google/j2objc#207]
This is [Issue 207](https://code.google.com/p/j2objc/issues/detail?id=207) moved from a Google Code project.
Added on 2013-07-08T15:41:27.000Z by [sparsew...@gmail.com](http://code.google.comhttps://code.google.com/u/115994043244498943245/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium

**Comment by tomball** [comment]
Properties no longer generated for fields.
