### ISSUE TITLE
iOS 17, beta 1: new exceptions in StreamDecoder

### ISSUE THREAD

**Issue by cfdrake** [google/j2objc#2113]
Hello!

I'm doing some testing of our app under Xcode 15 beta and iOS 17 beta, and I've noticed some new errors around network response decoding that are resulting in failures to load content across all of our screens. From what I can tell, these new errors are being produced in the underlying j2objc JRE. Here's what I'm seeing:

## iOS 16 and below

In current production versions of iOS, this snippet of code is able to handle reading the network response as a stream from the `connection`, can parse the JSON using the GSON library, and will return a model object of any type Java type `T`:

```swift
protected T parseResponse(HttpURLConnection connection) {
        InputStream stream = connection.getInputStream();
        Reader reader = new InputStreamReader(stream, Charset.forName("utf-8"));

        try {
            T response = gson.fromJson(reader, mResponseType.getType());
            /* ... callback with model object ... */
        } catch {
            /* ... error handling ... */
        }
}
```

## iOS 17, beta 1

Under iOS 17 beta 1, the following error message is now logged from the `catch` block above during all network requests:

```
java.lang.AssertionError: sun/nio/cs/StreamDecoder.java:301 condition failed: assert rem > 0;
```

This appears to be caused within `fromJson(...)` above when I pass in the `reader`.

I've double checked and the network response is returning HTTP status code 200 and contains valid JSON, so it does not appear to be a data problem. The models and returned data schema are the same as well.

## Summary

There appears to be a possible new error in `StreamDecoder` as of iOS 17 beta 1 which is causing reading the stream to fail.

**Comment by cfdrake** [comment]
Hello!

I've been probing more into this recently and think I have found the root issue.

Here is a minimal test case that will **work on iOS 16** and **fail on iOS 17 beta**, calling into j2objc's JRE emulation:

```swift
func testDecodeStream() {
    let testString = "{testtest}"
    let data = testString.data(using: .utf8)
    let byteArray = IOSByteArray(nsData: data)
    let stream: JavaIoInputStream = JavaIoByteArrayInputStream(byteArray: byteArray)
    let reader: JavaIoReader = JavaIoInputStreamReader(javaIoInputStream: stream, with: "UTF-8")
        
    print("ready? \(reader.ready())")
    while (reader.ready()) {
        let byte = reader.read()
        print(byte)
        print("--")
    }
}
```

On iOS 16 I see that the `reader` indicates it is ready, the stream has 10 characters available to read, and the loop executes printing each character out line by line.

With no changes, on iOS 17 I see that the `reader` indicates it is ready, the first byte is read, but the loop only executes once printing `65533`.

Based on what I've been reading GSON is using these functions/classes internally which is why we're seeing the failures in our app.

**Comment by cfdrake** [comment]
Just a note I've found that writing to a stream fails on iOS 17 as well. See the test code here:

```
private func testWriteSteam() {
        let stream = JavaIoByteArrayOutputStream()
        let writer = JavaIoBufferedWriter(javaIoWriter: JavaIoOutputStreamWriter(javaIoOutputStream: stream, with: "UTF-8"))
        
        let testString = "{testtest}"
        let byteArray = IOSCharArray(nsString: testString)!
        
        writer.write(with: byteArray, with: 0, with: byteArray.length())
        writer.flush()
        
        print(stream)
        print("DONE!")
    }
```

On iOS 16 I see "{testtest}" and on iOS 17 it just prints an empty line.

**Comment by litstrong** [comment]
Hi Cotlin, I apologize for my late reply. Your finding looks real, and thanks for your report and test cases!

The team is sort of under-staffed at the moment, so the response might be a bit slow. But this one is indeed import to us, and we'll look into it.

Thanks again. :)

**Comment by cfdrake** [comment]
@litstrong Great, thanks for confirming.

Just a note I've done some further testing on this and interestingly it only appears to be an issue with the simulator, not physical devices running the beta.

**Comment by litstrong** [comment]
Hi Cotlin,

I tested your code snippet under Xcode 15 beta 8 (simulator), and it seems running well.
