### ISSUE TITLE
Unable to build J2ObjC with Java 1.8

### ISSUE THREAD

**Issue by adil-hussain-84** [google/j2objc#2115]
I am trying to build the latest commit of J2ObjC (i.e. the [21378cc](https://github.com/google/j2objc/commit/21378cc6f10387035c9337774381b485dccd541d) commit dated Jun 20, 2023) with the following command:

```
export JAVA_HOME=`/usr/libexec/java_home -v 1.8`
export J2OBJC_ARCHS="iphone64 simulator64 simulator"
make -j8 dist
```

The `make` command fails quite early on with the following output:

```
...
Environment:
...
J2OBJC_ARCHS=iphone64 simulator64 simulator
JAVA_HOME=/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home
...
building jre_emul.jar
building json.jar
javac: invalid source release: 11
Usage: javac <options> <source files>
use -help for a list of possible options
make[1]: *** [/Users/adilhussain/Work/j2objc/jre_emul/build_result/json.jar] Error 2
make[1]: *** Waiting for unfinished jobs....
javac: invalid flag: --patch-module=java.base=.
Usage: javac <options> <source files>
use -help for a list of possible options
make[1]: *** [/Users/adilhussain/Work/j2objc/jre_emul/build_result/jre_emul.jar] Error 2
make: *** [jre_emul_jars_dist] Error 2
```

Should it still be possible, in theory, to build J2ObjC with Java 1.8? If so, is there any additional setup that I need to do to build J2ObjC with Java 1.8?

**Comment by sarsonj** [comment]
AFAIK Java 11 is required since some time.

**Comment by adil-hussain-84** [comment]
The pull request above removes "JDK 1.8" from the [Requirements](https://github.com/google/j2objc/blob/master/README.md#requirements) section in the [README.md](https://github.com/google/j2objc/blob/master/README.md) file based on my recent experience with it and @sarsonj's response above.

Somebody who has access needs to update the [Building J2ObjC](https://developers.google.com/j2objc/guides/building-j2objc) webpage accordingly. If it's open source, please somebody point me to it and I will make the change.
