### ISSUE TITLE
Methods with the same name but different generic return types have the same name when translated [moved]

### ISSUE THREAD

**Issue by kstanger** [google/j2objc#214]
This is [Issue 214](https://code.google.com/p/j2objc/issues/detail?id=214) moved from a Google Code project.
Added on 2013-07-11T17:54:10.000Z by [thomaswp...@gmail.com](http://code.google.comhttps://code.google.com/u/113015469821020246797/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium

**Comment by tomball** [comment]
Closed due to lack of an example showing the problem.
