### ISSUE TITLE
Files generated with --no-package-directories have directories in #include directivies [moved]

### ISSUE THREAD

**Issue by kstanger** [google/j2objc#216]
This is [Issue 216](https://code.google.com/p/j2objc/issues/detail?id=216) moved from a Google Code project.
Added on 2013-07-14T16:31:33.000Z by [tball@google.com](http://code.google.comhttps://code.google.com/u/tball@google.com/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium

**Comment by tomball** [comment]
Fixed: now only JRE library packages have paths.
