### ISSUE TITLE
CI Workflow Runs are failing

### ISSUE THREAD

**Issue by adil-hussain-84** [google/j2objc#2167]
I created a pull request earlier today. The CI Workflow Run for this pull request ([here](https://github.com/google/j2objc/actions/runs/6159118186/job/16713288822)) appears to have failed for a reason unrelated to my change. 

This is what I see in the build log:

```none
building jre_emul.jar
building jre_emul-src.jar
building json.jar
make[1]: *** [/Users/runner/work/j2objc/j2objc/jre_emul/build_result/json.jar] Error 2
javac: invalid source release: 11
make[1]: *** Waiting for unfinished jobs....
Usage: javac <options> <source files>
use -help for a list of possible options
make[1]: *** [/Users/runner/work/j2objc/j2objc/jre_emul/build_result/jre_emul.jar] Error 2
javac: invalid flag: --patch-module=java.base=.
Usage: javac <options> <source files>
use -help for a list of possible options
make: *** [jre_emul_jars_dist] Error 2
make: *** Waiting for unfinished jobs....
Error: Process completed with exit code 2.
```

Pay attention to the `javac: invalid source release: 11` line in the build log. The latest CI Workflow Run for the master branch appears to have failed for the same reason. See the build log [here](https://github.com/google/j2objc/actions/runs/6150847222/job/16689680270).

The problem is most likely caused by the `JAVA_HOME` environment variable on the build machines. It is set to JDK 8 and not JDK 11. See Issue #2115 for more information about this.

Can somebody who has access to the build machines please change the `JAVA_HOME` environment variable to JDK 11 🙏

**Comment by tomball** [comment]
Fixed in [PR #2168](https://github.com/google/j2objc/pull/2168).
