### ISSUE TITLE
Enums incorrectly generated if constructor present with "..." for multiple arguments [moved]

### ISSUE THREAD

**Issue by kstanger** [google/j2objc#217]
This is [Issue 217](https://code.google.com/p/j2objc/issues/detail?id=217) moved from a Google Code project.
Added on 2013-07-16T00:11:18.000Z by [ke...@intrameta.com](http://code.google.comhttps://code.google.com/u/102344509904089217235/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium

**Comment by tomball** [comment]
Fixed in 0.9.7.
