### ISSUE TITLE
JRE_Core.xcframework is missing headers

### ISSUE THREAD

**Issue by adil-hussain-84** [google/j2objc#2170]
I added `JRE_Core.xcframework` to a project. When I import any of its headers (e.g. `<java/lang/Integer.h>`) into the Objective-C files in my project , I get a `'J2ObjC_header.h' file not found` build error.

On comparing the headers in `JRE_Core.xcframework` against the headers in `JRE.xcframework`, I see that `JRE.xcframework` contains `J2ObjC_header.h` as well as a number of other headers that probably should be in `JRE_Core.xcframework`.

The headers which are missing from `JRE_Core.xcframework` seem to be the ones contained in the `PUBLIC_NATIVE_HEADERS` list in the [jre_emul/jre_sources.mk][1] file.

In order to add the missing headers to `JRE_Core.xcframework`, I am thinking to change the `FRAMEWORK_HEADERS` declaration in [jre_emul/subset_frameworks/jre_core_framework.mk][2] to the following:

```none
FRAMEWORK_HEADERS = $(PUBLIC_NATIVE_HEADERS) $(JAVA_PUBLIC_SOURCES_CORE:.java=.h)
```

Is this the right thing to do?

[1]: https://github.com/google/j2objc/blob/master/jre_emul/jre_sources.mk
[2]: https://github.com/google/j2objc/blob/master/jre_emul/subset_frameworks/jre_core_framework.mk

**Comment by tomball** [comment]
Yes, that's exactly right. I just built with this change and verified that the headers are now correct. Do you want to send out a pull request for this change? It will be faster to approve now.

**Comment by adil-hussain-84** [comment]
Yes, sure. I'll raise a pull request tomorrow. Thanks for the response 👍
