### ISSUE TITLE
Add System.loadLibrary() empty methods [moved]

### ISSUE THREAD

**Issue by kstanger** [google/j2objc#225]
This is [Issue 225](https://code.google.com/p/j2objc/issues/detail?id=225) moved from a Google Code project.
Added on 2013-07-24T16:45:30.000Z by [tball@google.com](http://code.google.comhttps://code.google.com/u/tball@google.com/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Medium

**Comment by tomball** [comment]
Added.
