### ISSUE TITLE
Private methods in derived class "hide" private methods in base class [moved]

### ISSUE THREAD

**Issue by kstanger** [google/j2objc#227]
This is [Issue 227](https://code.google.com/p/j2objc/issues/detail?id=227) moved from a Google Code project.
Added on 2013-07-26T00:25:53.000Z by [mic...@digitalchemy.us](http://code.google.comhttps://code.google.com/u/117101558154675053961/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium

**Comment by tomball** [comment]
Keith, you fixed this, right?

**Comment by kstanger** [comment]
Just verified that this is fixed
