### ISSUE TITLE
Main methods fail when defined in a class that is named with a primitive class signature. [moved]

### ISSUE THREAD

**Issue by kstanger** [google/j2objc#228]
This is [Issue 228](https://code.google.com/p/j2objc/issues/detail?id=228) moved from a Google Code project.
Added on 2013-07-26T16:07:02.000Z by [tball@google.com](http://code.google.comhttps://code.google.com/u/tball@google.com/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium

**Comment by tomball** [comment]
Fixed in latest release.
