### ISSUE TITLE
Building  j2objc fails on latest master

### ISSUE THREAD

**Issue by parveen-bhatia** [google/j2objc#2324]
Hi, we are trying to build `j2objc` from latest master as [supported source version is greater than 17](https://github.com/google/j2objc/blob/master/translator/src/main/java/com/google/devtools/j2objc/util/SourceVersion.java#L45) in master. But we are getting below issue when trying to build using  `make clean dist`

```
Note: src/main/java/com/google/devtools/j2objc/pipeline/InputFilePreprocessor.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
building jre_emul.jar
building jre_emul-src.jar
building json.jar
/bin/sh: jmod: command not found
building jre_emul_module
Error: file already exists: .../j2objc/jre_emul/build_result/jre_emul
make[1]: *** [.../j2objc/jre_emul/build_result/jre_emul_module] Error 2
make: *** [jre_emul_jars_dist] Error 
```

**Comment by myabc** [comment]
`jmod: command not found` is because `$JAVA_HOME/bin` isn't In your `PATH`. Try:
```
export PATH=$PATH:$JAVA_HOME/bin
```

**Comment by tomball** [comment]
PR #2327 fixes this.
