### ISSUE TITLE
Multiple commands produce JSONArray.h

### ISSUE THREAD

**Issue by parveen-bhatia** [google/j2objc#2330]
Found JSONArray.h, JSONObject.h etc. header files are available in both **JRE.xcframework** and **JSON.xcframework**. Both these frameworks are from j2objc dist.

When building in xcode, this causes issue `Multiple commands produce JSONArray.h`.

It is caused by https://github.com/google/j2objc/pull/2181 where frameworks started generating headers.

**Comment by tomball** [comment]
I moved your comment to a new issue, #2387. In the future, please file new issues for new problems; even if they are related, feedback from issues closed months earlier can otherwise get lost.
