### ISSUE TITLE
Add support for JAXB (Java Architecture for XML Binding) [moved]

### ISSUE THREAD

**Issue by kstanger** [google/j2objc#240]
This is [Issue 240](https://code.google.com/p/j2objc/issues/detail?id=240) moved from a Google Code project.
Added on 2013-08-07T09:00:58.000Z by [qwertyaa...@gmail.com](http://code.google.comhttps://code.google.com/u/106052398197383396199/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Low

**Comment by tomball** [comment]
J2ObjC moved to the Android source base for its JRE, and Android doesn't support JAXB. It should be possible to translate a JAXB implementation like Apache Camel without error, though it may have a dependency graph that is too big for iOS devices.
