### ISSUE TITLE
Create way to link in subsets of JRE library, to reduce app size [moved]

### ISSUE THREAD

**Issue by kstanger** [google/j2objc#248]
This is [Issue 248](https://code.google.com/p/j2objc/issues/detail?id=248) moved from a Google Code project.
Added on 2013-08-23T17:22:14.000Z by [tball@google.com](http://code.google.comhttps://code.google.com/u/tball@google.com/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Medium

**Comment by nbransby** [comment]
is there anyway to strip out unused JRE code at compile time? I think Xamarin uses such an approach on the .NET runtime to reduce size of the final binary.

**Comment by tomball** [comment]
The easiest savings is to avoid the -ObjC flag if your app doesn't need it.
This flag links in all Objective-C objects in a library, regardless whether
there are references to them. It's necessary for loading categories from
static libraries (not necessary for app categories), and to support
Objective-C or Java reflection. If you aren't sure whether your app needs
reflection, try removing the flag and run all your tests -- missing
reflection and categories errors are likely to be very visible.

**Comment by tomball** [comment]
Fixed in current release: instead of linking with libjre_emul.a, use the libjre_*.a subset libraries. For example, if your app uses the Java XML API, include the libjre_xml.a library. The list of what classes are in what libraries is j2objc/jre_emul/java_classes.mk.
