### ISSUE TITLE
Add flag to create properties for public fields [moved]

### ISSUE THREAD

**Issue by kstanger** [google/j2objc#252]
This is [Issue 252](https://code.google.com/p/j2objc/issues/detail?id=252) moved from a Google Code project.
Added on 2013-08-27T14:07:41.000Z by [tball@google.com](http://code.google.comhttps://code.google.com/u/tball@google.com/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Low

**Comment by tomball** [comment]
Harry Cheung created [pull request 463](https://github.com/google/j2objc/pull/463). He's offered to sync it with the current j2objc HEAD, and we'll pull it in when he does.

**Comment by zachgrayio** [comment]
@jonnolen So the pull request mentioned above looks promising, but I'm curious what you're doing in the meantime to get RAC binding working without public properties coming over from Java - this seems like a pretty big roadblock to ReactiveCocoa+j2objc at this point.

**Comment by tomball** [comment]
The [@Property annotation](http://j2objc.org/docs/Property.html) is now supported.
