### ISSUE TITLE
SystemClassLoader#findResource(String name) should check for nil nativeURL [moved]

### ISSUE THREAD

**Issue by kstanger** [google/j2objc#259]
This is [Issue 259](https://code.google.com/p/j2objc/issues/detail?id=259) moved from a Google Code project.
Added on 2013-09-23T09:02:18.000Z by [pat...@gmail.com](http://code.google.comhttps://code.google.com/u/114354141687789939610/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium

**Comment by tomball** [comment]
Fixed in latest source.
