### ISSUE TITLE
LinkedList descendingIterator() is not implemented? [moved]

### ISSUE THREAD

**Issue by kstanger** [google/j2objc#267]
This is [Issue 267](https://code.google.com/p/j2objc/issues/detail?id=267) moved from a Google Code project.
Added on 2013-10-07T20:50:44.000Z by [ke...@intrameta.com](http://code.google.comhttps://code.google.com/u/102344509904089217235/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium

**Comment by tomball** [comment]
java.util has been updated to Java 7 compliance.
