### ISSUE TITLE
Guava dependent test cases linking error  [moved]

### ISSUE THREAD

**Issue by kstanger** [google/j2objc#293]
This is [Issue 293](https://code.google.com/p/j2objc/issues/detail?id=293) moved from a Google Code project.
Added on 2013-12-05T23:40:39.000Z by [mahmoud....@lognlabs.com](http://code.google.comhttps://code.google.com/u/112263191180152075001/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium

**Comment by tomball** [comment]
Fixed in latest build.
