### ISSUE TITLE
Several unit tests fail for non-US locale [moved]

### ISSUE THREAD

**Issue by kstanger** [google/j2objc#300]
This is [Issue 300](https://code.google.com/p/j2objc/issues/detail?id=300) moved from a Google Code project.
Added on 2013-12-13T19:08:47.000Z by [tiptopl...@gmail.com](http://code.google.comhttps://code.google.com/u/115101336059252857219/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium

**Comment by tomball** [comment]
Cannot reproduce, as details from our old issue system has been lost.
