### ISSUE TITLE
with ARC, java.lang.reflect.Constructor.newInstance should not autorelease the returned instance [moved]

### ISSUE THREAD

**Issue by kstanger** [google/j2objc#314]
This is [Issue 314](https://code.google.com/p/j2objc/issues/detail?id=314) moved from a Google Code project.
Added on 2014-01-18T02:15:12.000Z by [mic...@digitalchemy.us](http://code.google.comhttps://code.google.com/u/117101558154675053961/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium

**Comment by tomball** [comment]
jre_emul library no longer supports ARC build.
