### ISSUE TITLE
Add support for SQLite3 wrapper library.

### ISSUE THREAD

**Issue by kstanger** [google/j2objc#325]
This is [Issue 325](https://code.google.com/p/j2objc/issues/detail?id=325) moved from a Google Code project.
Added on 2014-02-02T05:21:12.000Z by [tball@google.com](http://code.google.comhttps://code.google.com/u/tball@google.com/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Medium

**Comment by confile** [comment]
+1

**Comment by chemjournal** [comment]
Any news on this? I've heard that the inbox project has used shared data between Android and iOS. Has that been shared?

**Comment by tomball** [comment]
No, Inbox isn't open-sourced, so only our cross-platform strategy using
Java with the GWT and j2objc transpilers has been publicly shared.

**Comment by gingo** [comment]
Hi guys,

I have good news for you. We in SKOUMAL studio are working on clone of Sugar ORM (https://github.com/satyan/sugar) called joogar (not published on GitHub yet). It is based on Android SQLite API and low-lewel iOS SQLite3 library. More than 90% of code is pure Java shared on both platforms. 

ORM is opt-in choise, you can stay with plain SQL if you want. Unfortunately joogar is still in its pre-alpha stage, even if we currently use it in one of our projects. It is still missing documentation, examples, transaction support, etc. 

If you are interested to give it a try or contribute, please ping me on skoumal@skoumal.net.  

I'll let you know when we'll be ready for public alpha testing.

**Comment by chemjournal** [comment]
@gingo that seems like great news!! We're still early in our product lifecycle and I'll send you an email when I can try it out and contribute. By when are you expecting a public alpha rollout? Great work!

**Comment by gingo** [comment]
@chemjournal I'm worried it could take few month to public alpha. We are busy as hell on other projects :-)

**Comment by chemjournal** [comment]
@gingo let us know when you publish the alpha, I'd love to help you test it
out

**Comment by confile** [comment]
+1

**Comment by formvoltron** [comment]
How about providing support for sqlite4java out of the box?

**Comment by vkmsua** [comment]
I've created the following implementation to make it possible to use SQLite in conjunction with j2objc
https://github.com/vkmsua/sqlighter-4-j2objc .

**Comment by confile** [comment]
@vkmsua looks good. A little bit more documentation would help.

**Comment by tomball** [comment]
This looks great, Vlad! May I add it to our list of open-source libraries
<http://j2objc.org/docs/Projects-that-use-J2ObjC.html#open-source-projects>?

**Comment by vals-productions** [comment]
@ confile I have made some updates to the documentation, with more to come.

**Comment by vals-productions** [comment]
Tom, yes, please. I'd be happy for the project to be on the list.

**Comment by tomball** [comment]
Added sqlighter to list of [j2objc open-source libraries](http://j2objc.org/docs/Projects-that-use-J2ObjC.html#open-source-projects).

**Comment by tomball** [comment]
Thanks for your contributions!

**Comment by confile** [comment]
@vals-productions Lib looks great it would be awesome to have a doc like this: https://github.com/stephencelis/SQLite.swift/blob/master/Documentation/Index.md#sqliteswift-documentation

Where Select, Insert, Delete, Update, Create, etc. are explained with an example.

**Comment by vals-productions** [comment]
@confile Right now the doc has "Going By Example" provision with select, insert, update, delete and create examples for a particular data sample. I can extend it with more wording and explanations.

https://github.com/vals-productions/sqlighter#going-by-example

**Comment by confile** [comment]
@vals-productions Are you plan to actively maintain and develop this lib?

**Comment by vals-productions** [comment]
@confile Yes.

**Comment by sbosley** [comment]
For those who are interested, yet another option to consider: I've recently pushed an experimental branch for j2objc support to Yahoo's SquiDB library ([branch found here](https://github.com/yahoo/squidb/tree/ios_bindings_v2)). 

SquiDB was designed as a wrapper around the Android SQLite APIs and provides higher-level DAO functions and utilities for database I/O and constructing queries. This branch refactors the library to remove incidental Android dependencies from the core functionality and adds support for working with j2objc. Low-level SQLite access on iOS is accomplished via a fork/port of the android.database.sqlite package that removes OS-specific dependencies (e.g. Parcelable and ContentValues, neither of which are essential to SquiDB) and re-implements the native components like SQLiteConnection and CursorWindow in Objective-C rather than C++ (see the `squidb-ios` project). 

Because it's a straightforward port of the android.database.sqlite package, SQLite access should have nearly identical behavior characteristics on both platforms, and a large subset of the Android SQLiteDatabase APIs are available via a common ISQLiteDatabase interface. Adapter classes are included in the `squidb-android` and `squidb-ios` models to facilitate plugging in the SQLite APIs appropriate to either platform -- in your application code, you interact only with a SquidDatabase instance that wraps these lower level APIs.

The branch is definitely still experimental -- we need to test more thoroughly for any memory leaks on iOS, it is not yet being used in any production app, etc. -- but the full unit test suite is passing on both platforms. Apologies that this branch is not yet very well documented, but those interested should be able to get a good idea of how the pieces fit together by examining the `squidb-tests` and `squidb-ios-tests` projects, and we'll add more documentation in the coming days. We're intending to continue developing this going forward and would welcome community feedback!

**Comment by tomball** [comment]
Nice! Let us know when you believe the major bugs are shaken out, and we'll
add it to the list of J2ObjC apps and projects page.

**Comment by tomball** [comment]
@sbosley: do any Yahoo apps use SquiDB? Just interested, not trying to get any proprietary info. :-)

**Comment by sbosley** [comment]
@tomball yep! Android-only at the moment, but a few production apps have components using SquiDB, including the new Mail app and our SmartContacts app.

**Comment by tomball** [comment]
@sabosley Let me know when the iOS versions of those app are accepted by
the App Store if you'd like them added to the J2ObjC apps page
<http://j2objc.org/docs/Projects-that-use-J2ObjC.html>, or if you just want
congratulations. :-)

**Comment by gingo** [comment]
@tomball @chemjournal @confile finally joogar is on GitHub:

https://github.com/skoumalcz/joogar

We use it in this app (approved by Apple without any complains):

https://itunes.apple.com/us/app/prague-minos-guide/id427496512?mt=8

**Comment by ribads** [comment]
What's the update on this

**Comment by vals-productions** [comment]
@ribads , speaking of SQLite, SQLighter referenced in this thread will work
http://j2objc.org/docs/Projects-that-use-J2ObjC.html
https://github.com/vals-productions/sqlighter

**Comment by jdkoren** [comment]
@tomball [Yahoo Esports for iOS](https://itunes.apple.com/us/app/yahoo-esports/id1100906320) is using J2ObjC to cross compile our database layer, which is shared by the Android app and uses SquiDB mentioned earlier by @sbosley. We've merged the experimental branch into master and plan to release artifacts for version 3.0 very soon.

**Comment by formvoltron** [comment]
@jdkoren Thank you for sharing this!   Are these artifacts you mention available on github now?   I'd like to try an experimental project that uses SquiDB on Sqlite, cross compiling on android & iOS.

**Comment by sbosley** [comment]
@formvoltron the SquiDB 3.0 source code was merged into the master branch a few days ago. We haven't published jars for android development to jcenter() yet, but we intend to do so within the next couple of days. For iOS, the current solution is just to use j2objc to build from source, so if you want to clone the source and simply build the project directly on both platforms, you can definitely do that. You can let us know on that repo if you encounter any issues. Happy hacking!

**Comment by ManiPrakashsinghal** [comment]
my code is in java and i m run this code in xcode using j2objc and trying to connect with database but  
driver error come. so how to solve it and error is in xcode-----

---Get Connection   jdbcCorejdbcCore----<SrcSagSQLiteCore: 0x60800005d220>
java.lang.ClassNotFoundException: SQLite.JDBCDriver
	at 0x000000010c067fea java.lang.ClassNotFoundException.<init>() + 22
	at 0x000000010c171af6 java.lang.Class.forName_() + 930
	at 0x000000010c030663 src.sag.SQLiteCore.loadDriver() + 35
	at 0x000000010c03014d src.sag.SQLiteCore.getConnection() + 205
	at 0x000000010c014854 src.sag.SqliteDemo.getTestConnectionTestWay2() + 644
	at 0x000000010c011222 ViewController.createDatabase() + 514
	at 0x000000010c010fd2 ViewController.viewDidLoad() + 98
	at 0x000000010c8e3c99 UIViewController.loadViewIfRequired() + 1258
	at 0x000000010c8e40cc UIViewController.view() + 27
	at 0x000000010c7adc51 UIWindow.addRootViewControllerViewIfPossible() + 71
	at 0x000000010c7ae3a2 UIWindow._setHidden:forced:() + 293
	at 0x000000010c7c1cb5 UIWindow.makeKeyAndVisible() + 42
	at 0x000000010c73ac89 UIApplication._callInitializationDelegatesForMainScene:transitionContext:() + 4818
	at 0x000000010c740de9 UIApplication._run() + 1731
	at 0x000000010c73df69 UIApplication.workspaceDidEndTransaction:() + 188
	at 0x000000010fe0559c FBSSerialQueue._performNext() + 189
	at 0x000000010fe05925 FBSSerialQueue._performNextFromRunLoopSource() + 45
	at 0x000000010c73c7e6 UIApplication._run() + 434

**Comment by blazek** [comment]
SquiDB seems to be abandoned by Yahoo, last commit Jan 29, 2018, 
https://github.com/yahoo/squidb/issues/290
there are however maintained forks, we are trying that with the most recent commit
https://github.com/mobilemindtec/squidb
