### ISSUE TITLE
A Class With An ObjectiveCName Annotation Omits Include

### ISSUE THREAD

**Issue by thebcwhite** [google/j2objc#334]
j2objc: v0.9

For a simple pojo class, "MyClass", it transpiles into something like this in the MyClass.m file:

#include "MyClass.h"
@implementation ComExampleProjectMyClass
...
@end

I tried adding @ObjectiveCName("MyClass") before it and now get the following in the MyClass.m file:

@implementation MyClass
...
@end

The new name is all well and good but the #include directive is missing!  The result is that the generated .m file will not compile.

**Comment by jonnolen** [comment]
I am having the same problem using 0.9.5

**Comment by harrycheung** [comment]
Allowing this sounds like all kinds of sketch. If you change the class name, then all translated code should use the new class name.

If your goal is to drop the package from your class, then just use a prefix file with a blank prefix.

https://github.com/google/j2objc/wiki/Package-Prefixes
```
# no package prefix
com.google.j2objc: 
```

**Comment by bcwhite0** [comment]
Package prefixes works for me.  Thanks!

**Comment by tomball** [comment]
Works in latest source:

```
$ cat com/example/project/MyClass.java 
package com.example.project;

import com.google.j2objc.annotations.ObjectiveCName;

@ObjectiveCName("MyClass")
public class MyClass {}
$ j2objc com/example/project/MyClass.java 
translating com/example/project/MyClass.java
Translated 1 file: 0 errors, 0 warnings
$ head com/example/project/MyClass.m
//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/example/project/MyClass.java
//

#include "IOSClass.h"
#include "J2ObjC_source.h"
#include "com/example/project/MyClass.h"
#include "com/google/j2objc/annotations/ObjectiveCName.h"
```
