### ISSUE TITLE
Error Adding the JreEmulation project in Xcode project

### ISSUE THREAD

**Issue by cmdatab** [google/j2objc#335]
I've followed the giudelines of the wiki, when i test the JreEmulation in Xcode 5.0.2 with j2objc-0.8.8; the build works but the test failed with 11 errors
Someone can help me? Thanks.

jre_emul_tests Group
/jre_emul/Classes/IOSPrimitiveClassTest.m
/jre_emul/Classes/IOSPrimitiveClassTest.m: test failure: -[IOSPrimitiveClassTest testBooleanType] failed: 'java.lang.Boolean' should be equal to 'JavaLangBoolean' incorrect object type name

/jre_emul/Classes/IOSPrimitiveClassTest.m: test failure: -[IOSPrimitiveClassTest testByteType] failed: 'java.lang.Byte' should be equal to 'JavaLangByte' incorrect object type name

/jre_emul/Classes/IOSPrimitiveClassTest.m: test failure: -[IOSPrimitiveClassTest testCharType] failed: 'java.lang.Character' should be equal to 'JavaLangCharacter' incorrect object type name

/jre_emul/Classes/IOSPrimitiveClassTest.m: test failure: -[IOSPrimitiveClassTest testDoubleType] failed: 'java.lang.Double' should be equal to 'JavaLangDouble' incorrect object type name

/jre_emul/Classes/IOSPrimitiveClassTest.m: test failure: -[IOSPrimitiveClassTest testFloatType] failed: 'java.lang.Float' should be equal to 'JavaLangFloat' incorrect object type name

/jre_emul/Classes/IOSPrimitiveClassTest.m: test failure: -[IOSPrimitiveClassTest testIntType] failed: 'java.lang.Integer' should be equal to 'JavaLangInteger' incorrect object type name

/jre_emul/Classes/IOSPrimitiveClassTest.m: test failure: -[IOSPrimitiveClassTest testLongType] failed: 'java.lang.Long' should be equal to 'JavaLangLong' incorrect object type name

/jre_emul/Classes/IOSPrimitiveClassTest.m: test failure: -[IOSPrimitiveClassTest testShortType] failed: 'java.lang.Short' should be equal to 'JavaLangShort' incorrect object type name

/jre_emul/Classes/JavaLangReflectMethodTest.m
/jre_emul/Classes/JavaLangReflectMethodTest.m: test failure: -[JavaLangReflectMethodTest testGetReturnType] failed: 'int' should be equal to 'JavaLangInteger' wrong return type returned

/jre_emul/Classes/NSObject_JavaObjectTest.m
/jre_emul/Classes/NSObject_JavaObjectTest.m: test failure: -[NSObject_JavaObjectTest testGetClass] failed: 'java.util.ArrayList' should be equal to 'JavaUtilArrayList' incorrect class name

/jre_emul/Classes/NSObject_JavaObjectTest.m: test failure: -[NSObject_JavaObjectTest testGetClass] failed: 'java.util.ArrayList' should be equal to 'JavaUtilArrayList' incorrect class name

Warning: no rule to process file '/jre_emul/Classes/NSObject+JavaObject.m' of type sourcecode.c.objc for architecture armv6
Warning: no rule to process file '/jre_emul/Classes/NSString+JavaString.m' of type sourcecode.c.objc for architecture armv6
Warning: no rule to process file '/jre_emul/Classes/IOSArrayTest.m' of type sourcecode.c.objc for architecture armv6
Warning: no rule to process file '/jre_emul/Classes/IOSObjectArrayTest.m' of type sourcecode.c.objc for architecture armv6
Warning: no rule to process file '/jre_emul/Classes/IOSPrimitiveClassTest.m' of type sourcecode.c.objc for architecture armv6
Warning: no rule to process file '/jre_emul/Classes/JavaLangReflectMethodTest.m' of type sourcecode.c.objc for architecture armv6
Warning: no rule to process file '/jre_emul/Classes/NSObject_JavaObjectTest.m' of type sourcecode.c.objc for architecture armv6
Warning: no rule to process file '/jre_emul/Classes/NSString_JavaStringTest.m' of type sourcecode.c.objc for architecture armv6
Warning: no rule to process file '/jre_emul/Classes/IOSClassTest.m' of type sourcecode.c.objc for architecture armv6

**Comment by Qata** [comment]
This is sufficiently old that it can be closed despite not being resolved. Xcode is two major versions older now.

**Comment by tomball** [comment]
Good point, thanks.
