### ISSUE TITLE
Assert containing % causes XCode warnings

### ISSUE THREAD

**Issue by thelordoftheboards** [google/j2objc#342]
I am using j2objc 0.9, XCode 5.1. The following code:

assert calendarMonthlyWeekStart % CF.s_timeOneDay == 0;

Translates into:

  NSAssert(calendarMonthlyWeekStart % ComCodefoundriesIntengCommonCF_s_timeOneDay == 0, @"/[path edited out]/[File name edited out].java:99 condition failed: assert calendarMonthlyWeekStart % CF.s_timeOneDay == 0;");

and produces the following warnings:

/[path edited out]/[File name edited out].m:143:251: Flag ' ' results in undefined behavior with 'C' conversion specifier
/[path edited out]/[File name edited out].m:143:252: More '%' conversions than data arguments

**Comment by tomball** [comment]
Fixed in current release -- we now use a JreAssert macro instead of calling NSLog directly.
