### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by stalexxx** [google/j2objc#349]
I'm new to the project. I have cloned repository and try simply to compile. I'v got

Building j2objc jar
building jre_emul.jar
apache_harmony/classlib/modules/luni/src/main/java/java/util/EnumMap.java:155: error: incompatible types: Object cannot be converted to E
            return type.get(new MapEntry(enumMap.keys[prePosition],
                           ^
  where E is a type-variable:
    E extends Object declared in class EnumMapIterator
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error
make[1]: **\* [/Users/alex/projects/j2objc/jre_emul/build_result/jre_emul.jar] Error 1
make: **\* [jre_emul_jar_dist] Error 2

**Comment by alizainprasla** [comment]
@tomball, I am getting this error.

```
Building libxalan.a
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo -create /Users/alizain/Downloads/j2objc-master/xalan/build_result/objs-appletvos/libxalan.a /Users/alizain/Downloads/j2objc-master/xalan/build_result/objs-appletvsimulator/libxalan.a -output /Users/alizain/Downloads/j2objc-master/xalan/build_result/appletvos/libxalan.a
building j2objc_xalan.jar
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
```

**Comment by tomball** [comment]
That's not a compilation error. You'll get the same notice building Xalan with javac, since the issue being reported is that Xalan uses or overrides deprecated API (which it does):
```
$ cd j2objc/xalan
$ javac -d /tmp/xalan -sourcepath third_party/android/platform/external/apache-xml/src/main/java `find third_party -name '*.java'`
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
```

**Comment by tomball** [comment]
Closing this issue since this notice is reported by javac (which j2objc uses as its front-end) and since `-Xlint:-deprecation` doesn't suppress it.
