### ISSUE TITLE
java reflect set field value bugs

### ISSUE THREAD

**Issue by kingxt** [google/j2objc#351]
when I update j2objc lib from 0.8.8 to 0.9.1 
the code below

	private static <T> void setFieldToInstance(Field field, String pro, T instance, JSONObjectDef jsonObj) throws Exception
	{
		if (pro != null && !"".equals(pro))
		{
			if (!jsonObj.has(pro))
			{
				return;
			}
			if (field.getType() == int.class)
			{
				field.setInt(instance, Integer.parseInt(jsonObj.getString(pro)));
			}
			else if (field.getType() == String.class)
			{
				field.set(instance, jsonObj.getString(pro));
			}
			else if (field.getType() == double.class)
			{
				field.setDouble(instance, Double.parseDouble(jsonObj.getString(pro)));
			}
			else if (field.getType() == float.class)
			{
				field.setFloat(instance, Float.parseFloat(jsonObj.getString(pro)));
			}
			else if (field.getType() == long.class)
			{
				field.setLong(instance, Long.parseLong(jsonObj.getString(pro)));
			}

when run at field.set****, app crash, the instance bad access

**Comment by tomball** [comment]
Cannot reproduce with the following:
```
import java.lang.reflect.*;

class FieldSet {
  int i;
  String s;
  double d;
  float f;
  long l;

  private static <T> void setFieldToInstance(Field field, T instance, String s) throws Exception {
    if (field.getType() == int.class) {
        field.setInt(instance, Integer.parseInt(s));
    }
    else if (field.getType() == String.class) {
        field.set(instance, s);
    }
    else if (field.getType() == double.class) {
        field.setDouble(instance, Double.parseDouble(s));
    }
    else if (field.getType() == float.class) {
        field.setFloat(instance, Float.parseFloat(s));
    }
    else if (field.getType() == long.class) {
        field.setLong(instance, Long.parseLong(s));
    }
  }

  public static void main(String... args) throws Exception {
    FieldSet fs = new FieldSet();
    setFieldToInstance(FieldSet.class.getDeclaredField("i"), fs, "12345");
    setFieldToInstance(FieldSet.class.getDeclaredField("s"), fs, "abcde");
    setFieldToInstance(FieldSet.class.getDeclaredField("d"), fs, "123.45");
    setFieldToInstance(FieldSet.class.getDeclaredField("f"), fs, "987.65");
    setFieldToInstance(FieldSet.class.getDeclaredField("l"), fs, "98765");
    System.out.printf("i=%d s=%s d=%f f=%f l=%d\n", fs.i, fs.s, fs.d, fs.f, fs.l);
  }
}
```
I couldn't use the j2objc_bugs project because it doesn't have Java sources, and so its files can't be retranslated to be used with latest j2objc version.
