### ISSUE TITLE
boxing from reflection call not working on device, returning 0

### ISSUE THREAD

**Issue by hsponberg** [google/j2objc#352]
It seems that boxing the result of a reflection method invocation does not work on an actual iOS device. (It is working on the iOS simulator).
I have a class with a method that returns a primitive, double for getTemperature

```
Foo {

  double temp = 22.2;

  double getTemperature() {
     System.out.println("getTemperature called " + temp);
     return temp;
  }
}
```
When I get a method through reflection 
```Method m = classOfFoo.getMethod("getTemperature", ...);```

and invoke the method on an object of Foo
```Object temp = m.invoke(objectOfFoo)```

The value of temp is correct in the simulator, but is always 0 on an actual device.

The generated Objective-C code is:
```
id value = [((JavaLangReflectMethod *) nil_chk(m)) invokeWithId:object withNSObjectArray:
    [IOSObjectArray arrayWithLength:0 type:[IOSClass classWithClass:[NSObject class]]]];

[[JavaLangSystem out] printlnWithNSString:[NSString stringWithFormat:@"The value type is %@",
    [nil_chk(value) getClass]]];

double d = [((JavaLangDouble *) check_class_cast(value, [JavaLangDouble class])) doubleValue];

[[JavaLangSystem out] printlnWithNSString:[NSString stringWithFormat:@" the value is %@ %f", value, d]];
```
Which prints out (on the device):

getTemperature called 22.2
The value type is class java.lang.Double
 the value is 2.124585248303004e-314 0.000000

**Comment by tomball** [comment]
Fixed in 0.9.2.
