### ISSUE TITLE
Problem in translating static imports when using package mapping

### ISSUE THREAD

**Issue by mahmoud-khalifa** [google/j2objc#359]
I'm trying to translate a class that has static import to a method in another class, and it works only when there is no package mapping. But when I use package mapping, the translated code doesn't include the full path of the imported class

Here is a simple example 
TestClass.java
---------------
	package com.staticimport;
	
	import static com.staticimport.DependentClass.staticMethod;

	public class TestClass {
    	public static void testMethod(){
        	staticMethod();
	    }
	}

DependentClass.java
--------------------
	package com.staticimport;
	
	public class DependentClass {
    	public static void staticMethod(){

	    }
	}

package-prefix-mapping.properties
---------------------------------------------
    com.staticimport : staticImport

TestClass.m
----------------
    
    #include "com/staticimport/TestClass.h"
    #include "staticImportDependentClass.h"
    
    @implementation staticImportTestClass
    
    + (void)testMethod {
      [staticImportDependentClass staticMethod];
    }
    
    - (id)init {
      return [super init];
    }
    
    + (J2ObjcClassInfo *)__metadata {
      static J2ObjcMethodInfo methods[] = {
        { "testMethod", NULL, "V", 0x9, NULL },
        { "init", NULL, NULL, 0x1, NULL },
      };
      static J2ObjcClassInfo _staticImportTestClass = { "TestClass", "com.staticimport", NULL, 0x1, 2, methods, 0, NULL, 0, NULL};
      return &_staticImportTestClass;
    }
    
    @end
    
so i got the following compilation error

	Compiling com/staticimport/TestClass.m
	com/staticimport/TestClass.m:9:10: fatal error: 'staticImportDependentClass.h' file not found
	#include "staticImportDependentClass.h"
	         ^
	1 error generated.

It should be translated as the following (which is translated correctly where there is no package mapping provided)

    #include "com/staticimport/DependentClass.h"

**Comment by tomball** [comment]
Cannot reproduce, appears fixed.
