### ISSUE TITLE
Mac App hang at CFGetRetainCount with Chinese String in data?

### ISSUE THREAD

**Issue by liqiang** [google/j2objc#368]
I have a Mac App using j2objc lib, it runs normal when there's only English characters ( from files ), but when there are Chinese Character it hang at CFGetRetainCount. 
The code actually finish running, but App was hanging, it seems ARC was running try to release memory. Any solutions ?

**Comment by tomball** [comment]
Cannot reproduce. Please reopen with an attached test if it continues to be an issue.
