### ISSUE TITLE
EXC_BAD_ACCESS on ARC release memory?

### ISSUE THREAD

**Issue by liqiang** [google/j2objc#373]
Got a crash with EXC_BAD_ACCESS, it seems runtime is releasing memory to a released object, following is the stacktrace: 

 * thread #9: tid = 0x225f2, 0x00007fff915c0097 libobjc.A.dylib`objc_msgSend + 23, queue = 'com.apple.root.default-overcommit-priority', stop reason = EXC_BAD_ACCESS (code=EXC_I386_GPFLT)
  * frame #0: 0x00007fff915c0097 libobjc.A.dylib`objc_msgSend + 23
    frame #1: 0x000000010065849a myapp`MaybeQueueReferences + 442
    frame #2: 0x0000000100658299 myapp`ReferentSubclassRelease + 25
    frame #3: 0x00007fff915c265a libobjc.A.dylib`(anonymous namespace)::AutoreleasePoolPage::pop(void*) + 502
    frame #4: 0x00007fff897fe0ce libdispatch.dylib`_dispatch_root_queue_drain + 402
    frame #5: 0x00007fff897ff177 libdispatch.dylib`_dispatch_worker_thread2 + 40
    frame #6: 0x00007fff939b0ef8 libsystem_pthread.dylib`_pthread_wqthread + 314

**Comment by tomball** [comment]
No test to reproduce, assume fixed due to several recent ARC-related bug fixes.
