### ISSUE TITLE
Method mapping translates declaration but fails to translate invocation

### ISSUE THREAD

**Issue by nbransby** [google/j2objc#378]
The line in my mapping file is below:

com.app.facade.MockAppFacade.scheduleHandler(Lcom/app/facade/LoadHandler;Ljava/lang/Object;)Lcom/app/facade/LoadFuture;=ComAppFacadeMockAppFacade scheduleHandler:(id<ComAppFacadeLoadHandler>)handler mockData:(id)mockData

If this is not enough to go on I can provide the source

**Comment by ex3ndr** [comment]
Any news?

**Comment by kstanger** [comment]
I happen to be doing some work right now that should resolve this issue.
Stay tuned...

**Comment by ex3ndr** [comment]
Not yet?

**Comment by kstanger** [comment]
It's completed. Will be available in the next sync and release. In addition, method renamings will no longer require a full signature for the new name, just a selector name.

**Comment by kstanger** [comment]
Fix is available in the source now. I'd close this issue, but it's already closed...
