### ISSUE TITLE
Mockito.spy() Segmentation fault in 0.9.3

### ISSUE THREAD

**Issue by foens** [google/j2objc#411]
Running a Junit test using a Mockto spy results in a segmentation fault.

    JUnit version 4.10
    ../runTest.sh: line 25:  4515 Segmentation fault: 11  $J2OBJC_OUT/Tests org.junit.runner.JUnitCore MockitoTest

The MockitoTest.java source:

    import static org.mockito.Mockito.*;
    import org.junit.Test;
    import java.io.StringWriter;
    
    public class MockitoTest {
     @Test
     public void isXxx_returnsFalseForIncompatibleType() throws Exception {
        StringWriter w = spy( new StringWriter() );
        verify(w, never()).close();
     }
    }

I compile and execute it with (runTest.sh):

    #!/bin/bash
    set -e # Any subsequent commands which fail will cause the shell script to exit immediately
    
    J2OBJC_PATH=~/.gradle/j2objc-0.9.3
    J2OBJC=$J2OBJC_PATH/j2objc
    J2OBJCC=$J2OBJC_PATH/j2objcc
    J2OBJC_OUT=./build/
    
    # Cleanup
    if [ -d "$J2OBJC_OUT" ]; then
      rm -r $J2OBJC_OUT
    fi
    
    # Create build dir
    mkdir -p $J2OBJC_OUT
    
    # Translate main files
    CLASSPATH=${J2OBJC_PATH}/lib/junit-4.10.jar:${J2OBJC_PATH}/lib/mockito-core-1.9.5.jar:$J2OBJC_PATH/lib/jre_emul.jar
    ${J2OBJC} -classpath $CLASSPATH MockitoTest.java 
    
    # Create executable
    ${J2OBJCC} -ObjC -ljunit -lmockito -I $J2OBJC_OUT -o $J2OBJC_OUT/Tests MockitoTest.m
    
    # Run test
    $J2OBJC_OUT/Tests org.junit.runner.JUnitCore MockitoTest

**Comment by tomball** [comment]
Both tests now pass.
