### ISSUE TITLE
Wildcard support in package prefixes

### ISSUE THREAD

**Issue by zubchenok** [google/j2objc#418]
In my case all java classes have different names. I have a lot of modules and packages and it is quite annoying to add them all into prefixes.properites file.
It would be nice to have a possibility to set prefixes for all subpackages, specifying in prefixes.properties something like this

com.mycompany.**: MC

**Comment by tomball** [comment]
A '*' wildcard is now supported, and [the Package Prefixes doc](http://j2objc.org/docs/Package-Prefixes.html) has been updated.
