### ISSUE TITLE
IndexOutOfBoundsException not thrown. NSRangeException thrown instead

### ISSUE THREAD

**Issue by foens** [google/j2objc#421]
The following test works in Java but not when translated with j2objc.

    import org.junit.Test;

    import static org.junit.Assert.fail;

    public class TestJ2objc {
     @Test
     public void test() throws Exception {
         try {
             String foo = "Test";
             foo.substring(5);
             fail("Should throw IndexOutOfBoundsException");
         } catch (IndexOutOfBoundsException e) {
         }
     }
    }

The output given is:

    JUnit version 4.10
    .2014-10-27 14:04:30.781 Tests[14048:507] *** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSCFConstantString substringFromIndex:]: Index 5 out of bounds; string length 4'
    *** First throw call stack:
    (
        0   CoreFoundation                      0x00007fff8dcdf25c __exceptionPreprocess + 172
        1   libobjc.A.dylib                     0x00007fff90c0de75 objc_exception_throw + 43
        2   CoreFoundation                      0x00007fff8dcdf10c +[NSException raise:format:] + 204
        3   Foundation                          0x00007fff9575df41 -[NSString substringFromIndex:] + 107
        4   Tests                               0x000000010bda8e6b -[TestJ2objc test] + 59
        5   CoreFoundation                      0x00007fff8dbca9ac __invoking___ + 140
        6   CoreFoundation                      0x00007fff8dbca814 -[NSInvocation invoke] + 308
        7   Tests                               0x000000010c06161f -[JavaLangReflectMethod invokeWithId:withNSObjectArray:] + 535
        8   Tests                               0x000000010bd6be64 +[OrgJunitRunnersModelFrameworkMethod runReflectiveCall0WithJavaLangReflectMethod:withId:withNSObjectArray:] + 64
        9   Tests                               0x000000010bd54133 -[OrgJunitInternalRunnersModelReflectiveCallable run] + 19
        10  Tests                               0x000000010bd5b0ba -[OrgJunitRunnersParentRunner runLeafWithOrgJunitRunnersModelStatement:withOrgJunitRunnerDescription:withOrgJunitRunnerNotificationRunNotifier:] + 161
        11  Tests                               0x000000010bd5af4f -[OrgJunitRunnersParentRunner runChildrenWithOrgJunitRunnerNotificationRunNotifier:] + 293
        12  Tests                               0x000000010bd5b391 -[OrgJunitRunnersParentRunner runWithOrgJunitRunnerNotificationRunNotifier:] + 177
        13  Tests                               0x000000010bd5af4f -[OrgJunitRunnersParentRunner runChildrenWithOrgJunitRunnerNotificationRunNotifier:] + 293
        14  Tests                               0x000000010bd5b391 -[OrgJunitRunnersParentRunner runWithOrgJunitRunnerNotificationRunNotifier:] + 177
        15  Tests                               0x000000010bd55e44 -[OrgJunitRunnerJUnitCore runWithOrgJunitRunnerRunner:] + 217
        16  Tests                               0x000000010bd55af8 -[OrgJunitRunnerJUnitCore runMainWithOrgJunitInternalJUnitSystem:withNSStringArray:] + 879
        17  Tests                               0x000000010bd55661 +[OrgJunitRunnerJUnitCore runMainAndExitWithOrgJunitInternalJUnitSystem:withNSStringArray:] + 81
        18  CoreFoundation                      0x00007fff8dbca9ac __invoking___ + 140
        19  CoreFoundation                      0x00007fff8dbca814 -[NSInvocation invoke] + 308
        20  Tests                               0x000000010c06161f -[JavaLangReflectMethod invokeWithId:withNSObjectArray:] + 535
        21  Tests                               0x000000010c06529c main + 386
        22  libdyld.dylib                       0x00007fff8cef75fd start + 1
    )
    libc++abi.dylib: terminating with uncaught exception of type NSException
    Error: signal 6:
    0   Tests                               0x000000010c0650e4 signalHandler + 39
    1   libsystem_platform.dylib            0x00007fff8f1195aa _sigtramp + 26
    2   ???                                 0x0000000000000000 0x0 + 0
    3   libsystem_c.dylib                   0x00007fff91ef7b1a abort + 125
    4   libc++abi.dylib                     0x00007fff8a4a7f31 __cxa_bad_cast + 0
    5   libc++abi.dylib                     0x00007fff8a4cd952 _ZL26default_unexpected_handlerv + 0
    6   libobjc.A.dylib                     0x00007fff90c0e30d _ZL15_objc_terminatev + 103
    7   libc++abi.dylib                     0x00007fff8a4cb1d1 _ZSt11__terminatePFvvE + 8
    8   libc++abi.dylib                     0x00007fff8a4cae7b __cxa_rethrow + 109
    9   libobjc.A.dylib                     0x00007fff90c0e049 objc_exception_rethrow + 40
    10  Tests                               0x000000010bd55e99 -[OrgJunitRunnerJUnitCore runWithOrgJunitRunnerRunner:] + 302
    11  Tests                               0x000000010bd55af8 -[OrgJunitRunnerJUnitCore runMainWithOrgJunitInternalJUnitSystem:withNSStringArray:] + 879
    12  Tests                               0x000000010bd55661 +[OrgJunitRunnerJUnitCore runMainAndExitWithOrgJunitInternalJUnitSystem:withNSStringArray:] + 81
    13  CoreFoundation                      0x00007fff8dbca9ac __invoking___ + 140
    14  CoreFoundation                      0x00007fff8dbca814 -[NSInvocation invoke] + 308
    15  Tests                               0x000000010c06161f -[JavaLangReflectMethod invokeWithId:withNSObjectArray:] + 535
    16  Tests                               0x000000010c06529c main + 386
    17  libdyld.dylib                       0x00007fff8cef75fd start + 1

The problem seems to be that `NSRangeException` is thrown instead of `IndexOutOfBoundsException`. I can see that the reason for this is that Java's `String` is translated to a `NSString`, which of course does not throw any Java related exceptions. However, I felt this report was needed to at least show this problem.

**Comment by tomball** [comment]
Fixed in latest source.
