### ISSUE TITLE
DateFormat.parse() regression in 0.9.5

### ISSUE THREAD

**Issue by nbransby** [google/j2objc#437]
So the following code in java...

        SimpleDateFormat jsonDateFormat =  new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        System.out.println(jsonDateFormat.parse("2014-12-12 10:00:00"));

...results in the output....

        Fri Dec 12 10:00:00 GMT 2014

.... while the translated version results in....

        Exception in thread "main" java.text.ParseException: Unparseable date: "2014-12-12 10:00:00" (at offset 14)
	        at 0x00000001087d0959 java.lang.Exception.<init>() + 39
        	at 0x0000000108890776 java.text.ParseException.<init>() + 108
	        at 0x0000000108882a32 java.text.DateFormat.parse() + 221
        	at 0x0000000108759d62 Main.main() + 194
        	at 0x0000000108759c8d Main.main() + 29

Works fine in 0.9.3 (Didn't check 0.9.4), its the 00 minutes or seconds that cause the problem

**Comment by nbransby** [comment]
Is there a workaround that can be applied in the meantime? Apple aren't exactly rapid at fixing bugs

**Comment by kstanger** [comment]
The best suggestion I can offer right now is to try to comment out the code that sets the multiplier
https://github.com/google/j2objc/blob/765354b620b2c0248945b27062209620d4cf5e40/jre_emul/android/libcore/luni/src/main/java/libcore/icu/NativeDecimalFormat.java#L77.
I can't guarantee that it won't cause a regression elsewhere, but it might resolve your specific issue.

**Comment by tomball** [comment]
Long-term we want to rewrite our I18N support to use ICU directly. This
will avoid any bugs in Foundation classes like NSNumberFormatter, but
that's not a quick fix.

**Comment by foens** [comment]
Bonus info: Not fixed in 0.9.6.

**Comment by giladbeeri** [comment]
We encountered a `ParseException` with timestamps containing timezone offset of `+0000`, in the same method.

Our resolution is to replace `+0000` with `Z` before we input the data to the converted code, but IMO it should really be fixed in j2objc.

**Comment by tomball** [comment]
Fixed in current source (#661 was a duplicate).
