### ISSUE TITLE
EnclosingClass.super.methodCall() doesn't seem to work properly 

### ISSUE THREAD

**Issue by nbransby** [google/j2objc#460]
EnclosingClass.this.methodCall() is fine but super generates code that complies with a warning and crashes with does not recognise selector

**Comment by kstanger** [comment]
I'm unable to reproduce any issue. With your example code the "run" method produces the following translation, which executes correctly.

```` objective-c
- (void)run {
  ((void (*)(id, SEL))[Test instanceMethodForSelector:@selector(methodCall)])(this$0_, selector(methodCall));
}
````
