### ISSUE TITLE
Travis CI - Build and upload artifacts to tags

### ISSUE THREAD

**Issue by foens** [google/j2objc#462]
Hi.

I would really like that Travis would build and upload build artifacts each time a new [github tag](https://github.com/google/j2objc/tags) is created in the repository. This issue should be used to track the discussion of such a feature. 

Benefits:

* You do not have to manually build and upload release artifacts when you release.
* The release builds are scripted and thus problems such as #436 should not emerge.
* It is much easier to release hotfixes for critical issues to the j2objc userbase. An example could be #442. Such hotfixes can be delivered by simply adding a tag `0.9.5-http-hotfix` and Travis would upload the artifact to it automatically.

I have a build setup which automatically downloads and extracts a given j2objc version. It would thus be able to fetch those hotfixes and test them, given you a much faster feedback cycle. It would be a rather large job to change such a script to instead fetch the sources and compile it.

Travis-CI has a feature to [automatically upload build artifacts to github tags](http://docs.travis-ci.com/user/deployment/releases/). I am considering using some time on getting this to work and making a pull request, but since this would require some time being spent on setting it up, I would like to hear:

* Would you merge such a pull request?
* Would you consider making tags such as `0.9.5.http-hotfix`?
* Are you already working on this feature, thus I should not start investigating myself?

**Comment by tomball** [comment]
Google's legal folks won't allow this feature, because it requires that an outside entity has commit rights to one of its repositories. I'm looking into other options, and welcome any ideas.
