### ISSUE TITLE
In Swift, IOSClass doesn't behave correctly.

### ISSUE THREAD

**Issue by harrycheung** [google/j2objc#468]
A little background first: When Swift imports Objective-C code, it changes constructor signatures to a simpler form. For example, in Objective-C, this constructor call:
```
[[Person alloc] initWithFirstName:@"John" lastName:@"Doe"];
```
becomes this in Swift:
```
Person(firstName: "John", lastName: "Doe")
```

Keeping that in mind, let's look at IOSClass. IOSClass has a few static methods for creating IOSClass instances.
```
// IOSClass Getters.
+ (IOSClass *)classWithClass:(Class)cls;
+ (IOSClass *)classWithProtocol:(Protocol *)protocol;
+ (IOSClass *)arrayClassWithComponentType:(IOSClass *)componentType;
+ (IOSClass *)classForIosName:(NSString *)iosName;
+ (IOSClass *)primitiveClassForChar:(unichar)c;
```
Here's the problem. In Swift, Xcode thinks these static methods are actual constructors. You would expect the call to look like:
```
IOSClass.classWithClass(SomeClass.self)
```
but instead, code sense autocompletes to this:
```
IOSClass(class: SomeClass.self)
```
This looks wrong already since that is a constructor call which doesn't exist. Try compiling and you get a  syntax error.

I suspect this is an Xcode bug, but I found a quick fix by renaming 'classWithClass' to 'getClassWithClass'. Considering this will affect a lot of lines of code, I'm posing the solution here first. All tests pass with the renaming.

**Comment by tomball** [comment]
It's an Xcode bug: these can't be true constructors since they are class methods. Somebody on that team didn't think through their "cool" hack.

This is a big issue we can't easily solve, as there are currently 3118 such class methods in the J2ObjC's public headers (you can get the exact number using `egrep -r '^\+ \(.*\).*With.*:' $J2OBJC_HOME/include | wc -l`). I don't have a problem changing the names of the 3 IOSClass getters, but next it will be NSString+JavaString's 17 getters, then the 22 in all the public IOS* headers, then the 244 in java.util, etc.

**Comment by harrycheung** [comment]
More research. I believe Xcode is doing the right thing now. TL;DR: <code>class</code> a reserved word and
```
IOSClass(class: SomeClass.self)
```
is illegal. The factory method in IOSClass needs to be renamed.

I think they did think through the cool hack. See:

https://developer.apple.com/library/ios/documentation/Swift/Conceptual/BuildingCocoaApps/InteractingWithObjective-CAPIs.html
```
For consistency and simplicity, Objective-C factory methods get mapped as convenience 
initializers in Swift. This mapping allows them to be used with the same concise, clear 
syntax as initializers.
```
This means the getters are being translated to constructor syntax correctly. In this particular case, these methods are interpreted as factories since they follow the factory naming scheme of <return class pointer><class>[With or For]<some parameter>:
```
+ (IOSClass *)classWithClass:(Class)cls;
+ (IOSClass *)classWithProtocol:(Protocol *)protocol;
+ (IOSClass *)classForIosName:(NSString *)iosName;
```
Xcode maps the Swift calls as follows:
```
IOSClass(class: SomeClass.self)
IOSClass(protocol: SomeProtocol.self)
IOSClass(forIosName: "SomeClassName")
```
The first two cause syntax errors since <code>class</code> and <code>protocol</code> are reserved words.

There are two options now:

A. Change the parameter from Class/Protocol to something else. IE: <code>classWithClazz</code>
B. Change the method name so that Xcode doesn't generate the mapping. IE: <code>buildClassWithClass</code>.

Using your grep, @tomball, I only found this occurring in <code>IOSClass</code>. The rest of the codebase doesn't appear to show any usage of <code>withClass</code>.

**Comment by tomball** [comment]
Great, that's much simpler (though I disagree with the Swift doc-writers
that all class methods are factory methods, it doesn't matter here). Let's
change classWithClass to classFromClass, and classWithProtocol to
classFromProtocol. Could you hack this in and see if it works for you?
There are classes in jre_emul/Classes plus Proxy.java and TimeZone.java,
and two text references in the translator's StatementGenerator and
EnumWriter. Unfortunately, a quick search found lots of uses in internal
code, so as a project we'll need to deprecate and keep the old method
names, to give developers time to update.

Do you know if Xcode skips or marks deprecated methods in code completion?

**Comment by harrycheung** [comment]
Would you want to change the naming of all 5 class methods? I'm asking
because these two still don't get mapped to Swift constructors:

+ (IOSClass *)arrayClassWithComponentType:(IOSClass *)componentType;
+ (IOSClass *)primitiveClassForChar:(unichar)c;

**Comment by harrycheung** [comment]
<code>classFromClass</code> works. Xcode treats <code>with</code> and <code>from</code> differently. I did a global replace-all for both, and tests passed. 

Regarding, deprecation, I added <code>__deprecated_msg("use classFromClass instead")</code>, and this is what I get with code sense:
![screen shot 2015-01-08 at 4 48 05 pm](https://cloud.githubusercontent.com/assets/98389/5673845/4713f270-9756-11e4-9a25-e1e4fde708d9.png)
![screen shot 2015-01-08 at 4 47 36 pm](https://cloud.githubusercontent.com/assets/98389/5673846/4c105e58-9756-11e4-9751-97021326c164.png)
Unfortunately, in Swift you don't get the crossed out method names
![screen shot 2015-01-08 at 3 29 46 pm](https://cloud.githubusercontent.com/assets/98389/5673951/a04b65fc-9757-11e4-880a-80a8cb65474c.png)
And if it didn't cause a syntax error, you'd see:
![screen shot 2015-01-08 at 4 58 11 pm](https://cloud.githubusercontent.com/assets/98389/5673958/b12b2dda-9757-11e4-911e-37b64af7355b.png)

PR to follow.
