### ISSUE TITLE
private and protected class accessors translated as public 

### ISSUE THREAD

**Issue by brunobowden** [google/j2objc#472]
Private & protected methods and variables appears to be public for a virtually all class members (static or not). The only case where scope is limited is private static method (example below as "privateStaticMethod"). Seen the same error with 0.9.5 and HEAD.

Firstly, start with a class of all the variations of:
   * Public, Private, Protected
   * variable, method
   * static, non-static

Java class:

    public class J2objcExperimental {
        public Object publicObject = null;
        private Object privateObject = null;
        protected Object protectedObject = null;
    
        public static Object publicStaticObject = null;
        private static Object privateStaticObject = null;
        protected static Object protectedStaticObject = null;
    
        public Object publicMethod() { return null; }
        private Object privateMethod() { return null; }
        protected Object protectedMethod() { return null; }
    
        public static Object publicStaticMethod() { return null; }
        private static Object privateStaticMethod() { return null; }
        protected static Object protectedStaticMethod() { return null; }
    }

Attempt to access all these members from an Objective-C class that doesn't inherit and therefore shouldn't have access to protected members. All the public accessors work correctly as expected. The private and protected accessors should fail... all of them work except for "privateStaticMethod":

    CsiJ2objcExperimental_get_publicStaticObject_();
    CsiJ2objcExperimental_get_privateStaticObject_();
    CsiJ2objcExperimental_get_protectedStaticObject_();
    
    CsiJ2objcExperimental_publicStaticMethod();
    // CORRECT - FAILS WITH COMPILE ERROR: CsiJ2objcExperimental_privateStaticMethod();
    CsiJ2objcExperimental_protectedStaticMethod();
    
    CsiJ2objcExperimental *ptr = [[[CsiJ2objcExperimental alloc] init] autorelease];
    [ptr publicMethod];
    [ptr privateMethod];
    [ptr protectedMethod];

    CsiJ2objcExperimental_set_publicObject_(ptr, nil);
    CsiJ2objcExperimental_set_privateObject_(ptr, nil);
    CsiJ2objcExperimental_set_protectedObject_(ptr, nil);

J2objc Translation for header. Note that privateStaticMethod is missing - as it should be. Beyond that, the private and protected accessors aren't translated any different from public accessors... and they should be different.

    @interface CsiJ2objcExperimental : NSObject {
    @public
        id publicObject_;
        id privateObject_;
        id protectedObject_;
    }

    - (id)publicMethod;
    - (id)privateMethod;
    - (id)protectedMethod;
    + (id)publicStaticMethod;
    + (id)privateStaticMethod;
    + (id)protectedStaticMethod;
    - (void)testing;
    - (instancetype)init;
    - (void)dealloc;
    - (void)copyAllFieldsTo:(CsiJ2objcExperimental *)other;
    @end

    __attribute__((always_inline)) inline void CsiJ2objcExperimental_init() {}

    J2OBJC_FIELD_SETTER(CsiJ2objcExperimental, publicObject_, id)
    J2OBJC_FIELD_SETTER(CsiJ2objcExperimental, privateObject_, id)
    J2OBJC_FIELD_SETTER(CsiJ2objcExperimental, protectedObject_, id)
    FOUNDATION_EXPORT id CsiJ2objcExperimental_publicStaticMethod();
    FOUNDATION_EXPORT id CsiJ2objcExperimental_protectedStaticMethod();

    FOUNDATION_EXPORT id CsiJ2objcExperimental_publicStaticObject_;
    J2OBJC_STATIC_FIELD_GETTER(CsiJ2objcExperimental, publicStaticObject_, id)
    J2OBJC_STATIC_FIELD_SETTER(CsiJ2objcExperimental, publicStaticObject_, id)

    FOUNDATION_EXPORT id CsiJ2objcExperimental_privateStaticObject_;
    J2OBJC_STATIC_FIELD_GETTER(CsiJ2objcExperimental, privateStaticObject_, id)
    J2OBJC_STATIC_FIELD_SETTER(CsiJ2objcExperimental, privateStaticObject_, id)

    FOUNDATION_EXPORT id CsiJ2objcExperimental_protectedStaticObject_;
    J2OBJC_STATIC_FIELD_GETTER(CsiJ2objcExperimental, protectedStaticObject_, id)
    J2OBJC_STATIC_FIELD_SETTER(CsiJ2objcExperimental, protectedStaticObject_, id)

**Comment by tomball** [comment]
It's a temporary workaround; here's the comment in Options.java:

  // TODO(tball): set true again when native code accessing private Java methods is fixed.
  private static boolean hidePrivateMembers = false;

**Comment by brunobowden** [comment]
Makes sense. I just didn't believe that you missed something like that ;-)

**Comment by tomball** [comment]
Workaround removed.
