### ISSUE TITLE
compilation fails on unresolvable imports, even when those imports are unused

### ISSUE THREAD

**Issue by tamird** [google/j2objc#475]
Please see: https://github.com/tamird/j2objc_build_closure for a simple repro case.

**Comment by tomball** [comment]
We can't fix this, as the translator uses the Eclipse compiler's front-end to generate its abstract syntax trees. The translator relies heavily on the type bindings from that compilation, and bindings won't be determined if there are any syntax errors. We therefore can't filter out which syntax errors to ignore.
