### ISSUE TITLE
Iterable.m bad usage of self ptr as mutationPtr

### ISSUE THREAD

**Issue by wjobin** [google/j2objc#480]
The NSFastEnumerationState->mutationPtr in jre_emul/Classes/java/lang/Iterable.m is set to self (pointer). The mutationPtr is an unsigned long ptr that gets dereferenced and compared. This makes the for in objective c loop to validate that the first few bytes of the collection object hasn't change between each loop cycle.

This implementation is used for any Collection, not knowing what are the first bytes of the class. 

It would seems that the retainCount of NSObject is actually part of the first 8 bytes. In a multi threaded usage where the Collection is not modified but reference are added and subtracted, for in gave a lot of "was modified while enumerating".

The issue is fixed by declaring:

    static unsigned long mutationHack = 1;

and setting mutationPtr to its address:

    state->mutationsPtr = (unsigned long *) (ARCBRIDGE void *) &mutationHack;

Of course, mutation still cannot be detected between calls to countByEnumeratingWithState:objects:count: while for in is going through the returned objects stack.

**Comment by kstanger** [comment]
Thanks for the report. I was unaware that the retainCount was stored within the object. This must be new on 64 bit platforms.

While you're waiting for a fix, you can use the @LoopTranslation annotation to force your loop to use a java iterator instead of Objective-C's fast enumeration. See https://github.com/google/j2objc/blob/master/annotations/src/main/java/com/google/j2objc/annotations/LoopTranslation.java.

**Comment by wjobin** [comment]
Not sure if the retainCount is actually in the object. It's hard to find documentation about it. 
Never the less, checking the first 8 bytes of any Collection implementation as mutation indicator seems like quite a bad idea. Customs implementation are free to hold state that are not to be considered as enumeration mutation.

I wasn't award of the annotations. Thanks for pointing out. But I'll keep my fix pointed above, too many code to modify otherwise.

**Comment by kstanger** [comment]
I happened to be reading through this the other day:
https://www.mikeash.com/pyblog/friday-qa-2013-09-27-arm64-and-you.html

It clarifies the question retainCount question:
"On ARM64, 19 bits of the isa field go to holding the object's reference count inline."

**Comment by tomball** [comment]
Fixed in latest source.
