### ISSUE TITLE
EXC_BAD_ACCESS from GetResponseCode in HttpURLConnection

### ISSUE THREAD

**Issue by gdolling** [google/j2objc#484]
I asked on the forum and after some interchange it was suggested that I file a bug. The following code is a small example that elicits the problem. 

Regards,

Gavin. 

import java.io.BufferedReader;
import java.io.DataOutputStream;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.URL;

public class Main {

    public static void main(String[] args) {

        try {
            String url = "https://selfsolve.apple.com/wcResults.do";

            URL obj = new URL(url);

            HttpURLConnection con = (HttpURLConnection) obj.openConnection();

            // A get does work
            con.setRequestMethod("POST");
            con.setRequestProperty("User-Agent", "Mozilla/5.0");
            con.setRequestProperty("Accept-Language", "en-US,en;q=0.5");

            // If you disable this line it does not fail, obviously I would
            // actually write
            // some data normally, but it is not necessary to do this to produce
            // the error
            con.setDoOutput(true);

            // It will fail on next line with a bad access
            int responseCode = con.getResponseCode();
            System.out.println("Response Code : " + responseCode);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}

**Comment by mithepner** [comment]
I think I'm running into this same issue.  The issue for me appears to be the way that j2objc translates code for object arrays that are initialized in one line.

If I initialize an array this way:

        Param[] newHeaders = new Param[]{
            new Param("Content-Type", "application/json;charset=UTF-8"),
            new Param("Accept", "application/json")};
        
        // This fails with a EXC_BAD_ACCESS
        Log.e(TAG, "param0="+ newHeaders[0].getKey()+":"+newHeaders[0].getValue());

If I initialize the array this was it works

        Param[] headers = new Param[2];
        headers[0] = new Param("Content-Type", "application/json;charset=UTF-8");
        headers[1] = new Param("Accept", "application/json");
        
        //This does not fail
        Log.e(TAG, "param0="+ headers[0].getKey()+":"+headers[0].getValue());

**Comment by Navideck-fotis** [comment]
We are facing the same issue on GetResponseCode

**Comment by OMFOm** [comment]
Same issue here.

**Comment by tomball** [comment]
Foens submitted a separate patch that fixed this. When I run the above test, it prints "Response code: 200".
