### ISSUE TITLE
EXC_BAD_ACCESS on calling method's super implementation in anonymous class implementation on arm64 devices

### ISSUE THREAD

**Issue by chezzdev** [google/j2objc#486]
The problem arises when we try to call super implementation of the current method in anonymous class implementation. See the code:
```java
class Parent {
    public void foo(String message) {
    }
}

class Child extends Parent {
    @Override
    public void foo(final String message) {
        Runnable runnable = new Runnable() {
            @Override
            public void run() {
                Child.super.foo(message);
            }
        };
        runnable.run();
    }
}
```
This call of super implementation is translated as getting the function of the Parent class, casting it as a variadic function and executing it.

Program crashes on executing the function with EXC_BAD_ACCESS.

Translated code:
```objective-c
@implementation Parent

- (void)fooWithNSString:(NSString *)message {
}

@end

@implementation Child

- (void)fooWithNSString:(NSString *)message {
  id<JavaLangRunnable> runnable =
    [[[Child_$1 alloc] initWithChild:self withNSString:message] autorelease];
  [runnable run];
}

@end

@implementation Child_$1

- (void)run {
  ((void (*)(id, SEL, ...))[Parent instanceMethodForSelector:@selector(fooWithNSString:)])
  (this$0_, @selector(fooWithNSString:), val$message_);
}

@end
```
Again, problem exists only on arm64 devices.
So the cause of the crash and solution was found in Apple's "64-Bit Transition Guide for Cocoa Touch" in section [Function Pointers Must Use the Correct Prototype](https://developer.apple.com/library/ios/documentation/General/Conceptual/CocoaTouch64BitGuide/ConvertingYourAppto64-Bit/ConvertingYourAppto64-Bit.html#//apple_ref/doc/uid/TP40013501-CH3-SW12).
As it says:
> Never cast a variadic function to a function that takes a fixed number of parameters (or vice versa).
> ...
> Because the function pointer was cast to use a different set of calling conventions, a caller is going to place the parameters in a place that the called function is not expecting. This mismatch may cause your app to crash or to exhibit other unpredictable behaviors.

The problem should be fixed with explicit providing correct arguments` types when casting. So that translated version of the above code would look like:
```objective-c
  ((void (*)(id, SEL, NSString))[Parent instanceMethodForSelector:@selector(fooWithNSString:)])
  (this$0_, @selector(fooWithNSString:), val$message_);
```
In cases when arguments is interface implementation or unknown objects they can be translated just as ```id```.

**Comment by tomball** [comment]
Should be fixed now, please verify with latest source -- Keith updated prototype generation to match Apple's recommendations. Thanks for the detailed report and links.
