### ISSUE TITLE
'make dist' is not working

### ISSUE THREAD

**Issue by Ninganagouda** [google/j2objc#490]
* First we tried with the zip file & un-zipping it. It says 'j2objc' command not found. 

* Then we tried the alternate option of downloading the source file, tried to build it. But getting following error when we run 'make dist' & 'make test'. 

```j2objc-master/jre_emul/build_result/Classes/java/util/concurrent/atomic/AtomicInteger.m:31:34: error: unknown warning group
      '-Wobjc-designated-initializers', ignored [-Werror,-Wunknown-pragmas]
#pragma clang diagnostic ignored "-Wobjc-designated-initializers" ```

**Comment by tomball** [comment]
What version of the C compiler do you have installed (clang --version)? If
it's before clang-600, you'll need a newer version of Xcode
<https://developer.apple.com/xcode/downloads/> (free).

**Comment by Ninganagouda** [comment]
Hi, after upgrading the X-code, 'make dist' worked perfectly fine. But while running 'make test', ended up this following issues:

* 1) test_getIntegerInstance_ar(libcore.java.text.NumberFormatTest)
junit.framework.ComparisonFailure: expected:<#[0.###;]#0.###> but was:<#[,##0.###;#,#]#0.###>

* 2) test_getDisplayNameZILjava_util_Locale(libcore.java.util.OldTimeZoneTest)
junit.framework.ComparisonFailure: expected:<...normale du Pacifique[]> but was:<...normale du Pacifique[ nord-américain]>

* 3) test_getDisplayNameLjava_util_Locale(libcore.java.util.OldTimeZoneTest)
junit.framework.ComparisonFailure: expected:<...normale du Pacifique[]> but was:<...normale du Pacifique[ nord-américain]>

* 4) test_getByName(libcore.java.net.InetAddressTest)
junit.framework.AssertionFailedError: 1.2.3.4.

Also, not able to find 'j2objc' command.

**Comment by tomball** [comment]
"Also, not able to find 'j2objc' command." Its directory needs to be part
of your PATH, like any other command-line utility. Here's a blog entry
describing how to add your j2objc-master/dist directory (where j2objc is)
to your PATH:
http://osxdaily.com/2014/08/14/add-new-path-to-path-command-line/

**Comment by tomball** [comment]
It looks like the tests need to run in the US locale (blame the Android
folks, not us :-). Try running "make test LANG=en_US.UTF-8".

**Comment by Ninganagouda** [comment]
Nope it didn't work. Even after running 'make test LANG=en_US.UTF-8', it still ended up with those 4 issues.

**Comment by Ninganagouda** [comment]
It worked with zip file download & setting up the path. Used './j2objc' instead of 'j2objc' on mac, it worked.

Thanks.
