### ISSUE TITLE
Enhancement Request: java.text.Normalizer

### ISSUE THREAD

**Issue by ajhuntsman** [google/j2objc#498]
Per the discussion below, can translation be added for java.text.Normalizer, to support the use of commons-lang3?

https://groups.google.com/forum/#!topic/j2objc-discuss/lot97lAISZU

**Comment by tomball** [comment]
[java.text.Normalizer](https://github.com/google/j2objc/blob/master/jre_emul/android/libcore/luni/src/main/java/java/text/Normalizer.java) was recently added. [Here are the steps to build a new bundle.](https://github.com/google/j2objc/wiki/Building-J2ObjC)
