### ISSUE TITLE
Bug in String.matches() Regular Expression parsing, differs from Pattern.matches(,)  

### ISSUE THREAD

**Issue by astrotuna201** [google/j2objc#502]
per spec, String.matches(RegExp) should be identical to Pattern.matches(RegExp,String).
However, the js2objc native implementation of String.matches() differs from spec, and returns true/matched, even if there is only a partial match to the RegExp (e.g., one group), rather than matching the whole string.

Example:

import java.util.regex.Pattern;
public class RegexpTest6
{
    public static  void main(String[] args)
    {            
        String regex = "(analysis_description|\\w+)";
        String s = "@analysis_description";

//Using Pattern.matches(,)
        System.out.println("Matching string " +s);
        System.out.println("to regex " +regex);
        System.out.println("using Pattern.matches(regexp,s)");
        if (Pattern.matches(regex , s) == true) {
            System.out.println("pattern matched");
        }
        else {
            System.out.println("No match");
        }

//Using String.matches()
        System.out.println("using s.matches(regexp)");
        if (s.matches(regex) == true) {
            System.out.println("pattern matched");
        }
        else {
            System.out.println("No match");
        }
    }
}

per Spec :
> java RegexpTest6
Matching string @analysis_description
to regex (analysis_description|\w+)
using Pattern.matches(regexp,s)
No match
using s.matches(regexp)
No match

translated with j2objc// j2objcc:

Hello World
Matching string @analysis_description
to regex (analysis_description|\w+)
using Pattern.matches(regexp,s)
No match
using s.matches(regexp)
pattern matched                        <======= WRONG

Perhaps simply call Pattern.matches(,) from NSString+JavaString.m native implementation of String.matches()?

**Comment by astrotuna201** [comment]
alternatively, perhaps below would work in NSString+JavaString.m:

#import "Foundation/Foundation.h" // to get NSTextCheckingResult

- (BOOL)matches:(NSString *)regex {
  if (!regex) {
    @throw makeException([JavaLangNullPointerException class]);
  }
  NSError *error = nil;
  NSRegularExpression *nsRegex =
      [NSRegularExpression regularExpressionWithPattern:regex
                                                options:0
                                                  error:&error];
  if (error) {
    JavaUtilRegexPatternSyntaxException *exception =
        [[JavaUtilRegexPatternSyntaxException alloc]
         initWithNSString:[error localizedDescription]
             withNSString:regex
                  withInt:-1];
#if ! __has_feature(objc_arc)
    [exception autorelease];
#endif
    @throw exception;
  }
  NSTextCheckingResult * result = [nsRegex firstMatchInString:self
                                  options:0
                                    range:NSMakeRange(0, [self length])];
	if (result == nil){
		return FALSE;
	}
	else {
		return ((result.range.location != NSNotFound) && (result.range.length == [self length]));
	}
}

**Comment by tomball** [comment]
You're right, it should just return Pattern.matches(regex, this) like Android's version does (translated to ObjC, of course). This method was written before jre_emul supported java.util.regex, but now that it does, the results should be the same.

**Comment by tomball** [comment]
FYI, GitHub markdown will preserve code formatting if three backquotes are in the lines before and after it. More info is at [Mastering Markdown](https://guides.github.com/features/mastering-markdown/#examples), click on Code.

**Comment by jacky8hyf** [comment]
I just ran into the same issue... So now what should we do? Is this fixed?
 I am currently using Pattern.compile(String).matcher(String).matches() as alternative though...

**Comment by tomball** [comment]
Well, the problem was reported on the 11th and it's the 12th, so no, it's
not fixed yet. The workaround you're using will be the same as the fix, so
developers aren't blocked (just inconvenienced).

FWIW, this issue is due to differences between the Java and iOS regex
support. You'll see the same issue if you use the same regex expression in
Java and native code. Currently, j2objc's String.matches() uses
NSRegularExpression, after the above fix is applied, it won't.

**Comment by astrotuna201** [comment]
@jacky8hyf:

my temporary work-around was the following replacement for -matches in NSString+JavaString.m, 
which checks whether the length of the NSRegularExpression match extends to the full length of the String.

```
- (BOOL)matches:(NSString *)regex {
  if (!regex) {
    @throw makeException([JavaLangNullPointerException class]);
  }
  NSError *error = nil;
  NSRegularExpression *nsRegex =
      [NSRegularExpression regularExpressionWithPattern:regex
                                                options:0
                                                  error:&error];
  if (error) {
    JavaUtilRegexPatternSyntaxException *exception =
        [[JavaUtilRegexPatternSyntaxException alloc]
         initWithNSString:[error localizedDescription]
             withNSString:regex
                  withInt:-1];
#if ! __has_feature(objc_arc)
    [exception autorelease];
#endif
    @throw exception;
  }
  NSTextCheckingResult * result = [nsRegex firstMatchInString:self
                                  options:0
                                    range:NSMakeRange(0, [self length])];
	if (result == nil){
		return FALSE;
	}
	else {
		return ((result.range.location != NSNotFound) && (result.range.length == [self length]));
	}
}
```

**Comment by tomball** [comment]
I'm glad that works for your app, but there is still a potential for
differences in what String.matches() and Pattern.matches() return. I've
changed String.matches() to use a translation of Android's Java
implementation:

public boolean matches(String regularExpression) {
  return Pattern.matches(regularExpression, this);
}

Short, simple, guarantees that the two matches() methods return the same
results.

**Comment by tomball** [comment]
Fixed in current source.
