### ISSUE TITLE
undefined symbols for achitecture while trying to translate sqlite4java

### ISSUE THREAD

**Issue by hrabi0** [google/j2objc#509]
So I'm trying to translate sqlite4java, to have some neat sqlite framework to use with my project.

I tried two approaches:
 - adding sqlite4java source files directly to the project
 - translating sqlite4java sources externally using makefile

Both attempts resulted in similar linker errors, f.e:

Undefined symbols for architecture x86_64:
 "_ComAlmworksSqlite4java_SQLiteManualJNI_install_progress_handlerWithLong_withInt_withLongArray_withNSObjectArray_", referenced from:
      -[ComAlmworksSqlite4java_SQLiteManual install_progress_handlerWithComAlmworksSqlite4javaSWIGTYPE_p_sqlite3:withInt:] in _SQLiteManual.o
      +[ComAlmworksSqlite4java_SQLiteManualJNI install_progress_handlerWithLong:withInt:withLongArray:withNSObjectArray:] in _SQLiteManualJNI.o

(and then the whole list of over 80 similar entries follows)
(this is the makefile approach output - thus the x86_64 architecture, xcode build results are the same)

Where do I look now?

**Comment by kstanger** [comment]
It appears as though the library you're translating uses JNI to interface
between Java code and C code. The missing symbol is from a method declared
as "native" in java. You should be able to find the missing implementation
in a C file in your sqlite4java project. Look and see if the project has a
"native" directory.

Once you find the native implementations, you'll need to manually port them
by changing the function signatures to what J2ObjC expects and removing the
JNIEnv* parameters. Then compile them into your project.

Tom and I would like to make JNI projects easier to translate, but for now
some amount of porting of the native code is required.
