### ISSUE TITLE
Variable name clash with standard #define

### ISSUE THREAD

**Issue by pennersr** [google/j2objc#512]
Version 0.9.6.1 has trouble processing this file:

https://github.com/myabc/markdownj/blob/master/core/src/main/java/org/markdownj/CharacterProtector.java

Specifically, this:

    private String longRandomString() {
        StringBuilder sb = new StringBuilder();
        final int CHAR_MAX = GOOD_CHARS.length();
        for (int i = 0; i < 20; i++) {
            sb.append(GOOD_CHARS.charAt(rnd.nextInt(CHAR_MAX)));
        }
        return sb.toString();
    }

is turned into this:

    NSString *OrgMarkdownjCharacterProtector_longRandomString(OrgMarkdownjCharacterProtector *self) {
      JavaLangStringBuilder *sb = [[JavaLangStringBuilder alloc] init];
      jint CHAR_MAX = ((jint) [((NSString *) nil_chk(OrgMarkdownjCharacterProtector_GOOD_CHARS_)) length]);
      for (jint i = 0; i < 20; i++) {
        (void) [sb appendWithChar:[OrgMarkdownjCharacterProtector_GOOD_CHARS_ charAtWithInt:[((JavaUtilRandom *) nil_chk(self->rnd_)) nextIntWithInt:CHAR_MAX]]];
      }
      return [sb description];
    }

This results in a `Parse Issue: Expected identifier or '('` at this line:

    jint CHAR_MAX = ((jint) [((NSString *) nil_chk(OrgMarkdownjCharacterProtector_GOOD_CHARS_)) length]);

**Comment by pennersr** [comment]
This is due to `CHAR_MAX` being defined in `limits.h`

**Comment by tomball** [comment]
Added symbols from limits.h and i386/limits.h, awaiting code review. If you
need to get past this before this gets pushed, just add "CHAR_MAX" to the
reservedNames list in
translator/src/main/java/com/google/devtools/j2objc/util/NameTable.java.

**Comment by tomball** [comment]
Fixed in public source.
