### ISSUE TITLE
Inner Classes and inner Enums are not found during translation 

### ISSUE THREAD

**Issue by confile** [google/j2objc#513]
I read the comments from @tomball here (https://groups.google.com/forum/#!searchin/j2objc-discuss/translate$20jar/j2objc-discuss/FwXUxUzh7Ts/vu09QLo5MuMJ).I tried to use ``j2objc`` to translate my classes as well as dependent classes using the ``--build-closure`` flag here is the command I use: 
```
j2obc --no-package-directories -use-arc -d build/classes -sourcepath src/main/java:libSrc/javax.inject-1-sources.jar:libSrc/dagger-2.0-SNAPSHOT-sources.jar:libSrc/json-20140107-sources.jar src/main/java/com/example/SomeClassX.java src/main/java/com/example/ApplicationComponent.java src/main/java/com/example/ApplicationModule.java
```
Translation of classes works fine. Translation of dependent classes does also work, except that I get the following warnings: 

```
warning: could not find source path for dagger.Provides.Type
warning: could not find source path for com.example.Dagger_ApplicationComponent.Builder
warning: could not find source path for org.json.JSONObject.Null
```
These classes and types do exist on the source path. The Problem is that these classes are inner classes and inner types. 

For example: 
```
public class JSONObject {
       private static final class Null { ... }
      ...
}
```
and
```
@Documented @Target(METHOD) @Retention(RUNTIME)
public @interface Provides {
    enum Type { ... }
    ...
}
```

Somehow ``j2objc``does not find inner classes and inner types.

**Comment by confile** [comment]
As long as I get these warnings compiling the generated code in Xcode leads to errors like some file not found.

**Comment by confile** [comment]
I created a demo project for this case here: https://github.com/confile/j2objc-inner-classes

**Comment by lilianes** [comment]
I have the same problem translating Dagger2. Translation throws warnings for inner classes which could not be found.

**Comment by confile** [comment]
The ``@Provides`` annotation of dagger raises a problem in j2objc.

**Comment by kstanger** [comment]
Does this issue occur in 0.9.6.1, or are you building from up-to-date sources?

**Comment by confile** [comment]
Yes I compiles the latest source from git. it did not work. I created a simpler example here: 

https://groups.google.com/forum/#!topic/j2objc-discuss/eJhODNl3wtM

**Comment by lilianes** [comment]
For me the error occurs with 0.9.6.1.

**Comment by tomball** [comment]
A fix is pending code review.

**Comment by confile** [comment]
@tomball That is great thanks. I cannot see the fix yet.

**Comment by tomball** [comment]
Fixed in open-source.
