### ISSUE TITLE
XCode No Such File Or Directory when Building Project with JRE_Emulation

### ISSUE THREAD

**Issue by samirahmed** [google/j2objc#516]
When i follow the instructions the JRE Emulation wiki ... I can get the jre project to build in XCode 
but run into this error when trying to compile my project

```
no such file or directory: '/Users/samir/Library/Developer/Xcode/DerivedData/TestEwsJavaApi-etevarnpixccyzbgsgykukqdxjeh/Build/Products/Debug-iphonesimulator/libjre_emul.a'
```

Any ideas on what I might be doing wrong?

**Comment by tomball** [comment]
You need to add the location to where you unzipped the j2objc distribution
file to the target's Library Search Paths. For example, if you unzipped
j2objc-0.9.6.1.zip in ~/projects, then add $HOME/projects/j2objc-0.9.6.1/.

If you built the project from its source, then that location should be
project-path/dist. For example, if the project is in ~/src/j2objc, then use
$HOME/src/j2objc/dist/.
