### ISSUE TITLE
[ERROR] [system.err] warning: could not find source path for 

### ISSUE THREAD

**Issue by confile** [google/j2objc#518]
I use j2objc 0.9.7 and I got the following error: 

```
00:06:33.300 [ERROR] [system.err] warning: could not find source path for 
00:06:33.321 [QUIET] [system.out] translating
```
When I delete the file where this error occurs. The error moves to another file, where no error was before. The problem is that there is not description of what went wrong and it is very strange that the error is movie to a file which had no error before.

**Comment by kstanger** [comment]
Judging from the error messages, it appears that somehow j2objc is
attempting to translate nameless files (empty strings). Can you provide
more details, including the j2objc command line being invoked?

**Comment by confile** [comment]
@kstanger Hope that helps: https://gist.github.com/confile/3bad2f700b797093d85e

**Comment by kstanger** [comment]
One thing that stands out is that your command has multiple --classpath
flags. Currently j2objc only supports a single --classpath flag. Although I
would have expected a more useful error message. Try coalescing your
--classpath flags into one and let me know if that helps.

**Comment by confile** [comment]
@kstanger I did the same with only one ``-classpath`` argument with the same result.

**Comment by confile** [comment]
@kstanger I tested the latest snapshot today. The Warning is gone. I close this issue.
