### ISSUE TITLE
Xcode: "couldn't create directory" when copying Java Resources

### ISSUE THREAD

**Issue by confile** [google/j2objc#522]
I tried to include Java Resources in my Xcode project as described here (https://github.com/google/j2objc/wiki/Java-Resources). When I build the project I get the following errors: 

```
PBXCp /Users/mg/Documents/Grails/GGTS3.6.3-SR1-2/testproject-core/src/main/resources/testproject/core/i18n/Messages_de.properties /Users/mg/Library/Developer/Xcode/DerivedData/testproject-bkkczkzivpolszewxttakwlxnztk/Build/Products/Debug-iphoneos/testproject.app/testproject/core/i18n/Messages_de.properties
    cd /Users/mg/Documents/Grails/GGTS3.6.3-SR1-2/testproject
    export PATH="/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode-beta.app/Contents/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    builtin-copy -exclude .DS_Store -exclude CVS -exclude .svn -exclude .git -exclude .hg -resolve-src-symlinks /Users/mg/Documents/Grails/GGTS3.6.3-SR1-2/testproject-core/src/main/resources/testproject/core/i18n/Messages_de.properties /Users/mg/Library/Developer/Xcode/DerivedData/testproject-bkkczkzivpolszewxttakwlxnztk/Build/Products/Debug-iphoneos/testproject.app/testproject/core/i18n

	error: couldn't create directory /Users/mg/Library/Developer/Xcode/DerivedData/testproject-bkkczkzivpolszewxttakwlxnztk/Build/Products/Debug-iphoneos/testproject.app/testproject/core/i18n: Not a directoryerror: open /Users/mg/Library/Developer/Xcode/DerivedData/testproject-bkkczkzivpolszewxttakwlxnztk/Build/Products/Debug-iphoneos/testproject.app/testproject/core/i18n/Messages_de.properties: Not a directory
	
(null): error: couldn't create directory /Users/mg/Library/Developer/Xcode/DerivedData/testproject-bkkczkzivpolszewxttakwlxnztk/Build/Products/Debug-iphoneos/testproject.app/testproject/core/i18n: Not a directory

(null): error: open /Users/mg/Library/Developer/Xcode/DerivedData/testproject-bkkczkzivpolszewxttakwlxnztk/Build/Products/Debug-iphoneos/testproject.app/testproject/core/i18n/Messages_de.properties: Not a directory


```

**Comment by tomball** [comment]
That's an Xcode issue -- searching for "PBXCp" found lots of related
postings:

https://discussions.apple.com/thread/4715567?tstart=0
http://stackoverflow.com/questions/5183530/command-pbxcp-fails-xcode-build
http://stackoverflow.com/questions/15887410/pbxcp-no-such-file-or-directory-in-most-recent-xcode

"error: couldn't create directory
/Users/mg/Library/Developer/Xcode/DerivedData/testproject-bkkczkzivpolszewxttakwlxnztk/Build/Products/Debug-iphoneos/testproject.app/testproject/core/i18n:
Not a directory"

Try creating that directory using mkdir, and see what error is returned.

**Comment by confile** [comment]
The problem Is that I can build when I obmit the subpath

![buddyis_xcodeproj](https://cloud.githubusercontent.com/assets/64265/7275096/31cbb59e-e902-11e4-97af-a5a4c62f21b1.png)

With subpaths I get the error shown above.

![buddyis_xcodeproj](https://cloud.githubusercontent.com/assets/64265/7275124/4b5153e8-e902-11e4-8827-172177c13539.png)

**Comment by tomball** [comment]
It's still an Xcode problem. You can try (though there is no guarantee it works) creating a Run Script build phase at the top of your app target's build, which runs "mkdir -p test/core/i18n" (and any other sub-directories).
