### ISSUE TITLE
Source jar Classes are not translated in the latest SnapShot (Apr 21, 2015)

### ISSUE THREAD

**Issue by confile** [google/j2objc#523]
In my j2objc command I use ``dagger-2.0-sources.jar``. As of my local version from: Commits on Apr 13, 2015 classes from this jar have been translated when they are used in my project.

Example: 

```
import dagger.Lazy;
import dagger.Module;
import dagger.Provides;

@Module
public class ApplicationModule {
...
}
```
So far all the dependent dagger classes ``Lazy``, ``Module`` and ``Provides`` have been translated correctly. 

When using the latest Snapshot: (Date Commits on Apr 21, 2015) The classes classes ``Lazy``, ``Module`` and ``Provides`` are not translated anymore. Also they are not included in other classes because Xcode reported an compile error ``File .h not found``.

**Comment by tomball** [comment]
Appears fixed in latest version.
