### ISSUE TITLE
--build-closure Flag does not prefer taking classes from -classpath

### ISSUE THREAD

**Issue by confile** [google/j2objc#524]
``--build-closure`` Flag does not prefer taking classes from -classpath it takes dependent source jars first. 

That should be the same behaviour as javac. Taking classes from ``-classpath`` and if not found take them from the sources.

See the discussion in that discussion: https://groups.google.com/forum/#!topic/j2objc-discuss/juXn8G18Gw8

**Comment by advayDev1** [comment]
interesting, I think i'm using bug as a feature.  i'm masking files impossible to translate via j2objc from an existing jar on the classpath with my own j2objc-compatible variants on the sourcepath.

**Comment by confile** [comment]
Why don't you put them on the classpath instead?

**Comment by advayDev1** [comment]
See Keith Stranger's response on your thread at j2objc-discuss:
```
If it can resolve your dependency from the classpath, it does not compile the .java source in the sourcepath.
```

The goal is to have these j2objc-compatible variants of dependencies translated to objc when using ---build-closure, so I keep the .java files on the sourcepath.

**Comment by tomball** [comment]
j2objc has similar rules as javac:
<table>
  <th><td><b>javac</b></td><td><b>j2objc</b></td></th>
  <tr><td>Compiles specified files</td><td>always</td><td>always</td></tr>
  <tr><td>Compiles -sourcepath references</td><td>if newer than their class files</td><td>always with --build-closure flag</td></tr>
  <tr><td>Compiles -classpath references</td><td>never</td><td>never</td></tr>
</table>

Only .class files are read from -classpath entries. Only .java files are read from -sourcepath entries. "References" means types that were referenced during compilation, often (but not always) corresponding to a source file's import statements.
