### ISSUE TITLE
Wiki: Java Ressources customize logging

### ISSUE THREAD

**Issue by confilemg** [google/j2objc#528]
Based on the discussion here: https://groups.google.com/forum/#!topic/j2objc-discuss/ARramzuU9No
I write some notes you might like to add to the wiki: 
# Customize Logging Handler

iOS logging is handled by [IOSLogHandler.java](https://github.com/google/j2objc/blob/master/jre_emul/Classes/java/util/logging/IOSLogHandler.java), which overrides java.util.logging.Handler. You can set it as the default by adding a `logging.properties` resource to your app, as shown in [LogManager](https://github.com/google/j2objc/blob/master/jre_emul/android/libcore/luni/src/main/java/java/util/logging/LogManager.java).
## Change Logging Handler programmatically

To programmatically change the default Logging Handler, use `LogManager.getLogger("").addHandler(myHandler)`. If you don't want the old Handler(s) to also run, remove them first using `LogManager.getLogger("").removeHandler(otherHandler)`.
## Change Logging Handler with property file

To change  the default Logging Handler using a `logging.properties` file you have to specify your custom Logging Handler like this: 

```
handlers=java.util.logging.MyIOSLogHandler
java.util.logging.ConsoleHandler.level=ALL
```

To load the property file in code you have to set: 

```
private static final LogManager logManager = LogManager.getLogManager();
private static final Logger log = Logger.getLogger("confLogger");
  static{
    try {
        InputStream loggingProperties = Builder.class.getResourceAsStream("logging.properties");
        logManager.readConfiguration(loggingProperties);
      } catch (IOException exception) {
        log.log(Level.SEVERE, "Error in loading configuration",exception);
  }
}
```

@tomball hope this helps. Thanks again for your help.

**Comment by tomball** [comment]
[Updated.](https://developers.google.com/j2objc/guides/customize-ios-logging) I'm sorry it took so long to get this posted, as new bugs kept pushing this one down the list. Thank you very much for your contribution!
