### ISSUE TITLE
Abstract Java Class makes Interface Methods kind of optional in Objective-C

### ISSUE THREAD

**Issue by confile** [google/j2objc#530]
Create the following interface and abstract class in Java: 
```
package p;
public interface TestBaseView {
  Object getNativeInstance();
}
```
an abstract class: 
```
package p;
abstract class AbstractTestBaseViewImpl implements TestBaseView { }
```
translate this to Objective-C and use it like the following. I write it in Swift but I am sure the same problem occurs in Objective-C. I can Implement the interface directly in Swift like: 
```
class Test : NSObject, PTestBaseView { }
```
When you build the project the compiler tells you that you did not implement the protocol correctly since you did not implement ``getNativeInstance``. That case is fine, but when you extend the abstract class like this: 
```
class Test : PAbstractTestBaseViewImpl {
}
```
then you can compile without any errors. This is strange because you are required to implement the Java interface correctly.

**Comment by kstanger** [comment]
j2objc generates a stub method when it sees an abstract method. It also
tells the compiler to ignore incomplete protocol warnings if a protocol is
not fully implemented by an abstract class using '#pragma clang diagnostic
ignored "-Wprotocol"'. One of these might be the reason you're not seeing
the expected compiler error.

**Comment by confile** [comment]
Are there plans to change this or provide a flag for it?

**Comment by kstanger** [comment]
No. Those solutions are required to prevent compiler errors from abstract
classes, since Objective-C doesn't have abstract types.

**Comment by tomball** [comment]
If you remove the warning suppression in AbstractTestBaseViewImpl.m, then
it won't compile using clang. Does it then work as you'd expect in Swift?

**Comment by confile** [comment]
As @tomball suggested I removed the following line: 

```
#pragma clang diagnostic ignored "-Wprotocol"
```
but it does not change anything. There is no compiler error.

**Comment by tomball** [comment]
We don't control the Swift compiler's behavior. If you can find some change
to the generated output that works and can still be compiled as regular
Objective-C, we'll change what's output.

**Comment by confile** [comment]
I suggest to implement the unimlemented methods in the abstract class and throw an exception per default. I know this is runtime check only but you will find the error very easy if the Exception says that a certain method has not been implemented.

Here are other possible solutions: 

http://stackoverflow.com/questions/5222083/implement-a-pure-virtual-method-in-objective-c

http://stackoverflow.com/questions/22463605/objective-c-how-to-force-subclass-to-implement-methods

**Comment by tomball** [comment]
All you need to do then is declare the methods as abstract in the implementing class, and a stub will be generated that does that. Using your example code:

```java
package p;
abstract class AbstractTestBaseViewImpl implements TestBaseView { 
  public abstract Object getNativeInstance();
}
```
generates:
```objc
- (id)getNativeInstance {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
  return 0;
}
```

We don't do this by default because those method stubs add code to the generated classes that is never referenced if the class is only subclassed by other translated classes. For large apps, that makes a small but significant increase in their download sizes.

**Comment by confile** [comment]
Thanks for help!
