### ISSUE TITLE
JavaDoc Comments are not shown in Xcode

### ISSUE THREAD

**Issue by steffimueller** [google/j2objc#531]
I use the ``--doc-comments`` flag to translate JavaDocs as well. Here is an example: 

```
public class MyClass {

  /**
   * Does foo things.
   */
  public void foo() {
    
  }
  
  // does bar things.
  public void bar() {
    
  }
  
}
```
The translated class is: 
```
@interface BISMyClass : NSObject

#pragma mark Public

- (instancetype)init;

- (void)bar;

/**
 @brief Does foo things.
 */
- (void)foo;

@end
```
When I use the foo function as shown here: 

![test_swift_ _edited](https://cloud.githubusercontent.com/assets/5350431/7434723/4f487610-f03d-11e4-9b9b-c250895fee6a.png)

No documentation is show in the Xcode code completion window.

**Comment by confile** [comment]
+1

**Comment by tomball** [comment]
In Xcode 6, documentation has moved to the Quick Help panel. You can also use Option-click to show it as a popup in the editor panel. However, the old behavior works on my system, after typing 'f' + ctrl-space:

![code-complete](https://cloud.githubusercontent.com/assets/2991279/7841870/5ebb2cac-0454-11e5-8ce6-3c7321a3a1bd.png)

**Comment by confile** [comment]
thanks!
