### ISSUE TITLE
Cannot iterate over JavaUtilMap in Swift:  'JavaUtilSet' does not have a member named 'Generator'

### ISSUE THREAD

**Issue by confile** [google/j2objc#532]
Having the following Map: 

```
let params: JavaUtilMap = // defined
```
I tried this: 
```
for entry in params.entrySet() {
        
      }
```
But it leads to the following error: 
```
 'JavaUtilSet' does not have a member named 'Generator'
```

**Comment by confile** [comment]
I guess there is no other way to iterate over a Map which have been translated.

**Comment by confile** [comment]
Well I guess it is the following way, but it is not very easy:
```
      let params: JavaUtilMap = // defined
      let entrySet:JavaUtilSet = params.entrySet()
      let iteratory:JavaUtilIterator = entrySet.iterator()
      while iteratory.hasNext() {
        let entry:JavaUtilMap_Entry = iteratory.next() as! JavaUtilMap_Entry
      }
```

**Comment by kstanger** [comment]
I don't know Swift syntax. Is JavaUtilSet supposed to be the type for
"entry"? It should be JavaUtilMap_Entry.

**Comment by confile** [comment]
JavaUtilSet is the type of ``params.entrySet()``.  The type of  ``entry`` is whatever you stored in the JavaUtilSet. 

I tried this too: 

```
for entry:JavaUtilMap_Entry in params.entrySet() as! [JavaUtilMap_Entry] {
        
      }
```

So far there is only one way of doing it. It is using the iterator.

The problem is that you get a compiler error: ``'JavaUtilSet' does not have a member named 'Generator'``
You cannot use the a JavaUtilSet in a for in loop.

The same problem occurs for: 
```
var list:JavaUtilList = JavaUtilArrayList()
      for entry in list {
        
      }
```
with the same error.

**Comment by confile** [comment]
Here is my solution: https://github.com/google/j2objc/issues/533
