### ISSUE TITLE
Add CocoaPods in your releases

### ISSUE THREAD

**Issue by ex3ndr** [google/j2objc#537]
Almost all iOS developers use CocoaPods, but it is bad idea to keep such big project in cocoapods - it takes forever to download an configure on CI-servers.

In our project we use j2objc-local cocoapod for referencing locally installed j2objc distribution: https://github.com/actorapp/j2objc-local

You just need to define environment variable J2OBJC_HOME with path to J2OBJC.

Hope it helps someone.

**Comment by confile** [comment]
@ex3ndr The [j2objc-gradle plugin](https://github.com/brunobowden/j2objc-gradle) provides a task for cocoapods see: https://github.com/brunobowden/j2objc-gradle/blob/master/j2objc.gradle#L1153

**Comment by ex3ndr** [comment]
I have same file in my sources, but it will be better to have something official.

**Comment by bolsinga** [comment]
Having official CocoaPods support would be fantastic. Thanks!

**Comment by Toinouze** [comment]
+1

**Comment by ex3ndr** [comment]
I really believe that cocoapods is a bad way of integration of j2objc, i tried may different ways, this is just doesn't work well. Best type is writing makefile and compile java from sources to static library, link it with app and include all required headers.

Cocoapods always do some awful things.

**Comment by confile** [comment]
@ex3ndr That is not true. Integration with Cocoapods works great. See: https://github.com/brunobowden/j2objc-gradle

**Comment by ex3ndr** [comment]
@cdibona ok, when i will add/remove any file or update them i need to run something? Can't do this in better way? Recreating/updating xcode projects when add/remove files? Correct me if i wrong. Also your layout doesn't work well with GWT or something. I also tried to do something with gradle, but found it a bit unusable and switched to makefile. Very easy install and you can manage everything.

**Comment by tomball** [comment]
Cocoapods support available in https://github.com/brunobowden/j2objc-gradle.
