### ISSUE TITLE
GSON deserialization failed when using Generic Types

### ISSUE THREAD

**Issue by confile** [google/j2objc#538]
I tried to translate: 
```
Gson gson = new Gson();
Type resultType = new TypeToken<GetResult<SessionStartResultDto>>() {}.getType();
GetResult<SessionStartResultDto> result = gson.fromJson(jsonString, resultType);
```
It translates but when I run the code in Xcode I get the following error: 

```
Terminating app due to uncaught exception 'JavaLangTypeNotPresentException', reason: 'Type test.core.rest.dto.SessionStartResultDto not present'
```

**Comment by tomball** [comment]
Is that type actually present? iOS doesn't allow classes to be loaded from outside the app bundle, so unless that class is linked into the app, it can't be dynamically loaded. 

Try linking with the -ObjC flag, which links all Objective-C classes, regardless whether other code references them. If that doesn't work, try defining an explicit class reference to force the linker to include the class, such as "private static final Class<?> linkerRef = SessionStartResultDto.class;".
