### ISSUE TITLE
--static-accessor-methods flag leads to Xcode build error

### ISSUE THREAD

**Issue by confile** [google/j2objc#539]
Referring this discussion: https://github.com/google/j2objc/issues/520

Using the flag: ``--static-accessor-methods `` leads to: 

Xcode reports a lot of error when I use this flag. The errors are all in the generated files. Here is an example. It suggest to replace code in a translated file:

![parameterconfig_m](https://cloud.githubusercontent.com/assets/64265/7701435/61fa6154-fe27-11e4-8d6c-123da1c01b22.png)

The Java class was: 
```
public final class ParameterConfig {
   public static final int MAX_ITEMS_LOADED = 9; 
}

```

**Comment by confile** [comment]
Fixed.

**Comment by xyxjn** [comment]
How to fixed?Could you help me? I have the same problem, and I think maybe it is not "static" but "final" called this problem. Now I can call the variable in java function, but still can not call it with ObjectC

**Comment by confile** [comment]
@xyxjn See here: https://github.com/google/j2objc/issues/520

**Comment by xyxjn** [comment]
Thanks a lot!  I can use the variable with package prefix directly, and the problem is fixed! Finally it must see the translated file.
