### ISSUE TITLE
Ant Support

### ISSUE THREAD

**Issue by sethfri** [google/j2objc#540]
Is there any guide for getting j2objc set up with an Ant build system? Can't seem to find anything in the Wiki

**Comment by tomball** [comment]
We have no plans to support Ant, as it's getting old and is being eclipsed by other build systems like Gradle. That said, the separate [j2objc-eclipse-plugin project](https://github.com/hemantasapkota/j2objc-eclipse-plugin) has an [AntDelegate](https://github.com/hemantasapkota/j2objc-eclipse-plugin/blob/master/src/src/com/laex/j2objc/AntDelegate.java) you might be able to reuse.
