### ISSUE TITLE
String.indexOf(char) is broken

### ISSUE THREAD

**Issue by ex3ndr** [google/j2objc#542]
When try to use ```String.indexOf(char)``` it is always throw EXC_BAD_ACCESS. When i replace to ```String.indexOf(String)``` everything works right. It seems that method for ```char``` and for ```String``` arguments has same naming in ObjC and it seems to be incorrect.

**Comment by ex3ndr** [comment]
It seems that ```String.valueOf(Integer)``` is broken too - it throws class cast exception when argument is unboxed value.

**Comment by tomball** [comment]
Please give an example where these methods are failing. This test works:

```java
class StringTest {
  public static void main(String[] args) {
    System.out.println("abcde".indexOf('b'));
    System.out.println(String.valueOf(new Integer("12345")));
  }
}
```
```
$ ./a.out StringTest
1
12345
```

**Comment by ex3ndr** [comment]
I am still experiencing this problems, but at some places it works well, but sometimes not. Usually  invoking somwehere in JRE Emulation throws exception.

**Comment by tomball** [comment]
No, really, please provide a test example. We're engineers, not remote faith healers. :-)

**Comment by tomball** [comment]
Please reopen when you have a reproducible test.
