### ISSUE TITLE
Update doc-comment generation to Xcode 6

### ISSUE THREAD

**Issue by tomball** [google/j2objc#543]
In Xcode 6, the in-file doc-format has changed, such that tags like @param and @return no longer work. [NSHipster describes the new documentation format,](http://nshipster.com/swift-documentation/) which we need to update the translator to generate.

**Comment by confile** [comment]
+1

**Comment by tomball** [comment]
Updated in 0.9.8.2.1. Doc-comment translation isn't perfect, but much better. Here's a screenshot of the Quick Help for java.util.concurrent.locks.Condition:

![doccomment](https://cloud.githubusercontent.com/assets/2991279/10831605/e3c75826-7e43-11e5-9315-b48f006a7243.png)
