### ISSUE TITLE
Exception thrown creating SaxParser with SaxParserFactory

### ISSUE THREAD

**Issue by davidmoore1** [google/j2objc#547]
Using j2objc 0.9.7, I tried running a method that creates and parses an XML string using a Sax parser.  I don't even get into the parsing because it is unable to instantiate the Sax parser. 
Using SAXParserFactory.newInstance() generates the following runtime exception:
"org.xml.sax.SAXNotRecognizedException: org.xmlpull.v1.XmlPullParserException: No valid parser classes found in org.kxml2.io.kXmlParser,org.kxml2.io.KXmlSerializer"

The original java code is:
SAXParserFactory saxPF = SAXParserFactory.newInstance();
SAXParser saxP = saxPF.newSAXParser();
XMLReader xmlR = saxP.getXMLReader();

It dies on the newSaxParser call.

The generated code for the same segment is:

    JavaxXmlParsersSAXParserFactory *saxPF = JavaxXmlParsersSAXParserFactory_newInstance();
    JavaxXmlParsersSAXParser *saxP = [((JavaxXmlParsersSAXParserFactory *) nil_chk(saxPF)) newSAXParser];
    id<OrgXmlSaxXMLReader> xmlR = [((JavaxXmlParsersSAXParser *) nil_chk(saxP)) getXMLReader];

The exception is thrown on the second line of the generated code shown above.

**Comment by tomball** [comment]
Try linking your app or test with the -ObjC flag. Parser classes are
dynamically loaded, and the -ObjC flag tells the linker to include all
Objective C classes it finds in static libraries, regardless of whether
they are directly referenced by .o files or not.

**Comment by tomball** [comment]
Verified the following works when linked with -ObjC, fails without it:

```java
import javax.xml.parsers.SAXParser;
import javax.xml.parsers.SAXParserFactory;
import org.xml.sax.XMLReader;

class SaxTest {
  public static void main(String... args) throws Exception {
    SAXParserFactory saxPF = SAXParserFactory.newInstance();
    SAXParser saxP = saxPF.newSAXParser();
    XMLReader xmlR = saxP.getXMLReader();
    System.out.println(xmlR);
  }
}
```

**Comment by davidmoore1** [comment]
I added -Objc to the other Linker Flags of the application and got the same results

**Comment by davidmoore1** [comment]
That worked.  Thanks

**Comment by tomball** [comment]
If you have a better test than the one I added, please reopen this bug and
attach it.
