### ISSUE TITLE
Translate Java Generics to Objective-C Generics

### ISSUE THREAD

**Issue by confile** [google/j2objc#548]
Since Objective-c now supports Generics as well as Swift it would be great if Java Generics will be translated into Objective-C generics.

**Comment by steffimueller** [comment]
+1

**Comment by lilianes** [comment]
+1

**Comment by tomball** [comment]
How does Objective C support generics? I'd need either an Apple documentation link or at least a descriptive example. For example, should [this class](http://docs.guava-libraries.googlecode.com/git/javadoc/com/google/common/base/Function.html) be written in Objective C to support generics?

```java
public interface Function<F, T> {
  T apply(F input);
}
```

**Comment by confile** [comment]
@tomball Here you are: https://twitter.com/search?q=objective-c%20generics&src=tyah

Apple announced it today. This will solve a lot of casting problems.

**Comment by confile** [comment]
![ios_development_auf_twitter___this_is_what_objective-c_generics_look_like_in_action_http___t_co_qbgzw4xnmh_](https://cloud.githubusercontent.com/assets/64265/8046731/baeacd6e-0e3d-11e5-8715-1879b770aa89.png)

(Source: https://twitter.com/search?q=objective-c%20generics&src=tyah)

**Comment by ex3ndr** [comment]
+1

**Comment by tomball** [comment]
I appreciate the twitter link, but this will either have to wait until Xcode 7 releases (I can't keep up with weekly betas and stay productive), or someone else needs to contribute what should be a simple change.

**Comment by tomball** [comment]
According to the Apple documentation, Objective C generics will be checked in Objective C code, but ignored when imported by the Swift compiler ([doc here](https://developer.apple.com/library/prerelease/watchos/documentation/Swift/Conceptual/BuildingCocoaApps/InteractingWithObjective-CAPIs.html), search for generics). Anyone hoping for Java generics mapping to Swift generics will be disappointed.

**Comment by tamird** [comment]
@tomball that page must have changed since your last visit.

> Objective-C declarations of NSArray, NSSet and NSDictionary types using lightweight generic parameterization are imported by Swift with information about the type of their contents preserved.

**Comment by tomball** [comment]
What about generic protocols? I can't find any information. This is an
example of why we don't jump on new features days after they're announced
-- there just isn't the documentation to support them property yet.

**Comment by confile** [comment]
@tomball you are right, but having Generics imported into Swift would make code much more easy no lousy casting of JavaUtilList objects anymore.

**Comment by tomball** [comment]
That's my point: JavaUtilList is a protocol, so Objective C needs to
support generics in protocols to avoid casting. JavaUtilArrayList will work
since it's a class, but not if it's referenced as a JavaUtilList.

**Comment by spierce7** [comment]
:+1:

**Comment by ricardolyn** [comment]
+1

**Comment by tomball** [comment]
Closing, as Objective-C still doesn't support generics in protocols, and it looks like it never will.
