### ISSUE TITLE
Imports can't be resolved

### ISSUE THREAD

**Issue by ChrisChinchilla** [google/j2objc#552]
I may be misunderstanding something, and apologies if I am.

I am running the library over a java file from an Android Studio project and I get a lot of these error messages

```
error: MainActivity.java:3: The import android.app cannot be resolved
error: MainActivity.java:4: The import android.content cannot be resolved
error: MainActivity.java:5: The import android.os.Bundle cannot be resolved
error: MainActivity.java:7: The import android.view cannot be resolved
error: MainActivity.java:8: The import android.view cannot be resolved
error: MainActivity.java:9: The import android.view cannot be resolved
error: MainActivity.java:10: The import android.widget cannot be resolved
error: MainActivity.java:11: The import android.widget cannot be resolved
error: MainActivity.java:20: Activity cannot be resolved to a type
error: MainActivity.java:23: Bundle cannot be resolved to a type
error: MainActivity.java:24: Window cannot be resolved to a variable
error: MainActivity.java:25: The method getWindow() is undefined for the type MainActivity
error: MainActivity.java:25: WindowManager cannot be resolved to a variable
error: MainActivity.java:25: WindowManager cannot be resolved to a variable
error: MainActivity.java:28: R cannot be resolved to a variable
error: MainActivity.java:33: AssetManager cannot be resolved to a type
error: MainActivity.java:33: The method getApplication() is undefined for the type MainActivity
error: MainActivity.java:64: Globals cannot be resolved to a type
error: MainActivity.java:64: Globals cannot be resolved
error: MainActivity.java:73: Button cannot be resolved to a type
error: MainActivity.java:73: Button cannot be resolved to a type
error: MainActivity.java:73: R cannot be resolved to a variable
error: MainActivity.java:74: View cannot be resolved to a type
error: MainActivity.java:75: View cannot be resolved to a type
error: MainActivity.java:83: Globals cannot be resolved to a type
error: MainActivity.java:83: Globals cannot be resolved
error: MainActivity.java:87: TextView cannot be resolved to a type
error: MainActivity.java:87: TextView cannot be resolved to a type
error: MainActivity.java:87: R cannot be resolved to a variable
```

I understand the latter errors are to do with UI, which isn't supported, but what about the first errors? Is this something to do with the code coming from Android Studio?

I guess I'm looking for some guidance on what needs to be removed from Java code before running j2objc and I can't find this guidance anywhere.

I am actually writing an article on how to use the tool, so am attempting to create what is missing!

**Comment by kstanger** [comment]
j2objc needs all of your code's dependencies on either the -sourcepath or
the -classpath. If you swap "j2objc" for "javac" in your command, you will
probably see the same errors.
You will need to have the source code for all your dependencies (excluding
core java classes) and be able to translate that source to link into your
iOS app. So you'll have to refactor your code so that it's free of any
dependencies that can't be translated (such as Andoid UI).

**Comment by ChrisChinchilla** [comment]
Thanks, for anyone who has this issue in the future, on my mac, this is solved with:

-sourcepath ~/Workspace/android-sdk/sources/android-22

For example. Now I just need to solve the UI issues, fortunately my application is a simple test case.

**Comment by ChrisChinchilla** [comment]
@kstanger Sorry, reopening this…

So, whilst what you suggest works, when it comes to compiling with `j2objcc`

You end up with lines of include statements, such as 

`#include "android/app/Activity.h"`

that obviously can't be found. So is the solution to remove these from the original Android code or to run all of these through j2objc aswell? In which case, is there a way to do this in bulk?

Maybe I've missed the point in assuming that this was a tool for translating from Android to iOS and it's actually a more general Java -> Objc Library…

**Comment by kstanger** [comment]
You'll find more detailed discussions in our j2objc-discuss discuss about
app architecture. The goal of j2objc is not to provide a direct port of an
Android app to iOS, but rather to allow the developer to write portable
business logic once in Java, with custom UI written for each platform. This
will require you to have well-encapsulated business logic that is
platform-independent (i.e. no android platform dependencies) that you can
translate. The upside is that this encourages more a testable design. If
you follow a MVC design pattern, then your model and controller can be
platform-independent and translatable, while your view will require a
platform-specific implementation per platform.

**Comment by pernilla** [comment]
If you have a lot of files structured in different packages which depends on each other. How would I go about to translated all of them? I have tried to run j2objc on a flattened structure and on the structure as is. But it always complains over missing dependencies. It would be nice with a little more complex sample than HelloWorld.

**Comment by kstanger** [comment]
If you have missing dependencies make sure they are available either
through the sourcepath or the classpath.

**Comment by pernilla** [comment]
I've managed to get it to work with: 

j2objc --no-package-directories -classpath .:libs/* -sourcepath src/main/java/ src/main/java/com/SourceFile.java

Do you have any thoughts on officially support a gradle tool for this? The links to maven and gradle are third party and have not been updated in a very long time.

**Comment by kstanger** [comment]
We don't have the resources or expertise to add support for Maven or
Gradle. We do plan to provide support through Google's Bazel
<https://bazel.build/> be we don't know when we'll be able to deliver that.
