### ISSUE TITLE
Posix.preadBytes called pwrite64 in the native method

### ISSUE THREAD

**Issue by lukhnos** [google/j2objc#554]
`libcore.io.Posix.preadBytes` calls `pwrite64` instead of `pread64` in its native method implementation. I discovered this bug when I was reading from a `FileChannel` from a random access file.

I've made a fully reproducible gist [here](https://gist.github.com/lukhnos/5bc1749cd8ed6507e62c). In essence, this snippet:

```java
ByteBuffer buf = ByteBuffer.allocate(bufLength);
RandomAccessFile raf = new RandomAccessFile(dataFile, "r");
FileChannel channel = raf.getChannel();
int bytesRead = channel.read(buf, 0);
channel.close();
```

Would throw this exception:

```
java.io.IOException: pread failed: EBADF (Bad file descriptor)
    at 0x000000010a1cc4f0 libcore.io.ErrnoException.rethrowAsIOException() + 38
    at 0x000000010a11e749 java.nio.FileChannelImpl.readImpl() + 473
    at 0x000000010a08828d PreadBug.main() + 445
    at 0x000000010a0880bd PreadBug.main() + 29
    at 0x000000010a20664e java.lang.reflect.Method.invoke() + 634
```

Also, if the random access file is opened with mode `"rw"`, the code will finish quietly, causing the file to be overwritten with the content in the buffer, since `pwrite64` is actually called to read from the channel.

**Comment by lukhnos** [comment]
@tomball I saw that the bug has been fixed in https://github.com/google/j2objc/commit/f7725f0f2ce1685e0f14d4d5112d07b5ad2731d0. Would you like to remove the pending tag and close the issue? Thanks!

**Comment by tomball** [comment]
Fixed in current source (thanks for reminding me).
