### ISSUE TITLE
Support javax.sound subset [moved]

### ISSUE THREAD

**Issue by kstanger** [google/j2objc#56]
This is [Issue 56](https://code.google.com/p/j2objc/issues/detail?id=56) moved from a Google Code project.
Added on 2012-10-05T18:16:35.000Z by [yangofz...@gmail.com](http://code.google.comhttps://code.google.com/u/110033792215604512758/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Medium

**Comment by tomball** [comment]
We lost the original issue on code.google.com when we moved to GitHub, and so don't have the list of classes to subset.
