### ISSUE TITLE
RxJava support

### ISSUE THREAD

**Issue by ZakTaccardi** [google/j2objc#560]
As an Android developer, RxJava is a must have library. Once you start using it, you cannot go back.

j2objc should officially support this.

ref: https://groups.google.com/d/msg/j2objc-discuss/3eAwseG4Nms/FU7MgUbX3boJ

**Comment by tomball** [comment]
What's to support? I just cloned it, and it translates and compiles without
errors. Just add it to your project. Better yet, consider creating a static
library Xcode project and add it to the community-supported j2objc-contrib
organization <https://github.com/j2objc-contrib>.
