### ISSUE TITLE
J2ObjC Xcode import

### ISSUE THREAD

**Issue by guptatarun84** [google/j2objc#562]
I am getting below error's while importing J2ObjC code to Xcode. I am done with setting build configurations and header search paths, but could not able to resolve below errors. Please help on this.

Attempting to use the forward class ‘Class A’ as superclass of ‘Class B’
Cannot find interface declaration for ‘Class A’, superclass of ‘Class B’

Thanks,
Tarun

**Comment by confile** [comment]
You can try out this plugin makes Xcode import much more easy https://github.com/j2objc-contrib/j2objc-gradle

**Comment by guptatarun84** [comment]
@confile  I dont see any errors while converting the Java code using J2ObjC eclipse plugin. Is there any specific reason to use gradle for conversion.

**Comment by kstanger** [comment]
If possible, can you post the Java source and the translated .h file that
results in the error?

**Comment by guptatarun84** [comment]
Apologies for late reply. I could able to convert the code successfully by help of https://github.com/yixiang/Xcode-J2ObjC-Example. Now issue persist on SelectorManager.java where my application is crashing on selector.select(time) function. I appreciate if any alternative can be suggested by you.

**Comment by tomball** [comment]
Closed, cannot reproduce.
