### ISSUE TITLE
Trying to plug a memory leak possibly related to use of ThreadPoolExecutor

### ISSUE THREAD

**Issue by patluze** [google/j2objc#566]
(Originally posted as a question at j2objc-discuss)

I translated an application that processes a large volume of tasks using a ThreadPoolExecutor and found memory keeps growing as the application runs.  I specified -use-arc when running j2objc.
Here's a simple test that simulates the issue:

----------------------->
package XXX;

import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

public class ThreadPoolTest {

        static int niters = 0;

        public static void main(String[] args) {
                ThreadPoolTest test = new ThreadPoolTest();
                test.run();
        }

        private class MyAction implements Runnable        {
                public void run() {
                        System.out.println("TestAction run " + ++niters );
                }
        }
        
        void run()        {
                Object syncObj = new Object();
                ExecutorService defThreadPool = Executors.newCachedThreadPool();                
                synchronized(syncObj) {
                        for (int i=0; i<100000; i++) {
                                defThreadPool.execute(new MyAction());
                                try {
                                        syncObj.wait(100);
                                } catch (InterruptedException e) {
                                        // TODO Auto-generated catch block
                                        e.printStackTrace();
                                }
                        }
                }
        }
}
<---------------------

When I review persistent allocations in the XCode Allocations Instrument, I see a set of these persistent entries for each call to the thread pool's execute:

[16 bytes] new_XXXThreadPoolTest_MyAction_initWithXXXThreadPoolTest_
[32 bytes] new_JavaUtilConcurrentSynchronousQueue_TransferStack_SNode_initWithId_
[32 bytes] new_JavaUtilConcurrentSynchronousQueue_TransferStack_SNode_initWithId_

I tried using the @AutoreleasePool annotation in various places but that didn't seem to make a difference.  Is it possible the JRE emulator's ThreadPoolExecutor and/or one of the classes it uses (e.g. SynchronousQueue) is causing a leak?

Thanks in advance for any help.

**Comment by danieldickison** [comment]
When I `-use-arc` and run some ThreadPoolExecutor code via the "Leaks" tool in Instruments, I'm seeing it register tons of leaks almost wherever objects are allocated. The leaks go away when I disable `-use-arc`. This seems strange because the functions and methods that are leading to these leaks have proper `NS_RETURNS_RETAINED` annotations/naming conventions. Is this the same issue, and it is pointing to real leaks or is it confusing the Leaks detector somehow?

<img width="992" alt="screen shot 2015-10-01 at 5 35 00 pm" src="https://cloud.githubusercontent.com/assets/69632/10234484/d6b3acf8-6862-11e5-840d-bcb6caefb51c.png">

**Comment by kstanger** [comment]
Taking a look at SynchronousQueue, it looks like there is a very likely
leak coming from the "match" field of TransferStack.SNode here:
https://github.com/google/j2objc/blob/master/jre_emul/android/libcore/luni/src/main/java/java/util/concurrent/SynchronousQueue.java#L204.
I'll need to read through the implementation a little closer to fully
understand the implementation. In the meantime, feel free to file an issue
to track this.

**Comment by kstanger** [comment]
[Fixed in latest source.](https://github.com/google/j2objc/commit/1557a02c11477c67580adcee16c30996c45e5a40)
