### ISSUE TITLE
Add JreEmul to my framework

### ISSUE THREAD

**Issue by barilevi** [google/j2objc#568]
Hi Tom
I have created my own framework that using jreEmul.
I wrote a small TestApp in swift that using that framework.

While compiling it , I am getting the error:
“non-modular header inside framework module”
How can I "expose" the jreEmul header files for the swift TestApp?
How can I put it in umbrella file?

regards
Bari

**Comment by tomball** [comment]
My limited understanding is that a framework header just #imports all
public header files in the header. So try something like the following to
create an initial version of that header file, and see what breaks:

    $ cd jre_emul
    $ make dist
    $ cd ../dist/include
    $ find * -name '*.h' > ../../jre_emul/build_result/JreEmul.headers
    $ sed 's/^/#import/' ../../jre_emul/build_result/JreEmul.headers >
JreEmul.h

In theory, all that should then be needed for app classes is "#import
<JreEmul/JreEmul.h>", like other frameworks.

**Comment by barilevi** [comment]
Hi Tom
Still does not work.
I upload a new project that simulate the case. 
https://github.com/barilevi/JreEmulInsideFramework
Short Summery:
There is 'TestFramework' framework which has 2 java sources. The framework using JreEmul
Now, I am adding the framework to my Application called 'TestApp'.
TestApp compile  is failed.
Can you please take a look?

**Comment by leogeng** [comment]
@barilevi  Do you fix it?   I meet the same issue

**Comment by barylevy** [comment]
I used their pod:
J2ObjC-Framework

**Comment by leogeng** [comment]
Pod `J2ObjC-Framework` in framework or TestApp?

**Comment by tomball** [comment]
Either use the J2ObjC-Framework pod as @barylevy mentions, or use the JRE.framework now included in the j2objc distribution.
