### ISSUE TITLE
Aggregate notices/licenses for binary distribution?

### ISSUE THREAD

**Issue by advayDev1** [google/j2objc#573]
I'm trying to find all the associated license/NOTICE files for the various libraries (other than j2objc's own code) in the binary distribution (i.e. the ZIP file, and/or the output in the dist/ folder when I build it myself).  I do see various notice/license files in the source directories.  

Are there no license/NOTICE files in the binary distribution intentionally, or can I just not find them (or are they missing by mistake)?

**Comment by tomball** [comment]
I guess it's by mistake, as we only provide the pre-built distribution for
newbies -- all of Google's projects and most others I'm aware of build
j2objc from scratch. What's the recommended practice when building a
distribution to bundle up the licences?

**Comment by advayDev1** [comment]
(I am not a lawyer; this is not legal advice.)

I'm not sure what the requirements are - I assume Chris DiBona etc. would though.  There are tons of separate licenses, even for example: https://github.com/google/j2objc/blob/master/jre_emul/apache_harmony/LICENSE - I don't know if any of them require notices in the binary form though.

I do see a bunch of presumably-j2objc-related license notices in, for example, Google's Inbox app (in the UI, no idea what is in the apk).

**Comment by tomball** [comment]
Fixed in public source. Licenses are now copied into a license/ directory during the build, following the directory format Android Studio uses.
