### ISSUE TITLE
Support -processor and -processorpath for j2objc 

### ISSUE THREAD

**Issue by iCarry** [google/j2objc#574]
From javac doc/help menu:

-processor class1[,class2,class3...]
Names of the annotation processors to run. This bypasses the default discovery process.
-processorpath path
Specify where to find annotation processors; if this option is not used, the class path will be searched for processors.

Use case:
https://groups.google.com/forum/#!topic/j2objc-discuss/G4YzNQwq6Xc

**Comment by tomball** [comment]
Fixed in [latest source](https://github.com/google/j2objc/commit/8df3317bde19f942342675ffa1efcc820532a16a).
