### ISSUE TITLE
Support OCNI blocks for non-native methods

### ISSUE THREAD

**Issue by advayDev1** [google/j2objc#576]
I occasionally come across methods that I need to hand-roll in my iOS app, but want to keep Java in my Android app.  So I can't change the method in my Java source to be 'native'.  Currently I solve this in a roundabout fashion with a separate .java file just for the j2objc translation step, which does define the method as native and adds an OCNI implementation.  Much less hacky would be to allow an OCNI block for non-native methods as well.  When creating the .m file, the OCNI block would be inserted instead of the translated Java block, no different than for the current native OCNI blocks.

Thoughts?  Considered before but rejected?  On the roadmap?  Something that would be considered for merger if I or another external contributor did it?

**Comment by tomball** [comment]
You have a few options you can try today. One is GWT's "super-source" strategy: copy the Android version into a separate source tree, rewrite it as you see fit, and put that source path ahead of the main one when building for iOS. That way, your Android app's source is unchanged, and only those classes that need optimizing are duplicated.

Another approach is to have separate Android and iOS versions of the class, then dynamically load them in an abstract base class. This can be combined with super-sourcing, so methods needing separate implementations are abstract in the base class, with all shared methods remaining there. That reduces the chance of the two versions of the file getting out-of-sync.

Another option is to use a preprocessor. I wrote [munge](https://publicobject.com/2009/02/preprocessing-java-with-munge.html) back in the early JDK days, and it just won't die. As Jesse describes in that link, the Guice team uses it, and there's also a [Maven plugin](https://github.com/sonatype/munge-maven-plugin).

**Comment by advayDev1** [comment]
I use the super-source strategy right now (without knowing the name :).  Will try out munge and see how easy it is to put into my gradle workflow.  Thanks!

**Comment by tomball** [comment]
OCNI blocks can now be defined either inside or outside of a class.
