### ISSUE TITLE
JavaLangThrowable should be mapped to NSException

### ISSUE THREAD

**Issue by DanielZlotin** [google/j2objc#581]
In order to catch all exceptions in java we catch Throwable. In iOS we catch NSException.

When developing for a common code base and wanting to catch all exceptions is both environments we should map the translation for JavaLangThrowable to NSException, the same as mapping String to NSString or Number to NSNumber.

As discussed here https://groups.google.com/forum/#!topic/j2objc-discuss/svseZqKrdfE

**Comment by tomball** [comment]
I have a patch that should land early next week -- it's complicated by references to JavaLangThrowable in Objective C source files that don't #include java/lang/Throwable.h. <sigh/>

**Comment by kstanger** [comment]
This is fixed in 1.0.1
