### ISSUE TITLE
0.9.8: temp value may cause EXC_BAD_ACCESS code=1.

### ISSUE THREAD

**Issue by w-rui** [google/j2objc#586]
Like java code below:
```
        // 2. Devices & Connections
        Log.i(TAG, "Start to build Device & Connection relations of GlobalNetwork: " + Id());
        for (NetworkConfig.DeviceBaseConfig dev : GetDeviceConfs().values()) {
            networkChangeLsnrs.broadcast(l -> l.DeviceAdded(this, dev));
        }

        // 3. Groups
        Log.i(TAG, "Start to build Group relations of GlobalNetwork: " + Id());
        for (NetworkConfig.GroupConfig group : GetGroupConfs().values()) {
            networkChangeLsnrs.broadcast(l -> l.GroupAdded(this, group));
        }
```

will translated to code below:
```
AndroidUtilLog_iWithNSString_withNSString_(GlobalNetwork_TAG_, JreStrcat("$@", @"Start to build Device & Connection relations of GlobalNetwork: ", [self Id]));
  for (NetworkConfig_DeviceBaseConfig * __strong dev in nil_chk([((id<JavaUtilMap>) nil_chk([self GetDeviceConfs])) values])) {
    [((BaseListenerList *) nil_chk(networkChangeLsnrs_)) broadcastWithBaseListenerList_Lam:GetCapturingLambda(@protocol(BaseListenerList_Lam), @"GlobalNetwork_lambda$10", @selector(lWithId:),
    ^void(id _self, BaseGlobalNetwork_NetworkChangeLsnr * a) {
      void (^block)() = objc_getAssociatedObject(_self, (void *) 0);
      block(_self, a);
    },
    ^void(id _self, BaseGlobalNetwork_NetworkChangeLsnr * l){
      [((BaseGlobalNetwork_NetworkChangeLsnr *) nil_chk(l)) DeviceAddedWithGlobalNetwork:self withNetworkConfig_DeviceBaseConfig:dev];
    }
    )];
  }
  AndroidUtilLog_iWithNSString_withNSString_(GlobalNetwork_TAG_, JreStrcat("$@", @"Start to build Group relations of GlobalNetwork: ", [self Id]));
  for (NetworkConfig_GroupConfig * __strong group in nil_chk([((id<JavaUtilMap>) nil_chk([self GetGroupConfs])) values])) {
    [((BaseListenerList *) nil_chk(networkChangeLsnrs_)) broadcastWithBaseListenerList_Lam:GetCapturingLambda(@protocol(BaseListenerList_Lam), @"GlobalNetwork_lambda$11", @selector(lWithId:),
    ^void(id _self, BaseGlobalNetwork_NetworkChangeLsnr * a) {
      void (^block)() = objc_getAssociatedObject(_self, (void *) 0);
      block(_self, a);
    },
    ^void(id _self, BaseGlobalNetwork_NetworkChangeLsnr * l){
      [((BaseGlobalNetwork_NetworkChangeLsnr *) nil_chk(l)) GroupAddedWithGlobalNetwork:self withNetworkConfig_GroupConfig:group];
    }
    )];
  }
```

In the translated code above, when call `GetDevicwConfs().values()` ( translated to: `for (NetworkConfig_DeviceBaseConfig * __strong dev in nil_chk([((id<JavaUtilMap>) nil_chk([self GetDeviceConfs])) values]))`), it will first returns a `HashMap<>`, and then get values in it. But when I start to access values in it. The temp HashMap returned is already deallocated by ARC before I access it.
I have tried solution like below and it works ( holding all temp returned `HashMap<>` and `Collection<>` in local storage ):
```
  id<JavaUtilMap> maps = ((id<JavaUtilMap>) nil_chk([self GetDeviceConfs]));
  id<JavaUtilCollection> objs = nil_chk([maps values]);
  for (NetworkConfig_DeviceBaseConfig * __strong dev in objs) {
 // do something...
  }
```

So, my question is, how could I fix all problems above without manual-editing the translated code?

**Comment by w-rui** [comment]
Something more:
1. Only crash when the returned value is temp allocated and returned.
2. If the returned temp value is already hold by any other object, code will not crash.

In my previous app-version, all `GetDeivceConfs()` & `GetGroupConfs()` are hold by static storage, but the latest app-version, all returned values are cloned before, so the returned value must be saved.

So, the problem is how to generate code for holding any returned temp-allocated value in local storage.

**Comment by kstanger** [comment]
The HashMap returned by GetDeviceConfs() should live for the duration of the current autoreleasepool, unless the HashMap is created in another thread. If that is the case, the @RetainedLocalRef annotation will help.
https://github.com/google/j2objc/blob/master/annotations/src/main/java/com/google/j2objc/annotations/RetainedLocalRef.java

You can add this annotation to a local variable like this to ensure that it is retained for the duration of its scope:
@RetainedLocalRef Map deviceConfs = GetDeviceConfs();

**Comment by kstanger** [comment]
Hopefully my previous comment has helped. If the issue persists, please reopen this bug and add more info if possible, including the GetDeviceConfs() implementation.
