### ISSUE TITLE
Translator generate methods with language keywords in names and methods with identical names.

### ISSUE THREAD

**Issue by lordofdest** [google/j2objc#588]
Reproduced only with --static-accessor-methods.
Version: j2objc-master-Aug 10, 2015.

Generate accessors for enums:
+ (Log_LevelEnum *)DEBUG;

Affected Keywords:
NULL
YES
NO
TRUE
FALSE
DEBUG
EOF
etc.

Methods:
+ (SomeType*)engine {
  return SomeType_engine_;
}
......
+ (SomeType*)engine {
  return SomeType_engine();
}

**Comment by tomball** [comment]
Generators were using NameTable.getVariableBaseName(), which isn't escaped for reserve words.

**Comment by kstanger** [comment]
Fixed in current source.

**Comment by tomball** [comment]
Fix is still in review.

**Comment by tomball** [comment]
Fixed in current source (really this time :-)
