### ISSUE TITLE
Merge JUnit CycleFinder changes upstream

### ISSUE THREAD

**Issue by brunobowden** [google/j2objc#592]
@tomball, @kstanger - are there plans to merge the changes you've made to JUnit in to the upstream repository? After fixing Guava, this should leave behind `jre_emul` that'll have to remain as is.

@advayDev1 - FYI

**Comment by kstanger** [comment]
There's nothing in the works to speak of. But this will probably be worth
some effort at some point.

**Comment by tomball** [comment]
The JUnit team rejected adding a j2objc dependency.
