### ISSUE TITLE
Java Reflect Field crashes when using Prefixes

### ISSUE THREAD

**Issue by Lukasz2891** [google/j2objc#593]
Let have:

AnyClass.java:
```java
package testpackage.source;
public class AnyClass {
    public OtherClass field = new OtherClass();
}
```

OtherClass.java:
```java
package testpackage.source;
public class OtherClass {
    @Override
    public String toString() {
        return "an OtherClassObject";
    }
}
```

TestClass.java:
```java
package testpackage.source;
import java.lang.reflect.Field;
public class TestClass{
    public static void main(Object o) {
        try{
            Field f = o.getClass().getDeclaredField("field");
            Object x = f.get(o); //raises an exception, JavaLangClassNotFoundException when prefixes are used
            System.out.println(f.getName()+":"+x+"\n");
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }
}
```

And the following scenarios in Objective-C:

The first one:
```objective-c
    TestpackageSourceAnyClass* o = [[TestpackageSourceAnyClass alloc] init];
    TestpackageSourceTestClass_mainWithId_(o);
```

produces:
`field:an OtherClassObject`

All seems to be OK.

But the second one, using a prefixes.properties file:
    `testpackage.source:TS`
```objective-c
    TSAnyClass* o = [[TSAnyClass alloc] init];
    TSTestClass_mainWithId_(o);
```
produces:
  ` java.lang.ClassNotFoundException: testpackage.source.OtherClass`
	`at 0x0000000108eb0ae9 java.lang.ClassNotFoundException.<init>() + 22`
	`at 0x0000000108fde878 java.lang.Class.forName_() + 1048`
	`at 0x0000000108ff93fd java.lang.reflect.Field.getType() + 50`
	`at 0x0000000108ff8b02 java.lang.reflect.Field.get() + 37`
	`at 0x0000000108e8ef39 testpackage.source.TestClass.main() + 249`

I'm using the pre-building rule in xCode:
`${J2OBJC_HOME}/j2objc -d ${DERIVED_FILES_DIR} -sourcepath ${PROJECT_DIR}/java/module/src --prefixes ${PROJECT_DIR}/prefixes.properties --no-package-directories -use-arc -source 8 -Xforce-incomplete-java8 ${INPUT_FILE_PATH}`

Is there any way to fix it?

**Comment by Lukasz2891** [comment]
Ohhh.

I've added the prefixes.properties file to the Project and now it works.

But the issue could stay here for others...

**Comment by tomball** [comment]
Thanks for the follow-up explanation, it should indeed help other
developers.
