### ISSUE TITLE
Semantics of translated try-with-resources statements differs from that in Java

### ISSUE THREAD

**Issue by lukhnos** [google/j2objc#596]
There are three issues with the current translation of try-with-resources statements: They do not close the resources in the reverse order in which they are initialized; the `finally` block is evaluated before closing resources; and lastly, exceptions during resource initialzation are not handled according to the [extended try-with-resources semantics](https://docs.oracle.com/javase/specs/jls/se8/html/jls-14.html#jls-14.20.3.2).

Consider the following example:

```java
public class TryWithResourcesExample {
  public static class Resource implements AutoCloseable {
    String name;

    public Resource(String name) {
      System.out.println("created: " + name);
      this.name = name;
    }

    @Override
    public void close() throws Exception {
      System.out.println("closed: " + name);
    }
  }

  public static void main(String args[]) throws Exception {
    try (Resource r1 = new Resource("r1");
         Resource r2 = new Resource("r2");
         Resource r3 = new Resource("r3")) {
      System.out.println("body");
    } catch (Exception e) {
      e.printStackTrace();
    } finally {
      System.out.println("finally");
    }
  }
}
```

The expected output, as from the javac-compiled program, is:

```
created: r1
created: r2
created: r3
body
closed: r3
closed: r2
closed: r1
finally
```

The output from the current translation is:

```
created: r1
created: r2
created: r3
body
finally
closed: r1
closed: r2
closed: r3
```

This can be problematic when sequence matters. For example, if `r1` is a `FileChannel` and `r2` is a `FileLock`, closing `r1` before `r2` causes `r2.close()` to throw a `ClosedChannelException`.

I'm currently using a workaround to fix the closing order as well as to evaluate the `finally` block after resource closures: https://github.com/google/j2objc/commit/a5cb336e96f73dd836ebb9961072c2abab3f0c69.

I think the real fix should be to generate the try-with-resources code according to the semantics in the [Java spec](https://docs.oracle.com/javase/specs/jls/se8/html/jls-14.html#jls-14.20.3). The current translation implements part of the [basic try-with-resources](https://docs.oracle.com/javase/specs/jls/se8/html/jls-14.html#jls-14.20.3.1) case, where exceptions during the initialization of the first resource will be handled by the outer scope. However, for the example above, the translation should behave like an [extended try-with-resources](https://docs.oracle.com/javase/specs/jls/se8/html/jls-14.html#jls-14.20.3.2). Either way, the `ResourceSpecification_tail` (the `r2, ..., rn` part when there is more than one resource) should also be translated into nested try blocks.

I was wondering if this issue is already being considered, or if there are complications. Could there be any [memory management issues](https://developer.apple.com/library/ios/documentation/Cocoa/Conceptual/Exceptions/Tasks/HandlingExceptions.html#//apple_ref/doc/uid/20000059-SW7) if we translate try-with-resources into nested handlers with rethrows?

**Comment by tomball** [comment]
I agree that try-with-resources generation needs to follow the spec. The original translation was written when the spec was much simpler (Google contributed the original spec and javac support), but over time it's grown into a convoluted mess (IMO). We will certainly generate code for multiple resources that performs according to spec, but it's unlikely to be readable by mere mortals.

**Comment by tomball** [comment]
Rewrote try-with-resources support to match JLS spec.
