### ISSUE TITLE
Add reflection support for EasyMock tests [moved]

### ISSUE THREAD

**Issue by kstanger** [google/j2objc#6]
This is [Issue 6](https://code.google.com/p/j2objc/issues/detail?id=6) moved from a Google Code project.
Added on 2012-09-05T22:56:43.000Z by [tball@google.com](http://code.google.comhttps://code.google.com/u/tball@google.com/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Low, Testability

**Comment by tomball** [comment]
Implemented.
