### ISSUE TITLE
Add support for JNI code [moved]

### ISSUE THREAD

**Issue by kstanger** [google/j2objc#60]
This is [Issue 60](https://code.google.com/p/j2objc/issues/detail?id=60) moved from a Google Code project.
Added on 2012-10-09T14:32:23.000Z by [tball@google.com](http://code.google.comhttps://code.google.com/u/tball@google.com/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Low

**Comment by tomball** [comment]
Native methods that do not have OCNI embedded code are now translated using the JNI function format. A basic JNIEnv vtable is now defined in jni.h
