### ISSUE TITLE
Throwable leaks its suppressedExceptions array

### ISSUE THREAD

**Issue by lukhnos** [google/j2objc#601]
It appears that the `suppressedExceptions` array in `Throwable` is not released in `-dealloc`. It leaks the array when an exception is thrown or when an instance is created with the default parameters (with `enableSuppression` being `YES`).

This can be demonstrated using [the gist here](https://gist.github.com/lukhnos/65840aa045d79c98bf1f). Compile the code with j2objc and j2objcc, then run it using Instruments's Leaks to see that both `foo` and `bar` leak `IOSObjectArray`s.

**Comment by tomball** [comment]
Thanks!
