### ISSUE TITLE
FileChannelImpl and FileLock leak memory

### ISSUE THREAD

**Issue by lukhnos** [google/j2objc#603]
The three classes that implement `getChannel()` – `FileInputStream`, `FileOutStream`, `RandomAccessFile` – all own their `channel` field, and therefore `FileChannelImpl.stream` should be annotated as `@Weak`. The same applies to `FileLock`, which is owned by `FileChannelImpl`, and therefore `FileLock.channel` should have `@Weak`.

This can be demonstrated using [the gist here](https://gist.github.com/lukhnos/374f7b342e0a65a4cdfc).

**Comment by tomball** [comment]
Good catch.
