### ISSUE TITLE
The translated java.io.Reader leaks memory when the lock object is itself

### ISSUE THREAD

**Issue by lukhnos** [google/j2objc#605]
This is related to #169. `StringReader` is currently leaking itself, because the default constructor of `java.io.Reader`, its superclass, is using itself as the lock object:

``` java
protected Reader(Object lock) {
  if (lock == null) {
    throw new NullPointerException("lock == null");
  }
  this.lock = lock;
}
```

A [proposed fix](https://groups.google.com/d/msg/j2objc-discuss/fRgehuDZG5k/8MUFFzNfJP0J) discussed in the mailing list is to nullify `lock` in `StringReader.close`:

``` java
final StringReader reader = new StringReader(txt)  {
   public void close() {
    super.close();
    lock = null;
   }
};
```

This can be applied to `StringReader`'s own `close` method, but it is pretty common that `StringReader.close` is never called (presumably because people know that the underlying resource is a string).

I'm currently relying on modifying the translated `Reader.m`:

``` objc
- (void)dealloc {
  if (lock_ != self) {
    RELEASE_(lock_);
  }
  [super dealloc];
}

void JavaIoReader_init(JavaIoReader *self) {
  NSObject_init(self);
  // JreStrongAssign(&self->lock_, self);  // deleted
  self->lock = self;
}
```

Not sure if this is the best way to do it (and certainly modifying the translated output is not ideal), though it requires no changes to the `@synchorized(lock_)` uses in `Reader`'s other methods.

I haven't tried to move this back to the Java source using OCNI, though I assume it'll be needed (I realized, for example, that `IosX509Certificate` has its `-dealloc` implemented that way).

**Comment by tomball** [comment]
What do you think about changing Reader(lock) to something like:

```java
    protected Reader() {
        lock = new Object();
    }
```

It costs an extra object, but since it addresses the leak that's only for the life of the Reader.

**Comment by lukhnos** [comment]
@tomball Made a [pull request](https://github.com/google/j2objc/pull/606) and applied your suggestion to fix a number of `lock = this` uses. Thanks!

**Comment by himamis** [comment]
I have this problem again with j2objc release 1.2
It looks like pull request #606 which was accepted is now overwritten by this commit https://github.com/google/j2objc/commit/f2e9a2c25fc5a493d7f862c3885cfe6ae7e82afa.

**Comment by tomball** [comment]
All references to "lock = this;" are now fixed.
