### ISSUE TITLE
ConcurrentLinkedQueue relies on setting next to this, but that leaks memory

### ISSUE THREAD

**Issue by lukhnos** [google/j2objc#609]
When a ConcurrentLinkedQueue dequeues a node, the Java implementation relies on [setting its next field to itself](https://github.com/google/j2objc/blob/07bbe6b5f089205c79585e7272d4c457e572c43a/jre_emul/android/libcore/luni/src/main/java/java/util/concurrent/ConcurrentLinkedQueue.java#L274) as a way to mark the node as removed. It also uses that technique to prevent [unbounded retention](https://github.com/google/j2objc/blob/07bbe6b5f089205c79585e7272d4c457e572c43a/jre_emul/android/libcore/luni/src/main/java/java/util/concurrent/ConcurrentLinkedQueue.java#L105) (in other words, only live nodes should be GC-reachable).

The technique leaks memory when it's translated to Objective-C. I wonder if we can add a marker object to the translated version, similar to what we did for #605.

The code sets `next` to `this` with a compare-and-swap call and compares `this` to `next` in a lot of places in the non-obvious form of `if (p == q)` ([example](https://github.com/google/j2objc/blob/07bbe6b5f089205c79585e7272d4c457e572c43a/jre_emul/android/libcore/luni/src/main/java/java/util/concurrent/ConcurrentLinkedQueue.java#L312)), and so if we take this approach we'll need to carefully examine the changes.

There is a potential problem of reading stale values in a non-GC environment – the "ABA problem" discussed in [the original paper](http://www.cs.rochester.edu/~scott/papers/1996_PODC_queues.pdf) as well as in [the code comment](https://github.com/google/j2objc/blob/07bbe6b5f089205c79585e7272d4c457e572c43a/jre_emul/android/libcore/luni/src/main/java/java/util/concurrent/ConcurrentLinkedQueue.java#L85). For example, when we finally get to compare-and-swap `tail->next` with the new node we're enqueuing, we want to make sure that `tail`'s memory content is still what we saw before (because the node at `tail` may actually have been dequeued in another thread at that point, and the address at `tail` may mean something else in a non-GC environment). The paper pairs pointers with counters to mitigate the problem. I wonder if this has to be introduced back into the Objective-C translation.

I haven't looked into it too much, but [LinkedTransferQueue](https://github.com/google/j2objc/blob/master/jre_emul/android/libcore/luni/src/main/java/java/util/concurrent/LinkedTransferQueue.java) appears to have the same issue.

(Edit: Example for the ABA problem.)

**Comment by kstanger** [comment]
I'll be using the marker object solution as you suggest. The ABA problem should not affect us because our translation of volatile variables ensure that they live for at least the duration of the autorelease pool where they are read.

**Comment by kstanger** [comment]
[Fixed ConcurrentLinkedQueue](https://github.com/google/j2objc/commit/db2597b64e3cd8ce18a6d8832df08b35a7a7b529) and [fixed LinkedTransferQueue](https://github.com/google/j2objc/commit/ec115ebab1a493035aadbc9ab427f6b20fdb0d0c).

**Comment by lukhnos** [comment]
Thanks for the fixes!

**Comment by kstanger** [comment]
Sure. Let me know if you find more.
