### ISSUE TITLE
BitCode support

### ISSUE THREAD

**Issue by ex3ndr** [google/j2objc#610]
BitCode is new cool technology from apple that allows to submit LLVM IR(?) instead of compiled binary that can dramatically reduce amount of code it might be cool to have such thing in j2objc as it may reduce binary size up to 3x times.

If you will be succeeded in this, please provide information how makefiles need to be modified to make it work.

**Comment by tomball** [comment]
You need to [rebuild jre_emul with Xcode 7](https://github.com/google/j2objc/blob/master/jre_emul/environment.mk#L161) as the default. Apple (in its infinite wisdom) decided to add the new bitcode flag to all new projects, even though earlier versions of clang will report a bad-flag error when it's used. We therefore cannot support bitcode by default, until Xcode 7/iOS 9 are the minimum supported releases. In other words, not for a year or two.

**Comment by ex3ndr** [comment]
If someone is insterested i have recompiled j2objc 0.9.8.1 with bitcode support and fixed simulator build: https://dl.bintray.com/actor/j2objc/j2objc-0.9.8.1.zip

**Comment by tomball** [comment]
What did you have to change to support bitcode? We currently add the
-f-embed-bitcode-marker flag if clang is 7.0 or greater.
<https://github.com/google/j2objc/blob/master/jre_emul/environment.mk#L164> Did
other libraries require the same change?
