### ISSUE TITLE
libguava.a(Strings.o)' does not contain bitcode. You must rebuild it with bitcode enabled

### ISSUE THREAD

**Issue by confile** [google/j2objc#613]
I saw [this issue](https://github.com/google/j2objc/issues/610) it solved the problem for the simulator. 
I use Xcode7 downloaded the latest j2objc and build the lib using ``make dist`` with clang7. It works perfectly with the simulator but when it comes to a real device I get: 

```
ld: '/Applications/J2Objc/j2objc-0.9.8.1/lib/libguava.a(Strings.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

It seems that bitcode is not compiled correctly for architecture armv7.

**Comment by steffimueller** [comment]
same here. Works fine on simulate but armv7 does not run.

**Comment by tomball** [comment]
Add "-fembed-bitcode-marker" to the end of the FAT_LIB_IPHONE_FLAGS
definition in make/fat_lib_macros.mk
<https://github.com/google/j2objc/blob/master/make/fat_lib_macros.mk#L26>
and rebuild. Since bitcode is only an option with armv7 builds, the flags
for the other archs don't need to change.

**Comment by confile** [comment]
@tomball You saved my life thank you!
