### ISSUE TITLE
libjre_emul.a(AsyncTask.o)' was built only with bitcode marker. The library must be generated from Xcode archive build with bitcode enabled (Xcode setting ENABLE_BITCODE)

### ISSUE THREAD

**Issue by confile** [google/j2objc#615]
I use Xcode7 and compiled j2objc with bitcode flag as @tomball suggested here: https://github.com/google/j2objc/issues/613

My app runs perfectly on simulator and on my device, but when I want to archive my app I get the following error:

```
ld: warning: full bitcode bundle could not be generated because '/Applications/J2Objc/j2objc-0.9.8.1/lib/libjre_emul.a(AsyncTask.o)' was built only with bitcode marker. The library must be generated from Xcode archive build with bitcode enabled (Xcode setting ENABLE_BITCODE)
ld: '/Applications/J2Objc/j2objc-0.9.8.1/lib/libguava.a(Strings.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

```

**Comment by confile** [comment]
Here is the solution: add ``-fembed-bitcode-marker`` here:

https://github.com/google/j2objc/blob/master/make/fat_lib_macros.mk#L29

**Comment by tomball** [comment]
We don't support bitcode submissions yet -- it takes us awhile to recover
from any major Xcode releases (I'm currently fixing the build, now that
Xcode no longer forwards the build environment to tasks). Contributions are
welcome if anyone finds our pace too slow.

Question for anyone: can a static library compiled as bitcode be included
in a fat library? It would be much easier to support bitcode if that were
the case.

**Comment by tomball** [comment]
Updated fat_lib_macros.mk as you suggested.

**Comment by confile** [comment]
@tomball thanks Tom!

**Comment by confile** [comment]
Sorry, but I have no idea on your question.

**Comment by hermanccw** [comment]
Just wanted to added that the updated fat_lib_macros.mk did not work for me.  Instead of -fembed-bitcode-marker, I changed it to -fembed-bitcode and my archive build started to work.

**Comment by tomball** [comment]
You need to build from current source; the relevant flags are in [make/fat_lib_macros.mk](https://github.com/google/j2objc/blob/master/make/fat_lib_macros.mk#L41) and [jre_emul/environment.mk](https://github.com/google/j2objc/blob/master/jre_emul/environment.mk#L173). 

You also need to build with [clang 7.0.0 or later](https://github.com/google/j2objc/blob/master/make/common.mk#L159), which is distributed with Xcode 7.0+. You can verify that with:

    $ clang --version
    Apple LLVM version 7.0.0 (clang-700.1.76)
    Target: x86_64-apple-darwin15.0.0
    Thread model: posix
