### ISSUE TITLE
Using --no-package-directories results in declaration errors

### ISSUE THREAD

**Issue by amlcurran** [google/j2objc#618]
When running the following two commands, I get many "could not find declaration" errors in the second, some of which are shown below. However, removing the `--no-package-directories` flag results in no errors.

```bash
j2objc --prefix uk.co.amlcurran.social=SC -d build/ios/objc -sourcepath core/src/main/java --no-package-directories `find core/src/main/java/ -name '*.java'`
j2objcc -c -I. `find . -name '*.m'`
```

Errors:
```
In file included from ./CalendarItem.m:7:
In file included from ./CalendarItem.h:9:
In file included from /Users/amlcurran/bin/include/J2ObjC_header.h:18:
In file included from /Users/amlcurran/bin/include/J2ObjC_common.h:18:
In file included from /System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:6:
In file included from /System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:26:
./time.h:11:20: error: cannot find protocol declaration for 'NSObject'
@protocol SCTime < NSObject, JavaObject >
                   ^
./time.h:11:30: error: cannot find protocol declaration for 'JavaObject'
@protocol SCTime < NSObject, JavaObject >
                             ^
./time.h:13:32: error: expected a type
- (id<SCTime>)plusDaysWithInt:(jint)days;
                               ^
./time.h:15:4: error: expected a type
- (jint)daysSinceEpoch;
   ^
./time.h:17:4: error: expected a type
- (jlong)getMillis;
   ^
./time.h:23:1: error: expected function body after function declarator
J2OBJC_TYPE_LITERAL_HEADER(SCTime)
^
```

The only difference seems to be the ordering of the imports in the m files. In the one which works:

```objc
#include "J2ObjC_source.h"
#include "uk/co/amlcurran/social/CalendarItem.h"
```

```objc
#include "CalendarItem.h"
#include "J2ObjC_source.h"
```

**Comment by tomball** [comment]
You may have in import cycle, so try the --segmented-headers flag (it won't
hurt, but just adds more preprocessor noise to the generated .h files).

Also check that you don't have two classes with the same name (like the
JRE's java.util.Date and java.sql.Date), as stripping the packages will
cause the second translation to overwrite the first. If that's the case,
either rename one class or build your translated files separately using
Make into a static library, then link that into your app.

**Comment by tomball** [comment]
Quick question: which ordering of the two headers works for you? Does the second pair of #include lines fail?

**Comment by kstanger** [comment]
I think your problem is that you have a Java class named "Time.java", and
the generated header conflicts with an existing header in the
CoreFoundation framework. Without the --no-package-directories flag, the
conflict goes away because your generated header has an added path
component.

If you want to use --no-package-directories, then I recommend renaming your
Time.java class.

**Comment by amlcurran** [comment]
Yeah, I was thinking it was the same thing, I had some other errors when I tried another way but renaming Time.h to ScTime.h fixed those. Will try again tonight and re-verify - I'll close the issue if I can't reproduce it.

**Comment by amlcurran** [comment]
Doesn't seem to be a problem, so will happily close. Thanks guys, for your help!

Relatedly, is there an ability to add the package-prefix to the header file name? So the header would translate as SCTime.h, rather than Time.h?

**Comment by tomball** [comment]
> Relatedly, is there an ability to add the package-prefix to the header
file name? So the header would translate as SCTime.h, rather than Time.h?

No, but contributions are cheerfully accepted. :-)  That can't be the
default behavior, however, since most build systems work off of suffixes to
determine build products. Still, some sort of --output-prefix-names flag
would probably be useful for developers like yourself.
