### ISSUE TITLE
0.9.8.2 Guava is missing

### ISSUE THREAD

**Issue by sadevelopment** [google/j2objc#620]
@tomball We have upgraded to the latest release but Guava is missing. This is a dependency of some of our other translated java dependencies. Is there any chance you can add it in, we'd rather use the vanilla build you provide as all our CI systems are configured to use your tagged version?

**Comment by tomball** [comment]
Just rebuilt as [0.9.8.2.1](https://github.com/google/j2objc/releases/tag/0.9.8.2.1).

**Comment by sadevelopment** [comment]
Thanks Tom for the speedy resolution :)
