### ISSUE TITLE
Unknown type name 'CF_EXTERN_C_BEGIN'

### ISSUE THREAD

**Issue by xudeheng** [google/j2objc#621]
Used j2objc in .mm file ,prompt this compile error.

**Comment by tomball** [comment]
CF_ is the prefix used by the CoreFoundation framework, and CF_EXTERN_C_BEGIN is defined in its CFBase.h header. Since this header is included by all j2objc-generated files (j2objc->Foundation->CoreFoundation), my guess is you are compiling this as a Objective-C file instead of an Objective-C++ one. The C compiler, clang, will normally assume Objective-C++ for files with a .mm suffix, so my guess is it is being compiled with the "-x objective-c" flag. If you are building in Xcode, click on the details icon at the right of the log entry with the problem to show the full compile command. To force Objective-C++ compilation, you can use the "-x objective-c++" flag.

Another way this can fail is if you are not compiling on a Mac with Xcode installed (plus the Xcode command-line tools if you are building outside of Xcode). An iOS SDK is required to use j2objc, and if it's not installed then the CoreFoundation headers aren't present. Please note that we do not support compiling translated files on other platforms, since the iOS SDK license restricts its use to a Mac.

If you have a j2objc-generated .mm file which shows this error with the -x objective-c++ flag, please reopen this issue and attach the file having trouble.

**Comment by alizainprasla** [comment]
I am using **J2Reversi** project to test and trying to build with few libraries.
1- [gnu.trove](https://github.com/palantir/trove-3.0.3)
2- [SourceAFIS](https://github.com/azihassan/sourceafis-android)

While build the code, i checked my derived source directory converted files into objc but getting these error.
<img width="313" alt="Screenshot 2019-07-19 at 8 58 18 PM" src="https://user-images.githubusercontent.com/820419/61548841-0cd33600-aa68-11e9-910b-d11c6cd025ef.png">



As you said above, 

> /dist/frameworks/JRE.framework/Headers/J2ObjC_common.h:68:1: Unknown type name 'CF_EXTERN_C_BEGIN'
> /usr/local/bin/j2objc/examples/j2objc-sample-reversi-master/J2Reversi-Prefix.pch:12:11: In file included from /usr/local/bin/j2objc/examples/j2objc-sample-reversi-master/J2Reversi-Prefix.pch:12:
> /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.2.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIKit.h:8:9: In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.2.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIKit.h:8:
> /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.2.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:6:10: In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.2.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:6:
> /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.2.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:43:10: In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.2.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:43:
> /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.2.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFBase.h:72:10: In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.2.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFBase.h:72:
> /Users/alizain/Library/Developer/Xcode/DerivedData/J2Reversi-cdblqxdinkulsgbvdbqqcxbcsall/Build/Intermediates.noindex/J2Reversi.build/Debug-iphonesimulator/J2Reversi.build/DerivedSources/Block.h:6:10: In file included from /Users/alizain/Library/Developer/Xcode/DerivedData/J2Reversi-cdblqxdinkulsgbvdbqqcxbcsall/Build/Intermediates.noindex/J2Reversi.build/Debug-iphonesimulator/J2Reversi.build/DerivedSources/Block.h:6:
> /dist/frameworks/JRE.framework/Headers/J2ObjC_header.h:18:9: In file included from ../../dist/frameworks/JRE.framework/Headers/J2ObjC_header.h:18:
> /dist/frameworks/JRE.framework/Headers/IOSObjectArray.h:25:9: In file included from ../../dist/frameworks/JRE.framework/Headers/IOSObjectArray.h:25:
> /dist/frameworks/JRE.framework/Headers/IOSArray.h:21:9: In file included from ../../dist/frameworks/JRE.framework/Headers/IOSArray.h:21:

**Comment by tomball** [comment]
To update j2reversi to use Objective-C++, I made three changes to the Xcode project:

- Ran Product->Clean Build Folder. This is necessary to rebuild the PCH (precompiled header) file (notice how that's the second line in your error);
- Updated the Build Rule for Java Source Files, adding the "-x objective-c++" flag to its script; and
- Changed that rule's "${DERIVED_FILES_DIR}/${INPUT_FILE_BASE}.m" output file to "${DERIVED_FILES_DIR}/${INPUT_FILE_BASE}.mm".

**Comment by alizainprasla** [comment]
Thanks for your quick response. I followed all the instructions getting same error. One more thing i want to add is that i changed `package gnu.trove` into `package Othello.Engine` and add all gnu.trove files into **Othello/Engine** folder. i hope it's not the reason for these error.


- Ran Product->Clean Build Folder. This is necessary to rebuild the PCH (precompiled header) file (notice how that's the second line in your error);

_I do clean build folder before build_

- Updated the Build Rule for Java Source Files, adding the "-x objective-c++" flag to its script; and

Added the flag as you mention above.

`if [ ! -f "${J2OBJC_HOME}/j2objc" ]; then echo "J2OBJC_HOME not correctly defined in Settings.xcconfig, currently set to '${J2OBJC_HOME}'"; exit 1; fi;
"${J2OBJC_HOME}/j2objc" -d ${DERIVED_FILES_DIR} -sourcepath "${PROJECT_DIR}/Classes" --no-package-directories -x objective-c++ -use-arc --prefix Othello.Engine=JOE -g ${INPUT_FILE_PATH};`

- Changed that rule's "${DERIVED_FILES_DIR}/${INPUT_FILE_BASE}.m" output file to "${DERIVED_FILES_DIR}/${INPUT_FILE_BASE}.mm".

<img width="355" alt="Screenshot 2019-07-22 at 12 43 51 PM" src="https://user-images.githubusercontent.com/820419/61615004-77f65580-ac7e-11e9-9d83-ed963263ef67.png">


These is how it looks like on xcode.
<img width="1372" alt="Screenshot 2019-07-22 at 12 56 39 PM" src="https://user-images.githubusercontent.com/820419/61615778-4f6f5b00-ac80-11e9-8363-e6180de687dc.png">
