### ISSUE TITLE
ThreadPoolExecutor releases tasks prematurely when interrupted

### ISSUE THREAD

**Issue by danieldickison** [google/j2objc#622]
When `cancel(true)` is called on a Future that is currently being run by a ThreadPoolExecutor, the Callable object is released immediately which can lead to null pointer dereferencing if the body of the `call()` method accesses `this`.

While it's possible in some cases to catch an InterruptedException in the `call()` method, this isn't always possible (e.g. when doing networking with HttpURLConnection), and checking `Thread.interrupted()` is unreliable since the interrupt can happen between the check and subsequent code.

The bug is observed both with `-use-arc` and without. (Sorry about multiple edits here — initially I thought it only happened with -use-arc; it appears to happen less reliably without ARC, but it still does happen.)

Example:

```java
package com.bandcamp.shared;

import android.util.Log;

import java.util.LinkedList;
import java.util.List;
import java.util.concurrent.Callable;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;

public class ExecutorServiceTest {
    private static final int THREADS = 2;
    private static final int DELAY = 1000;
    private String x = "something";
    private List<Future<Object>> futures = new LinkedList<>();
    private ExecutorService execServ = Executors.newFixedThreadPool(THREADS);

    public void test() {
        Future<Object> f = execServ.submit(new Callable<Object>() {
            @Override
            public Object call() throws Exception {
                doSomething();
                try {
                    Thread.sleep(DELAY);
                }
                catch (InterruptedException e) {}
                Thread.sleep(DELAY);
                doSomething(); // Crashes here
                return null;
            }
        });
        try {
            Thread.sleep(DELAY / 2);
            f.cancel(true);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }

        //futures.add(f); // prevents crash
    }

    private void doSomething() {
        Log.i("ExecutorServiceTest", "doSomething: " + x);
    }
}
```

```swift
let executorServiceTest = BCExecutorServiceTest()
executorServiceTest.test()
```

**Comment by danieldickison** [comment]
One workaround is to enable `-use-arc` and then create a strong reference to `this` for the duration of `call()`:

```java
public Object call() throws Exception {
    Object strongThis = this;
    strongThis.hashCode(); // quick way to suppress unused var warnings in both java and objc.
    ...
```

**Comment by kstanger** [comment]
An alternative to `-use-arc` in your workaround is our `@RetainedLocalRef` annotation:
```
@RetainedLocalRef Object strongThis = this;
```
See http://j2objc.org/docs/RetainedLocalRef.html

**Comment by kstanger** [comment]
In either workaround we still have a race condition: if cancel() is called before the Callable's thread reaches the `strongThis` declaration.

**Comment by kstanger** [comment]
The race condition has been fixed for volatiles [here](https://github.com/google/j2objc/commit/113a0cf69d54eac4637fa7b1585221939a1eff97). And this specific issue has been updated by [making FutureTask.callable a volatile variable](https://github.com/google/j2objc/commit/03667bda2dce029bc22892c15b766a4a3be316f0).
