### ISSUE TITLE
An "_init..." issue

### ISSUE THREAD

**Issue by Lukasz2891** [google/j2objc#624]
```
j2objc-0.9.8.2
```

Let have:
```java
public class TestClass {
    public String initTest(){
        return "";
    }
    public String _initTest(){
        return "";
    } 
}
```
The Obj-C translated code is:
```Obj-C
...
#pragma mark Public
...
- (NSString *)_initTest;
- (NSString *)initTest OBJC_METHOD_FAMILY_NONE;
...
```
The first (and the first one only) method causes an compiler-error:
```
ARC error: init methods must return a type related to the receiver type
```

Is there any way to workaround that?

**Comment by tomball** [comment]
We weren't aware of the "drop leading underscores" part of determining [method families](http://clang.llvm.org/docs/AutomaticReferenceCounting.html#method-families), but it's easy to add.

Until this is fixed, you can build with the -Wno-mismatched-method-attributes flag to turn off this warning.

**Comment by tomball** [comment]
Fixed in latest source.
