### ISSUE TITLE
BigDecimal set scale in j2Objc not working

### ISSUE THREAD

**Issue by prasadavhad** [google/j2objc#625]
Hello,

I am trying to use setScale method on BigDecimal but in J2Objc it fails as BigDecimal is converted to an NSNumber and setScale method is not available in NSNumber.

Java code:
```
return String.format("%.6f",price.setScale(6,BigDecimal.ROUND_HALF_EVEN).floatValue()); 
```
where price is BigDecimal

Translated J2Objc code is::
```
return NSString_formatWithNSString_withNSObjectArray_(@"%.6f", [IOSObjectArray newArrayWithObjects:(id[]){ JavaLangFloat_valueOfWithFloat_([((JavaMathBigDecimal *) nil_chk([((JavaMathBigDecimal *) nil_chk(price)) setScaleWithInt:6 withInt:JavaMathBigDecimal_ROUND_HALF_EVEN])) floatValue]) } count:1 type:NSObject_class_()]);
```
This code fails on setScale method with unrecognized selector sent message- setScale method not available for NSNumber. Even if price is casted to JavaMathBigDecimal it is still treating it as NSNumber in Obj-C. Is there any other way to handle this? I can write an interface in Java and then implement that protocol but I would prefer to have just Java code here. Any help is greatly appreciated.

**Comment by tomball** [comment]
Can't reproduce, using your example:

**Comment by tomball** [comment]
Can't reproduce, using your example. If you are trying to call setScale on a BigDecimal from native code, remember that the method signature is actually setScaleWithInt:withInt:.

```java
import java.math.BigDecimal;

class SetScale {
  static String test(BigDecimal price) {
    return String.format("%.6f",price.setScale(6,BigDecimal.ROUND_HALF_EVEN).floatValue()); 
  }

  public static void main(String... args) {
    System.out.println("test: " + test(new BigDecimal(9.99)));
  }
}
```

```bash
$ javac SetScale.java
$ java SetScale
test: 9.990000
$ j2objc SetScale.java
$ j2objcc SetScale.m
$ ./a.out SetScale
test: 9.990000
```
