### ISSUE TITLE
Convert process stuck at the first stage

### ISSUE THREAD

**Issue by ganoa** [google/j2objc#628]
Hi,

Updating my convertor from version j2objc-0.9.4 which was working perfectly to the latest j2objc-0.9.8.2.1
cause the process to stuck when running the command j2objc with the same params which was working in version 0.9.4. no error message, no log just stuck :/

Any idea why?

Thanks in advanced

**Comment by kstanger** [comment]
Are there any log messages if you add -v to the command line? This should
enable verbose logging.

**Comment by ganoa** [comment]
nothing :\ i am running with verbose enable

**Comment by kstanger** [comment]
That's odd. What happens if you run the j2objc command with no arguments at
all? It should print out a help message.

**Comment by ganoa** [comment]
I discover some new info maybe it will help you understand, it seems that the problem related to the deep linking of the folders. when giving the full path to a file to convert its working but when giving path to a folder like b4 it stuck on the first file that he scan in that folder.
Any idea?

**Comment by kstanger** [comment]
Can you provide examples of your commands that are working and commands
that are not working?

**Comment by ganoa** [comment]
Found the problem! 
Using Process object in Java stuck when running shell script that is very long - some buffer issue i assume :/
Problem solved when i created the string command save into new file.sh and run this script using Process object and catching the output back.
(This Java project we convert is super big that's why probably no one faced this issue)

Thanks anyway :)

**Comment by tomball** [comment]
Congrats! Sounds like a tough nut to crack. :-)
