### ISSUE TITLE
static_framework.mk: No such file or directory

### ISSUE THREAD

**Issue by Esardes** [google/j2objc#631]
Hello
I just cloned the repo and tried to 'make dist' it but it failed with the following message 

"Makefile:1380: ../make/static_framework.mk: No such file or directory
make[1]: *** No rule to make target `../make/static_framework.mk'.  Stop.
make: *** [jre_emul_jar_dist] Error 2"

(I checked the make folder and couldn't find the static_framework.mk file.)

Thanks for your help

**Comment by tomball** [comment]
[Fixed in latest source.](https://github.com/google/j2objc/commit/38253ae6a2e62306b917c0c0a77561b6ac221445)
