### ISSUE TITLE
facing issue on building the j2objc-master - ../make/static_framework.mk: No such file or directory make[1]: *** No rule to make target `../make/static_framework.mk'.  Stop.

### ISSUE THREAD

**Issue by sajidsajj** [google/j2objc#632]
sam-MacBook-Pro:j2objc-master paddik$ make dist
Locale:
Darwin sam-MacBook-Pro.local 14.3.0 Darwin Kernel Version 14.3.0: Mon Mar 23 11:59:05 PDT 2015; root:xnu-2782.20.48~5/RELEASE_X86_64 x86_64
Xcode 6.3.2 Build version 6D2105
Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin14.3.0
Thread model: posix

Environment:
Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.GO2wOwXqxr/Render
HOME=/Users/paddik
JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home
LC_CTYPE=UTF-8
LOGNAME=paddik
MAKEFLAGS=
MAKELEVEL=1
MFLAGS=
PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/git/bin:/Users/paddik/.rvm/bin
PWD=/Users/paddik/Documents/testapp/j2objc-master
SECURITYSESSIONID=186a5
SHELL=/bin/bash
SHLVL=2
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.SQwU0k8LJ7/Listeners
TERM=xterm-256color
TERM_PROGRAM=Apple_Terminal
TERM_PROGRAM_VERSION=343.7
TERM_SESSION_ID=4D738882-64DD-46CD-92FE-C3D77EBC8BE6
TMPDIR=/var/folders/rt/kjz3y7rs13x4_lkdt3b8sphs3__7wg/T/
USER=paddik
XPC_FLAGS=0x0
XPC_SERVICE_NAME=0

Makefile:1380: ../make/static_framework.mk: No such file or directory
make[1]: *** No rule to make target `../make/static_framework.mk'.  Stop.
make: *** [jre_emul_jar_dist] Error 2
sam-MacBook-Pro:j2objc-master paddik$ java -version
java version "1.7.0_79"
Java(TM) SE Runtime Environment (build 1.7.0_79-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.79-b02, mixed mode)
sam-MacBook-Pro:j2objc-master paddik$

**Comment by sajidsajj** [comment]
while building j2objc-master facing the  above issue . please go through this. thanks in advance.

**Comment by kstanger** [comment]
[Fixed in latest source.](https://github.com/google/j2objc/commit/38253ae6a2e62306b917c0c0a77561b6ac221445)

**Comment by alizainprasla** [comment]
@kstanger there is no file in iterable file in **jre_emul/Classes/java/lang/Iterable.h**

**Comment by alizainprasla** [comment]
@kstanger i am getting this issue. 
**make[2]: *** No rule to make target `/Applications/Xcode.app/Contents/Developer/Plat', needed by `/Users/alizain/Downloads/j2objc-master/guava/build_result/objs-watchv7k/com/google/common/collect/UsingToStringOrdering.o'.  Stop.**
