### ISSUE TITLE
[Proposal] j2objc runtime as framework in cocoapod

### ISSUE THREAD

**Issue by ex3ndr** [google/j2objc#634]
I am working on simlifying distribution of app and libraries for people that doesn't want/need to work with j2objc directly.
One of the easiest way is supplying framework.

Now if you will add `pod 'J2ObjC-Framework'` - you will get installed j2objc runtime and you can easily cal any methods in j2objc runtime.

Only change is needed to j2objc header files.
Need to replace "im/actor/whatever.h" to <<FrameworkName>/im/actor/whatever.h> in generated sources and <j2objc/***.h> to j2objc runtime.

I have successfully done this with simple python script: https://github.com/actorapp/J2ObjC-Framework/blob/master/Scripts/convert.py. Script also builds umbrella header for include all headers. A bit different script is used for app's generated sources.

In the end i have cocoapod that downloads distribution, forms framework and include everything: https://github.com/actorapp/J2ObjC-Framework

It will be nice to make this standart for j2objc as it much more easier to maintain because people doesn't need to instal any dependencies at all.

Months ago i filled other issue about cocoapods and cocoapods wasn't enough mature for big frameworks, but now it can handle it correctly and download pod only once on machine.

**Comment by Toinouze** [comment]
Facing the same issue right now, +1

**Comment by advayDev1** [comment]
As someone who doesn't, and doesn't want to, use CocoaPods, please make any pod integration entirely optional.  Right now the j2objc is entirely agnostic to the build tools you use with it, and it would be nice for it to remain that way.

**Comment by ex3ndr** [comment]
Of course this must be optional, but when you writing really big app, you need to use cocoapods or Cartnage.

**Comment by Toinouze** [comment]
I completely agree with you @advayDev1, it should be 100% optional

**Comment by tomball** [comment]
FWIW, running "make frameworks" in j2objc's top directory now creates dist/frameworks for its libraries. You can drag them into an Xcode project (Swift or Objective C), but being static library frameworks (which Xcode only partially supports), the Header Search Paths build setting needs to be updated with entries like "$(PROJECT_DIR)/NAME.framework/Headers". These are raw, so there are likely to be issues using them.

This may or may not help with this cocoapods issue, but I noticed that #include directives in generated headers didn't have to be modified, just how they are included in the framework header.

**Comment by ex3ndr** [comment]
After XCode 7.1 you need to replace headers with `@import`s

**Comment by ex3ndr** [comment]
I have checked `make frameworks` and there is one problem.
Frameworks in iOS are dynamically linked libraries, but your approach is same statically linked so files.

Unfortunately because of this compiler became crazy and link dynamic framework as static library without any warrings. Applications works well until you try to make frameworks that depends on j2objc framework. From this point BOTH app and target framework got symbols from j2objc and it, of course, crash.

**Comment by Lukasz2891** [comment]
Is there any progress with this issue according to j2objc 1.0 on CocoaPods?

**Comment by Palleas** [comment]
I don't want to be the "Up ?" guy but is there any news with this?

**Comment by tomball** [comment]
The j2objc team itself doesn't support CocoaPods, and never did. Instead,
independent community developers have stepped in, just like they did with
other build systems including Gradle
<http://j2objc.org/docs/Using-J2ObjC-with-Gradle.html> and Maven
<http://j2objc.org/docs/Using-J2ObjC-with-Maven.html>.

The J2ObjC CocoaPod page <https://cocoapods.org/pods/J2ObjC> lists Larry Tin
<https://cocoapods.org/owners/1488> as the maintainer, so either work with
him on an update, or fork his work and submit a new version. If someone
lets us know when the pod is updated, I'll add a short doc on the j2objc.org
site similar to Gradle's and Maven's pages.
