### ISSUE TITLE
java.lang.reflect.Field.getType() throws ClassNotFoundException when using package prefix file

### ISSUE THREAD

**Issue by NCrouther** [google/j2objc#637]
Getting Class<?> objects via instance.getClass() or Class.forName() works properly once we added the prefixes file to the resource bundle on the IOS side, however, many of the methods in java.lang.reflect.Field appear to not be using the prefix file and thus cause an exception.

**Comment by kstanger** [comment]
Please be more specific. Which method in java.lang.reflect.Field are
broken? Adding some sample code to this issue would be helpful as well.

**Comment by NCrouther** [comment]
The most straightforward way to reproduce is to call java.lang.reflect.Field.getType() on a Field of a type that is renamed by a prefixes file.  I'll try to put together a simplified example.

**Comment by NCrouther** [comment]
Digging into it more, I think I had bad information before.  It looks like instance.getClass() works, but Calss.forName() also throws the exception.  Since instance.getClass() is called from the class itself, no string lookup is necessary, so it wouldn't need the prefix file.  I am suspicious that the prefix file is not being included correctly, since I was mistaken about the observation that lead me to believe that it was having an effect.
