### ISSUE TITLE
Access public Class properties

### ISSUE THREAD

**Issue by confile** [google/j2objc#640]
I have the following class: 

```
public class Form {
  public String test1;
  public int test2;
} 
```

How do I set and get values from public class members?

**Comment by kstanger** [comment]
NSString *str = form->test1_;
ThePkgForm_set_test1_(form, newStr);
jint i = form->test2_;
form->test2_ = 1234;

We're working on formalizing and documenting this before releasing a 1.0
version.

**Comment by tomball** [comment]
If you want Objective C-like properties (which should be Swift friendly), you can use the [@Property annotation](http://j2objc.org/docs/Property.html). This cause `@property` declarations to be made in the header, and `@synthesize` declarations in the .m file.

**Comment by confile** [comment]
thanks
