### ISSUE TITLE
Translator doesn't generate method generic signatures

### ISSUE THREAD

**Issue by tomball** [google/j2objc#641]
After translating:

```java
import java.lang.reflect.*;
import java.util.*;

class GenericTest <T> {
  void test(Map<Long, List<T>> map) {}

  public static void main(String... args) throws Exception {
    for (Method m : GenericTest.class.getDeclaredMethods()) {
      if (m.getName().equals("test")) {
        Type[] paramTypes = m.getGenericParameterTypes();
        ParameterizedType type = (ParameterizedType) paramTypes[0];
        System.out.println("actual type arguments: "
            + Arrays.toString(type.getActualTypeArguments()));
      }
    }
  }
}
```
The metadata for the test method shows a NULL generic signature, and running the above fails with a cast exception because the returned paramType is not a ParameterizedType. This test runs identically to Java once the method's generic signature is added to its metadata:
```
{ "testWithJavaUtilMap:", "test", "V", 0x0, NULL,
  "(Ljava/util/Map<Ljava/lang/Long;Ljava/util/List<TT;>;>;)V" },
```

**Comment by tomball** [comment]
Fixed test for generating generic method signatures to include argument types with type parameters.

**Comment by kstanger** [comment]
[Fixed in latest source.](https://github.com/google/j2objc/commit/4a318b33fb09d0fe706f53dbadbcc1e0d84ef76f)
