### ISSUE TITLE
Native methods with -use-arc produces code that doesn't compile

### ISSUE THREAD

**Issue by gcjg** [google/j2objc#646]
I've previously been happily using version 0.9.6.1 and I just updated to 0.9.8.2.1. Now wherever I have a native method like:

public native void Method(SomeType var);

I get generated code of the form:

JNIEXPORT void Java_package_method(JNIEnv *_env_, jobject self, jobject var);

void Package_MethodWithSomeType_(Class *self, SomeType *var) {

  Java_package_method(&J2ObjC_JNIEnv, self, var);

}

Which leads to a build error like:

file.java:38: Implicit conversion of Objective-C pointer type 'SomeType *' to C pointer type 'jobject' (aka 'void *') requires a bridged cast

**Comment by kstanger** [comment]
[Fixed in latest source.](https://github.com/google/j2objc/commit/cfd443c0ca83cf60f4db001d7b4a26021a95255a)
