### ISSUE TITLE
Translate time-related Java types into Objective C equivalents

### ISSUE THREAD

**Issue by NCrouther** [google/j2objc#647]
A nice enhancement would be to translate some of the time-related types from the Java types into the equivalents on objective C to provide a cleaner interface in the translated code.

JavaUtilDate -> NSDate
JavaUtilTimeZone -> NSTimeZone
JavaLangCalendar -> NSDateComponents

**Comment by tomball** [comment]
Although both the Foundation date/time/calendar classes and Java's base their support on ICU, the type hierarchies and localization support vary significantly enough to prevent this optimization. Before j2objc was open-sourced, we used these Foundation classes as you describe, but found that Java libraries depended too much on JRE behavior for this to work. You are right that conceptually these classes are similar, but they just didn't map well.
