### ISSUE TITLE
 Cast Exception for unboxing operation.

### ISSUE THREAD

**Issue by lordofdest** [google/j2objc#648]
Java code:
Integer tmp_int = new Integer(100);
long tmp_long = (long)tmp_int;

after translation to ObjC code:
JavaLangInteger *tmp_int = [new_JavaLangInteger_initWithInt_(100) autorelease];
jlong tmp_long = [(JavaLangLong *) check_class_cast(tmp_int, [JavaLangLong class]) longLongValue];

Actual result:
Can't be cast JavaLangInteger to JavaLangLong.

**Comment by tomball** [comment]
Thanks for the test (I wish they were all that clear). A temporary workaround (which you've probably already figured out) is to use `tmp_int.longValue()` instead of casting it to long.

**Comment by kstanger** [comment]
[Fixed in latest source.](https://github.com/google/j2objc/commit/1bf06af55096e5697aa0754ebca7ed7c93bbe046)
