### ISSUE TITLE
Distribute j2objc libraries with Bitcode enabled (only jre libs were built with Bitcode)

### ISSUE THREAD

**Issue by brunobowden** [google/j2objc#651]
It appears that Bitcode support in the j2objc libraries is limited to jre_emul and jre_emul_core and not supported in other libraries. Running the standard Bitcode marker test:

$ otool -l libjre_emul.a | grep __LLVM | head -1
   segname __LLVM
$ otool -l libjre_emul_core.a | grep __LLVM | head -1
   segname __LLVM

All the other libraries come up negative. This request is to add support to all those libraries to enable support of watchOS apps. I don't believe it's needed for junit or mockito but is necessary for the others.

**Comment by tomball** [comment]
All libraries are built with the -fembed-bitcode-marker flag. To verify this, be sure and specify otool's -arch flag (only the armv7 and arm64 should set this flag):

$ otool -l libguava.a -arch armv7 | grep __LLVM | head -1
segname __LLVM
$ otool -l libguava.a -arch arm64 | grep __LLVM | head -1
segname __LLVM

I don't know why otool will find the segment in some fat libraries, like libjre_emul.a, but not others.

**Comment by gianlucabertani** [comment]
Actually if you try to Build & Archive an app that uses `jre_emul.a`, you get an error saying the library was built without full bitcode:

```
ld: bitcode bundle could not be generated because '[...]/lib/libjre_emul.a(IosHttpHandler.o)'
was built without full bitcode. All object files and libraries for bitcode must be generated
from Xcode Archive or Install build for architecture armv7
```

Redistributable binaries should be built with ***-fembed-bitcode***, not *-fembed-bitcode-marker* flag. The difference between these two flags is explained well here:

* [How do I xcodebuild a static library with Bitcode enabled?](http://stackoverflow.com/questions/31486232/how-do-i-xcodebuild-a-static-library-with-bitcode-enabled)

**Comment by tomball** [comment]
Has anyone successfully rebuilt j2objc with -fembed-bitcode? Only the [jre_emul/environment.mk](https://github.com/google/j2objc/blob/master/jre_emul/environment.mk#L173) and [make/fat_lib_macros.mk](https://github.com/google/j2objc/blob/master/make/fat_lib_macros.mk#L41) need to be updated.

**Comment by gianlucabertani** [comment]
Successfully rebuild just now, my environment is:
```
Xcode 7.1.1 Build version 7B1005
Apple LLVM version 7.0.0 (clang-700.1.76)
```

The resulting `libjre_emul.a` contains full bitcode segments (and in fact it is > 250 MB, way greater than the ~120 MB of currently released version) and links correctly against a test app.

**Comment by lukhnos** [comment]
I have also successfully built, archived, and validated an app of mine with the latest `libjre_emul.a` (current master at 0eb168059abccd74cb2026d88ab1d114711b017c).

**Comment by yurevich1** [comment]
lukhnos, do you mean what the file at path `j2objc-1.1/lib/libjre_emul.a` works for watchOS?   I'm getting this warning:

https://github.com/google/j2objc/issues/780
