### ISSUE TITLE
SimpleDateFormat - Unparseable date when parsing time

### ISSUE THREAD

**Issue by Lukasz2891** [google/j2objc#661]
So, let have the following code:
```java
DateFormat sdf = new SimpleDateFormat("HH:mm:ss");
```
Now we are using this formatter 

```java
String timeString = "00:00:23";
sdf.setTimeZone(TimeZone.getTimeZone("UTC"));
Date d = sdf.parse(timeString);
```
In the Objective-C translated code an "Unparseable date" exception is thrown, at char number 0.
Probably a date without the time part is parsed properly, only the time part is not.

Any ideas?

**Comment by tomball** [comment]
The problem turned out to be in NativeDecimalFormat parsing, which returned an incorrect parse position when zeroes were followed by a non-numeric character, such as the third character of your "00:00:23" time string. Fix is pending review.

**Comment by tomball** [comment]
Fixed in [current source](https://github.com/google/j2objc/commit/0eb168059abccd74cb2026d88ab1d114711b017c).
