### ISSUE TITLE
Can't build archive: "...was built without full bitcode"

### ISSUE THREAD

**Issue by eddieSullivan** [google/j2objc#664]
This looks similar to but different from #615:

Here's the full error I get:

Ld /Users/eddiesullivan/Library/Developer/Xcode/DerivedData/ChorderatorIos-cljddthufcwsahdpbgbuvehwwaft/Build/Intermediates/ArchiveIntermediates/ChorderatorIos/IntermediateBuildFilesPath/ChorderatorIos.build/Release-iphoneos/ChorderatorTarget.build/Objects-normal/armv7/ChorderatorTarget normal armv7
    cd /Users/eddiesullivan/src/ChorderatorIos
    export IPHONEOS_DEPLOYMENT_TARGET=9.0
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch armv7 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.1.sdk -L/Users/eddiesullivan/Library/Developer/Xcode/DerivedData/ChorderatorIos-cljddthufcwsahdpbgbuvehwwaft/Build/Intermediates/ArchiveIntermediates/ChorderatorIos/BuildProductsPath/Release-iphoneos -L/Users/eddiesullivan/opt/j2objc-0.9.8.2.1/lib -F/Users/eddiesullivan/Library/Developer/Xcode/DerivedData/ChorderatorIos-cljddthufcwsahdpbgbuvehwwaft/Build/Intermediates/ArchiveIntermediates/ChorderatorIos/BuildProductsPath/Release-iphoneos -filelist /Users/eddiesullivan/Library/Developer/Xcode/DerivedData/ChorderatorIos-cljddthufcwsahdpbgbuvehwwaft/Build/Intermediates/ArchiveIntermediates/ChorderatorIos/IntermediateBuildFilesPath/ChorderatorIos.build/Release-iphoneos/ChorderatorTarget.build/Objects-normal/armv7/ChorderatorTarget.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -miphoneos-version-min=9.0 -dead_strip -fembed-bitcode -Xlinker -bitcode_verify -Xlinker -bitcode_hide_symbols -Xlinker -bitcode_symbol_map -Xlinker /Users/eddiesullivan/Library/Developer/Xcode/DerivedData/ChorderatorIos-cljddthufcwsahdpbgbuvehwwaft/Build/Intermediates/ArchiveIntermediates/ChorderatorIos/BuildProductsPath/Release-iphoneos -ljre_emul -fobjc-arc -fobjc-link-runtime -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphoneos -Xlinker -add_ast_path -Xlinker /Users/eddiesullivan/Library/Developer/Xcode/DerivedData/ChorderatorIos-cljddthufcwsahdpbgbuvehwwaft/Build/Intermediates/ArchiveIntermediates/ChorderatorIos/IntermediateBuildFilesPath/ChorderatorIos.build/Release-iphoneos/ChorderatorTarget.build/Objects-normal/armv7/ChorderatorTarget.swiftmodule -framework CoreAudio -framework AudioToolbox -licucore -Xlinker -dependency_info -Xlinker /Users/eddiesullivan/Library/Developer/Xcode/DerivedData/ChorderatorIos-cljddthufcwsahdpbgbuvehwwaft/Build/Intermediates/ArchiveIntermediates/ChorderatorIos/IntermediateBuildFilesPath/ChorderatorIos.build/Release-iphoneos/ChorderatorTarget.build/Objects-normal/armv7/ChorderatorTarget_dependency_info.dat -o /Users/eddiesullivan/Library/Developer/Xcode/DerivedData/ChorderatorIos-cljddthufcwsahdpbgbuvehwwaft/Build/Intermediates/ArchiveIntermediates/ChorderatorIos/IntermediateBuildFilesPath/ChorderatorIos.build/Release-iphoneos/ChorderatorTarget.build/Objects-normal/armv7/ChorderatorTarget

ld: bitcode bundle could not be generated because '/Users/eddiesullivan/opt/j2objc-0.9.8.2.1/lib/libjre_emul.a(IOSArray.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by tomball** [comment]
iOS 9.0 requires that you [build j2objc](http://j2objc.org/docs/Building-J2ObjC.html) from the latest source, as 0.9.8.2.1 (or earlier) releases don't include bitcode.
