### ISSUE TITLE
Building all all_frameworks fails when compiling protobuf

### ISSUE THREAD

**Issue by JamesMcIntosh** [google/j2objc#665]
When trying to build the project using the following command compilation fails.
```
make dist all_frameworks
```
The error message
```
Xcode 7.1.1 Build version 7B1005
Apple LLVM version 7.0.0 (clang-700.1.76)
Target: x86_64-apple-darwin15.0.0
...
c++ -MD -c -o /Users/james/repos/3rd-party/j2objc/protobuf/compiler/build_result/google/protobuf/compiler/j2objc/j2objc_enum.o -x c++ -stdlib=libc++ -Isrc -I../google/src src/google/protobuf/compiler/j2objc/j2objc_enum.cc
In file included from src/google/protobuf/compiler/j2objc/j2objc_enum.cc:35:
src/google/protobuf/compiler/j2objc/j2objc_enum.h:41:10: fatal error: 'google/protobuf/stubs/common.h' file not found
#include <google/protobuf/stubs/common.h>
```
I checked that the file common.h does exist ./protobuf/runtime/src/com/google/protobuf/common.h

I see that there was some discussion by Keith about breaking apart the frameworks and all_frameworks targets because 'it wont work'. I could find no information as to why it wont work or how to get it to work.
https://groups.google.com/forum/embed/#!topic/j2objc-discuss/6u7MjcL0n8o

**Comment by kstanger** [comment]
Do you have protocol buffers installed as per [their README](https://github.com/google/protobuf/blob/master/README.md)? With a default installation the headers will be installed to /usr/local/include and the libraries to /usr/loacl/lib.

**Comment by Buggaboo** [comment]
Use [homebrew](http://brew.sh/) to install the protobuf, that contains everything you need to make a succesful build on j2objc.

```bash
brew install protobuf
```

**Comment by kstanger** [comment]
If you don't need the protobuf compiler or runtime, then just run "make
dist frameworks".

If you do need protocol buffers, then I recommend installing version 2.6.1
<https://github.com/google/protobuf/releases/tag/v2.6.1> using these
instructions <https://github.com/google/protobuf/blob/master/src/README.md>
which will install it in /usr/local. This is where j2objc will expect to
find the libraries and public headers to build against. You will also need
to define an environment variable "PROTOBUF_ROOT_DIR" and set it to the
location where the protobuf distribution was extracted. This is where
j2objc will find the .java and .proto sources it needs to build the runtime
library.
