### ISSUE TITLE
Unsupported major.minor version 51.0

### ISSUE THREAD

**Issue by JanX2** [google/j2objc#668]
Seems like this issue has resurfaced:
https://groups.google.com/forum/#!topic/j2objc-discuss/6ceJr8-y0WU

This is when trying to build
https://github.com/tomball/j2objc-sample-reversi
using
Xcode 7.1.1
with
https://github.com/google/j2objc/releases/tag/0.9.8.2.1
in the correct path.

**Comment by tomball** [comment]
As described in the http://j2objc.org Requirements section, Java 7 is now the minimum version of Java we work with.

**Comment by JanX2** [comment]
I have installed Oracle JRE 8, but can’t find a way to get j2objc use it instead of the Apple Java. Any pointers?

**Comment by tomball** [comment]
It's nothing specific to j2objc: every Java developer on a Mac needs to now
set their environment using /usr/libexec/java_home in their ~/.bash_profile
(and log out and back in). The good news is that switching between Java
versions is now much easier:

http://stackoverflow.com/questions/6588390/where-is-java-home-on-osx-yosemite-10-10-mavericks-10-9-mountain-lion-10

**Comment by tomball** [comment]
I'm sorry for the recent build failures. We're cleaning things up for a 1.0 release, and some of those changes were unfortunately disruptive.
