### ISSUE TITLE
Nonnull annotation not added for return types

### ISSUE THREAD

**Issue by egu002** [google/j2objc#671]
Using the --swift-friendly flag, 

@Nonnull
public static String bag(@Nonnull final Double tag)

is translated to

+ (NSString *)bagWithJavaLangDouble:(JavaLangDouble * __nonnull)tag;

whereas it should be

+ (NSString * __nonnull)bagWithJavaLangDouble:(JavaLangDouble * __nonnull)tag;

**Comment by tomball** [comment]
The fix proved to be easy, if you want to try it before it's reviewed and promoted. At [TypeGenerator.java:307](https://github.com/google/j2objc/blob/master/translator/src/main/java/com/google/devtools/j2objc/gen/TypeGenerator.java#L307) add:

      if (BindingUtil.hasAnnotation(binding, Nonnull.class)) {
        return " __nonnull";
      }

**Comment by tomball** [comment]
Fixed in current source.
