### ISSUE TITLE
java.lang.reflect.Method should wrap -invokeWithId:withNSObjectArray: with @try and wrap with JavaLangException

### ISSUE THREAD

**Issue by eddydas** [google/j2objc#677]
In Java if I write
```
try {
  // method is a java.lang.reflect.Method
  // object, however, has not defined the selector targeted by "method".
  // So this will throw unrecognised selector exception.
  method.invoke(object, args);
} catch (Throwable e) {
  // Hope to catch unrecognised selector here
}
```
I will never be able to catch that, because in Method.m, -invokeWithId:withNSObjectArray:
you wrapped some of your own custom-thrown exception with Java counterpart (e.g. JavaLangNullPointerException), but the actual NSInvocation is not wrapped.
So when the target object has no such selector, it will throw an NSException, and it will throw straight out, and NSException by itself is not a JavaLangThrowable, so it won't be caught by the translated catch path.

**Comment by tomball** [comment]
How are you able to get a no such selector exception? Method instances can only be created by calling one of the Class.getMethod methods, which should throw a NoSuchMethodException if the method doesn't exist. 

Please provide a test example that demonstrates this issue. We can verify catching the NSException then, which should most likely be rethrown as a NoSuchMethodError.

**Comment by eddydas** [comment]
```
public class classA {
    public void methodA() { }
    public void methodB() { }
}
public class classB { 
    public void methodA() { }
}
```
Class B is intentionally not a subclass of ClassA, but it does implement the some methods as ClassA. Class B is potentially implemented only in Objective C.

```
Class<?>[] interfaces = (new classA()).getClass().getInterfaces();
Method[] methods = interfaces[0].getMethods();
try {
    methods[1].invoke(new classB(), args); // assuming methods[1] is methodB
} catch (Throwable e) {
    // Can never catch it here
}
```
