### ISSUE TITLE
ClassLoader.findResources should also search for resource in [NSBundle allFrameworks]

### ISSUE THREAD

**Issue by lukhnos** [google/j2objc#678]
Currently `ClassLoader.findResources` searches for resources in all non-framework bundles ([code](https://github.com/google/j2objc/blob/4db820aa197f07cba175d31cecf4bb5daf5544d8/jre_emul/android/libcore/luni/src/main/java/java/lang/ClassLoader.java#L714)):

```objc
for (NSBundle *bundle in [NSBundle allBundles]) {
  NSURL *nativeURL = [bundle URLForResource:name withExtension:nil];
  if (nativeURL) {
    [urls addWithId:JavaNetNetFactory_newURLWithNSString_([nativeURL description])];
  }
}    
```

I suggest we also search in `[NSBundle allFrameworks]`. This will enable J2ObjC-translated libraries with resources – for example, libraries that use `ServiceLoader` to implement SPI (service provider interface) – to be built as dynamic frameworks.

**Comment by tomball** [comment]
Thanks!
