### ISSUE TITLE
"String += int" doesn't convert the int correctly

### ISSUE THREAD

**Issue by Sundin-13** [google/j2objc#681]
In the Java source, I used "string += i" where i = 1 produced the string "01" and i = 2 produced "11".

j2objc v0.9.8.2.1, Xcode v7.2

**Comment by tomball** [comment]
What you described isn't valid Java syntax. Please modify the following test, run it with javac and j2objc to report a difference, and if there's a difference between the two outputs, reopen this issue and attach the test that fails.

This is what I *think* you meant, which works the same on both platforms:

StrCat.java:
```
class StrCat {
  public static void main(String... args) {
    String s = "";
    s += 1;
    System.out.println(s);
    s = "";
    s += 2;
    System.out.println(s);
  }
}
```
```
$ javac StrCat.java
$ java StrCat 
1
2
$ j2objc StrCat.java 
translating StrCat.java
Translated 1 file: 0 errors, 0 warnings
$ j2objcc StrCat.m
$ ./a.out StrCat
1
2
```

**Comment by Sundin-13** [comment]
Actually, I simplified my example too much. What I had in my code was "string += i + 1" which on Android appends the result of "i + 1" to the string but j2objc appends i then 1. (Hence i=0 => "01" and i=1 => "11")

What do you mean, not valid Java? I've used this in my Android code for years. (And it's accepted by j2objc but produces a different result)

**Comment by tomball** [comment]
I hate guessing games: J2ObjC is a compiler, and the best tests/bug-reports for compilers are simple classes with a main() that executes some code and reports a result, such as the StrCat.java class I included. Your comment was still vague (example code would have required less typing), but I was able to reproduce your problem with the following:

```
class StrCat {
  public static void main(String... args) {
    String s = "";
    int i = 0;
    s += i + 1;
    System.out.println(s);
    s = "";
    i = 1;
    s += i + 1;
    System.out.println(s);
  }
}
```

**Comment by tomball** [comment]
Fixed in [current source](https://github.com/google/j2objc/commit/4cd19de53557a8de404da86913db34ef7846550f).
