### ISSUE TITLE
Nullability annotations warning suppression missing for inner interfaces and enums

### ISSUE THREAD

**Issue by egu002** [google/j2objc#683]
j2objc built at commit 82001ee
Regular inner classes are fine now, but inner interfaces and enums still warn about missing nullability annotations
e.g
public class Foo {
    public enum Bar {
        HEADS,
        TAILS
    }

**Comment by egu002** [comment]
Still a problem in 1.0, can workaround by copying the #pragma GCC diagnostic ignored "-Wnullability-completeness" blocks (and related closing block)

**Comment by chezzdev** [comment]
I faced the same problem. Compiler flags doesn't surround translated versions of the inner interfaces and this omission produces thousands of errors.

Please consider this problem. It makes the usage of nullability conversion very inconvenient.

**Comment by tomball** [comment]
Do you have a more complete example of this problem? I built the Foo class above, but no nullability pragmas were generated since there aren't any nullability annotations. I suspect clang checks on a per-module level instead of per-class, but can't verify that.

**Comment by egu002** [comment]
Hmm, perhaps this -
MyAverager.java
import javax.annotation.Nullable;

public interface MyAverager {
    @Nullable
    Average getAverage();
    interface Average {
        double getValue();
    }
}

translated with j2objc --swift-friendly -classpath ./lib/jsr305-3.0.0.jar MyAverager.java

I'm encountering this problem when I translate our sources and build them into a framework, exposing the headers, so I'm trying to reproduce it in a simpler fashion here. Please let me know if that doesn't work. 

I also encounter the problem with all enum classes as of j2objc 1.2 and swift 3 now, so a simple enum class might suffice for reproducing the issue

**Comment by egu002** [comment]
Update:
This class

import javax.annotation.Nullable;

public class MyAverager {
    
}

```
interface MyAveragerHelper {
    @Nullable
    Average getAverage();
    interface Average {
        double getValue();
    }
}
```

translates to 
```

//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: MyAverager.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_MyAverager")
#ifdef RESTRICT_MyAverager
#define INCLUDE_ALL_MyAverager 0
#else
#define INCLUDE_ALL_MyAverager 1
#endif
#undef RESTRICT_MyAverager

#if !defined (MyAverager_) && (INCLUDE_ALL_MyAverager || defined(INCLUDE_MyAverager))
#define MyAverager_

@interface MyAverager : NSObject

#pragma mark Public

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(MyAverager)

FOUNDATION_EXPORT void MyAverager_init(MyAverager *self);

FOUNDATION_EXPORT MyAverager *new_MyAverager_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT MyAverager *create_MyAverager_init();

J2OBJC_TYPE_LITERAL_HEADER(MyAverager)

#endif

#if !defined (MyAveragerHelper_) && (INCLUDE_ALL_MyAverager || defined(INCLUDE_MyAveragerHelper))
#define MyAveragerHelper_

@protocol MyAveragerHelper_Average;

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

@protocol MyAveragerHelper < JavaObject >

- (id<MyAveragerHelper_Average> __nullable)getAverage;

@end

J2OBJC_EMPTY_STATIC_INIT(MyAveragerHelper)

J2OBJC_TYPE_LITERAL_HEADER(MyAveragerHelper)

#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#endif

#if !defined (MyAveragerHelper_Average_) && (INCLUDE_ALL_MyAverager || defined(INCLUDE_MyAveragerHelper_Average))
#define MyAveragerHelper_Average_

@protocol MyAveragerHelper_Average < JavaObject >

- (jdouble)getValue;

@end

J2OBJC_EMPTY_STATIC_INIT(MyAveragerHelper_Average)

J2OBJC_TYPE_LITERAL_HEADER(MyAveragerHelper_Average)

#endif

#pragma pop_macro("INCLUDE_ALL_MyAverager")

```

but it should be 
```

//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: MyAverager.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_MyAverager")
#ifdef RESTRICT_MyAverager
#define INCLUDE_ALL_MyAverager 0
#else
#define INCLUDE_ALL_MyAverager 1
#endif
#undef RESTRICT_MyAverager

#if !defined (MyAverager_) && (INCLUDE_ALL_MyAverager || defined(INCLUDE_MyAverager))
#define MyAverager_

@interface MyAverager : NSObject

#pragma mark Public

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(MyAverager)

FOUNDATION_EXPORT void MyAverager_init(MyAverager *self);

FOUNDATION_EXPORT MyAverager *new_MyAverager_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT MyAverager *create_MyAverager_init();

J2OBJC_TYPE_LITERAL_HEADER(MyAverager)

#endif

#if !defined (MyAveragerHelper_) && (INCLUDE_ALL_MyAverager || defined(INCLUDE_MyAveragerHelper))
#define MyAveragerHelper_

@protocol MyAveragerHelper_Average;

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

@protocol MyAveragerHelper < JavaObject >

- (id<MyAveragerHelper_Average> __nullable)getAverage;

@end

J2OBJC_EMPTY_STATIC_INIT(MyAveragerHelper)

J2OBJC_TYPE_LITERAL_HEADER(MyAveragerHelper)

#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#endif

#if !defined (MyAveragerHelper_Average_) && (INCLUDE_ALL_MyAverager || defined(INCLUDE_MyAveragerHelper_Average))
#define MyAveragerHelper_Average_

@protocol MyAveragerHelper_Average < JavaObject >

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

- (jdouble)getValue;

@end

J2OBJC_EMPTY_STATIC_INIT(MyAveragerHelper_Average)

J2OBJC_TYPE_LITERAL_HEADER(MyAveragerHelper_Average)

#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#endif

#pragma pop_macro("INCLUDE_ALL_MyAverager")

```

**Comment by tomball** [comment]
Clang turns on its completeness detector when it finds a nullability annotation anywhere in a header, whereas j2objc was generating pragmas per-type. Fix to make suppression for the whole header if any type has nullability annotations is in review.

**Comment by tomball** [comment]
Fixed in current source. Please reopen with an example if there's still a problem.

**Comment by egu002** [comment]
This (the previous example), now works
```
import javax.annotation.Nullable;
import javax.annotation.Nonnull;

interface MyAveragerHelper {
    @Nullable
    Average getAverage();
    interface Average {
        double getValue();
    }
}
```
However, this
```
import javax.annotation.Nullable;
import javax.annotation.Nonnull;

interface MyAveragerHelper {
    @Nonnull
    Average getAverage();
    interface Average {
        double getValue();
    }
}
```
doesn't. It seems like having Nonnull causes the pragma to not be generated?

**Comment by akramhussein** [comment]
Hi @tomball -

Is there a target release date/schedule that will include these fixes? Currently using 1.2.zip, so seeing if we should hold off changing compilation of our project to use source if it isn't too far.

Thanks

**Comment by tomball** [comment]
We are in the final stages of switching j2objc's front-end from the Eclipse compiler to javac, and it doesn't make sense to make an official release until this major change is fully tested first. We also haven't fixed the test case @egu002 reported, which is why this issue was reopened.

That said, anyone at any time can [build a personal release](http://j2objc.org/docs/Building-J2ObjC.html). Well, sometimes the build is broken, but we have [a Travis-CI build](https://travis-ci.org/google/j2objc) that shows when the build is successful, and if broken, what the last commit was that successfully built. None of Google's app teams wait for (or even care about) a release number; instead those projects build j2objc as part of their app build. That's why we are comfortable suggesting developers build their own when they need specific fixes.

**Comment by akramhussein** [comment]
Thank you for the clarification - makes a lot of sense.

**Comment by tomball** [comment]
Verified fixed in current release.
