### ISSUE TITLE
j2objc-0.9.8.2.1 build not sucessful, but j2objc-0.9.8.1 is ok to build ?

### ISSUE THREAD

**Issue by eric8words** [google/j2objc#684]
ld: in /XXXXXXXXX/j2objc-0.9.8.2.1/lib/libjre_emul.a(IOSArray.o), building for OSX, but linking in object file built for iOS, for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by tomball** [comment]
The reason for the newer release was due to Xcode 7 requiring separate x86_64 builds for OSX and the 64-bit iPhone simulator, so going to an old build with Xcode 7 won't work on the simulator. 0.9.8.1 should work on iOS devices and 32-bit simulators like the iPhone 4s, though.

**Comment by eric8words** [comment]
Thanks !
