### ISSUE TITLE
j2objc maven plugin

### ISSUE THREAD

**Issue by vicmosin** [google/j2objc#686]
Didn't know where to write...
In our project we use maven so in order to make it easier (and since the plexus-compiler-j2objc has some issues with j2objc's advanced options) I implemented custom j2objc maven plugin. Main advantage  of this plugin is that it converts not only current project's source files but its dependencies as well, similar to Gradle Plugin for J2ObjC.

https://github.com/smoope/j2objc-maven-plugin

**Comment by tomball** [comment]
Thanks for your contribution! I added a [Maven Plugin for J2ObjC](http://0.0.0.0:4000/docs/Using-J2ObjC-with-Maven.html) doc page with links to your project. If you want to improve this page, clone the j2objc project, switch to its gh-pages branch, edit the file and submit a pull request.
