### ISSUE TITLE
"Projects that use J2ObjC" Google Calendar link broken

### ISSUE THREAD

**Issue by tyiu** [google/j2objc#690]
I was looking through the project website and noticed that the link to Google Calendar is broken on the "Projects that use J2ObjC" page:
http://j2objc.org/docs/Projects-that-use-J2ObjC.html

It points to:
https://itunes.apple.com/app/idid909319292

But should be:
https://itunes.apple.com/app/id909319292

It doesn't appear like the web page source is hosted in this repository, so I'm creating an issue instead of a pull request.

**Comment by tomball** [comment]
Thanks, I can fix this directly. In the future, the j2objc.org site pages
are all on the gh-pages branch of our GitHub repository (we use GitHub
Pages).

**Comment by tyiu** [comment]
Good to know. Thanks!

**Comment by tomball** [comment]
Fixed, site should update in a few minutes. Thanks for reporting this.
