### ISSUE TITLE
Improve guide; add Apache Maven is required

### ISSUE THREAD

**Issue by marchv** [google/j2objc#691]
Hello there,

I have just followed the instructions at http://j2objc.org/docs/Adding-the-JreEmulation-project-to-your-Xcode-project.html. But I got this error:

    mvn -q generate-resources dependency:sources
    make[1]: mvn: No such file or directory

Could you please add to the guide that Apache Maven is required.

Thanks a lot in advance :)

**Comment by tomball** [comment]
Thanks for the suggestion, I'll update it later today. In the meantime,
here are some useful StackOverflow installation tips:

http://stackoverflow.com/questions/8826881/maven-install-on-mac-os-x

**Comment by tomball** [comment]
Fixed: https://github.com/google/j2objc/commit/4a8c368b75e7163f3ea5284ba8c110c68a16a91b (it may take a few minutes for our site to see this change.)

**Comment by marchv** [comment]
Excellent @tomball ! Thanks! :D
