### ISSUE TITLE
v1.0.0 enum linking issue

### ISSUE THREAD

**Issue by pellet** [google/j2objc#697]
When building against v1.0.0 I had a linking issue relating to using the standard log level imported using:
`import java.util.logging.*;`
I had a call which referenced log levels like `Level.SEVERE`
for e.g:
`logger.log(Level.SEVERE, content.toString());`

`Undefined symbols for architecture i386:
  "_JavaUtilLoggingLevel_FINE", referenced from:
      -[JOLSharedLogger debugWithNSString:withNSString:] in libOtherLevels.a(SharedLogger.o)
     (maybe you meant: _JavaUtilLoggingLevel_FINE_, _JavaUtilLoggingLevel_FINER_ , _JavaUtilLoggingLevel_FINEST_ )
  "_JavaUtilLoggingLevel_FINER", referenced from:
      -[JOLSharedLogger verboseWithNSString:withNSString:] in libOtherLevels.a(SharedLogger.o)
     (maybe you meant: _JavaUtilLoggingLevel_FINER_)
  "_JavaUtilLoggingLevel_INFO", referenced from:
      -[JOLSharedLogger infoWithNSString:withNSString:] in libOtherLevels.a(SharedLogger.o)
     (maybe you meant: _JavaUtilLoggingLevel_INFO_)
  "_JavaUtilLoggingLevel_SEVERE", referenced from:
      -[JOLSharedLogger errorWithNSString:withNSString:] in libOtherLevels.a(SharedLogger.o)
      -[JOLSharedLogger errorWithNSString:withNSString:withJavaLangThrowable:] in libOtherLevels.a(SharedLogger.o)
     (maybe you meant: _JavaUtilLoggingLevel_SEVERE_)
  "_JavaUtilLoggingLevel_WARNING", referenced from:
      -[JOLSharedLogger warningWithNSString:withNSString:] in libOtherLevels.a(SharedLogger.o)
     (maybe you meant: _JavaUtilLoggingLevel_WARNING_)
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

**Comment by kstanger** [comment]
This was intentional. Direct access to the enum values (and static variables) is unsafe. Please use the provided accessors (eg. "JavaUtilLoggingLevel_get_FINE()"), these will ensure static initialization occurs and the values are properly initialized. See http://j2objc.org/docs/Translation-Reference.html#enums.

**Comment by pellet** [comment]
I'm not referencing these enums from objective-c code, they are referenced from java code which is translated to objective-c by j2objc.  I noticed there was some changes to enums from v9.8.2.1 -> 1, maybe this could have something to do with it?

**Comment by kstanger** [comment]
Is the translated code all translated by 1.0.0? If so, can you provide an example of the Java code and the ObjC that gets generated?

**Comment by tomball** [comment]
+1

Although we can't stop people from saving translated code, j2objc is
designed to be and supported as a build tool, where the generated files are
only useful for the next build step. Down the road we hope to stop
generating source and instead invoke clang directly to produce .o files,
though there's a lot of work to do before that happens.
