### ISSUE TITLE
objc_constructInstance isn't supported in ARC

### ISSUE THREAD

**Issue by twoboxen** [google/j2objc#701]
if -use-arc is specified, code with enums will not compile due to generated code having "objc_constructInstance" which is not supported with ARC.

error: 'objc_constructInstance' is unavailable: not available in automatic reference counting mode
    (JreEnum(ComMyCompanyMyClassNetworkType, Mobile) = e = objc_constructInstance(self, (void *)ptr), ptr += objSize);

Additionally, tests should actually compile generated code with different flags, rather than using string matching e.g.
+    assertTranslatedLines(translation,
+        "(JreEnum(Test, A) = e = objc_constructInstance(self, (void *)ptr), ptr += objSize);",
+        "Test_initWithId_withNSString_withInt_(e, @\"foo\", @\"A\", 0);");

**Comment by kstanger** [comment]
FYI, we recommend against using ARC for translated code (even though we support it). See: http://j2objc.org/docs/Memory-Management.html#automatic-reference-counting-arc

I'll fix the enum issue ASAP, since that's rather severe.
