### ISSUE TITLE
Integer overflow with long fields set via reflection on 32-bit architecture

### ISSUE THREAD

**Issue by danieldickison** [google/j2objc#705]
On 32-bit platforms, setting a `long` field via reflection using `Field.set()` appears to cause integer overflow resulting in an incorrect (negative) field value. I've tested this in the iOS simulator (using `ios_i386` arch) and it also seems to affects 32-bit ARM devices, though I haven't tested this myself.

Test case:

```java

public class LongTest {
    public long a;

    public long getA() {
        return a;
    }

    public static LongTest makeLongBoxed(Long value) throws NoSuchFieldException, IllegalAccessException {
        LongTest o = new LongTest();
        Field field = LongTest.class.getField("a");
        field.set(o, value);
        return o;
    }

    public static LongTest makeLongRaw(long value) throws NoSuchFieldException, IllegalAccessException {
        LongTest o = new LongTest();
        Field field = LongTest.class.getField("a");
        field.set(o, value);
        return o;
    }
}
```

```objc
+ (void)run {
    jlong raw = 3000000000LL;
    JavaLangLong *boxed = [JavaLangLong valueOfWithLong:raw];
    
    BCSLongTest *direct = [[BCSLongTest alloc] init];
    direct->a_ = raw;
    NSLog(@"direct.a = %lld", [direct getA]); // => 3000000000
    
    BCSLongTest *reflectBoxed = [BCSLongTest makeLongBoxedWithJavaLangLong:boxed];
    NSLog(@"reflectBoxed.a = %lld", [reflectBoxed getA]); // => -1294967296
    
    BCSLongTest *reflectRaw = [BCSLongTest makeLongRawWithLong:raw];
    NSLog(@"reflectRaw.a = %lld", [reflectRaw getA]); // => -1294967296
}
```

**Comment by kstanger** [comment]
https://github.com/google/j2objc/blob/master/jre_emul/Classes/IOSPrimitiveClass.m#L207
Calls "longValue", should be calling "longLongValue".
Fix is on the way.

**Comment by tomball** [comment]
Good catch! I checked for other occurrences (since it's an easy mistake to
make), and that's the only place longValue is called.

**Comment by kstanger** [comment]
[Fixed in current source](https://github.com/google/j2objc/commit/e1cdbc1f386ec09baefe182fee1b611d4984762b)

**Comment by danieldickison** [comment]
Confirmed that it's fixed in our app in both simulator and devices. Thanks for the quick turnaround!
