### ISSUE TITLE
Possible for translated output to have no prefix?

### ISSUE THREAD

**Issue by adil-hussain-84** [google/j2objc#706]
Would have been great if the file-name of translated output matched the class-name when a prefix is specified. Given that this is not the case I'd like to perform translation so that neither the file-name of the output nor the class-name has a prefix. Is this possible? I can't see how to do this with the `--prefix` parameter...

**Comment by tomball** [comment]
You probably want the --no-package-directories flag.

**Comment by adil-hussain-84** [comment]
Hi Tom, the `--no-package-directories` flag puts all translated files in a single, flat output folder. That's fine but not what I'm requesting here. What I'm requesting is that when a prefix is applied either (1) both the file names of the translated files as well as the classes have the prefix or (2) it should be possible to specify that both the file names of the translated files as well as the classes have no prefix.

Currently the prefix is applied to the name of the class within the translated file but to the name of the file itself.

**Comment by kstanger** [comment]
Have you tried specifying empty prefixes for all your classes? Seems like
that should achieve #2 for you.

**Comment by adil-hussain-84** [comment]
@kstanger before my last comment above I had tried with the `--prefix` flag but it didn't like `com.mycompany.*=` with nothing after the `=`. I get an "invalid prefix format" error. Just occurred to me to try with the `--prefixes` flag and a `prefixes.properties` file with contents as follows...

    com.mycompany.*:

... and, yay, success! It works.

**Comment by kstanger** [comment]
Excellent. I think I could fix the --prefix flag to accept empty prefixes
pretty easily for an upcoming release.

**Comment by adil-hussain-84** [comment]
Awesome. Thanks @kstanger. I prefer using the inline `--prefix` flag if I'm honest rather than the `--prefixes` flag... especially given that I'm using the J2Objc Gradle plugin.

**Comment by kstanger** [comment]
Fixed at head: https://github.com/google/j2objc/commit/6b69027c758903b0926fa8ead6007a3d5898ea0d

**Comment by adil-hussain-84** [comment]
Awesome! I look forward to using it when the Gradle J2ObjC plugin is updated to work with the latest release of J2ObjC. Thanks for the change :+1:
