### ISSUE TITLE
Error after a make dist command

### ISSUE THREAD

**Issue by eboily** [google/j2objc#708]
I encounter an issue a few minutes after issuing a `make dist` command (with j2objc 's latest commit e1cdbc1):

```
install -m 0644 /Users/eboily/Downloads/j2objc-master/junit/build_result/objc/org/hamcrest/internal/SelfDescribingValueIterator.h ../dist/include/org/hamcrest/internal/SelfDescribingValueIterator.h
  File "<string>", line 1
    execfile("constants.bzl"); print " ".join(CONSTANTS_JSR_305_PATHS)
                                       ^
SyntaxError: invalid syntax
```

then after a few more similar messages:

```
Building libjsr305.a
touch: /Users/eboily/Downloads/j2objc-master/jsr305/build_result/objs-iphone/jsr305_objs_list: No such file or directory
make[1]: *** [/Users/eboily/Downloads/j2objc-master/jsr305/build_result/objs-iphone/libjsr305.a] Error 1
make: *** [jsr305_dist] Error 2

```

My environment is as follows:

```
Locale: en_CA.UTF-8
Darwin MacBook-Pro-de-Edouard.local 15.2.0 Darwin Kernel Version 15.2.0: Fri Nov 13 19:56:56 PST 2015; root:xnu-3248.20.55~2/RELEASE_X86_64 x86_64
Xcode 7.2 Build version 7C68
Apple LLVM version 7.0.2 (clang-700.1.81)
Target: x86_64-apple-darwin15.2.0
Thread model: posix
```

I'd appreciate if anyone can help. Thanks!
- Edouard

**Comment by tomball** [comment]
That's failing in what should be a vanilla Python command. What's returned if you run it separately? Here's what my system reports:

    $ python --version
    Python 2.7.10
    $ python -c 'execfile("constants.bzl"); print " ".join(CONSTANTS_JSR_305_PATHS)'
    javax/annotation/CheckForNull.java javax/annotation/CheckForSigned.java javax/annotation/CheckReturnValue.java javax/annotation/concurrent/GuardedBy.java javax/annotation/concurrent/Immutable.java javax/annotation/concurrent/NotThreadSafe.java javax/annotation/concurrent/ThreadSafe.java javax/annotation/Detainted.java javax/annotation/MatchesPattern.java javax/annotation/meta/Exclusive.java javax/annotation/meta/Exhaustive.java javax/annotation/meta/TypeQualifier.java javax/annotation/meta/TypeQualifierDefault.java javax/annotation/meta/TypeQualifierNickname.java javax/annotation/meta/TypeQualifierValidator.java javax/annotation/meta/When.java javax/annotation/Nonnegative.java javax/annotation/Nonnull.java javax/annotation/Nullable.java javax/annotation/OverridingMethodsMustInvokeSuper.java javax/annotation/ParametersAreNonnullByDefault.java javax/annotation/PropertyKey.java javax/annotation/RegEx.java javax/annotation/Signed.java javax/annotation/Syntax.java javax/annotation/Tainted.java javax/annotation/Untainted.java javax/annotation/WillClose.java javax/annotation/WillCloseWhenClosed.java javax/annotation/WillNotClose.java

I'm running OS X El Capitan (10.11.3), which includes Python 2.7. If you have the same OS version but an older Python, perhaps it's separately installed?

**Comment by eboily** [comment]
Actually, I have a more recent python...

```
$ python --version
Python 3.4.4
$ python -c 'execfile("constants.bzl"); print " ".join(CONSTANTS_JSR_305_PATHS)'
  File "<string>", line 1
    execfile("constants.bzl"); print " ".join(CONSTANTS_JSR_305_PATHS)
                                       ^
SyntaxError: invalid syntax
```
I'll install an old one and see.

Thanks!

**Comment by tomball** [comment]
Or if you're a Python wizard (I'm not), suggest a better script. All we're
doing here is converting a Python list of filenames into a space-separated
list.

**Comment by tomball** [comment]
Does this work?

    python -c "execfile('constants.bzl'); print ' '.join(CONSTANTS_JSR_305_PATHS)"

I switched the delimiters, since single-quotes are preferred by most Pythonistas.

**Comment by eboily** [comment]
here is the result:

```
$ python -c "execfile('constants.bzl'); print ' '.join(CONSTANTS_JSR_305_PATHS)"
  File "<string>", line 1
    execfile('constants.bzl'); print ' '.join(CONSTANTS_JSR_305_PATHS)
                                       ^
SyntaxError: invalid syntax
```

**Comment by tomball** [comment]
Got it; BZL_CMD in jsr305/Makefile needs to read:

    'exec(open("constants.bzl").read()); print(" ".join(CONSTANTS_JSR_305_PATHS))'

I verified this command works in both 2.7 and 3.4. I'll update that file now.

**Comment by eboily** [comment]
Cool! Thanks sir! :-)
