### ISSUE TITLE
 Problematic variable name INCLUDE_ALL in Java.

### ISSUE THREAD

**Issue by MarcImbert** [google/j2objc#710]
I've encountered an issue after upgrading j2objc from 0.9.8.2.1 to 1.0.1
Now, the translation of jackson library didn't build anymore.
I've found in TokenFilter.java file they use a variable called INCLUDE_ALL.
It seems this variable name is used too by j2objc for header generation in the generateFileHeader method of the ObjectiveCSegmentedHeaderGenerator.java file for create a constant.
This create a conflict during the build of my project.
Since, I've changed the variable name in the TokenFilter.java file but it will be problematic again if other java files use this variable name "INCLUDE_ALL".
Is it possible to handle that case?

**Comment by tomball** [comment]
The translator needs to include all preprocessor definitions it makes in NameTable's reserved names list.

**Comment by MarcImbert** [comment]
Thank you for your reactivity. I've added "INCLUDE_ALL" and "RESTRICT" to the reserved name list and rebuild the j2objc.jar but it seems not be used by j2objc during the translation. The translation didn't add an _ at the end of the variable name. Have you got an idea?

**Comment by tomball** [comment]
Fixed in current source.

**Comment by MarcImbert** [comment]
Thank's for all! All work perfectly!
