### ISSUE TITLE
j2objc_guava.jar in release 1.0.1 does not contain compiled classes

### ISSUE THREAD

**Issue by chaitanya0bhagvan** [google/j2objc#711]
Looks like release 1.0.1 does not contain guava compiled classes, its a jar file just the java source file.

**Comment by tomball** [comment]
You're right, we'll fix this for the next release. In the meantime, you can download [Guava 18.0 here](http://central.maven.org/maven2/com/google/guava/guava/18.0/guava-18.0.jar).

**Comment by tomball** [comment]
Fixed in current source.
