### ISSUE TITLE
Static fields

### ISSUE THREAD

**Issue by vahidshirvani** [google/j2objc#713]
The Java source is 
![screen shot 2016-02-18 at 13 49 51](https://cloud.githubusercontent.com/assets/3033371/13143823/d53c227c-d646-11e5-9484-7b947da12405.png)
while the generated Objective C code is
![screen shot 2016-02-18 at 13 51 08](https://cloud.githubusercontent.com/assets/3033371/13143841/f4c8002a-d646-11e5-8e50-27cb7ce420cd.png)
I downloaded "j2objc-1.0.1.zip" today and it appears that the file "J2ObjC_common.h" does not contain the "J2OBJC_STATIC_FIELD_GETTER" micro (setter as well) while the old "j2objc-0.9.8.2.1.zip" did. Any reason why it was removed?

**Comment by amlcurran** [comment]
What is the resolution to fix this issue?

**Comment by kstanger** [comment]
The generated Objective-C code in this issue likely was generated with an older version of j2objc and compiled against a newer runtime library. J2ObjC generation is designed to be a part of the build process and translated code must always be generated with the same version as the runtime it's being compiled against.

**Comment by amlcurran** [comment]
OK I thought I had changed this but I would not be surprised if I missed
something. Will check again this evening

**Comment by amlcurran** [comment]
Found it - I hadn't updated what J2Objc build was on my path. Thanks for
the pointer and thanks for the tool!
