### ISSUE TITLE
Multiple calls to nested Lambdas returns an invalid result

### ISSUE THREAD

**Issue by L6Echo** [google/j2objc#717]
We are using in our transpiled Android  Code a lot of lambda expressions (in combination of retrolambda).  When calling nested lambdas multiple times, the result is invalid.

We can reproduce this issue and prepared a simple JUnit Test.

```
import org.junit.Test;

import static junit.framework.Assert.assertEquals;

public class MultipleCallsToNestedLambdasTest {

    public interface Func1<T1, TRes, TException extends Exception> {

        TRes invoke(T1 arg1) throws TException;
    }

    public interface Func<TRes, TException extends Exception> {

        TRes invoke() throws TException;
    }

    private <T> T runFunc(Func<T, RuntimeException> f) {
        return f.invoke();
    }

    private <T> T loop(final Func1<Integer, T, RuntimeException> f) {
        f.invoke(1);
        return f.invoke(0);
    }

    @Test
    public void testMultipleCallsToNestedLambdas() {
        String actual = loop(i -> runFunc(() -> runFunc(() -> "x" + i)));
        String expected = "x" + 0;
        assertEquals("expected '" + expected + "', actual: '" + actual + "'.", expected, actual);
    }

}
```

**Comment by lukhnos** [comment]
The current compiler out for the expression `loop(i -> runFunc(() -> runFunc(() -> "x" + i)))` reads like this (comments are mine):

```objc
  NSString *actual = Main_loopWithMain_Func1_(GetNonCapturingLambda(@protocol(Main_Func1), @"Main_lambda$0", @selector(invokeWithId:),
  ^NSString *(id _self, JavaLangInteger * i){ // the i -> ... lambda
    return Main_runFuncWithMain_Func_(GetCapturingLambda(@protocol(Main_Func), @"Main_lambda$1", @selector(invoke),
    ^NSString *(id _self) { // helper for the second () -> ... lamdba
      NSString * (^block)() = objc_getAssociatedObject(_self, (void *) 0);
      return block(_self);
    },
    ^NSString *(id _self){ // the actual block for the second () -> ... lamdba
      return Main_runFuncWithMain_Func_(GetNonCapturingLambda(@protocol(Main_Func), @"Main_lambda$2", @selector(invoke),
      ^NSString *(id _self){ // the third, inner most () -> ... lamdba, which should have been a capturing one
        return JreStrcat("C@", 'x', i);
      }
      ));
    }
    ));
  }
  ));
```

So the outermost lambda `i -> ...` is correctly compiled to a non-capturing block. The two inner lambdas should both capture the `JavaLangInteger *i` in the produced outermost block, but for some reason the innermost lambda is compiled to a non-capturing one.

**Comment by minichma** [comment]
Any plans yet, when this issue will be addressed? This rather severely influences our ability to use J2ObjC (which we love, by the way) for a larger app with many async, functional-style constructs.

Would it be a valid workaround to make every lambda a capturing one in the following line of code (well aware of the fact, that this will have negative performance impact)?
https://github.com/google/j2objc/blob/e5039c9307a78342f4bbed135976f863b6f62e33/translator/src/main/java/com/google/devtools/j2objc/translate/Rewriter.java#L398

Thanks for any help!

**Comment by sjkirby** [comment]
Making every lambda capturing would work as a stopgap, with the caveat that every lambda instance will have a new object associated with it.

The underlying issue is that we have a bug in the way lambdas interact with the OuterReferenceResolver.  I'm looking into it, but don't have an OS X machine available at the moment so it might be slow going.

**Comment by L6Echo** [comment]
Thank you for your help. The by minichma provided workaround does work for this issue. We discovered additional reprodruceable issue. It seems that they are related with this issue. Here some additional unit tests

### Exception during transpiling
 The following test causes a TreeVisitorAssertionError Exception during transpiling:
```java

 com.google.devtools.j2objc.ast.TreeVisitorAssertionError: 

****.java:70: internal error translating "***.java"
error: null
	at com.google.devtools.j2objc.translate.OuterReferenceFixer.fixPath(OuterReferenceFixer.java:187)
	at com.google.devtools.j2objc.translate.OuterReferenceFixer.visit(OuterReferenceFixer.java:153)
	at com.google.devtools.j2objc.ast.SimpleName.acceptInner(SimpleName.java:67)
	at com.google.devtools.j2objc.ast.TreeNode.accept(TreeNode.java:105)
	at com.google.devtools.j2objc.ast.ChildLink.accept(ChildLink.java:76)
	at com.google.devtools.j2objc.ast.ChildList.accept(ChildList.java:86)
	at com.google.devtools.j2objc.ast.InfixExpression.acceptInner(InfixExpression.java:180)
	at com.google.devtools.j2objc.ast.TreeNode.accept(TreeNode.java:105)
	...
```

   ```java
 ...
    @Test
    public void testLambdaNestedInAnonymousInnerClass() {
    
        String vOuter = "x";

        String actual = loop(new Func1<Integer, String, RuntimeException>() {
            @Override
            public String invoke(Integer argMiddle) throws RuntimeException {
                return runFunc(() -> vOuter + argMiddle);
            }
        });

        String expected = vOuter + 0;
        assertEquals("expected '" + expected + "', actual: '" + actual + "'.", expected, actual);
    }
    ...
```

### Warning during transpiling
The following unit test will produce the following warning during transpiling:
`    // warning: (Recovered) Internal inconsistency detected during lambda shape analysis
`

```java
    @Test
    public void testNestedLambdaWarnings() {

        String vOuter = "x";

        String actual = loop(i -> {
            return loop(ii -> {
                return loop(iii -> "y" + i + " " + ii + " " + iii);
            });
        });

        String expected = "y0 0 0";
        assertEquals("expected '" + expected + "', actual: '" + actual + "'.", expected, actual);
    }
```

### Undelcared Identifier
The following unit Test got successfully transpiled, but compiling the transpiled j2ObjC source failes with:
`Use of undeclared identifier 'vOuter'`

```java
    @Test
    //  Use of undeclared identifier 'vOuter'
    public void testAnonymousInnerClassNestedInLambda() {

        String vOuter = "x";

        String actual = loop(argMiddle -> runFunc(new Func<String, RuntimeException>() {
            @Override
            public String invoke() throws RuntimeException {
                return vOuter + argMiddle;
            }
        }));

        String expected = vOuter + 0;
        assertEquals("expected '" + expected + "', actual: '" + actual + "'.", expected, actual);
    }

```

**Comment by L6Echo** [comment]
Thank you very much for your great and fast work! We successfully replaced the by @minichma suggested workaround with your bugfix. Our code seems to work now.

The transpiler warning `warning: (Recovered) Internal inconsistency detected during lambda shape analysis` does still occurs. I don't know how critical is such a situation, but i created another ticket for this issue: 

[warning: (Recovered) Internal inconsistency detected during lambda shape analysis #725](https://github.com/google/j2objc/issues/725)

**Comment by ex3ndr** [comment]
Unfortunately in some rare and complex cases it is still not working. Sorry, it is very hard to make example as i can't find exact configuration. I hope will provide something in the future.

**Comment by ex3ndr** [comment]
![image](https://cloud.githubusercontent.com/assets/400659/14771657/99974656-0a9a-11e6-852a-04a3f591f35c.png)

Ok, i found an issue. Looks like that when you use method reference instead of lambda it captures data incorrectly.

When i commented lines and replaced everything with lambdas everything started working.

**Comment by lukhnos** [comment]
@ex3ndr It'd be great if you can create a new issue for that.

We currently translate method references into non-capturing blocks. A workaround you can try is to set `isCapturing` to `true` in [`StatementGenerator.printMethodReferenceCallWithoutBlocks`](https://github.com/google/j2objc/blob/master/translator/src/main/java/com/google/devtools/j2objc/gen/StatementGenerator.java#L824).
