### ISSUE TITLE
IOSClass getResourceAsStream returns nil although the resource is in the bundle

### ISSUE THREAD

**Issue by sketchydroide** [google/j2objc#723]
I'm having this issue where IOSClass getResourceAsStream is being called and returns nil on a file.
I know this file is in the bundle, and even if I change the file name to something else, like the app icon image file, it still returns nil.

I tried using [[[JavaLangClassLoader alloc] init] getResourceAsStreamWithNSString], and I start getting something back, this led me to believe that the problem is with the IOSClass method.

This was only after I updated j2objc to 1.0.1.

Here is a code example bellow:

[[[JavaLangClassLoader alloc] init] getResourceAsStreamWithNSString:@"icon.png"]; // returns a JavaIoBufferedInputStream instance.
[[[IOSClass alloc] init] getResourceAsStream:@"icon.png"]; // returns nil

Thanks,
Andre

**Comment by tomball** [comment]
Never define IOSClass instances using [[ClassName alloc] init] -- Java obviously doesn't support "new Class()", and neither does j2objc. The class instance you've improperly created has no instance data (IOSClass is an abstract class, and is never instantiated directly). Instead use either [instance getClass], the defined class literal function (TYPE_class_(), where TYPE is the camel-cased IOS equivalent of the Java class name) or Class.forName("Java class name"), to fetch a class instance.
