### ISSUE TITLE
The *lib/j2objc_guava.jar* file in the 1.0.1 release contains *.source* files rather than *.class* files??

### ISSUE THREAD

**Issue by adil-hussain-84** [google/j2objc#736]
I've just compared the `lib/j2objc_guava.jar` file in the 1.0.1 release with earlier releases and the jar file in the latest release contains `.source` files rather than `.class` files. Is this intentional or is this a mistake?

I'm confused by this because not only does it differ from earlier releases but it also differs from other `.jar` files in the `lib` folder of the 1.0.1 release (which contain `.class` files).

**Comment by tomball** [comment]
Fixed in [release 1.0.2](https://github.com/google/j2objc/releases/tag/1.0.2) -- the library is now called "guava-19.0.jar" and is an unmodified copy of [the jar Google Guava team distributes via Maven](http://mvnrepository.com/artifact/com.google.guava/guava/19.0).

**Comment by tomball** [comment]
And yes, it was a mistake. :-)

**Comment by adil-hussain-84** [comment]
Phew! That's good to hear. I was getting worried that something major had changed in the 1.0.1 release which would mean a significant change on my side to get things working. (I'm using the J2ObjC Gradle plugin and I'm experimenting to see whether it works with the 1.0+ releases of the J2ObjC library.

Thanks for the swift response. Much appreciated.
