### ISSUE TITLE
java.time.LocalDateTime is not supported

### ISSUE THREAD

**Issue by mahmoud-khalifa** [google/j2objc#737]
I am trying to translate java code that reference `java.time.LocalDateTime` using the flag `-source 8` to use jdk 1.8 as this class was introduced in jdk7 but I am getting error that it is not resolved to a type

    error: TestProject/src/main/java/com/test/TestJavaTime.java:8: The import java.time cannot be resolved
    error: TestProject/src/main/java/com/test/TestJavaTime.java:26: LocalDateTime cannot be resolved to a type

Then I checked the supported classes at http://j2objc.org/reference/packages.html and didn't find any `java.time` package classes.

So is there is plan to support `java.time` classes soon?

**Comment by tomball** [comment]
J2ObjC's JRE classes use Android's source, since classes not included with
Android can't be shared with iOS (J2ObjC's goal is to support portable
code, not necessarily fully support the latest Java runtime). When Android
supports the java.time packages, we'll add them.

**Comment by mahmoud-khalifa** [comment]
@tomball Thanks for your fast reply
