### ISSUE TITLE
Protobuf nano and J2Objc translated classes in Swift

### ISSUE THREAD

**Issue by gchoza** [google/j2objc#741]
I initially posted this on Protobuf and they suggested I post it here.

I have a J2Objc project using protobuf nano. The issue I'm having is that the instance variables in the generated Objective C code (from javanano) are iVars and Swift cannot access them directly. I have to use the "valueForKey("mResponseData_")" syntax and cast the result to the correct type which is not ideal. I cannot annotate the generated protobuf Java classes with the J2Objc @Property since I don't control code generation, and I have not found a way of annotating my .proto file to add @Property in the generated Java classes.

As a workaround I'm using " option 'optional_field_style=accessors'" in protobuf to generate accessors for primitive data types. However, reference types do not have generated accessors so for those I'll have to use the "valueForKey" syntax.
I could create a script to add the annotation after javanano generation but I'd rather not.

Has anyone solved this issue or have a better way of doing this?

Thanks,

Gabriel

**Comment by tomball** [comment]
The javanano generator has an option to create accessor methods
<https://github.com/google/protobuf/tree/master/javanano>. Although the
default is direct field access, specifying "optional_field_style=accessors"
will provide accessors that Swift should be able to import.

**Comment by tomball** [comment]
There's no magic j2objc can add here. Swift won't access ivars directly, so your options include:
- Have javanano generate accessors,
- Post-process the generated Java file to add @Property annotations,
- Post-process the generated Objective C file to add @property declarations,
- Use regular protobufs, which j2objc has a custom generator for (that's what Google apps use), or
- Use Objective C instead of Swift to access your proto classes.

**Comment by gchoza** [comment]
I'm using the optional_field_style option but it does not generate accessor methods for reference variables, only for primitives. It's a workable solution but I'm looking for a better way of solving this issue.

**Comment by kstanger** [comment]
One idea would be to add a command-line flag that tells j2objc to generate properties for all public fields as if they had a @Property annotation.

**Comment by gchoza** [comment]
j2objc does that. I went with the second option listed by tomball: post-processed the generated java files to add the @Property annotation. Turned out to be fairly simple and j2objc generated the properties.
