### ISSUE TITLE
Linking error when using @Singleton annotation

### ISSUE THREAD

**Issue by mahmoud-khalifa** [google/j2objc#744]
I have multiple classes that has `@Singleton` annotation and after translating them using the latest version `1.0.2` I got the following linking error

    Undefined symbols for architecture x86_64:
      "_create_JavaxInjectSingleton", referenced from:
          +[AbstractMqttConnection __annotations] in com.mycompany.services.messaging.mqtt.AbstractMqttConnection
          +[AbstractMqttSubscriber __annotations] in com.mycompany.services.messaging.mqtt.AbstractMqttSubscriber
          +[AbstractMqttPublisher __annotations] in com.mycompany.services.messaging.mqtt.AbstractMqttPublisher
    ld: symbol(s) not found for architecture x86_64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)

here the `__annotation` method

    + (IOSObjectArray *)__annotations {
        return [IOSObjectArray newArrayWithObjects:(id[]){ create_JavaxInjectSingleton() } count:1 type:JavaLangAnnotationAnnotation_class_()];
    }
I have checked `javax.inject.Singleton.h` inside the `dist` folder and found that the method `create_JavaxInjectSingleton` exists, also checked `javax/build_result/objc`  and found that the method exists in the `.m` file 

I don't know why I am getting this error in linking, note that I use the following flags when linking 
`-ObjC -ljre_emul -ljunit -lguava -ljsr305` with `j2objcc` command

**Comment by kstanger** [comment]
That symbol is in libjavax_inject.a. Add -ljavax_inject to your link command.

**Comment by mahmoud-khalifa** [comment]
Thanks a lot
