### ISSUE TITLE
IOSClass resolves to nil in Application that uses Cocoa Touch Framework that uses J2ObjC

### ISSUE THREAD

**Issue by adil-hussain-84** [google/j2objc#745]
I have a Cocoa Touch Framework that contains code translated by the J2ObjC library. In some of the iOS native classes in my Framework I have a need to get the `IOSClass` that corresponds to a class within my J2ObjC translated code. Let's call that class `MyClass` for example's sake. All of the following techniques for getting the `IOSClass` associated to `MyClass` work within my Framework (confirmed by means of unit tests within my Framework project):

    IOSClass *class1 = MyClass_class_();
    IOSClass *class2 = [IOSClass forName:@"MyClass"];
    IOSClass *class3 = [IOSClass classForIosName:@"MyClass"];

The problem arises when I plug my Framework into an Application. All of the above techniques for getting the `IOSClass` associated to `MyClass` resolve to `nil`. I am very confused by this. **Any ideas on how I could get the above code from the Framework to work in the Application?** (I tried including the `prefixes.properties` file to the Framework's bundle resources but no luck.)

**Comment by lukhnos** [comment]
Do you mean you build your framework as a separate target that your application links to? And is your application linking to the framework statically? If so, are you having `-ObjC` in your application's linker flag?

**Comment by adil-hussain-84** [comment]
Hi @lukhnos, yeah, I definitely have `-ObjC` in my application's linker flags. And, yes, my framework is a separate entity which links into my application (they're two separate Xcode projects). In my application's main target the framework shows up in the "Embedded binaries" list as well as the "Linked Frameworks and Libraries" list.

So the translated code links as a library to the framework which links to the application. Interestingly I see that when the framework code which is running within the application calls `MyClass_class_()`, this resolves to `nil`. However, when the translated code which is running within the framework which is running within the application calls `MyClass_class_()`, this resolves to a concrete `IOSClass` instance. Very strange.

**Comment by tomball** [comment]
You mentioned that you use a prefixes.properties file, and I've heard of issues sharing resources between apps and frameworks. Would you please try loading a non-prefixed class (one that uses a camel-cased package+name) from your framework in your app? If that works, we can focus on whether it's a resource access issue or not.

**Comment by adil-hussain-84** [comment]
Thanks @tomball. I'll run that experiment some time this week and report back with my findings.

**Comment by tomball** [comment]
Thank @lukhnos, not me. :-)

**Comment by adil-hussain-84** [comment]
Hmm... it turns out that this might not be an issue after all! Looks like I was debugging my application with a release build of my Framework and thus when stepping into my Framework with the debugger the variables inspector was not quite accurate. Printing out values and debugging the application with a debug build of the Framework appears to show that `IOSClass` can be resolved.

Thanks @lukhnos and @tomball for your assistance.
