### ISSUE TITLE
The [IOSClass getDeclaredClasses] method fails when called on a class that has prefix applied

### ISSUE THREAD

**Issue by adil-hussain-84** [google/j2objc#746]
Assume I have a Java class as follows:

```
package com.mycompany.mysdk;

public class SomeClass {
    public class Inner {
    }
}
```

If I translate this Java class to Objective-C without applying a prefix, then making the following call...

```
IOSObjectArray *declaredClasses = [ComMycompanyMysdkSomeClass_class_() getDeclaredClasses];
```

... succeeds and I get a sensible array for `declaredClasses`.

However, if I translate the Java class to Objective-C with a prefix applied (albeit an empty prefix), then making the following call...

```
IOSObjectArray *declaredClasses = [SomeClass_class_() getDeclaredClasses];
```

... results in a `JavaLangClassNotFoundException` being thrown with this message: `"com.mycompany.mysdk.SomeClass$Inner"`.

**Comment by adil-hussain-84** [comment]
Note 1: I get the same result even if the inner class is a static inner class.

Note 2: I've tried adding the `prefixes.properties` file to my Xcode targets but that makes no difference.

**Comment by adil-hussain-84** [comment]
Note 3: the other `getDeclared...` methods work okay when called on `SomeClass_class_()`, as follows...

    IOSObjectArray *declaredAnnotations = [SomeClass_class_() getDeclaredAnnotations];
    IOSObjectArray *declaredFields = [SomeClass_class_() getDeclaredFields];
    IOSObjectArray *declaredMethods = [SomeClass_class_() getDeclaredMethods];

... All of the above return sensible arrays.

**Comment by adil-hussain-84** [comment]
Note 4: the following call does work...

IOSClass *innerClass = [IOSClass forName:@"SomeClass$Inner"];

So the issue only appears to be the `getDeclaredClasses` method when called on a class that contains an inner class and which has had a prefix applied.

**Comment by kstanger** [comment]
I'm doing a bunch of work on our reflection support right now and I should have an opportunity to fix this in the process. Stay tuned.

**Comment by adil-hussain-84** [comment]
Thanks @kstanger. Looking forward to the fix so that I can remove workaround code from my project.

**Comment by adil-hussain-84** [comment]
@kstanger Whenever you or anyone gets around to investigating this... as well as issues around creating an `IOSClass` with the `[IOSClass forName:]` method when a prefix is applied I'm also seeing issues around the `[IOSClass initWithClass:]` method.

**Comment by tomball** [comment]
Do not use the initWithClass: method, as it's private to j2objc's runtime.
Only use methods that are part of the public java.lang.Class API
<https://docs.oracle.com/javase/7/docs/api/java/lang/Class.html>, which
doesn't have any public constructors.

**Comment by adil-hussain-84** [comment]
Ah, okay. Noted. Thanks for pointing that out @tomball. Ignore my previous message in that case. But the original issue still stands: the `[IOSClass getDeclaredClasses]` method fails when called on a class that has had a prefix applied during translation.

**Comment by tomball** [comment]
Right, that's why the issue is still open. :-)

**Comment by kstanger** [comment]
I just synced a large number of changes to our reflection support. I haven't tested this issue specifically, but I expect it to work correctly now. Can you verify?

**Comment by adil-hussain-84** [comment]
@kstanger: How do I get a build of `j2objc` with these changes? Could you send me a zip of the library with these changes?

**Comment by tomball** [comment]
http://j2objc.org/docs/Building-J2ObjC.html

**Comment by adil-hussain-84** [comment]
Really sorry I haven't tested this yet. I've got a big deadline at work for the end of July and have not been able to get around to testing this fix. I will run the test at the beginning of August if I'm not able to do so earlier. Apologies again for the delay.

**Comment by kstanger** [comment]
That's perfectly fine. We might have a new release soon that will make it easier for you to test.

**Comment by adil-hussain-84** [comment]
Tested with versions 1.1 and 1.2 of the library and the issue is indeed resolved. Many thanks.

**Comment by kstanger** [comment]
Thanks for verifying.
