### ISSUE TITLE
Does not have a member named 'unseq$1'

### ISSUE THREAD

**Issue by egu002** [google/j2objc#748]
Translating this:

MyClass
private Double average = null;
private int count = 0;
...
this.average = (this.average * this.count + value) / (++this.count);

resulted in this:

jint unseq$1 = self->count_;
JreStrongAssign(&self->average_, JavaLangDouble_valueOfWithDouble_(([self->average_ doubleValue] * self->unseq$1 + value) / ++self->count_));

which gave an error ''MyClass' does not have a member named unseq$1'

Fixing the original, ambiguous statement works around this problem

**Comment by kstanger** [comment]
Fixed in [current source](https://github.com/google/j2objc/commit/a28a33e6184969666264e8bb69b3e86424edd7fc).
