### ISSUE TITLE
Who is at Google I/O for a chat about j2objc?

### ISSUE THREAD

**Issue by zasadnyy** [google/j2objc#749]
Hello guys,

Are there anyone on Google I/O to meet in person who can share experience about building apps with j2objc?

Regards

**Comment by kstanger** [comment]
I'm not around, since I work out of Google's office in Kitchener, Ontario.

In the future, please use our [j2objc-discuss mailing list](https://groups.google.com/forum/#!forum/j2objc-discuss) for this sort of discussion instead of filing an issue.

**Comment by zasadnyy** [comment]
Sure, thanks
