### ISSUE TITLE
Port Android's Posix.java, use it for I/O support [moved]

### ISSUE THREAD

**Issue by kstanger** [google/j2objc#75]
This is [Issue 75](https://code.google.com/p/j2objc/issues/detail?id=75) moved from a Google Code project.
Added on 2012-10-25T16:33:24.000Z by [tball@google.com](http://code.google.comhttps://code.google.com/u/tball@google.com/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium

**Comment by tomball** [comment]
Implemented.
