### ISSUE TITLE
Regex not working correctly in Objective C

### ISSUE THREAD

**Issue by TarasOsiris** [google/j2objc#751]
```java
	private String extractAppIdFromAppKey(String appId) {
		// take the second half of the 40 characters
		String working = appId.substring(20);

		// this removes leading 0's
		working = working.replaceFirst("^0+(?!$)", "");
		return working;
	}
```

This is the method that removes zeros from the beginning of the string, in Objective C it does not.

```
1) testAppIdExactly40SymbolsAndZerosInTheMiddle(im.getsocial.sdk.core.AppIdTest)
java.lang.AssertionError: 
Expected: "103456789"
     but: was "0103456789"
```

Version j2objc-0.9.8.2.1

**Comment by kstanger** [comment]
Thanks for the report. I have a fix prepared that will be available next time we sync our codebase.

**Comment by kstanger** [comment]
Fixed in [current source](https://github.com/google/j2objc/commit/0367d54aed7fc1952cb624110e1491dce4ab25e5).
