### ISSUE TITLE
Question: bitcode in j2objc necessary before releasing?

### ISSUE THREAD

**Issue by Buggaboo** [google/j2objc#755]
As I understand it, it's compulsory nowadays, to bake-in your bitcode (aka llvm ir?), do I have to add a parameter (i.e. `-fembed-bitcode`) to the j2objc Makefile process?

As I understand the release procedure, during the app review process, the offered ipa is stripped from its arch-specific bits and bobs, then the bitcode is used to recompile for that specific device+os version that requires it.

**Comment by tomball** [comment]
That flag is already used in the [jre_emul](https://github.com/google/j2objc/blob/master/jre_emul/environment.mk#L190) and [other library](https://github.com/google/j2objc/blob/master/make/fat_lib_macros.mk#L50) builds.
