### ISSUE TITLE
Text Decimal Format not adding minus to negative numbers in Arabic

### ISSUE THREAD

**Issue by chezzdev** [google/j2objc#757]
Hello.
As you can guess from the title this code:

``` objective-c
JavaUtilLocale *javaLocale = [[JavaUtilLocale alloc] initWithNSString:@"ar"withNSString:@"AR"];
JavaTextDecimalFormatSymbols *symbols = [[JavaTextDecimalFormatSymbols alloc] initWithJavaUtilLocale:javaLocale];
JavaTextNumberFormat *numberFormat = [[JavaTextDecimalFormat alloc] initWithNSString:@"0" withJavaTextDecimalFormatSymbols:symbols];
[numberFormat setMaximumFractionDigitsWithInt:2];

NSLog(@"%@", [numberFormat formatWithDouble:-3.75f]);
```

prints

```
3٫75
```

instead of

```
-3٫75
```

Trying to debug that I came to `LibcoreIcuNativeDecimalFormat` inside of the `JavaTextNumberFormat` and saw that attribute `negativePrefix` of inner `nsFomatter` ivar is empty string. Not sure how inner `NSFormatter` is created and set but `negativePrefix` should probably be `"-"` even for Arabic. 
How do you think?

**Comment by tomball** [comment]
Sounds like a bug we'll investigate. I implemented your code as a Java unit test, which shows the problem both using java.text.DecimalFormatSymbols (whose javadoc says to normally not use), and the preferred NumberFormat.getNumberInstance(locale). The latter is easier to use, too:

    Locale locale = new Locale("ar", "AR");
    NumberFormat formatter = NumberFormat.getNumberInstance(locale);
    formatter.setMaximumFractionDigits(2);
    String number = formatter.format(-3.75);

**Comment by chezzdev** [comment]
Thanks @tomball. Looking forward to updates.

**Comment by kstanger** [comment]
This issue appear to have been fixed by [this commit](https://github.com/google/j2objc/commit/459c93e992c39a52aa390264cb5e5f4130aef6c8).

**Comment by denisleal** [comment]
Hi! I am having a similar issue, but the other way around. In my case, we are trying to convert a string value to a number. Our backend sends the string value formatted using Sweden locale. When the string comes with a negative value, for example "-14,00", and we try to convert it to a Number object, we get a NumberFormatException.

Piece of exception printed in Xcode output:
Exception in thread "pool-1-thread-20" java.lang.NumberFormatException: The string -14,00 could not be converted to money units
	at 0x0000000105c1601c C.DataConverter.convertMoneyStringToUnits() + 476

Below is our Java Code:
public static long convertMoneyStringToUnits(String moneyString)
            throws NumberFormatException {
        Number interpretation;
        try {
            interpretation = NumberFormat.getNumberInstance(new Locale("sv", "se"))
                    .parse(moneyString);
        } catch (Exception e) {
            throw new NumberFormatException("The string " + moneyString + " could not be " +
                    "converted to money units");
        }
        return Math.round(interpretation.doubleValue() * MONEY_UNITS_PER_CURRENCY_UNIT);
    }

Would you mind to help figure if it is a bug in J2Objc or if we are doing something wrong?
