### ISSUE TITLE
Accessing a "volatile" from different thread may cause a deadly spinlock

### ISSUE THREAD

**Issue by mbaron** [google/j2objc#761]
When accessing a java `volatile` variable, the access to the variable is protected using a spinlock. 

# Problem description
1) If the lock is owned by a background thread with low priority
2) and the main thread (which has higher priority) is trying to acquire the lock
then CPU ressources are only allocated to the main thread which is spinning forever and never yield control to the background thread (which has the lock).

This is not only a theoretical problem, we have a path in our application which can easily lead to this situation.

Other references on the subject:
http://engineering.postmates.com/Spinlocks-Considered-Harmful-On-iOS/
https://github.com/ReactiveCocoa/ReactiveCocoa/issues/2619
http://mjtsai.com/blog/2015/12/16/osspinlock-is-unsafe/
https://lists.swift.org/pipermail/swift-dev/Week-of-Mon-20151214/000372.html

# In depth analysis
https://github.com/google/j2objc/blob/master/jre_emul/Classes/J2ObjC_common.m#L84
```
#define VOLATILE_POWER 7
#define VOLATILE_MASK ((1 << VOLATILE_POWER) - 1)
#define VOLATILE_HASH(x) (((long)x >> 5) & VOLATILE_MASK)
#define VOLATILE_GETLOCK(ptr) &volatile_locks[VOLATILE_HASH(ptr)]
#define VOLATILE_LOCK(l) while (__c11_atomic_exchange(l, 1, __ATOMIC_SEQ_CST)) {}
#define VOLATILE_UNLOCK(l) __c11_atomic_store(l, 0, __ATOMIC_SEQ_CST)
```

In macro `VOLATILE_GETLOCK`. you can see this will spin forever until the lock is available.
On iOS, the thread scheduler is using the concept of "Quality of Service" which may only give priority to the main thread and the background thread will be starving of CPU resources, and therefore will never release the lock. 

# Possible solution
References on the web are suggesting using `pthread_mutexes ` instead of spin locks to avoid falling into a priority inversion problem.

**Comment by kstanger** [comment]
Thanks for the report. We were aware of this issue, but considered it low priority because no users have had a problem until now. We're considering using dispatch_semaphore for mutual exclusion.

**Comment by kstanger** [comment]
Fixed in current source.

**Comment by tomball** [comment]
Commit https://github.com/google/j2objc/commit/e97bb995e1d6eeb5a8b29acc961c302aa42436bd
