### ISSUE TITLE
Do J2Objc support predefine

### ISSUE THREAD

**Issue by leogeng** [google/j2objc#763]
i have some shared code to support android and iOS, and  i add some annotation to the shared code as the following:

shared.java:
public class javaClass{
   ....
  @ObjectiveCName(value="enbaled")
   public boolean isEnable() {
        .......
    }
  ...
}

I must add a jar named  'com.google.j2objc:j2objc-annotations', I do not want to import it in android side.

How to resolve it?

**Comment by tomball** [comment]
You have to add it on the Android side. If necessary, the library is available independent of a j2objc release, [using Maven](https://search.maven.org/#artifactdetails%7Ccom.google.j2objc%7Cj2objc-annotations%7C1.3%7Cjar). If your team builds the Android app with Gradle, [you can specify that Maven dependency in your project](https://docs.gradle.org/current/userguide/artifact_dependencies_tutorial.html#sec:repositories_tutorial).
