### ISSUE TITLE
final instance variables not read in reflection

### ISSUE THREAD

**Issue by kpgalligan** [google/j2objc#766]
final non-static instance variables that are instantiated directly when declared are not read properly with reflection.

In the following example, the field 'value' does not return '5' being read through reflection.

private static class BasicFinal {
    public final long value = 5;
  }

The value is translated as a constant, but the code in Field.m that reads the value doesn't deal with this case. The code currently falls into this 'if' block, but doesn't match the next condition, and no value gets set for return.

https://github.com/google/j2objc/blob/master/jre_emul/Classes/java/lang/reflect/Field.m#L114

For a workaround, making this value static would probably work in most cases, as this is kind of a nonsense case to begin with. This was for gson, which would ignore non-instance fields, so if you had to make this work, set the value in a default constructor.

private static class BasicFinal {
    public final long value;
    public BasicFinal(){value = 5;}
}

**Comment by tomball** [comment]
Keith's comment to j2objc-discuss held the fix:

> Final primitive instance variables that have a constant value are translated as if they were static constants. (Java does this too) 

So change ReadRawValue's second test from `if (IsStatic(field))` to `if (IsStatic(field) || IsFinal(field))`, and your test case passes. Keith may want a more rigorous test after reviewing change tomorrow, but it should unblock you until the final fix is promoted.

Thanks for the simple test (the best kind); you'll find it in `jre_emul/Tests/com/google/j2objc/FieldTest.java` with this commit.

**Comment by kpgalligan** [comment]
Looks very logical, and I probably would've spent hours trying to find that. Glad I posted ;) Going to run that locally and try out.

**Comment by kpgalligan** [comment]
Tried it and that breaks non-constant final fields (assuming I put it in the right place). This returns 0 instead of 5.

private static class BasicFinal {
    public final long value;
    public BasicFinal()
    {
      value = 5;
    }
}

Adding a check for the ivar to that line "works", but feels inelegant. Could probably be in a better place, or maybe there should be something that means "IsConstant".  I'm going to try that out with the broader set of tests to see if it works, then put this down for the night.

if (IsStatic(field) || (IsFinal(field) && field->ivar_ == NULL))

**Comment by kpgalligan** [comment]
Tried creating a simple version minus gson to break, but its not cooperating. The EXC_BAD_ACCESS issue above seems to be related, but may be something else.  The case in question is on the pretty extreme edge, so I'm going to shelve it for now. The original issue, IsFinal/etc, still an issue, of course. The check for IsFinal and null ivar_ seems to be working locally.

I was working from master as of a couple weeks ago, but updated and reran. No change in reported issues/fixes (or the other 961 tests, so thats good!)

**Comment by tomball** [comment]
[Fixed in current source.](https://github.com/google/j2objc/commit/cd05adcb186b14ffccddbe8e57dcbd34895d4f84)
