### ISSUE TITLE
Enum values don't have annotations available in reflection

### ISSUE THREAD

**Issue by kpgalligan** [google/j2objc#768]
This test fails:

https://github.com/google/gson/blob/master/gson/src/test/java/com/google/gson/functional/EnumTest.java#L148

Enum defined here:

https://github.com/google/gson/blob/master/gson/src/test/java/com/google/gson/functional/EnumTest.java#L195

From the gson test code:

```java
public enum Gender {
    @SerializedName("boy")
    MALE,

    @SerializedName("girl")
    FEMALE
  }
```

Running this in java gets a length of 1. J2objc length is 0.

```java
public void testEnumFieldAnnotations()throws Exception {
    Field male = Gender.class.getDeclaredField("MALE");
    int length = male.getAnnotations().length;
    assertEquals(1, length);
}
```

**Comment by kstanger** [comment]
Fixed in [current source](https://github.com/google/j2objc/commit/219219ff9f732bb3facb3050c201da2eb343bab6).
