### ISSUE TITLE
Translated files including source absolute path

### ISSUE THREAD

**Issue by mlmateo** [google/j2objc#772]
Hi!
I'd like to know if is there a way to change or remove the comment specifying the source file in translated files. Something like a parameter for the converter telling not to include this line, or a pattern for that comment. Our problem is that this line specifies the absolute path of the source file (which obviously may change among different computers) and that marks files as modified in the repo... Making it a relative path would be great too.

Thanks!

**Comment by tomball** [comment]
Files generated by j2objc are supposed to be transitory build artifacts,
similar to .o files created by the C compiler. We recommend that you *not*
save translations to version control systems like git, or share them
between developers.

**Comment by mlmateo** [comment]
Thanks for the suggestion
