### ISSUE TITLE
Memory leaks in transpiled classes of JRE Emul

### ISSUE THREAD

**Issue by gianlucabertani** [google/j2objc#773]
Hello,

our code makes heavy use of classes from `java.util.concurrent` that appear to be at the origin of important memory leaks in JRE Emul.

One of the memory leaks is in `LinkedBlockingQueue`, in particular when used by a `ThreadPoolExecutor`. It is due to a cyclic reference in `LinkedBlockingQueue.Node`. This is how Instruments visualizes it:

![screen shot 2016-07-29 at 16 42 26](https://cloud.githubusercontent.com/assets/5794311/17300887/a6a0d124-5814-11e6-8165-787ed92b2433.png)

Our guess is that it can be explained with the second use case of `next` in the following extract of the JDK's source code:

```java
package java.util.concurrent;

[…]

public class LinkedBlockingQueue<E> extends AbstractQueue<E>
        implements BlockingQueue<E>, java.io.Serializable {

    […]

    /**
     * Linked list node class
     */
    static class Node<E> {
        E item;

        /**
         * One of:
         * - the real successor Node
         * - this Node, meaning the successor is head.next <-- Cyclic reference
         * - null, meaning there is no successor (this is the last node)
         */
        Node<E> next;

        Node(E x) { item = x; }
    }

    […]
```

Another memory leak is in `ScheduledThreadPoolExecutor`. It is due to a cyclic reference in `ScheduledThreadPoolExecutor.ScheduledFutureTask`. This is how Instruments visualizes it:

![screen shot 2016-07-29 at 16 42 13](https://cloud.githubusercontent.com/assets/5794311/17300880/9d629cd2-5814-11e6-8ecd-c74f4afb5564.png)

Our guess is that it can be explained by the following extract of the JDK's source code:

```java
package java.util.concurrent;

    […]

    private class ScheduledFutureTask<V>
            extends FutureTask<V> implements RunnableScheduledFuture<V> {

        […]

        /** The actual task to be re-enqueued by reExecutePeriodic */
        RunnableScheduledFuture<V> outerTask = this; <-- Cyclic reference

        […]
```

We understand that the source code of the JDK is not under J2ObjC responsibility, but is there something that can be done for cases like these?

Thanks in advance.
Best regards.

**Comment by danieldickison** [comment]
I think a similar issue was previously fixed in ConcurrentLinkedQueue e.g. in https://github.com/google/j2objc/commit/db259
It looks like a similar solution might work here.

**Comment by danieldickison** [comment]
It looks like a similar issue was previously fixed in ConcurrentLinkedQueue e.g. in https://github.com/google/j2objc/commit/db259
Perhaps a similar solution would work here.

**Comment by kstanger** [comment]
Both [LinkedBlockingQueue](https://github.com/google/j2objc/commit/4a1f9091d98a553cf5fc1aea32c6cf3121c311a2) and [ScheduledFutureTask](https://github.com/google/j2objc/commit/e9d868b1ea65aed0e6df852cc08c77b02d7a17fb) are fixed in current source.
