### ISSUE TITLE
Crash on formatWithId: for locale with AF region

### ISSUE THREAD

**Issue by chezzdev** [google/j2objc#774]
Hello everybody!
I have a problem with this simple snippet.

```objc
jlong timestamp = 1234;

JavaUtilLocale *locale = new_JavaUtilLocale_initWithNSString_withNSString_(@"en", @"AF");
JavaTextDateFormat *dateFormat_ = JavaTextDateFormat_getDateInstanceWithInt_withJavaUtilLocale_(JavaTextDateFormat_MEDIUM, locale);

NSString *result = [dateFormat_ formatWithId:JavaLangLong_valueOfWithLong_(timestamp)];
```

This code crashes in the last line, `formatWithId:` method. The trigger for the crash is `AF` region in locale initialization.

Stack trace is:

```objc
2016-08-02 14:01:23.918 myApp[46264:2979550] *** Terminating app due to uncaught exception 'JavaLangArrayIndexOutOfBoundsException', reason: 'index out of range: 1 for array containing 1 elements'
*** First throw call stack:
(
	0   CoreFoundation                     0x01e57494 __exceptionPreprocess + 180
	1   libobjc.A.dylib                    0x0190fe02 objc_exception_throw + 50
	2   myApp                              0x004657b5 -[IOSArray descriptionOfElementAtIndex:] + 0
	3   myApp                              0x0018e810 JavaTextSimpleDateFormat_appendWithJavaLangStringBuffer_withJavaTextFieldPosition_withJavaUtilList_withChar_withInt_ + 1850
	4   myApp                              0x0018e091 JavaTextSimpleDateFormat_formatImplWithJavaUtilDate_withJavaLangStringBuffer_withJavaTextFieldPosition_withJavaUtilList_ + 615
	5   myApp                              0x0018f235 -[JavaTextSimpleDateFormat formatWithJavaUtilDate:withJavaLangStringBuffer:withJavaTextFieldPosition:] + 39
	6   myApp                              0x0017f857 -[JavaTextDateFormat formatWithId:withJavaLangStringBuffer:withJavaTextFieldPosition:] + 305
	7   myApp                              0x00185b68 JavaTextFormat_formatWithId_ + 72
	8   myApp                              0x00185b1b -[JavaTextFormat formatWithId:] + 17
    ...
)
libc++abi.dylib: terminating with uncaught exception of type JavaLangArrayIndexOutOfBoundsException
```

Please consider the issue. It is quite critical for Afghanistan users.
Thanks in advance.

**Comment by tomball** [comment]
I agree we need to fix the ArrayIndexOutOfBoundsException, but what are you trying to do here? When your example runs in a Java VM, the result is "Dec 31, 1969". Although I'm not an expert in internationalization, I suspect that is because [Java doesn't support Afghanistan locales](http://www.oracle.com/technetwork/java/javase/java8locales-2095355.html). So even after we fix the thrown exception, you probably won't get the formatted string you want.

However, NSDateFormatter appears to work (it outputs "Dey 10, 1348 AP" instead of "Dec 31, 1969"):

```
  NSDate *date = [NSDate dateWithTimeIntervalSince1970:1.234];
  NSDateFormatter *dateFormatter = [[NSDateFormatter alloc] init];
  dateFormatter.dateStyle = NSDateFormatterMediumStyle;
  dateFormatter.timeStyle = NSDateFormatterNoStyle;
  dateFormatter.locale = [[NSLocale alloc] initWithLocaleIdentifier:@"en_AF"];
  result = [dateFormatter stringFromDate:date];
  NSLog(@"result: %@", result];
```

**Comment by chezzdev** [comment]
Thanks for the future fix, Tom. 
What I'm trying to do is to translate Java code into Objective-C code. I'm using this snippet (well, more complex version of it) in cross-platform logic and expecting it to work as similar as possible in both (Java and ObjC) cases. 
However thank you for noting about absence of Afghanistan locale in Java I will consider revising date formatting logic.

**Comment by tomball** [comment]
Fixed in current source.

**Comment by zubchenok** [comment]
@tomball 
Do you have any idea when will fix of this issue be released?
We actually have a critical case about it.
Thank you
