### ISSUE TITLE
dealloc without [super dealloc]

### ISSUE THREAD

**Issue by jaspervp** [google/j2objc#778]
J2objc creates a dealloc method without  [super dealloc] when transpiling a class with a volatile object. This causes problem when trying to compile the class.

For example:
`
public class Something {
    volatile Object a;
}
`

has the method:

`- (void)dealloc {
  JreReleaseVolatile(&a_);
}`

**Comment by kstanger** [comment]
Are you using the `-use-arc` flag when running j2objc? With `-use-arc` the `[super dealloc]` statements are removed because they are a compile error with ARC.
