### ISSUE TITLE
j2obc fails when classpath jars contains annotation processors

### ISSUE THREAD

**Issue by phobe77** [google/j2objc#779]
The conversion from java to objc code fails in the following situation with a 'misleading' error message.

> j2objc -x objective-c  -sourcepath </some/path> -classpath <jar containing APT> foo/bar/Hello
> File foo/bar/Hello.java is missing

While prefixing the absolute path to the sources compiles fine:

> j2objc -x objective-c  -sourcepath </some/path> -classpath <jar containing APT> \ /some/path/foo/bar/Hello

Some initial debugging shows that the challenge most likely is somewhere in the eclipse code. The j2objc original parts work fine in either situation.

Any thoughts?

**Comment by tdavis** [comment]
Just hit this too. Also works if you run the command from the source root, though not helpful when using Maven. I guess in the meantime I need to tweak the maven plugin to output the absolute path for every file.

**Comment by tomball** [comment]
I cannot reproduce this on the command line. The Eclipse comment has me wondering whether this was an issue when j2objc used Eclipse's Java compiler as its front end, so perhaps this was fixed when we switched to using javac instead.

**Comment by tdavis** [comment]
I love seeing these old issues get action, like, wow, you're really on the ... *sigh* ... ball. I'm sorry, that's not a dig, I just had to say it. I have only the vaguest of recollection of this issue, but I do recall learning far more than I wanted to know about the EJC. Honestly, `j2objc` was a legit badass project when I needed it and I thank you for the continued support!
