### ISSUE TITLE
Add Prefixes to Category Methods on NSObject

### ISSUE THREAD

**Issue by efirestone** [google/j2objc#785]
We recently ran into an issue where `+[NSObject getClass]` provided by the `NSObject (JavaObject)` category was getting called unintentionally from our non-J2ObjC code. The single shared namespacing in Objective-C means that category methods are available to all code in the memory space, and with a category on NSObject, it means it applies to all Objective-C objects.

[Apple recommends prefixing methods](https://developer.apple.com/library/ios/documentation/Cocoa/Conceptual/ProgrammingWithObjectiveC/CustomizingExistingClasses/CustomizingExistingClasses.html#//apple_ref/doc/uid/TP40011210-CH6-SW4) that you add in a category [[more here](http://nshipster.com/namespacing/)], and that would solve this issue as well. For example, changing `+[NSObject getClass]` to `+[NSObject java_getClass]` or `+[NSObject J2OBJC_getClass]`.

This is most important for the `NSObject` category, but applies equally well to any category provided by J2ObjC.

**Comment by tomball** [comment]
Sounds reasonable. My vote is for "java_" prefixes, since it's more obvious why the method is necessary. I can imagine more "why are there j2objc methods in this category?" whining than "why are there java methods in this category?" :-)

**Comment by efirestone** [comment]
Thanks @tomball, working on a fix now. It looks like `finalize` has actually already been renamed to `javaFinalize` so I'll go with that pattern (`javaClone`, `javaGetClass`, etc) unless you would prefer we switch to something else (at which point I can change `javaFinalize` as well).

**Comment by tomball** [comment]
That sounds great, thanks!

**Comment by tomball** [comment]
All NSObject+JavaObject methods now have java_ prefixes, as do the ones in the other jre_emul categories.
