### ISSUE TITLE
JRE missing sun.misc.Unsafe.copyMemory

### ISSUE THREAD

**Issue by guyshefner** [google/j2objc#786]
When attempting to translate the java source for the proto3 runtime, the following errors occur:

error: com/google/protobuf/UnsafeUtil.java:78: The method copyMemory(byte[], long, byte[], long, long) is undefined for the type Unsafe
error: com/google/protobuf/UnsafeUtil.java:98: The method copyMemory(long, long, long) is undefined for the type Unsafe

It seems the j2objc JRE emulation of sun.misc.Unsafe is missing an implementation of copyMemory.

j2objc version is 1.1.
protobuf sources are from protobuf-java-3.0.0-sources.jar.

**Comment by tomball** [comment]
It's easy to add these methods to [Unsafe.java](https://github.com/google/j2objc/blob/master/jre_emul/Classes/sun/misc/Unsafe.java), and [pull contributions are cheerfully accepted](http://j2objc.org/docs/Contributing.html).  I realize this is important to your project, but the priority of this API addition has to be lower than our current effort to bring jre_emul up to the Java 8 API. We can certainly get to these methods once that's done.

Besides, those Google proto3 engineers shouldn't be using sun.misc.Unsafe, as javac tells them not to with each build. :-)

**Comment by kstanger** [comment]
[copyMemory(long, long, long) added here](https://github.com/google/j2objc/commit/79ba81cc3e261e59c49650088884abed4a9e2ac7).
[copyMemory(Object, long, Object, long, long) added here](https://github.com/google/j2objc/commit/8cf644e459e59e615608147f94d14870d29d4061).
