### ISSUE TITLE
Apple reject non-public APIs: readFloat, readByte, readLong, readInt

### ISSUE THREAD

**Issue by dzungpv** [google/j2objc#792]
I submit an update version and Apple rejected it:

"Performance - 2.5.1
Your app uses or references the following non-public APIs:
readFloat, readByte, readLong, readInt
The use of non-public APIs is not permitted on the App Store because it can lead to a poor user experience should these APIs change."

**Comment by tomball** [comment]
Do you have more information from the rejection? There are "readFloat", "readByte", "readLong" or "readInt" function references, and the only methods defined with those names  in J2ObjC's libraries are defined by the following Java classes (and therefore not part of any Apple API, public or non-public):

* java.io.DataInput
* java.io.DataInputStream
* java.io.ObjectInputStream
* java.io.RandomAccessFile
* java.sql.SQLInput
* libcore.io.BufferIterator
* libcore.io.HeapBufferIterator
* okio.Buffer
* okio.BufferedSource
* okio.RealBufferedSource

These are common function names -- could they be defined in your app's code or another library it references?

**Comment by dzungpv** [comment]
It is from J2ObjC generated code (from java code), i have check it by "strings" command with final ipa file, many "readByte" and some other. They said like i copy above include the guide to check binary for those function. The app affect has been published more than 1 year ago, but Apple always change their mind, and this time they rejected it.

**Comment by tomball** [comment]
I think Apple's automated API tester made a mistake, and you should request a personal explanation (which is likely to get your app validated). Apple does not claim ownership of common method names in unrelated classes, unless those method override unpublished methods in Apple-authored classes. J2ObjC generates translated classes that all extend NSObject, and it doesn't have any private methods. 

But if you don't want to respectfully stand up for yourself with Apple, you have another solution: add these method names (and any others your heart desires) into NameTable's reservedNames list, rebuild j2objc and its libraries, then rebuild your app. Every reservedName gets an underscore appended to it, so it doesn't conflict with similar system names.

**Comment by dzungpv** [comment]
I do following your guide but can not build it. I add this to end of reservedNames list:
`, "readFloat", "readInt", "readLong", "readByte"`
Error:
`compiling /Volumes/MData/j2objc/jre_emul/build_result/Classes/java/lang/StringBuilder.m
/Volumes/MData/j2objc/jre_emul/build_result/Classes/java/lang/StringBuilder.m:283:23: error: instance method '-readInt' not
      found (return type defaults to 'id') [-Werror,-Wobjc-method-access]
  jint count = [inArg readInt];
                      ^~~~~~~
/Volumes/MData/j2objc/jre_emul/build_result/Classes/java/io/ObjectInputStream.h:48:12: note: receiver is instance of class
      declared here
@interface JavaIoObjectInputStream : JavaIoInputStream < JavaIoObjectInput, JavaIoObjectStreamConstants >
           ^
/Volumes/MData/j2objc/jre_emul/build_result/Classes/java/lang/StringBuilder.m:283:8: error: incompatible pointer to integer
      conversion initializing 'jint' (aka 'int') with an expression of type 'id' [-Werror,-Wint-conversion]
  jint count = [inArg readInt];
       ^       ~~~~~~~~~~~~~~~
2 errors generated.`

**Comment by tomball** [comment]
Change "readInt" to "readInt_" in StringBuilder.m -- it's proof that the
method name changed the way you wanted.
