### ISSUE TITLE
unrecognized selector crash upon calling interface's method which is implemented in super class

### ISSUE THREAD

**Issue by chainans** [google/j2objc#793]
I run into a runtime issue which I have narrowed to the following case. I can run the JMain.bar() without an issue with Java but, with translated code, I got below error when I run translated code.
'-[A fooWithD:]: unrecognized selector sent to instance 0x7fc924a2cf00'

Here [Archive.zip](https://github.com/google/j2objc/files/478325/Archive.zip) is all source files with translated .h & .m files.

A.java
```
class A extends B implements C<B> {
}
```

B.java
```
class B extends D {
  public void foo(B b) {
    // Do something
    System.out.println("B:foo");
  }
}
```

C.java
```
interface C<T extends D> {
  public void foo(T d);
}
```

D.java
```
class D {
}
```

JMain.java
```
public class JMain {
  public static <T extends D, U extends C> void bar() {
    T d = (T)(new B());
    U a = (U)(new A());
    a.foo(d);
  }
}
```

Here is crashed code in JMain.m
```
void JMain_bar() {
  JMain_initialize();
  D *d = (create_B_init());
  id<C> a = (create_A_init());
  [a fooWithD:d];
}
```
Calling fooWithD: causes problem because there is only fooWithB: implemented in B (A's superclass)

**Comment by kstanger** [comment]
Thanks for the full (and condensed) example! I'll see what I can do. In the meantime, if you add a foo implementation in class A, you should be able to get by.

class A extends B implements C<B> {
  public void foo(B b) {
    super.foo(b);
  }
}

**Comment by kstanger** [comment]
Fixed in [current source](https://github.com/google/j2objc/commit/538ef42ec3457cb97f636638320d6593da6aaa9f).
