### ISSUE TITLE
`description` on NSException prints 'java.lang.Throwable'

### ISSUE THREAD

**Issue by mdiiorio** [google/j2objc#794]
We recently integrated J2ObjC into our existing Objective-C project. We're now seeing 'java.langThrowable' printed even for exceptions that have nothing to do with J2ObjC code. For example,

```
    NSLog(@"%@", [NSException exceptionWithName:@"foo" reason:@"bar" userInfo:nil]);
```

will print

```
java.lang.Throwable: bar
```

Looking through the code it appears the overridden `description` method in `NSException+JavaThrowable.m` is responsible for this.

It looks like `description` could be changed so that it only prints the class name if it's a Java-created exception, which would fix this issue. But from what I understand, overriding methods in categories is bad practice, so might there be another way to fix this that involves removing the overridden `description` method altogether?

**Comment by tomball** [comment]
I like your idea of moving this to Java-created exceptions, where those constructors can prepend the class name to the description string. It won't work for native code calling [[SomeJavaException alloc] init], but they'll still get the right stack trace.

**Comment by mdiiorio** [comment]
Ok, let me take a look and see what I can come up with.

**Comment by tomball** [comment]
No need, I have a fix pending review. Thanks for offering to help!

**Comment by mdiiorio** [comment]
Great, thanks!

**Comment by tomball** [comment]
Fixed in current source.
