### ISSUE TITLE
Undefined symbols for architecture x86_64: "_OBJC_CLASS_$_

### ISSUE THREAD

**Issue by tjerkw** [google/j2objc#796]
So I transpiled my .java code to objective c.
Then i added all those files to my project (just copy pasted them)
I updated the build to link the right libraries.
But now trying to build the project with an import from this shared code i get:

>>>
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_TWalletDataWalletOrder", referenced from:
      objc-class-ref in AppDelegate.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I dont really understand whats going on.
Note: Its a clean ios project. Noe ios code written yet.
I dont use Cocoa Pods.

Any tips on what todo?

**Comment by tomball** [comment]
Xcode only builds what you say it should, so my guess is that the target's Compile step doesn't include those copied files in its compile list. To fix this, select the target (normally your app), then select the Build Phases panel and open the Compile Sources step, then click the + button and add them (that list should include all sources needed to build the app).

To add new files in the future and repeating this manual compile list updating, right click on a project folder, click "Add Files to <project-name>...", select the file(s), **click the Options button** and select the target, then click Add.

**Comment by vsguji** [comment]
ok,thank you

**Comment by 1170197998** [comment]
very good

**Comment by AbdoElabd** [comment]
ignoring file /Users/abdelrahmanelabd/Desktop/DEMOOFNATIVE/Pods/PPBlinkID/MicroBlink.framework/MicroBlink, file was built for unsupported file format ( 0x76 0x65 0x72 0x73 0x69 0x6F 0x6E 0x20 0x68 0x74 0x74 0x70 0x73 0x3A 0x2F 0x2F ) which is not the architecture being linked (x86_64): /Users/abdelrahmanelabd/Desktop/DEMOOFNATIVE/Pods/PPBlinkID/MicroBlink.framework/MicroBlink
