### ISSUE TITLE
Translated Guava Hashing implementation returns different values when called successively

### ISSUE THREAD

**Issue by safetydank** [google/j2objc#797]
I've found this method returns different values when called successively, using j2objc v1.1. The same method returns consistent values in Java (tested on Android).

public static String testHash(String input) {
        byte[] bytes = input.getBytes("UTF-8");
        return Hashing.sha1().hashBytes(bytes).toString();
}

assert(testHash("foo").equals(testHash("foo")) == true);

**Comment by tomball** [comment]
I'm away from my desk until Monday, but reviewing the code I think I see the problem. In [IosSHAMessageDigest.java, line 66](https://github.com/google/j2objc/blob/master/jre_emul/Classes/com/google/j2objc/security/IosSHAMessageDigest.java#L66), the initial digest buffer is declared on the stack but not cleared, so its initial values are likely to differ between invocations (depending on what was previously on the stack). 

If you have a local j2objc build and have time to experiment, try adding a memset() call after the digest declaration and before the CC_SHA1() call:

    protected native byte[] engineDigest() /*-[
      IOSByteArray *bytes = [buffer_ toByteArray];
      unsigned char digest[CC_SHA1_DIGEST_LENGTH];
      memset(digest, 0, CC_SHA1_DIGEST_LENGTH);  // Add this line.
      CC_SHA1(bytes->buffer_, bytes->size_, digest);
      return [IOSByteArray arrayWithBytes:(jbyte *)digest count:CC_SHA1_DIGEST_LENGTH];
    ]-*/;

**Comment by safetydank** [comment]
Thanks for looking into this. I won't have time today but will update here if I get a chance to try the fix.

**Comment by tomball** [comment]
The `memset()` call wasn't necessary. The issue turns out to be an incomplete clone() method in IosSHAMessageDigest, which com.google.common.hash uses but not our unit tests.

**Comment by tomball** [comment]
Fixed in [current source](https://github.com/google/j2objc/commit/e4fbaac7c5ed23f22357ea017ce461ebbc178ff9).
