### ISSUE TITLE
Unsafe should throw exception when creating an interface or abstract class

### ISSUE THREAD

**Issue by kpgalligan** [google/j2objc#801]
Found during gson unit tests:

https://github.com/google/gson/blob/master/gson/src/test/java/com/google/gson/internal/UnsafeAllocatorInstantiationTest.java

Creating an interface or abstract class with Unsafe should throw an exception.  I had put in a simple check a while ago directly into Unsafe in an earlier version

https://github.com/doppllib/j2objc/commit/4c4bcf98b098b8c85d73faa396f3470349f799c3#diff-604e876f4e2566614eaca7cb1d389697

I'm reluctant to similarly hack the newer jni version. I'm just going to comment out the gson tests for now, to be honest. However, it points at a deeper issue, which is [c.objcClass alloc] can create a "viable" instance of an interface or abstract class.

https://github.com/google/j2objc/blob/master/jre_emul/android/libcore/luni/src/main/native/sun_misc_Unsafe.m#L82

Probably not the highest priority, but seems like an issue.

**Comment by tomball** [comment]
Your approach looks correct, so I'll update our latest with your fix.

**Comment by tomball** [comment]
I found Android's sun_misc_Unsafe.allocateInstance() just returned the value returned from the JNI AllocObject() function. J2ObjC didn't have that function, so I added it plus your checks and changed Unsafe to call it. It's out for review, so we'll see what Keith thinks. :-)

**Comment by tomball** [comment]
Fixed in current source.
