### ISSUE TITLE
AtomicLong (and probably others) extend NSNumber but don't implement objCType

### ISSUE THREAD

**Issue by kpgalligan** [google/j2objc#807]
I don't have my head around this 100%, but as I understand things, if extended from NSNumber, objCType needs to be defined. I don't know if that's all that needs to be defined, but that does seem to blow up when calling hashCode() on AtomicLong. Not sure what it should return, although I guess whatever Long returns is probably a safe bet. Running some tests now.

**Comment by tomball** [comment]
Good catch! You're right that the same type characters should be used, so I'll update the atomic Number subclasses today, and Keith (our atomics expert) will review early next week.

**Comment by kpgalligan** [comment]
Ah, good! Wish I had run into it by calling hashCode on an AtomicLong. Was trying to figure out intermittent errors on an rxjava test, that calls hashCode on an internal rxjava class, which extends AtomicLong, but only if one thread beats another in an internal structure. Error message seems obvious in retrospect, as they all do.
