### ISSUE TITLE
Add support for java.sql package [moved]

### ISSUE THREAD

**Issue by kstanger** [google/j2objc#81]
This is [Issue 81](https://code.google.com/p/j2objc/issues/detail?id=81) moved from a Google Code project.
Added on 2012-11-01T14:21:03.000Z by [ravisrid...@gmail.com](http://code.google.comhttps://code.google.com/u/103852707011212282246/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Low

**Comment by Navideck-fotis** [comment]
Isn't java.sql supported now?

**Comment by tomball** [comment]
Yes it is, thanks for noticing so I can close this bug. :-)
