### ISSUE TITLE
issue in decimal format

### ISSUE THREAD

**Issue by rammuralidhar** [google/j2objc#811]
If you run the java code:
float floatValue = new DecimalFormat("0.0#%").parse("12.0%").floatValue();

It produces 0.12.

j2Objc:
jfloat floatValue = [((NSNumber *) nil_chk([new_JavaTextDecimalFormat_initWithNSString_(@"0.0#%") parseWithNSString:"12%"])) floatValue];
 produces 12.

**Comment by ashitikov** [comment]
try

```objc
jfloat floatValue = [((NSNumber *) nil_chk([new_JavaTextDecimalFormat_initWithNSString_(@"0.0#%") parseWithNSString:"12.0%"])) floatValue];
```

If it will produce 0.12 then the problem in translation part. It's strange that string "12.0%" became "12%"

**Comment by tomball** [comment]
Thanks for the feedback, as it will make this that much quicker to fix.

**Comment by rammuralidhar** [comment]
It is typo. It is not problem in translation..
 
float floatValue = new DecimalFormat("0.0#%").parse("12.0%").floatValue();

jfloat floatValue = [((NSNumber *) nil_chk([new_JavaTextDecimalFormat_initWithNSString_(@"0.0#%") parseWithNSString:"12.0%"])) floatValue];

**Comment by tomball** [comment]
I found the real problem: NSNumberFormatter ignores its percentage style
when parsing. I have a fix pending review.

**Comment by tomball** [comment]
Fixed in current source.
