### ISSUE TITLE
Problem in generation of class with package com.google.android

### ISSUE THREAD

**Issue by rammuralidhar** [google/j2objc#813]
If we have class 
package com.google.android;
public class A {
}

package com.google.android;
public class B {
	A a;
}

Generated B.m has wrong inclusion of A.h
#include "B.h"
#include "J2ObjC_source.h"
#include "com/google/android/A.h"

Note:  I have used generate output directories to specific directory without sub-directory.

**Comment by kstanger** [comment]
The package prefix "com.google.android" is specifically whitelisted because our JRE emulation ships some classes with this prefix.
Why are you using this package in your sources?

**Comment by rammuralidhar** [comment]
I face this problem when I try to migrate third party libraries.  If any library classes starts with android. or com.google.android, I get this problem.. I could work around by using com.google package or r.com.google package. But I need to run repackaging on the third party library and repackage all the references associated with it.. Is there a way to force the j2objc compiler to properly generate the reference to the class..

**Comment by kstanger** [comment]
Since the com.google.android sources in our JRE are all internal we may be able to remove this package prefix from the whitelist. @tomball do you see any consequence to making this change?

**Comment by tomball** [comment]
It should be okay, since none of the classes have duplicated names in other
packages.

**Comment by kstanger** [comment]
Fixed in current source.
