### ISSUE TITLE
Reflection method's isBridge() is missing

### ISSUE THREAD

**Issue by chainans** [google/j2objc#814]
When trying to translate jackson-databind library, I encountered 

AnnotatedClass.java:856: The method isBridge() is undefined for the type Method

Seem like it was removed earlier in https://github.com/google/j2objc/commit/ef45e04815a635f663b7f551635a3c96ff5d6df1 as I was able to translate without issue a month ago.

**Comment by tomball** [comment]
Java 8 added a public Executable class as the superclass to Method and Constructor, and it looks like when it was implemented we dropped this method. We'll put it back first thing next week.

**Comment by chainans** [comment]
Great, thanks for help.

**Comment by tomball** [comment]
Fixed in current source.
