### ISSUE TITLE
Exception in Using Guava EventBus in Swift application

### ISSUE THREAD

**Issue by MyCADDev** [google/j2objc#818]
Hi,
I am using the Guava EventBus in Swift (via Bridging Header). I am registering an object of Subscriber (written in Java and brought into Swift via bridging header). I am getting an Exception with this call stack. Is there something I am doing wrong or is this not expected to work.

thanks
Harish

#0	0x00000001023aa1ee in objc_exception_throw ()
#1	0x0000000100ad0548 in JreParseClassList ()
#2	0x0000000100ac7d58 in -[JavaLangReflectExecutable getParameterTypesInternal] ()
#3	0x0000000100ac7db7 in -[JavaLangReflectExecutable getParameterTypes] ()
#4	0x0000000100cac98d in ComGoogleCommonEventbusSubscriberRegistry_getAnnotatedMethodsNotCachedWithIOSClass_ ()
#5	0x0000000100cad6ad in -[ComGoogleCommonEventbusSubscriberRegistry_$1 load__WithId:] ()
#6	0x0000000100b3bce4 in -[ComGoogleCommonCacheLocalCache_LoadingValueReference loadFutureWithId:withComGoogleCommonCacheCacheLoader:] ()
#7	0x0000000100b31420 in -[ComGoogleCommonCacheLocalCache_Segment loadSyncWithId:withInt:withComGoogleCommonCacheLocalCache_LoadingValueReference:withComGoogleCommonCacheCacheLoader:] ()
#8	0x0000000100b30d39 in -[ComGoogleCommonCacheLocalCache_Segment lockedGetOrLoadWithId:withInt:withComGoogleCommonCacheCacheLoader:] ()
#9	0x0000000100b2fe7e in -[ComGoogleCommonCacheLocalCache_Segment getWithId:withInt:withComGoogleCommonCacheCacheLoader:] ()
#10	0x0000000100b22e1d in -[ComGoogleCommonCacheLocalCache getWithId:withComGoogleCommonCacheCacheLoader:] ()
#11	0x0000000100b22e75 in -[ComGoogleCommonCacheLocalCache getOrLoadWithId:] ()
#12	0x0000000100b43d4c in -[ComGoogleCommonCacheLocalCache_LocalLoadingCache getWithId:] ()
#13	0x0000000100b43d88 in -[ComGoogleCommonCacheLocalCache_LocalLoadingCache getUncheckedWithId:] ()
#14	0x0000000100cac583 in ComGoogleCommonEventbusSubscriberRegistry_getAnnotatedMethodsWithIOSClass_ ()
#15	0x0000000100cab761 in ComGoogleCommonEventbusSubscriberRegistry_findAllSubscribersWithId_ ()
#16	0x0000000100cab2f1 in -[ComGoogleCommonEventbusSubscriberRegistry register__WithId:] ()
#17	0x0000000100ca7fac in -[ComGoogleCommonEventbusEventBus register__WithId:] ()
#18	0x000000010073c6b8 in BaseCommand.onStart() -> () at

**Comment by MyCADDev** [comment]
To clarify - the Java Subscriber class has a @Subscribe annotation for a member function. I feel that the Objective C translation of this class is not correctly exposing this method to the registry.

**Comment by tomball** [comment]
Correct annotation support is easy to verify. For the method:
```
@Subscribe
public void handleEvent(Object event) {
    events.add(event);
}
```
look in the generated .m file to find a class method with the name "__annotations_" + the translated method name. For the above, that is:
```
+ (IOSObjectArray *)__annotations_handleEventWithId_ {
  return [IOSObjectArray arrayWithObjects:(id[]){ create_ComGoogleCommonEventbusSubscribe() } count:1 type:JavaLangAnnotationAnnotation_class_()];
}
```
When the runtime needs to fetch the annotation for that method, it just calls that method and returns the array it creates. For this example, that's an array of Annotations, which contains a single Subscribe annotation. 

 I suspect the problem is with `Method.getParameterTypes()`, which is called by `SubscriberRegistry. getAnnotatedMethodsNotCached()`. Do you have a small test that demonstrates this problem?

**Comment by tomball** [comment]
I'll need an example that reproduces this problem, as Guava's SubscriberRegistryTest's tests passed.

**Comment by MyCADDev** [comment]
Thanks for the note @tomball 

I do not see the function __annotations_ in my translated class. Instead I see a different function returning the IOSObjectArray.

I am using j2objc-1.0.2. I will create a small test project to recreate this behavior.

My Java class and translation function is below.

public class AppEventRecorder {
    protected AppEventConsumer eventConsumer;

    public AppEventRecorder() {

    }

    public AppEventRecorder(AppEventConsumer eventConsumer) {
        this.setAppEventConsumer(eventConsumer);
    }

    public void setAppEventConsumer(AppEventConsumer eventConsumer) {
        this.eventConsumer = eventConsumer;
    }

    @Subscribe
    public void eventChange(AppEventData appEventData) {
        eventConsumer.onEvent(appEventData);
    }

}

IOSObjectArray *NDDocumentCreateRecorder__Annotations$0() {
  return [IOSObjectArray newArrayWithObjects:(id[]){ create_ComGoogleCommonEventbusSubscribe() } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

**Comment by tomball** [comment]
Unless your real Java class name is NDDocumentCreateRecorder without a
package declaration, you're using package prefixes to shorten the real
package name. That's fine, but at runtime the reflection support can't find
those classes without help. As described in last section of the Package
Prefixes doc <http://j2objc.org/docs/Package-Prefixes.html>, you need to
include a prefixes.properties file as an iOS resource to your app.

If that's the issue and this fixes it, please close this issue. Otherwise,
we'll need that test project.

**Comment by MyCADDev** [comment]
Its not the Package Prefix because In Swift I use the class name with Prefix. Its something else in my build config. 

The below unit test works when I made a separate project with just 4 Java Classes bring them into swift with Bridging headers. Note my package Prefix is "ML" in the below code (ML stands for com.example.mylib)

I will close this issue. Thanks for your help. I will update this issue when I find the real problem.

```
class TestAppTests: XCTestCase {
    var status: Bool = false
    
    class TestEventConsumer : MLAppEventConsumer {
        var testAppTests: TestAppTests
        
        init(testAppTests: TestAppTests) {
            self.testAppTests = testAppTests
            super.init()
        }
        
        override func onEvent(with appEventData: MLAppEventData) {
            self.testAppTests.status = true
        }
    }
    
    class TestEventData : MLAppEventData {
        init(type : MLAppEventType) {
            super.init(mlAppEventType: type)
        }
    }
    
    func testExample() {
        let eventBus: ComGoogleCommonEventbusEventBus = ComGoogleCommonEventbusEventBus(nsString: "XCTestCase")
        
        let appEventRecorder: MLAppEventRecorder = MLAppEventRecorder(mlAppEventConsumer: TestEventConsumer(testAppTests: self))

        eventBus.register__(withId: appEventRecorder)
        
        eventBus.post(withId: TestEventData(type: MLAppEventType.window_RESIZE_()))
        
        XCTAssertTrue(self.status, "expected status to be true")
    }
}
```

**Comment by MyCADDev** [comment]
OK I debugged this further. I linked the debug version of j2objc and could stop the debugger at the exact line which fails. Its a case of "IOSClass classForIosName:name" returning nil for one a class named NDAppEventData.

I have the prefixes for entire library with wild card. I also added the same prefix file into the XCode project.

The funny thing is the classForIosName fails for NDAppEventData but works for NDDocument

Both classes belong to same library. The failing class is below 

```
package com.xxx.yyy.core.events;

abstract public class   AppEventData {
    abstract public void accept(AppEventVisitor v);
}
```

The package prefix is 
```
com.xxx.yyy.*: ND
```

I will continue to debug this.

**Comment by MyCADDev** [comment]
Finally got to the bottom of this. 

I am in the initial stages of coding the application and had not yet created an object of the type NDAppEventData. So the RunTime did not know about that class. I assumed that the runtime knew about all the classes at startup.

After I created derived types of NDAppEventData in my application everything works as expected.

Thanks for the help.

**Comment by tomball** [comment]
That makes sense, as j2objc's runtime is based on the Objective C runtime, which delays class initialization until a message is sent to it. Creating an instance of a subtype will cause the subtype and its supertypes to be loaded. The j2objc runtime iterates through the list of all classes returned by the Objective C runtime, so while those classes were linked into the app, if they haven't been loaded they won't be part of the classes list.
