### ISSUE TITLE
Large number of generic parameters on interface/class causes transpiler to slow to a crawl

### ISSUE THREAD

**Issue by phobe77** [google/j2objc#823]
Hi,

ran into the following issue: when adding classes/interfaces with a large number (e.g. ~15) generic parameters explodes transpilation time... Going from 10 seconds before to 55 MINUTES after. A little bit of investigating and profiling shows that the slow down is in eclipse's JDT code that had a similar issue way back when... 

[https://bugs.eclipse.org/bugs/show_bug.cgi?id=434326](url) 

Which they fixed in 4.5 and back-ported to 4.4.

The j2objc source shows we are using:
    org.eclipse.jdt.compiler.apt-1.1.0.v20140509-1235.jar
    org.eclipse.jdt.core-3.10.0.v20140604-1726.jar

Which look to be from before the patches were applied, but not sure how eclipse numbering scheme works.

Are we using the JDT from a few Eclipse major releases ago? In which case i believe we should look at upgrading those, if not i will do some more debugging to see why we trigger this issue.

-- 
Michel

**Comment by tomball** [comment]
Yes, we're using an older Eclipse, but no, we won't be updating to a newer
version since the very latest still has Java 8 bugs. We've been instead
converting to use javac as our front-end, and hope to be done in a month or
so. It's definitely not been a trivial conversion, but we're excited to
have fewer front-end bugs, slightly better performance, and a jump on Java
9 when it releases next year.

**Comment by phobe77** [comment]
Thanks Tom for the swift reply. I don't think there is anything i can do to help you on that one?

As an FYI a similar issue still exists in Eclipse which gives me a good incentive to final put some effort into moving away from Eclipse.

-- 
Michel

**Comment by tomball** [comment]
The javac front-end is almost ready for extended testing (hopefully before
the end of the month), and we'd appreciate developers to check it out then
before it becomes the default. However, here's almost 100 unit test
failures to clean up first, and then the jre_emul and Guava builds are
likely to find other issues. Once those all pass, we'll send out an appeal
for test help, so developers with complex projects like yours can try
building with it.

**Comment by tomball** [comment]
The javac front-end is now the default in the current source (not in the 1.3.1 release, though). Would you please try building your project with the latest?
