### ISSUE TITLE
Missing type cast for narrowed generic method return type

### ISSUE THREAD

**Issue by danieldickison** [google/j2objc#828]
As of 1.3 there's a missing type cast when calling a subclass/interface method where the return type has been narrowed by the subclass, and narrowed even further by the current method context. For example:

```java
interface Foo<A> { A foo(); }
interface Bar<B extends Number> extends Foo<B> { }
Integer test(Bar<Integer> bar) { return bar.foo(); } }
```

Produces:

```objc
return [((id<Test_Bar>) nil_chk(bar)) call];
```

The method body for `test` should cast the return type to `JavaLangInteger`. The type cast exists in 1.2 but not in 1.3, causing a warning from the objc compiler.

Here is a test case: https://github.com/bandcampdotcom/j2objc/commit/874144e7f4a5b1736d7e44ed15d4af85cbc9cb0b

**Comment by kstanger** [comment]
Thanks for the bug report and the test case. I've got a fix ready and should be able to push it later today.

**Comment by kstanger** [comment]
Fixed in current source. We're considering doing a 1.3.1 release next week to include this fix.
