### ISSUE TITLE
Release 1.3.1 Missing Support

### ISSUE THREAD

**Issue by andrewbrandt** [google/j2objc#829]
When I move from 1.1 to 1.3.1, I get lots of "Pointer is missing a nullability type specifier ..." for Thread.h in addition to the TimeUnit.h which is described in the release notes as missing.

.../j2objcDist/j2objc-current/include/java/lang/Thread.h:69:4: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]

**Comment by kstanger** [comment]
See Issue #827
