### ISSUE TITLE
Constant boolean expressions cannot be used to initialize constant booleans.

### ISSUE THREAD

**Issue by tomball** [google/j2objc#833]
When a constant boolean is initialized with a constant expression other than "false" or "true", during class initialization an attempt is made to set that constant:
```
public class Test {
  public static final boolean FOO = true && false;
  public static final boolean BAR = true || false;
}
```
Test.h:
```
#define Test_FOO false
#define Test_BAR true
```
Test.m:
```
+ (void)initialize {
  if (self == [Test class]) {
    Test_FOO = false;
    Test_BAR = true;
    J2OBJC_SET_INITIALIZED(Test)
  }
}
```
Compilation errors are reported for the attempts to set the #define'd constants.

**Comment by kstanger** [comment]
Fixed in current source.
