### ISSUE TITLE
getErrorStream() in HttpURLConnection no longer supported.

### ISSUE THREAD

**Issue by alexander-larsson** [google/j2objc#834]
When I switched over to J2ObjC 1.3.1 from a quite old version (1.1) the app I'm working on started to behave very strange when errors was return from the API. Inte the case of errors, we are parsing the byte stream returned from `getErrorStream()` to a String in JSON format and then parsing that to objects using GSON.

The problem seems to be that the stream returned from `getErrorStream()` is always `null` in the latest version of the JRE.framework. How is this case supposed to be handled in our Java code? Is there some other stream we should use?

**Comment by lukhnos** [comment]
A fix is on its way. Meanwhile, if you build from source, you can patch [IosHttpURLConnection.java, lines 621-635](https://github.com/google/j2objc/blob/ba9bd24c7c65ddfaa540e0f834975662874ebc9e/jre_emul/Classes/com/google/j2objc/net/IosHttpURLConnection.java#L621-L635) and replace them with:

```java
if (response.statusCode >= JavaNetHttpURLConnection_HTTP_BAD_REQUEST) {
  JreStrongAssign(&self->errorDataStream_, self->responseBodyStream_);
}
completionHandler(NSURLSessionResponseAllow);
```

**Comment by tomball** [comment]
Fixed in current source.
