### ISSUE TITLE
Compile errors when translating Mockito Answers.h

### ISSUE THREAD

**Issue by gchoza** [google/j2objc#835]
I'm updating a project from j2objc 1.0-2.2 to j2objc 1.3.1. 
Using the latest gradle plugin, JVM 1.8+, mockito-core:2.+. I get the following errors:

In file included from /Users/developer/AndroidStudioProjects/Mobile/shared/build/j2objcSrcGenTest/com/gcatconsult/testBase/SharedConfig.m:21:
/Users/gabrielchoza/SoftwareDev/Mobile/External/j2objc-1.3.1/include/org/mockito/Answers.h:64:4: error: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Werror,-Wnullability-completeness]
- (id<OrgMockitoStubbingAnswer>)get;
   ^
/Users/developer/SoftwareDev/Mobile/External/j2objc-1.3.1/include/org/mockito/Answers.h:66:22: error: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Werror,-Wnullability-completeness]
+ (OrgMockitoAnswers *)valueOfWithNSString:(NSString *)name;
                     ^

What am I missing?

**Comment by tomball** [comment]
You aren't missing anything, it's a bug. Until we fix this, you can work around this in two ways. The first is to turn off this check using the -Wno-nullability-completeness flag. I don't use Gradle, but there should be a way to specify Objective C compiler flags. This turns off the check for all translated files.

You can also edit j2objc-1.3.1/include/org/mockito/Answers.h and make the following changes (just cut and paste):

 1. After the #include "java/lang/Enum.h" line, add the following:
```
#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif
```
2. At the end of the file, add:
```
#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
```
This turns off the check for just this file.

**Comment by gchoza** [comment]
Thanks, you got me past that issue. 
However, although my Java tests passed, my translated tests failed wit HTTP error 400. The server did not get any HTTP requests from the translated code.
I used the latest JDK 1.8.0_121 and I also tried 1.8.0_91 with no luck.
I've reverted for now to my prod version and I'll open a separate issue when I reattempt the upgrade if I cannot figure it out.
Thanks.

**Comment by tomball** [comment]
Fixed in current source.
