### ISSUE TITLE
Translating empty "if" body results in an invalid source

### ISSUE THREAD

**Issue by akarthik10** [google/j2objc#841]
The following statement is legal in Java:
```
if (a > b)
;
```

This is not legal in Objective C, however. The translator produces a source file that results in a compilation error.

**Comment by tomball** [comment]
That statement is also legal in Objective C, it's just a warning the C compiler (clang) emits:

```
hello.m:10:14: error: if statement has empty body [-Werror,-Wempty-body]
  if (a > b) ;
             ^
hello.m:10:14: note: put the semicolon on a separate line to silence this warning
1 error generated.
```

If that statement was illegal, then it wouldn't matter whether there's a space or a line ending (whitespace is just whitespace).

That said, this looks easy to fix -- just generate that statement so it always has a line between the condition and the empty statement.

**Comment by tomball** [comment]
BTW, translating with the -g flag "fixes" this, because it inserts a line directive between the condition and empty statement if they are on different lines in the Java source.

**Comment by tomball** [comment]
Fixed in current source. Translator now detects whether empty statement is on different line from its parent statement, and generates a line-ending if in original source. With this change:
```
    // clang empty-statement warning emitted.
    if (condition) ;

    // clang empty-statement warning suppressed.
    if (condition)
      ;
```
This allows developers to suppress intentional empty statements the same way in Java as it's done in Objective C.
