### ISSUE TITLE
NullPointerException while compiling

### ISSUE THREAD

**Issue by informatimago** [google/j2objc#842]
Hi!

I'm trying to compile the HEAD, using make dist, and it fails with NullPointerExceptions while compiling the jre_emul.

Also, please find attached a patch to the Makefile to detect mktemp GNU vs. BSD instead of Linux vs. Darwin.

I'm working on MacOSX El Capitan, with MacPorts installed and the GNU tools in the PATH, therefore mktemp is GNU mktemp (along as about 120 other GNU commands shadowing Darwin BSD ones).

Also, I have java 1.8 installed:
java version "1.8.0_92"
Java(TM) SE Runtime Environment (build 1.8.0_92-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.92-b14, mixed mode)

[j2objc-mktemp.patch.txt](https://github.com/google/j2objc/files/864971/j2objc-mktemp.patch.txt)
[j2objc.log.txt](https://github.com/google/j2objc/files/864972/j2objc.log.txt)

**Comment by tomball** [comment]
Thanks for the improvement. I've merge your change in, which will get pushed to the public repository after review and testing.
