### ISSUE TITLE
Using @Weak doesn't generate __weak fields in ObjC with ARC

### ISSUE THREAD

**Issue by MohammadHejazi** [google/j2objc#845]
I'm using `@Weak` with a field in java, and passing `-use-arc` to `j2objc`, but the generated field in ObjC is marked with `__unsafe_unretained` not `__weak` as stated in the docs.

Quoting from http://j2objc.org/docs/Memory-Management.html:

>### Weak References
>
>J2ObjC supports the WeakReference class, so Java code that uses it will work the same way when translated. Fields can also be annotated with com.google.devtools.j2objc.Weak, which the transpiler uses to generate fields that follow Objective-C weak reference semantics. When using reference counting, this means that the field is not retained when initialized, and it is autoreleased when the containing instance is released. **With ARC, weak fields are marked with the __weak annotation, and the related properties are declared weak**.

Is the previous statement still valid, or I'm doing something wrong?

**Comment by lukhnos** [comment]
You are doing nothing wrong–`@Weak` has been translated to `__unsafe_unretained` since 5330cd3b3d79bf1872da714606e06aac092f4cdd over a year ago. The doc needs to be updated. :)

**Comment by tomball** [comment]
Updated docs. Thanks for bringing this to our attention.
