### ISSUE TITLE
Problem upgrading from version 1.2 to 1.3.1

### ISSUE THREAD

**Issue by adil-hussain-84** [google/j2objc#848]
I've just tried upgrading from version 1.2 of this library to version 1.3.1 and I'm getting a number of "instance method not found" and "class method not found" warnings for simple Java methods like `String.isEmpty()`, `String.split(String)`, `String(byte[], String)` and `Object.getClass()`.

I'm also getting an "implicit declaration of function" error for the `String.format(String format, Object... args)` which fails the build.

The way I've been doing the translation till now is by means of the following command:

`${J2OBJC_HOME}/j2objc -d ${GENERATED_FILES_DIR} --prefixes ${PREFIXES_PROPERTIES_PATH} --batch-translate-max=40 --no-package-directories --doc-comments -sourcepath ${SHARED_CODE_JAVA_SOURCE_PATH} $SHARED_CODE_JAVA_SOURCE_FILES`

Is this still valid?

**Comment by adil-hussain-84** [comment]
I've managed to get the `j2objc` command to work by adding the `-Xuse-jdt` flag as follows:

`${J2OBJC_HOME}/j2objc -d ${GENERATED_FILES_DIR} --batch-translate-max=40 --prefixes ${PREFIXES_PROPERTIES_PATH} -Xuse-jdt --no-package-directories --doc-comments -sourcepath ${SHARED_CODE_JAVA_SOURCE_PATH} $SHARED_CODE_JAVA_SOURCE_FILES`

Trying now with the `-Xuse-javac` flag...

**Comment by adil-hussain-84** [comment]
... Success! Looks like it's working A-Ok. Is this the recommended way to be doing the translation with version 1.3.1 of the library? i.e.

`${J2OBJC_HOME}/j2objc -d ${GENERATED_FILES_DIR} --prefixes ${PREFIXES_PROPERTIES_PATH} -Xuse-javac --batch-translate-max=40 --no-package-directories --doc-comments -sourcepath ${SHARED_CODE_JAVA_SOURCE_PATH} $SHARED_CODE_JAVA_SOURCE_FILES`

**Comment by kstanger** [comment]
While JDT is the default in 1.3.1. We strongly encourage using Javac with the -Xuse-javac flag. This will become the default in our next release and the JDT parser will be removed some time after that.

**Comment by tomball** [comment]
My guess is that your initial issue was due to generated files from the
previous version failing to link with the new library. Regardless of
platform or project, it's always a good idea when updating a SDK or any
kind to start with a clean build or new copy of the project's repository.
j2objc-generated files are build artifacts (like .o files), and so should
never be saved or used across versions.
