### ISSUE TITLE
Translated primitive properties have "null_resettable" specifier when --swift-friendly set.

### ISSUE THREAD

**Issue by Vladlex** [google/j2objc#855]
Primitive properties (like jint, jlong) are normally translated into something like (nonatomic, readwrite), but when you set  --swift-friendly flag – "null_resettable" specifier added.

I. e., you have following file:

```
import com.google.j2objc.annotations.Property;

public class TestClass {
    @Property("readonly, nonatomic") private int fieldBar, fieldBaz;
}
```

Without --swift-friendly translated file looks like that (ignoring defines and static methods):
```
@interface TestClass : NSObject
@property (readonly, nonatomic) jint fieldBar;
@property (readonly, nonatomic) jint fieldBaz;

#pragma mark Public

- (instancetype)init;

@end
```

But if  --swift-friendly set, then result interface is another **(null_resettable added, which caused compilation error because jint is type)**:

```
@interface TestClass : NSObject
@property (readonly, nonatomic, null_resettable) jint fieldBar;
@property (readonly, nonatomic, null_resettable) jint fieldBaz;

#pragma mark Public

- (instancetype)init;

@end
```

**Comment by tomball** [comment]
Thanks for the report, which we should be able to resolve by next week.

**Comment by tomball** [comment]
Fixed in current source.

**Comment by prettynatty** [comment]
@tomball Thanks for a quick fix! When do you plan to publish the next release?
