### ISSUE TITLE
Memory leak in java.util.regex.Pattern

### ISSUE THREAD

**Issue by congt** [google/j2objc#857]
It happens to j2objc 1.2 release, not sure if it's fixed in 2.0

Sample code: 
`Pattern.compile("\\s").matcher("ab cd").replaceAll("");`

![regex_pattern](https://cloud.githubusercontent.com/assets/12762242/26020911/b373a2e6-3752-11e7-8058-d2a0f729886e.png)

**Comment by kstanger** [comment]
Sometimes Instruments reports false positives. Do you notice an increase in memory usage over time in the memory profile?

**Comment by congt** [comment]
@kstanger Yes, verified that the memory usage continuously increases by repeatedly calling  `Pattern.compile("\\s").matcher("ab cd").replaceAll("")` over time.

**Comment by tomball** [comment]
While that leak needs to be fixed, you should be aware that
Pattern.compile() is an expensive operation, whether run in a JVM, Android,
or on iOS via j2objc. Anywhere this is repeatedly called with the same
pattern string is a great place to optimize, by caching and reapplying the
compiled Pattern:

http://stackoverflow.com/questions/1720191/java-util-regex-importance-of-pattern-compile

**Comment by kstanger** [comment]
I do not observe a memory leak with this code in my own testing. Please make sure that you are using autorelease pools to occasionally drain memory. You can add autorelease pools in your Java code with the [@AutoreleasePool](https://developers.google.com/j2objc/javadoc/annotations/reference/com/google/j2objc/annotations/AutoreleasePool) annotation.

Here is the test code that I used. When run with Xcode Instruments the memory profile was stable and not increasing. However, when the AutoreleasePool annotation is removed, memory usage does indeed grow continuously.
```
import com.google.j2objc.annotations.AutoreleasePool;
import java.util.regex.*;

class Test {

  @AutoreleasePool
  private static void test() {
    Pattern.compile("\\s").matcher("ab cd").replaceAll("");
  }

  public static void main(String[] args) {
    while (true) {
      test();
    }
  }
}
```

**Comment by congt** [comment]
Thank you for the quick response and help!
