### ISSUE TITLE
Error during 'make dist' when sync'd to latest commit (bf8156e)

### ISSUE THREAD

**Issue by mainr** [google/j2objc#859]
When I run 'make dist' after sync'ing to latest commit (bf8156e - May 17, 2017), I get the following error:

`
...
compiling /Users/xxx/Documents/j2objc/jre_emul/build_result/Classes/java/util/stream/StreamSpliterators.m
compiling /Users/xxx/Documents/j2objc/jre_emul/build_result/Classes/java/util/stream/TerminalOp.m
compiling /Users/xxx/Documents/j2objc/jre_emul/build_result/Classes/libcore/icu/ICU.m
make[1]: *** No rule to make target `Classes/IOSLocaleData.h', needed by `/Users/xxx/Documents/j2objc/jre_emul/build_result/objs-iphone/libcore/icu/LocaleData.o'.  Stop.
make: *** [jre_emul_dist] Error 2
`

???
Possibly the IOSLocaleData.h file should be in the repo, but was left out?
Thanks,
R. Main.

**Comment by kstanger** [comment]
I think you just need to do a "make clean". IOSLocaleData.m and .h have been removed.
