### ISSUE TITLE
TypeVariableImpl appears to create a retain cycle with `formalVar` instance variable

### ISSUE THREAD

**Issue by danieldickison** [google/j2objc#861]
The 3-argument constructor for `TypeVariableImpl` assigns `this.formalVar = this`. It seems like this creates a retain cycle because the only other place where `formalVar` is set is short-circuited unless the variable is currently `null`.

I'm also curious why cycle_finder is not flagging this field despite it not being in the whitelist.

Here is the constructor line:
https://github.com/google/j2objc/blob/66348c337084b37c09e5e017e4f4169bec6f37c7/jre_emul/android/libcore/luni/src/main/java/libcore/reflect/TypeVariableImpl.java#L59

**Comment by kstanger** [comment]
cycle_finder ignores single-object cycles because that type of cycle occurs a lot in linked data structures.

**Comment by danieldickison** [comment]
Fix works great here. Thanks!
