### ISSUE TITLE
We are looking for a lot more

### ISSUE THREAD

**Issue by lancemao** [google/j2objc#862]
Hi there, first of all, j2objc rocks. It rocks so much, we aligned our career with it. We are developing a framework that will translate Android into iOS, to achieve cross-platform mobile development.
https://plugins.jetbrains.com/plugin/9727-lark-studio

Yes, we understand there are other solutions in the market but none of them really solved the cross-platform issue. Because every single of them requires more skill from developer instead of less. e.g. H5 requires both Web skill and native skill unless the app is very simple. Xamarin requires .Net on top of native.
And we also understand j2objc clearly stated UI is not the target. It's alright, leave the dirty work to us, we have solved the most difficult issue in Android UI: The layout system. We support all android layouts. Now, we need to write all other part of Android API, which indeed is a huge work, but we believe it is achievable, if we can work together with j2objc community

So, could you please consider adding some of the basic classes & API in the UI part, we are only asking the very basic and independent part

Let's start with android.graphics.Matrix, what do you think?

**Comment by kpgalligan** [comment]
This isn't really a bug as much as a product discussion. Probably best for the google group: https://groups.google.com/forum/#!forum/j2objc-discuss. We're releasing something like what you're talking about in a couple weeks, although still staying away from UI. More android and popular libraries. Database, threading, etc. Profile has contact info. Ping me if you want to discus.
