### ISSUE TITLE
Jsoup-1.8.3 parser String throw NPE.

### ISSUE THREAD

**Issue by wdxxl** [google/j2objc#863]
Hi There, 
Currently I just use very simple String to parse. (@"<html><body>123123</body></html>"), it always throw NPE, except once. 

![jsoup-1 8 3-npe](https://user-images.githubusercontent.com/1063750/27136680-851a8c78-514e-11e7-9235-9ff07c891bb1.jpg)

Regards
King

**Comment by kstanger** [comment]
This looks like an issue with Jsoup, not J2ObjC.

**Comment by wdxxl** [comment]
Hi kstanger,

Thanks for the response. but still face one more problem of reading properties files,  please check bleow:

The root cause was because of Jsoup-1.8.3 Entities.java (it going to reader properties under package), but when code convert into objective. (related properties cannot been found, even I manually put those two properties under Xcode project) - (all related code & properties combine into Static Lib still raise NPE.)
<img width="1082" alt="source_code_entities" src="https://user-images.githubusercontent.com/1063750/27176399-ed859978-51f4-11e7-8df8-037b2a7863fb.png">

Any Suggestion about J2objc convert some of the code need to read properties file? where should setup related properties if it required some of the class during initialized?

(P.S. ignore properties, just hard code it works)
![hardcode_entities](https://user-images.githubusercontent.com/1063750/27176347-bdaac32c-51f4-11e7-84af-baf1a77b6c1b.jpg)

Regards
King

**Comment by kstanger** [comment]
It sounds like you iOS app is failing to load some resource files. Make sure to put all the necessary resource files into your iOS resource bundle with the same file path (relative to the bundle root) as they have in Java.

**Comment by wdxxl** [comment]
thanks for the response, as current project just use j2objc to convert code as one of the plugin under cordova project, manually set up IOS resources bundler might not a very good case, I will try your suggestion today to verify it.
