### ISSUE TITLE
package java.lang.management does not exist

### ISSUE THREAD

**Issue by wdxxl** [google/j2objc#867]
Hi There,

I'm trying to convert lucene-core-4.0.0.jar file, while one error raised. please check as below:

![screenshot](https://user-images.githubusercontent.com/1063750/28008206-2acd4504-6589-11e7-80d4-2ec51597c5db.png)

Thanks.

**Comment by tomball** [comment]
J2ObjC does not have a Java VM, so it cannot support classes that manage a VM.

I recommend that you create stub classes for the missing API, which return null, false, or 0 depending on the return value. The easiest way to do this is to start with the output from "javap -protected <pkg>.<class>".
