### ISSUE TITLE
Translated h m file contains comments that cannot be checked into VCS

### ISSUE THREAD

**Issue by lancemao** [google/j2objc#868]
after translation, there is some comments at the beginning of h or m file. e.g.:
```
//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/lancemao/TestBundle/src/main/java/com/huawei/bundle/BundleActivity.java
//
```
this is uncomfortable for iOS projects as we cannot check these files into VCS.
We want to check in, because the java project is huge and it is quite some hassle for everyone to do the translation every time somebody made a change on java code. 
Further more, if we cannot check in h&m files, we need to setup j2objc environment as well as telling everybody how to translate. 
Could you please fix this? thanks in advance

**Comment by tomball** [comment]
Although we understand why some teams feel the need to check-in translated files, we consider them transient build artifacts, similar to .o files. Also, projects that use Xcode frequently use the "--no-package-directories" flag, which makes it hard to find the original source. So we have to deny this request.

However, it's easy to change locally by adding a sed or perl post-processing step. Here's an example script you can hack to your liking:
```
#!/bin/bash
#
# Wrapper for the j2objc command which strips the source: comments from
# generated files.

function stripSource () {
  # Delete third line in file.
  sed -e '3d' "$1" > "$1".tmp
  mv "$1".tmp "$1"
}

ARGS=$()
OUTPUT_DIR=.
JAVA_SOURCES=$()

while [ $# -gt 0 ]; do
  ARGS[nArgs++]=$1
  case $1 in
    -d) OUTPUT_DIR=$2;;
    *.java) JAVA_SOURCES[nSources++]=$1;;
  esac
  shift
done

j2objc ${ARGS[@]}

if [ $? -eq 0 ]; then
  for ((i = 0; i < ${#JAVA_SOURCES[@]}; i++)); do
    stripSource "${OUTPUT_DIR}"/"${JAVA_SOURCES[$i]%.java}.h"
    stripSource "${OUTPUT_DIR}"/"${JAVA_SOURCES[$i]%.java}.m"
  done
fi
```
