### ISSUE TITLE
J2OBJC make dist throwing error

### ISSUE THREAD

**Issue by Ankur0713** [google/j2objc#872]
Hi Team

i have run the command on terminal make dist on latest version of j2objc and i am getting below errors

src/main/java/com/google/devtools/j2objc/javac/JavadocConverter.java:148: error: method does not override or implement a method from a supertype
  @Override
  ^
src/main/java/com/google/devtools/j2objc/javac/JavadocConverter.java:155: error: method does not override or implement a method from a supertype
  @Override
  ^
src/main/java/com/google/devtools/j2objc/javac/JavadocConverter.java:161: error: package DCTree does not exist
      ((DCTree.DCErroneous) node).pos = ((DCTree) node).pos(docComment).getStartPosition();
              ^
Note: src/main/java/com/google/devtools/j2objc/jdt/AbstractTypeBinding.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
100 errors
make[1]: *** [/Users/Documents/J2OBJC/translator/build_result/j2objc.jar] Error 1
make: *** [translator] Error 2

Please suggest

**Comment by tomball** [comment]
The j2objc build requires that you have JDK 1.8
<https://developers.google.com/j2objc/#requirements> or higher installed.
These errors are caused either by the JDK's lib/tools.jar not on your
system, or it is an old version (DocTreeScanner and DCTree are from the
JDK). You can download the latest JDK release here
<http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html>
.
