### ISSUE TITLE
[Proposal] Generating Xcode framework automantically

### ISSUE THREAD

**Issue by wspl** [google/j2objc#874]
Similar to Embeddinator-4000 of Mono Project / Go Mobile for iOS.

https://mono.github.io/Embeddinator-4000/getting-started-objc-ios.html
https://github.com/golang/go/wiki/Mobile#building-and-deploying-to-ios

**Comment by tomball** [comment]
We plan on supporting [Tulsi](http://tulsi.bazel.io/), but first j2objc's build needs to move to [Bazel](https://bazel.build/).

**Comment by andrewebling** [comment]
@tomball any plans to revisit or implement this soon? We'd love to have J2ObjC as an XCFramework in our project.

**Comment by tomball** [comment]
This was implemented to support Mac Catalyst in #1094 , and released in [j2objc-2.6](https://github.com/google/j2objc/releases/tag/2.6). I'm sorry this issue was left open, but the good news is you aren't blocked anymore.
