### ISSUE TITLE
Linking error when building for x86_64(Simulator) 

### ISSUE THREAD

**Issue by zombierzn** [google/j2objc#877]
After upgrading to j2objc 2.0.3 we can not build project for simulator. Build ends with error:

> Undefined symbols for architecture x86_64:
  "_JNU_ThrowByName", referenced from:
      _Inet6AddressImpl_getHostByAddr0 in libjre_emul.a(Inet6AddressImpl.o)
  "_JVM_Socket", referenced from:
      _Inet4AddressImpl_isReachable0 in libjre_emul.a(Inet4AddressImpl.o)
      _Inet6AddressImpl_isReachable0 in libjre_emul.a(Inet6AddressImpl.o)
  "_JVM_Connect", referenced from:
      _Inet4AddressImpl_isReachable0 in libjre_emul.a(Inet4AddressImpl.o)
      _Inet6AddressImpl_isReachable0 in libjre_emul.a(Inet6AddressImpl.o)
  "_JVM_GetSockOpt", referenced from:
      _Inet4AddressImpl_isReachable0 in libjre_emul.a(Inet4AddressImpl.o)
      _Inet6AddressImpl_isReachable0 in libjre_emul.a(Inet6AddressImpl.o)
  "_NET_ThrowByNameWithLastError", referenced from:
      _Inet4AddressImpl_isReachable0 in libjre_emul.a(Inet4AddressImpl.o)
      _Inet6AddressImpl_isReachable0 in libjre_emul.a(Inet6AddressImpl.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

With j2objc 2.0 building for simulator works fine.

**Comment by zhouyanggao** [comment]
This is a known issue. I will fix it in the next release. 
You can comment out these functions in Inet4AddressImpl.m and InetAddress6Impl.m and rebuild if you want to resolve them yourself.

**Comment by zombierzn** [comment]
Ok. Thank you!

**Comment by zhouyanggao** [comment]
Fixed.
