### ISSUE TITLE
nullability @ParametersAreNonnullByDefault and clone

### ISSUE THREAD

**Issue by kpgalligan** [google/j2objc#878]
Kind of an edge case here, but, if you have nullability enabled, @ParametersAreNonnullByDefault on and override 'clone', the zone parameter is set to __nonnull, which fails to compile. You can't really apply @Nullable or similar because the translation code itself is adding the 'zone' param, so there's nothing in the java source to attach it to.

I've "fixed" it in a fairly hacky method in ElementUtil

```java
public static boolean isNonnull(Element element, boolean parametersNonnullByDefault) {
    boolean shouldBeNonnull = hasNonnullAnnotation(element)
            || (isParameter(element)
            && parametersNonnullByDefault
            && !element.asType().getKind().isPrimitive());

    if (shouldBeNonnull) {
      Element parentElement = element.getEnclosingElement();
      boolean copyWithZone = parentElement instanceof ExecutableElement && parentElement.getSimpleName().toString().contains("copyWithZone");
      return !copyWithZone;
    } else {
      return false;
    }
  }
```

Essentially testing if the enclosing method is 'copyWithZone'. That has compiled, but I haven't done much more testing with it, and I'm sure there's a more appropriate place/method to do this.

Alternatively it might make more sense to add a @Nullable to the parameter when it's generated.

```java
// Add NSZone *zone parameter.
    VariableElement zoneParam =
        GeneratedVariableElement.newParameter("zone", NSZONE_TYPE, copyElement);
// Add @Nullable here 
    copyElement.addParameter(zoneParam);
    copyDecl.addParameter(new SingleVariableDeclaration(zoneParam));
```

Having trouble finding the code to create an AnnotationMirror, so letting the first solution stand for today and seeing if there are any thoughts on this.

**Comment by tomball** [comment]
Fixed in source. There is now a [GeneratedAnnotationMirror class](https://github.com/google/j2objc/blob/master/translator/src/main/java/com/google/devtools/j2objc/types/GeneratedAnnotationMirror.java) for creating an annotation mirror from its declared type.

**Comment by tomball** [comment]
Thanks for your help! It made addressing this much easier.
