### ISSUE TITLE
J2objc script since 2.0.2 fails if path contains spaces

### ISSUE THREAD

**Issue by gianlucabertani** [google/j2objc#881]
Hello,

since version 2.0.2, the j2objc script contains this variable:

    ANNOTATIONS_ARG="-Xannotations-jar ${LIB_DIR}/j2objc_annotations.jar"

used as-is in the command line:

    java ${JAVA_ARGS[*]} -jar "${JAR}" "${BOOT_PATH}" ${ANNOTATIONS_ARG} "${J2OBJC_ARGS[@]}"

If ${LIB_DIR} contains spaces, the command line fails.

A simple fix is removing the variable and adding the -Xannotations-jar flag directly on the command line, with ${LIB_DIR} appropriately quoted. E.g.:

    java ${JAVA_ARGS[*]} -jar "${JAR}" "${BOOT_PATH}" -Xannotations-jar "${LIB_DIR}"/j2objc_annotations.jar "${J2OBJC_ARGS[@]}"

Hope this is of help.
Best regards.

**Comment by kstanger** [comment]
Fixed in [current source](https://github.com/google/j2objc/commit/325664340cfd3e62972b92402930ca5eca92ea8c).
