### ISSUE TITLE
JreRetainedLocalValue not defined when compiling with ARC

### ISSUE THREAD

**Issue by gianlucabertani** [google/j2objc#882]
Hello again.

In [J2ObjC_Common.h](https://github.com/google/j2objc/blob/master/jre_emul/Classes/J2ObjC_common.h), as of version 2.0.3, the inline function *JreRetainedLocalValue* is defined as follows:

```obj-c
#if !__has_feature(objc_arc)
__attribute__((always_inline)) inline id JreRetainedLocalValue(id value) {
  return [[value retain] autorelease];
}
#endif
```

When compiling transpiled code under ARC, the function results as non-defined and multiple compilation errors are produced, since the function is frequently referenced.

A simple fix is to declare it as an empty function under ARC, such as this:

```obj-c
#if !__has_feature(objc_arc)
__attribute__((always_inline)) inline id JreRetainedLocalValue(id value) {
  return [[value retain] autorelease];
}
#else
__attribute__((always_inline)) inline id JreRetainedLocalValue(id value) {
    return value;
}
#endif
```

Hope this is of help.
Best regards.

**Comment by clementmangin** [comment]
I already reported this bug in the J2ObjC discussion group: https://groups.google.com/forum/#!topic/j2objc-discuss/KdDBW_kleq8

And there is a fix here: https://github.com/google/j2objc/commit/e79436e90c131a073d2a222aee29dfe0ac334af3

**Comment by kstanger** [comment]
The fix will make the next release.
