### ISSUE TITLE
Initial value for ThreadLocal

### ISSUE THREAD

**Issue by tux-mind** [google/j2objc#892]
I have a `ThreadLocal<Boolean>` static field in a class.

As specified by docs of `ThreadLocal#get`:

> ... If the variable has no value for the current thread, it is first initialized to the value returned by an invocation of the initialValue() method.

The transpiled code for

```java
if(threadLocalVariable.get()) {
  // wow
}
```

is

```objc
if ([((JavaLangBoolean *) nil_chk([((JavaLangThreadLocal *) nil_chk(CLASSNAME_threadLocalVariable)) get])) booleanValue]) {
  // wow
}
```

Sadly `([((JavaLangThreadLocal *) nil_chk(CLASSNAME_threadLocalVariable)) get]` returns `nil` on first call, resulting in a `NullPointerException`.
Expected Behaviour is that `get` shall return a Boolean object initialized with the `false` value.

I hope that this will improve the tool a little, thank you for all your work.

PS:
I just searched for the cause to verify that even the master branch has this issue and I found a comment about a custom implementantion is required. (https://github.com/google/j2objc/blob/master/jre_emul/android/platform/libcore/ojluni/src/main/java/java/lang/ThreadLocal.java#L124 )

So you may want to mark this as **work-as-intented** or may not, you choice :blush:

**Comment by tomball** [comment]
Right, the jre_emul source is primarily based on Android source code, to ensure the best JRE compatibility for Android apps (and likely the best trade-offs for mobile devices). In Android N, the code was replaced with source from the Java 8 version of OpenJDK, so this code should also be compatible with Java server code as well.

Note the javadoc for the initialValue(): you can define a custom ThreadLocal class for each variable. I haven't verified this, but in theory this should give you what you want:
```
private static final ThreadLocal<Boolean> someFlag = new ThreadLocal<>() {
  @Override
  protected Boolean initialValue() {
    return Boolean.FALSE;
  }
};

public Boolean myflag() {
  return someFlag.get();
}
```
