### ISSUE TITLE
Wrong locale for Simplified Chinese and Traditional Chinese

### ISSUE THREAD

**Issue by aminelaadhari** [google/j2objc#895]
Hi,

When the device is configured to use Simplified Chinese or Traditional Chinese, JavaUtilLocale.getDefault() doesn't return the correct locale. 

**For Traditional Chinese**
NSLocal.current.identifier = "zh-Hant_US" 
JavaUtilLocale.getDefault() = "zh_US"

NSLocal.current.identifier = "zh-Hant" 
JavaUtilLocale.getDefault() = "zh"

**For Simplified Chinese**
NSLocal.current.identifier = "zh-Hans_US" 
JavaUtilLocale.getDefault() = "zh_US"

NSLocal.current.identifier = "zh-Hans" 
JavaUtilLocale.getDefault() = "zh"

The problem is that we lose the language script part which is really important for Chinese.
Is this the expected behavior? or the correct value should be zh_CN for simplified and zh_TW for traditional?

Thanks

**Comment by aminelaadhari** [comment]
We implemented this workaround:
```
if NSLocale.current.identifier.hasPrefix("zh-Hans") {
            JavaLangSystem.setPropertyWith("user.language", with: "zh")
            JavaLangSystem.setPropertyWith("user.region", with: "CN")
        } else if NSLocale.current.identifier.hasPrefix("zh-Hant") {
            JavaLangSystem.setPropertyWith("user.language", with: "zh")
            JavaLangSystem.setPropertyWith("user.region", with: "TW")
        }
```

**Comment by lukhnos** [comment]
Fixed in the commit mentioned above.
