### ISSUE TITLE
 Possible misuse of comma operator in enum

### ISSUE THREAD

**Issue by jaspervp** [google/j2objc#899]
I am seeing a lot of 'Possible misuse of comma operator here' warnings in the generated code for enums.

Is the correct way to solve this adding `#pragma clang diagnostic ignored "-Wcomma"` to EnumRewriter.java?

**Comment by kstanger** [comment]
Looks like it may be possible to silence -Wcomma warnings by selectively casting the first operand to void, similar to how we handle statement expressions with non-void results.
http://lists.llvm.org/pipermail/cfe-commits/Week-of-Mon-20160215/150637.html

**Comment by jaspervp** [comment]
fixed in #900
