### ISSUE TITLE
different java class result in exactly same OC class

### ISSUE THREAD

**Issue by lancemao** [google/j2objc#906]
e.g.  we have two java classes:
1. com.google.j2objc.Rock
2. com.google.j2objcRock
they will result in same OC class after translating: ComGoogleJ2objcRock

We find this issue because of an actual use case:
https://github.com/eclipse/californium/tree/master/californium-core/src/main/java/org/eclipse/californium/core

note that there is a class CoapResponse, and unfortunately inside coap package, there is a class called Response

The problem is that j2objc omitted the 'dot' signal, which decreased the number of cases that can be represented by Java. We can't find a solution rather than translate Java class to something like:
1. ComDotGoogleDotJ2objcDotRock
2. ComDotGoogleDotJ2objcRock

any idea?

**Comment by tomball** [comment]
You can use the [@ObjectiveCName annotation](https://developers.google.com/j2objc/javadoc/annotations/reference/com/google/j2objc/annotations/ObjectiveCName) to rename one of these classes. Encoding the dots in packages would increase translated class name sizes, and developers already complain they are too long.
