### ISSUE TITLE
j2objc - exception when deserialize enum with ARC

### ISSUE THREAD

**Issue by mnrkeller** [google/j2objc#909]
(Note that this was originally posted as a question on StackOverflow and answered by Tom Ball there. I'm posting here for completeness and tracking purposes.)

I am having trouble deserializing objects that contain an enum. The object serializes without complaint, but I get an InvalidObjectException when I deserialize the object. The exception message says that there is "No enum constant com.mypackagname."

I have isolated and reproduced the problem by creating some test code based on the testSerialization() method in SerializationTest.java.

```
public class SerializationTest {
    private static final String TEST_FILE_NAME = "serialization-test.bin";
    public enum Gender { MALE, FEMALE }

    public void testEnumSerialization() throws IOException, ClassNotFoundException {
        Gender gender = Gender.MALE;

        // Save the enum to a file.
        ObjectOutputStream out = new ObjectOutputStream(new FileOutputStream(TEST_FILE_NAME));
        out.writeObject(gender);
        out.close();

        // Read back the enum.
        ObjectInputStream in = new ObjectInputStream(new FileInputStream(TEST_FILE_NAME));
        Gender gender2 = (Gender) in.readObject();
        in.close();
    }
}
```

I have discovered that if I add a string value to the enum initialization in the generated Objective C code the deserialization works fine. The resulting initialize method in Obj C looks like this:

```
+ (void)initialize {
    if (self == [SerializationTest_Gender class]) {
        JreEnum(SerializationTest_Gender, MALE) = new_SerializationTest_Gender_initWithNSString_withInt_(@"MALE", 0);
        JreEnum(SerializationTest_Gender, FEMALE) = new_SerializationTest_Gender_initWithNSString_withInt_(@"FEMALE", 1);
        J2OBJC_SET_INITIALIZED(SerializationTest_Gender)
    }
}
```

Note that I added the @"MALE" and @"FEMALE", the default from the j2objc output is @"".

Thanks for all of your hard work on this really valuable tool!

**Comment by tomball** [comment]
What version of j2objc are you using? This looks to already be fixed, since the test passes (and the initialize method for Gender is completely different). The serialization-test.bin generated by the JVM and j2objc are byte-for-byte identical (as they should be). I verified this with [release 2.0.5](https://github.com/google/j2objc/releases/tag/2.0.5) as well as a build of the latest source.

**Comment by mnrkeller** [comment]
I confirmed that I am using version 2.0.5.  Not sure if it makes a difference but here are the options I am using:  -l -d . --swift-friendly --no-package-directories -use-arc --static-accessor-methods

**Comment by tomball** [comment]
Thanks for the quick response. The issue only shows up with the -use-arc flag. Investigating...

**Comment by tomball** [comment]
Fixed in current sourc.
