### ISSUE TITLE
Annotation classes need generated equals and hashCode methods

### ISSUE THREAD

**Issue by kpgalligan** [google/j2objc#911]
When you get annotation classes from metadata, they are created with a method defined by the J2objc translator. Running 'equals' on 2 instances from calling the same method twice, you would expect true, but you get false. This is because equals is not defined for them, and they're doing object instance comparison. Similarly, hashCode is also not what you'd expect.

I've made changes locally to translator, but would need to update to latest source and do some more solid verification before any kind of pull request. Also hashCode seems totally wrong. Just going by expected results in the code I was translating (Moshi, again).

Updating to latest J2objc source soon and see how this goes.

https://github.com/doppllib/j2objc/blob/e7cdd9e4b12ed147d0c39c6c2e1f955e950301fc/translator/src/main/java/com/google/devtools/j2objc/translate/AnnotationRewriter.java#L193

**Comment by tomball** [comment]
Fixed in current source.
