### ISSUE TITLE
Memory Leak While use Gson converted jar file

### ISSUE THREAD

**Issue by wdxxl** [google/j2objc#921]
Hi There,

I'm working on J2objc With Lucene project, source data will use Gson format, after that to generate index. currently memory still have big issue.

<img width="988" alt="screenshot" src="https://user-images.githubusercontent.com/1063750/33760203-de0a0422-dc3f-11e7-898f-f8eabf037ef9.png">

<img width="1095" alt="screenshot" src="https://user-images.githubusercontent.com/1063750/33760218-e93a9a6e-dc3f-11e7-8300-11de15b4736e.png">

I use "j2objc -use-arc" to convert gson-2.6.2-sources.jar and make it as static lib for project using, the rest thing is use java file to read like 70,000 json records, that write into Lucene one by one. looks like -use-arc for gson not work as expected.

Regards
King

**Comment by tomball** [comment]
All the -use-arc flag does is generate code so it can be compiled with clang's -fobjc-arc flag without warnings. That code doesn't reference any of the j2objc runtime memory management macros (like JreStrongAssign), so the ARC support in the Objective C runtime is responsible for all memory management, not j2objc's runtime.

If you are reading these records in a loop (say, in a background thread), then you may need to add autoreleasepool support (just like if this were hand-written Objective C code). Unlike Java's garbage collector, Objective C memory management supports [deferred object releasing with explicit scoped pools](https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/MemoryMgmt/Articles/mmAutoreleasePools.html). It doesn't matter whether the project is built with ARC or not,
 as [ARC doesn't eliminate the need for autorelease pools.](https://stackoverflow.com/questions/9086913/why-is-autoreleasepool-still-needed-with-arc).

There is an [@AutoreleasePool annotation](https://developers.google.com/j2objc/javadoc/annotations/reference/com/google/j2objc/annotations/AutoreleasePool) to support generating autoreleasepool directives. [Here are AutoreleasePool  references in j2objc's source.](https://github.com/google/j2objc/search?utf8=%E2%9C%93&q=AutoreleasePool&type=)

**Comment by tomball** [comment]
FYI, you don't need to translate and build libraries to use ARC just because your app uses it. Apps can mix ARC and non-ARC code, as ARC is just an effective way to automate the calling of retain, release, and autorelease messages. That's perfect for developers since we can all make reference counting mistakes, but has less benefit for generated code. From a project perspective, all that means is that the Java library needs to be translated and built as a separate target from the app, with ARC turned off.

**Comment by iousin** [comment]
Hi @tomball , 
We are also facing same issue, have setup a sample project with gson compiled into a framework and a swift project using that framework. All the transpiled code has been checked in. The project is here:
https://github.com/iousin/EmployeeGson
You can just open the xcode project under employee-gson/employee-gson-ios/EmployeeGson folder and change user defined setting of "J2OBJC_HOME" then if you profile using instruments it'll report memory leaks related to ComGoogleGsonInternalLinkedTreeMap_Node. Have tried using autoreleasepool still doesn't help. Please advise. 
The github readme has more information. 
https://github.com/iousin/EmployeeGson/blob/master/README.md

We are using gson in android as well and android app doesn't report any memory leaks. Don't know if this helps, just adding as information. 

Appreciate any help.
Thanks.

**Comment by danieldickison** [comment]
If I'm reading this correctly, it looks like internal data structure of `com.google.gson.internal.LinkedTreeMap` contains a cyclical linked list by design, using the `header` node as the placeholder for both the beginning and end of the list: https://github.com/google/gson/blob/9d44cbc19a73b45971c4ecb33c8d34d673afa210/gson/src/main/java/com/google/gson/internal/LinkedTreeMap.java#L449

So that create a retain cycle, which could probably be broken by annotating both `next` and `prev` instance variables as `@Weak`. In addition to that, the tree structure also contains strong references from child to parent in addition to the parent-to-child variables, a cycle that could probably be broken by annotating the `parent` variable as `@Weak`. I haven't looked at this closely enough to know if this will end up releasing nodes _too_ early, though I think the parent-to-children references should be sufficient for maintaining strong references.

In a situation like this, what's the recommended way of annotating a third party library? I'm not sure if creating a dependency on the j2objc annotations in the general gson library would be appropriate for an upstream pull request.

**Comment by iousin** [comment]
@danieldickison , 
Thanks for the quick response, have tried annotating as suggested. Commit is here:
https://github.com/iousin/EmployeeGson/commit/892adb80edef74b1afe55ccfef40442dc70388aa

Doesn't help, still reporting leaks. Have I put these annotations at the right place?

Thanks

**Comment by danieldickison** [comment]
@iousin that fixes one retain cycle but there's still a leak by the EntrySet and KeySet inner classes holding strong references to the LinkedTreeMap (and vice versa). Here's a pull request that fixes this issue with `@WeakOuter`: https://github.com/iousin/EmployeeGson/pull/1

The memory graph visualization within Xcode is sometimes more useful than the Leaks instrument for tracking down these retain cycles.

I'm still curious if folks think it would be sensible to try and get gson upstream to incorporate these j2objc annotations.

**Comment by iousin** [comment]
Hi @danieldickison , 
Excellent, I can confirm this fixed the issue. I don't know if Gson team would accept these changes to the mainstream project. I think maybe another static library as part of the j2objc release bundle like guava may also do.

Thanks for the help, much appreciated.

**Comment by tomball** [comment]
I encourage you to send a pull request to the Gson project when you're happy with these changes. You might mention that [Guava has j2objc annotations](https://github.com/google/guava/blob/master/pom.xml#L234), so be sure to include a cut-and-paste from Guava's pom.xml to Gson's pom.xml with that dependency.

**Comment by iousin** [comment]
@tomball , 
OK, just finishing some final testing on our real project, will then create pull request. 

Thanks.

**Comment by antonio-cortes-perez** [comment]
Hopefully in the not-too-distant future, we will have the capability of specifying external annotations (https://checkerframework.org/annotation-file-utilities/). In this particular scenario, it will allow us to specify the Weak annotation without modifying the source.

**Comment by tomball** [comment]
Gson is (or should be, IMO) on life-support, as better alternatives exist. [Moshi](https://github.com/square/moshi) from Square is my favorite, as it was developed by some of Gson's authors as a replacement for it. [Jesse Wilson wrote up his concerns](https://medium.com/square-corner-blog/moshi-another-json-processor-624f8741f703), and here's [a Reddit discussion comparing the two](https://www.reddit.com/r/androiddev/comments/684flw/why_use_moshi_over_gson/).

What I love about Moshi for j2objc apps is that it's relatively small: a transpiled static library with its okio dependencies is 1.3M, while Gson is 1.9M and Jackson is 3.4M. Square is also very responsive to bug reports and pull requests, so any issues should be addressed quickly one way or the other.

**Comment by iousin** [comment]
Hi, @tombal, 
I tried to transpile moshi, it uses some kotlin files so stopped. Do we have moshi available to use for iOS?
Thanks.

    On Tuesday, 11 December, 2018, 6:21:41 PM GMT, Tom Ball <notifications@github.com> wrote:  
 
 
Gson is (or should be, IMO) on life-support, as better alternatives exist. Moshi from Square is my favorite, as it was developed by some of Gson's authors as a replacement for it. Jesse Wilson wrote up his concerns, and here's a Reddit discussion comparing the two.

What I love about Moshi for j2objc apps is that it's relatively small: a transpiled static library with its okio dependencies is 1.3M, while Gson is 1.9M and Jackson is 3.4M. Square is also very responsive to bug reports and pull requests, so any issues should be addressed quickly one way or the other.

**Comment by tomball** [comment]
We only include libraries with the j2objc release if a) our build uses them (Guava, JUnit, Hamcrest), or b) we added custom iOS support (Mockito). 

I recommend you ask any Moshi-specific questions on StackOverflow with a "moshi" tag.
