### ISSUE TITLE
J2OBJC_DISABLE_CAST_CHECKS maybe not working

### ISSUE THREAD

**Issue by dfsilva** [google/j2objc#923]
Hello Guys,
Does anyone have this problem too? 
When I define the parameter J2OBJC_DISABLE_CAST_CHECKS the function cast_check is not supposed to be disabled?

<img width="1265" alt="erro_j2objc" src="https://user-images.githubusercontent.com/424713/34082457-e6ac1f86-e345-11e7-8dc8-9aeca8fd90d4.png">

**Comment by flovilmart** [comment]
you should set J2OBJC_DISABLE_CAST_CHECKS in your xcode build settings or your pch, before the j2objc headers are imported.

**Comment by tomball** [comment]
Yes, J2OBJC_DISABLE_CAST_CHECKS is a build setting, not something done per-file. Thanks, Florent for pointing out the issue.
