### ISSUE TITLE
class header file not found

### ISSUE THREAD

**Issue by lancemao** [google/j2objc#924]
in android framework android/media package, there is a file ClosedCaptionRenderer.java
the main class is
 
`public class ClosedCaptionRenderer extends SubtitleController.Renderer`

inside this java file. there is another class:
```
/** @hide */
class Cea608CaptionTrack extends SubtitleTrack
```
which is at the same level as the public class. In this case, j2objc translates to 
#include "android/media/Cea608CaptionTrack.h"

however there is no such file as this class is actually inside ClosedCaptionRenderer.h

it should instead include 
#include "android/media/ClosedCaptionRenderer.h"

please take a look, thanks

**Comment by tomball** [comment]
Please submit a test case demonstrating this issue. I tried simplifying ClosedCaptionRenderer but couldn't reproduce the issue, and it's difficult to translate that class because of all its Android API dependencies.

**Comment by lancemao** [comment]
sorry for missing one important step. You need to write another class to use Cea608CaptionTrack.
in general, if you have Foo.java which contains public class Foo and a parallel class Bar. Now in another java file say HelloWorld.java, you try to access Bar. This issue should occur

sorry we are under company firewall, uploading attachments are disallowed

**Comment by tomball** [comment]
Fixed in current source.
