### ISSUE TITLE
Translate Gson: reflect ArrayList is failed

### ISSUE THREAD

**Issue by barylevy** [google/j2objc#930]
I have added Gson open source to my project and it translated very well.
It seems like the inside objects in ArrayList cannot be serialized in Gson

Try the following code:

//create array list with single String
ArrayList<String> arr = new ArrayList<String>();
arr.add("Object A");

//try to create json fom array list
String jsonStr = gson.toJson(arr, arr.getClass());

//print it:
//java: ["Object A"]
//objc: {"size":1}
System.out.println(jsonStr);
        
LinkedList<Boolean> arrRestore = gson.fromJson(jsonStr, LinkedList.class);
//The next line got exception: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
System.out.println(arrRestore.get(0));

What is wrong in my code?

**Comment by adil-hussain-84** [comment]
Does your Gson translation code work okay in an Android or plain Java project?

I've not tried translating the Gson source and using it in an Objective-C project but I do now that generally when translating a `List` of objects with Gson you're advised to use the [TypeToken](https://google.github.io/gson/apidocs/com/google/gson/reflect/TypeToken.html) class.

See [this](https://stackoverflow.com/a/4318722/1071320) StackOverflow answer and [this](https://stackoverflow.com/a/5554296/1071320) one for an example.

**Comment by tomball** [comment]
What version of j2objc are you using, and how are you translating Gson? I converted your code into a Java class:
```
import com.google.gson.Gson;
import java.util.ArrayList;
import java.util.LinkedList;

class GsonTest {
  public static void main(String... args) throws Exception {
    Gson gson = new Gson();

    ArrayList arr = new ArrayList();
    arr.add("Object A");

    //try to create json fom array list
    String jsonStr = gson.toJson(arr, arr.getClass());

    //print it:
    //java: ["Object A"]
    //objc: {"size":1}
    System.out.println(jsonStr);

    LinkedList arrRestore = gson.fromJson(jsonStr, LinkedList.class);
    //The next line got exception: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
    System.out.println(arrRestore.get(0));
  }
}
```
I then compiled and ran it as a Java app, using a newly downloaded [gson-2.8.2.jar](http://central.maven.org/maven2/com/google/code/gson/gson/2.8.2/gson-2.8.2.jar):
```
$ mkdir /tmp/test      # make sure it's a new, empty directory.
$ cd /tmp/test
$ javac -classpath ~/Downloads/gson-2.8.2.jar ~/tmp/GsonTest.java
$ java -classpath ~/Downloads/gson-2.8.2.jar:. GsonTest
["Object A"]
Object A
```
Next, using the latest j2objc release ([2.0.5](https://github.com/google/j2objc/releases/tag/2.0.5)) I translated the [gson-2.8.2-sources.jar](http://central.maven.org/maven2/com/google/code/gson/gson/2.8.2/gson-2.8.2-sources.jar) and this test, then compiled and ran it:
```
$ ~/j2objc-2.0.5/j2objc ~/Downloads/gson-2.8.2-sources.jar ~/tmp/GsonTest.java
$ ~/j2objc-2.0.5/j2objcc -I. `find . -name '*.m'`
$ ./a.out GsonTest
["Object A"]
Object A
```
I think you need to first verify you have the latest j2objc and gson source, then fix your build and verify that the above works.

Once that's working, you'll want to update your code to use TypeToken as Adil recommends, as he knows more about Gson than I do. :-)
