### ISSUE TITLE
JavaTextNumberFormat does not convert digits into Arabic

### ISSUE THREAD

**Issue by atitovdev** [google/j2objc#933]
Hello. We have just updated from 1.3.0 to 2.0.5 and wanted to test [our previous problem](https://github.com/google/j2objc/issues/757)

As you can guess from the title, this code:

```
JavaUtilLocale *javaLocale = [[JavaUtilLocale alloc] initWithNSString:@"ar"withNSString:@"AR"];
JavaTextDecimalFormatSymbols *symbols = [[JavaTextDecimalFormatSymbols alloc] initWithJavaUtilLocale:javaLocale];
JavaTextNumberFormat *numberFormat = [[JavaTextDecimalFormat alloc] initWithNSString:@"0" withJavaTextDecimalFormatSymbols:symbols];
[numberFormat setMaximumFractionDigitsWithInt:2];
NSLog(@"%@", [numberFormat formatWithDouble:-3.75f]);
```

prints
`-3٫75`

instead of
`-٣٫٧٥`

What do you think?

**Comment by tomball** [comment]
Thanks, your example code will be easy to convert to a JUnit test. The regressions are related to our upgrading the jre_emul to OpenJDK (from Apache Harmony); once these bugs are fixed, hopefully there will be improved compatibility going forward.

**Comment by tomball** [comment]
This is unexpected:
```
class ARSymbols {
  public static void main(String... args) {
    Locale javaLocale = new Locale("ar", "AR");
    DecimalFormatSymbols symbols = new DecimalFormatSymbols(javaLocale);
    NumberFormat numberFormat = new DecimalFormat("0", symbols);
    numberFormat.setMaximumFractionDigits(2);
    System.out.println("-3.75f: " + numberFormat.format(-3.75f));
  }
}
```
prints:
```
$ javac ARSymbols.java
$ java ARSymbols
-3.75f: -3.75
```
According to [Arabic Digits: DecimalFormat](http://www.java2s.com/Tutorial/Java/0220__I18N/ArabicDigits.htm), you have to set the zero character to indicate what numeric characters to use:
```
...
    DecimalFormatSymbols symbols = new DecimalFormatSymbols(javaLocale);
    symbols.setZeroDigit('\u0660');  // U660 is the zero symbol in Arabic
...
$ java ARSymbols
-3.75f: -٣.٧٥
```
The comma is still off, so this fixes that both on the JVM and with j2objc:
```
...
    DecimalFormatSymbols symbols = new DecimalFormatSymbols(javaLocale);
    symbols.setZeroDigit('\u0660');  // U660 is the zero symbol in Arabic
    symbols.setDecimalSeparator(',');
...
$ java ARSymbols
-3.75f: -٣,٧٥
```
So 2.0.5 didn't regress, it fixed an unnoticed JRE incompatibility in jre_emul. Whoa, internationalization continues to be hard, no matter how long I've been working with it!

**Comment by tomball** [comment]
The Arabic decimal separator should be '\u066B', not an ASCII comma.
