### ISSUE TITLE
Timer doesn't release executed tasks

### ISSUE THREAD

**Issue by MohammadHejazi** [google/j2objc#935]
After checking in Instruments I found out that many `TimerTask` instances are still live (retain count is `1`) even they are actually `autorelease`d.

I checked how `Timer` class works, and suspect the problem is in `TimerThread.mainLoop()` which has an infinite loop that executes tasks but doesn't have its own auto release pool, which keeps all executed tasks live as long as the timer is live. Did I miss something?

This is an example of a timer task that is not released:
<img width="983" src="https://user-images.githubusercontent.com/388359/35215953-fda0d144-ff76-11e7-8cd1-753ae24676b6.png">

**Comment by tomball** [comment]
You're right, good find! You can test the fix I'm about to make (once I wake up), by changing the `while (true)` in mainLoop() (line 519) to `for (@AutoreleasePool int i = 0;;)`.

**Comment by MohammadHejazi** [comment]
Actually I'm using the last release in my project (not building it from source files), so I can't verify the fix works (but I think it should).
Thanks for your hard and amazing work 👍

**Comment by tomball** [comment]
Fixed in current source.
