### ISSUE TITLE
Error when running java2objc sample

### ISSUE THREAD

**Issue by RandyMuhroji** [google/j2objc#936]
/bin/sh -c if\ [\ !\ -f\ \"${J2OBJC_HOME}/j2objc\"\ ];\ then\ echo\ \"J2OBJC_HOME\ not\ correctly\ defined\ in\ Settings.xcconfig,\ currently\ set\ to\ \'${J2OBJC_HOME}\'\";\ exit\ 1;\ fi;\
\"${J2OBJC_HOME}/j2objc\"\ -d\ ${DERIVED_FILES_DIR}\ -sourcepath\ \"${PROJECT_DIR}/Classes\"\ --no-package-directories\ -use-arc\ --prefix\ Othello.Engine=JOE\ -g\ ${INPUT_FILE_PATH};

error in : 
/j2objc-2.0.5/j2objc: line 88: /Library/Java/JavaVirtualMachines/jdk-9.0.4.jdk/Contents/Home/jre/bin/java: No such file or directory

**Comment by tomball** [comment]
[Install JDK 8 from Oracle](http://www.oracle.com/technetwork/java/javase/overview/index.html), as the j2objc command does not run on Java 9 yet. You can have both Java 8 and Java 9 installed with the default being Java 9, as the j2objc script will find the Java 8 JDK using /usr/libexec/java_home.
