### ISSUE TITLE
Leak in ConcurrentSkipListMap's Marker nodes

### ISSUE THREAD

**Issue by flovilmart** [google/j2objc#946]
Marker nodes are bound to leak in `ConcurrentSkipListMap` as they are self-referencing.

https://github.com/google/j2objc/blob/master/jre_emul/android/platform/libcore/luni/src/main/java/java/util/concurrent/ConcurrentSkipListMap.java#L415

As self referencing go, I believe the proper workaround / fix would either be to weakify the self reference iff this is a marker node, OR to break the cycle when removing a marker node from the ListMap.

**Comment by tomball** [comment]
What we've done for other concurrency classes with self-references is replace them with assignment to a shared sentinel. Would you be interested in creating a pull request with this class updated to do the same? There are two unit tests for that class, so it should be safe if the tests pass.

https://github.com/google/j2objc/blob/master/jre_emul/android/platform/libcore/luni/src/main/java/java/util/concurrent/ConcurrentLinkedQueue.java#L924

**Comment by flovilmart** [comment]
Thanks @tomball for the quick reply! We’ll have a look!

**Comment by flovilmart** [comment]
(Please reopen)
