### ISSUE TITLE
Memory leak in org.apache.xml.serializer.NamespaceMappings

### ISSUE THREAD

**Issue by System25** [google/j2objc#949]
Hi everybody,
 when using instruments in my application a memory leak is detected in org.apache.xml.serializer.NamespaceMappings.

**Stack trace:**
   0 libsystem_malloc.dylib malloc_zone_calloc
   1 libsystem_malloc.dylib calloc
   2 libobjc.A.dylib class_createInstance
   3 libobjc.A.dylib +[NSObject allocWithZone:]
   4 MyApp new_OrgApacheXmlSerializerNamespaceMappings_Stack_initWithOrgApacheXmlSerializerNamespaceMappings_
   5 MyApp OrgApacheXmlSerializerNamespaceMappings_init
   6 MyApp new_OrgApacheXmlSerializerNamespaceMappings_init
   7 MyApp OrgApacheXmlSerializerToXMLStream_init
   8 MyApp -[OrgApacheXmlSerializerToXMLStream init]
   9 MyApp -[IOSConcreteClass newInstance]
  10 MyApp OrgApacheXmlSerializerSerializerFactory_getSerializerWithJavaUtilProperties_
  11 MyApp OrgApacheXalanTransformerTransformerIdentityImpl_createResultContentHandlerWithJavaxXmlTransformResult_
  12 MyApp -[OrgApacheXalanTransformerTransformerIdentityImpl transformWithJavaxXmlTransformSource:withJavaxXmlTransformResult:]
  13 MyApp MyClass_Document2StringWithOrgW3cDomDocument_ 

**Another stack trace:**
   0 libsystem_malloc.dylib malloc_zone_calloc
   1 libsystem_malloc.dylib calloc
   2 libobjc.A.dylib class_createInstance
   3 libobjc.A.dylib +[NSObject allocWithZone:]
   4 MyApp create_OrgApacheXmlSerializerNamespaceMappings_MappingRecord_initWithOrgApacheXmlSerializerNamespaceMappings_withNSString_withNSString_withInt_
   5 MyApp OrgApacheXmlSerializerNamespaceMappings_initNamespaces
   6 MyApp OrgApacheXmlSerializerNamespaceMappings_init
   7 MyApp new_OrgApacheXmlSerializerNamespaceMappings_init
   8 MyApp OrgApacheXmlSerializerToXMLStream_init
   9 MyApp -[OrgApacheXmlSerializerToXMLStream init]
  10 MyApp -[IOSConcreteClass newInstance]
  11 MyApp OrgApacheXmlSerializerSerializerFactory_getSerializerWithJavaUtilProperties_
  12 MyApp OrgApacheXalanTransformerTransformerIdentityImpl_createResultContentHandlerWithJavaxXmlTransformResult_
  13 MyApp -[OrgApacheXalanTransformerTransformerIdentityImpl transformWithJavaxXmlTransformSource:withJavaxXmlTransformResult:]
  14 MyApp MyClass_Document2StringWithOrgW3cDomDocument_ /Users/pleon/svn/trunk/client/java/src/org/ulteo/ovd/sm/SessionManagerCommunication.java:212

**Another stack trace:**
   0 libsystem_malloc.dylib malloc_zone_calloc
   1 libsystem_malloc.dylib calloc
   2 libobjc.A.dylib class_createInstance
   3 libobjc.A.dylib +[NSObject allocWithZone:]
   4 evaOS Client new_JavaUtilHashtable_HashtableEntry_initWithInt_withId_withId_withJavaUtilHashtable_HashtableEntry_
   5 MyApp -[JavaUtilHashtable putWithId:withId:]
   6 MyApp OrgApacheXmlSerializerNamespaceMappings_createPrefixStackWithNSString_
   7 MyApp OrgApacheXmlSerializerNamespaceMappings_initNamespaces
   8 MyApp OrgApacheXmlSerializerNamespaceMappings_init
   9 MyApp new_OrgApacheXmlSerializerNamespaceMappings_init
  10 MyApp OrgApacheXmlSerializerToXMLStream_init
  11 MyApp -[OrgApacheXmlSerializerToXMLStream init]
  12 MyApp -[IOSConcreteClass newInstance]
  13 MyApp OrgApacheXmlSerializerSerializerFactory_getSerializerWithJavaUtilProperties_
  14 MyApp OrgApacheXalanTransformerTransformerIdentityImpl_createResultContentHandlerWithJavaxXmlTransformResult_
  15 MyApp -[OrgApacheXalanTransformerTransformerIdentityImpl transformWithJavaxXmlTransformSource:withJavaxXmlTransformResult:]
  16 MyApp MyClass_Document2StringWithOrgW3cDomDocument_ /Users/pleon/svn/trunk/client/java/src/org/ulteo/ovd/sm/SessionManagerCommunication.java:212

**Document2String source code:** 
```
public static String Document2String(Document document) {
		DOMSource domSource = new DOMSource(document);
		StringWriter writer = new StringWriter();
		StreamResult result = new StreamResult(writer);
		TransformerFactory tf = TransformerFactory.newInstance();
		Transformer transformer;
		try {
			transformer = tf.newTransformer();
			transformer.transform(domSource, result);
		} catch (TransformerConfigurationException e) {
			logger.error(e);
			return null;
		} catch (TransformerException e) {
			logger.error(e);
			return null;
		}

		return writer.toString();
	}
```

Thank you and best regards!

**Comment by tomball** [comment]
This should be fixed in current source now. The fix was to change inner classes that don't reference the enclosing type to be static. This is a safe change to apply to other cycles if you find them, as the compiler will log errors if the inner class cannot be static.

A small benefit to this change is that static inner classes are slightly smaller and initialize slightly faster, because they no longer have an inner$ field (this is true for the JVM, Android and j2objc). Please submit a pull request if you'd like to fix the Xalan source for other places inner classes can be made static; whether or not it fixes a reference cycle, it's still a good code cleanup.
