### ISSUE TITLE
Retain Cycle in SynchronizedMap

### ISSUE THREAD

**Issue by flovilmart** [google/j2objc#958]
SynchronizedMap is leaking as it has a self reference through the mutex property.

https://github.com/google/j2objc/blob/master/jre_emul/android/platform/libcore/ojluni/src/main/java/java/util/Collections.java#L2293

**Comment by tomball** [comment]
Merged pull request #959. Thanks for your fix!

**Comment by flovilmart** [comment]
My pleasure!
