### ISSUE TITLE
Multicast socket doesn't work

### ISSUE THREAD

**Issue by sfuku7** [google/j2objc#962]
Hi

I'm trying to translate the software which uses multicast socket. The translation is successful but the the program doesn't work, SocketException is thrown at runtime.

Could you please give some advice ?

A part of code is below.

```
import java.io.IOException;
import java.net.InetAddress;
import java.net.MulticastSocket;
import java.net.InterfaceAddress;

public class MulticastTest {
    public static void main(String[] args) {

        try {
        InetAddress multicastAddress = InetAddress.getByName("239.255.255.250");
        MulticastSocket socket = new MulticastSocket(1900);
        socket.joinGroup(multicastAddress);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    private static final Class<?>[] unused = {
        InterfaceAddress.class,
    };
}
```

The log is below. The program run on Mac terminal app.

```
$ ./MulticastTest MulticastTest
java.net.SocketException: setsockopt IP_ADD_MEMBERSHIP failed
	at 0x0000000109b21421 MulticastTest.main() + 145
	at 0x0000000109b2137d MulticastTest.main() + 29
	at 0x0000000109de5ad2 java.lang.reflect.Method.invoke:object:() + 22
	at 0x0000000109de56fb java.lang.reflect.Method.invoke() + 333
```

Translate and compile as below.
revision of J2ObjC: 2933088a7e75e5fca2339fb01c4a56cc8dbf54c2

```
$ j2objc MulticastTest.java
$ j2objcc -c MulticastTest.m
$ j2objcc -g -o MulticastTest MulticastTest.o
```

**Comment by tomball** [comment]
Does your test run with Java? When I run it, I got the following:
```
$ java MulticastTest 
java.net.SocketException: Can't assign requested address
	at java.net.PlainDatagramSocketImpl.join(Native Method)
	at java.net.AbstractPlainDatagramSocketImpl.join(AbstractPlainDatagramSocketImpl.java:178)
	at java.net.MulticastSocket.joinGroup(MulticastSocket.java:323)
	at MulticastTest.main(MulticastTest.java:12)
```

Android's libcore library has a unit test for MulticastSocket, so I'll see if it reproduces the problem.

**Comment by sfuku7** [comment]
Thank you for the comment.

Yes, I run with Java as below.

```
$ java -Djava.net.preferIPv4Stack=true MulticastTest
```

I faced the same situation and I found below discussion.

https://stackoverflow.com/questions/18747134/getting-cant-assign-requested-address-java-net-socketexception-using-ehcache

**Comment by sfuku7** [comment]
Hi,
This issue is duplicated with #1061.
Above java program works fine, but executable translated and compiled by J2ObjC is not working.

**Comment by tomball** [comment]
FYI, Android doesn't reference the java.net.preferIPv4Stack property anywhere.
