### ISSUE TITLE
Java Proxy can not be casted to original Interface

### ISSUE THREAD

**Issue by hydro0** [google/j2objc#964]
When using Mockito for tests, mocked implementation can not be casted to the original interface.

> Cannot cast object of type `my/class/fqdm$Proxy5` to `my.class.fqdm`

Java Version `1.8.0_102`.
J2Objc Version `2.0.5`.

**Comment by sfuku7** [comment]
Hi

Is this issue reproduced with current code on the master branch ?

I found similar issue before and some fixes around Mockito are added to the master branch since 2.0.5 release.
So I recommend that you try with current code.

**Comment by antonio-cortes-perez** [comment]
Please reopen if the issue persists in the latest release.
