### ISSUE TITLE
Enum static functions - linker error when used in Swift (problem with inline function)

### ISSUE THREAD

**Issue by sarsonj** [google/j2objc#967]
Hi,

when using Java enums in Swift (static function style - like inline `ComGoogleColor *ComGoogleColor_get_RED();`), the compiler crash on linking - with message like:

Undefined symbol ComGoogleColor_initialize

I looked into code and macros that are used in generated code and it looks like, that when using Swift, compiler ignores "inline function thats calling another inline function" and compiles it, as the second function was not inline. This doesn't happen when using Objective-C. 

I also tried to make quick & dirty fix - just change `J2OBJC_ENUM_CONSTANT` macro body and not to call `CLASS##_initialize();` inline function but copy CLASS##_initialize() function content directly into macro (that is what should compiler do when using inline function, right?). With this 'fix' it works.

The workaround for Swift is to use --static-accessor-methods, then generated static accessors works. HOWEVER - the problem is with Protocol Buffer generator, that doesn't generate those static accessor methods.

Attached is example project, that demonstrates this problem on generated file from protoc - source .proto file is also included. Just set path in Config.xconfig to your j2objc release dir and try to compile to see the issue.
[enumexample.zip](https://github.com/google/j2objc/files/1892084/enumexample.zip)

**Comment by chrisvire** [comment]
We are also having this issue.  Where is the definition of initialize supposed to be coming from? We are trying to access "static final String" variable in a class. 

We have ended up using the INTERNAL ONLY static variable instead of the methods since `CLASS##_initialize` is not defined.

**Comment by tomball** [comment]
Are you building with j2objc's --swift-friendly flag? That sets the --class-properties, --static-accessor-methods and --nullability flags, all of which improve the headers j2objc generates to better support Swift importing. 

With these flags, you should use the imported Swift enum, not the C functions j2objc generates. Using your example, that means ComGoogleColor.RED, not ComGoogleColor_get_RED(). Here's how the ComGoogleColor enum is translated with the --swift-friendly flag:
```
package com.google;

public enum Color { RED, YELLOW, GREEN, BLUE; }
```
```
@interface ComGoogleColor : JavaLangEnum

@property (readonly, class, nonnull) ComGoogleColor *RED NS_SWIFT_NAME(RED);
@property (readonly, class, nonnull) ComGoogleColor *YELLOW NS_SWIFT_NAME(YELLOW);
@property (readonly, class, nonnull) ComGoogleColor *GREEN NS_SWIFT_NAME(GREEN);
@property (readonly, class, nonnull) ComGoogleColor *BLUE NS_SWIFT_NAME(BLUE);
...
```

**Comment by tomball** [comment]
The definition of the CLASS_initialize() functions is in the [J2OBJC_STATIC_INIT(CLASS) macro](https://github.com/google/j2objc/blob/master/jre_emul/Classes/J2ObjC_common.h#L167):
```
  FOUNDATION_EXPORT _Atomic(jboolean) CLASS##__initialized; \
  __attribute__((always_inline)) inline void CLASS##_initialize() { \
    if (__builtin_expect(!__c11_atomic_load(&CLASS##__initialized, __ATOMIC_ACQUIRE), 0)) { \
      [CLASS class]; \
    } \
  }
```
That function needs to be inline because it has to be called first from all static methods, since we cannot assume that the class's +initialize method has been invoked. That's not an issue in Swift if you generate with --swift-friendly, and use the imported enum constants and class properties.
