### ISSUE TITLE
J2Objc fails when generics type is used with @Property

### ISSUE THREAD

**Issue by sarsonj** [google/j2objc#969]
This code fails with:

error: internal error translating "/Users/sarsonj/Documents/work/ios/ttmonitor-common/src/com/tappytaps/ttm/backend/comm/messages/RecievedMessage.java"
java.lang.AssertionError: Cannot resolve qualified name for type: T
	at com.google.devtools.j2objc.util.TypeUtil.getQualifiedName(TypeUtil.java:735)
	at com.google.devtools.j2objc.gen.TypeDeclarationGenerator.findSetterMethod(TypeDeclarationGenerator.java:320)

```java
import com.google.j2objc.annotations.Property;
import com.google.protobuf.GeneratedMessageV3;

public class RecievedMessage<T extends GeneratedMessageV3> {

    @Property("readonly") private String from;
    @Property("readonly") private T message;

    public RecievedMessage(T message, String from) {
        this.from = from;
        this.message = message;
    }

    public T getMessage() {
        return message;
    }

    public String getFrom() {
        return from;
    }
}
```

When I remove `@Property` annotation for message, it works.

**Comment by tomball** [comment]
Fixed in current source.

**Comment by kiyos88** [comment]
still the latest release have the same issue can you update please

**Comment by tomball** [comment]
The latest release is more than 17 days old, so this fix cannot be part of it (that would violate the rules of time and space ;-).

[Here are the instructions for building from source.](https://developers.google.com/j2objc/guides/building-j2objc)
