### ISSUE TITLE
Change header template

### ISSUE THREAD

**Issue by hydro0** [google/j2objc#972]
Is that possible to change `file-header` value that is defined [here](https://github.com/google/j2objc/blob/master/translator/src/main/resources/com/google/devtools/j2objc/J2ObjC.properties)?

**Comment by tomball** [comment]
Of course, just edit it and rebuild (cd translator && make dist). What's the issue?

**Comment by hydro0** [comment]
Okay, thanks. The question was is it possible without rebuilding but seems it is not. Thanks.
