### ISSUE TITLE
error: package java.awt does not exist and so on

### ISSUE THREAD

**Issue by jkluolin3000** [google/j2objc#975]
I want to convert jlatexmath,but always error.
command line:
/Users/xx/j2objc-2.1.1/dist/j2objc -sourcepath /Users/luolin/j2objc-2.1.1/dist/jlatexmath `find /Users/xx/j2objc-2.1.1/dist/jlatexmath -name *.java` -d /Users/xx/j2objc-2.1.1/dist/jlatexmath_ios -classpath /Users/xx/j2objc-2.1.1/dist/jlatexmathclass

if use javac it is ok.
command line:
javac -sourcepath /Users/luolin/j2objc-2.1.1/dist/jlatexmath `find /Users/xx/j2objc-2.1.1/dist/jlatexmath -name *.java` -d /Users/xx/j2objc-2.1.1/dist/jlatexmath_ios -classpath /Users/xx/j2objc-2.1.1/dist/jlatexmathclass

my jdk version is: 1.8.0_172

waitting for help

**Comment by jkluolin3000** [comment]
luolindeMac-mini:~ luolin$ /Users/luolin/j2objc-2.1.1/dist/j2objc -sourcepath /Users/luolin/j2objc-2.1.1/dist/jlatexmath `find /Users/luolin/j2objc-2.1.1/dist/jlatexmath -name *java` -d /Users/luolin/j2objc-2.1.1/dist/jlatexmath_ios -classpath /Users/luolin/j2objc-2.1.1/dist/jlatexmathclass 
/Users/luolin/j2objc-2.1.1/dist/jlatexmath/Box.java:51: 错误: 程序包java.awt不存在
import java.awt.BasicStroke;
               ^
/Users/luolin/j2objc-2.1.1/dist/jlatexmath/Box.java:52: 错误: 程序包java.awt不存在
import java.awt.Color;
               ^
/Users/luolin/j2objc-2.1.1/dist/jlatexmath/Box.java:53: 错误: 程序包java.awt不存在
import java.awt.Graphics2D;
               ^
/Users/luolin/j2objc-2.1.1/dist/jlatexmath/Box.java:54: 错误: 程序包java.awt不存在
import java.awt.Stroke;
               ^
/Users/luolin/j2objc-2.1.1/dist/jlatexmath/Box.java:55: 错误: 程序包java.awt.geom不存在
import java.awt.geom.Rectangle2D;
                    ^
/Users/luolin/j2objc-2.1.1/dist/jlatexmath/HorizontalBox.java:49: 错误: 程序包java.awt不存在
import java.awt.Color;
               ^
/Users/luolin/j2objc-2.1.1/dist/jlatexmath/HorizontalBox.java:50: 错误: 程序包java.awt不存在
import java.awt.Graphics2D;
               ^
/Users/luolin/j2objc-2.1.1/dist/jlatexmath/VerticalBox.java:49: 错误: 程序包java.awt不存在
import java.awt.Graphics2D;
               ^
/Users/luolin/j2objc-2.1.1/dist/jlatexmath/Box.java:83: 错误: 找不到符号
    protected Color foreground;
              ^
  符号:   类 Color
  位置: 类 org.scilab.forge.jlatexmath.Box
/Users/luolin/j2objc-2.1.1/dist/jlatexmath/Box.java:89: 错误: 找不到符号
    protected Color background;
              ^
  符号:   类 Color
  位置: 类 org.scilab.forge.jlatexmath.Box
/Users/luolin/j2objc-2.1.1/dist/jlatexmath/Box.java:91: 错误: 找不到符号
    private Color prevColor; // used temporarily in startDraw and endDraw
            ^
  符号:   类 Color
  位置: 类 org.scilab.forge.jlatexmath.Box
/Users/luolin/j2objc-2.1.1/dist/jlatexmath/Box.java:125: 错误: 找不到符号
    protected Color markForDEBUG;
              ^
  符号:   类 Color
  位置: 类 org.scilab.forge.jlatexmath.Box
/Users/luolin/j2objc-2.1.1/dist/jlatexmath/Box.java:165: 错误: 找不到符号
    protected Box(Color fg, Color bg) {
                  ^
  符号:   类 Color
  位置: 类 org.scilab.forge.jlatexmath.Box
/Users/luolin/j2objc-2.1.1/dist/jlatexmath/Box.java:165: 错误: 找不到符号
    protected Box(Color fg, Color bg) {
                            ^
  符号:   类 Color
  位置: 类 org.scilab.forge.jlatexmath.Box
/Users/luolin/j2objc-2.1.1/dist/jlatexmath/Box.java:269: 错误: 找不到符号
    public abstract void draw(Graphics2D g2, float x, float y);
                              ^
  符号:   类 Graphics2D
  位置: 类 org.scilab.forge.jlatexmath.Box
/Users/luolin/j2objc-2.1.1/dist/jlatexmath/Box.java:286: 错误: 找不到符号
    protected void startDraw(Graphics2D g2, float x, float y) {
                             ^
  符号:   类 Graphics2D
  位置: 类 org.scilab.forge.jlatexmath.Box
/Users/luolin/j2objc-2.1.1/dist/jlatexmath/Box.java:301: 错误: 找不到符号
    protected void drawDebug(Graphics2D g2, float x, float y, boolean showDepth) {
                             ^
  符号:   类 Graphics2D
  位置: 类 org.scilab.forge.jlatexmath.Box
/Users/luolin/j2objc-2.1.1/dist/jlatexmath/Box.java:335: 错误: 找不到符号
    protected void drawDebug(Graphics2D g2, float x, float y) {
                             ^
  符号:   类 Graphics2D
  位置: 类 org.scilab.forge.jlatexmath.Box
/Users/luolin/j2objc-2.1.1/dist/jlatexmath/Box.java:346: 错误: 找不到符号
    protected void endDraw(Graphics2D g2) {
                           ^
  符号:   类 Graphics2D
  位置: 类 org.scilab.forge.jlatexmath.Box
/Users/luolin/j2objc-2.1.1/dist/jlatexmath/HorizontalBox.java:97: 错误: 找不到符号
    public HorizontalBox(Color fg, Color bg) {
                         ^
  符号:   类 Color
  位置: 类 org.scilab.forge.jlatexmath.HorizontalBox
/Users/luolin/j2objc-2.1.1/dist/jlatexmath/HorizontalBox.java:97: 错误: 找不到符号
    public HorizontalBox(Color fg, Color bg) {
                                   ^
  符号:   类 Color
  位置: 类 org.scilab.forge.jlatexmath.HorizontalBox
/Users/luolin/j2objc-2.1.1/dist/jlatexmath/HorizontalBox.java:108: 错误: 找不到符号
    public void draw(Graphics2D g2, float x, float y) {
                     ^
  符号:   类 Graphics2D
  位置: 类 org.scilab.forge.jlatexmath.HorizontalBox
/Users/luolin/j2objc-2.1.1/dist/jlatexmath/VerticalBox.java:113: 错误: 找不到符号
    public void draw(Graphics2D g2, float x, float y) {
                     ^
  符号:   类 Graphics2D
  位置: 类 org.scilab.forge.jlatexmath.VerticalBox
/Users/luolin/j2objc-2.1.1/dist/jlatexmath/TeXParser.java:48: 错误: 程序包java.awt不存在
import java.awt.Color;
               ^
/Users/luolin/j2objc-2.1.1/dist/jlatexmath/TeXFormula.java:51: 错误: 程序包java.awt不存在
import java.awt.Color;
               ^
/Users/luolin/j2objc-2.1.1/dist/jlatexmath/TeXFormula.java:52: 错误: 程序包java.awt不存在
import java.awt.Graphics2D;
               ^
/Users/luolin/j2objc-2.1.1/dist/jlatexmath/TeXFormula.java:53: 错误: 程序包java.awt不存在
import java.awt.GraphicsEnvironment;
               ^
/Users/luolin/j2objc-2.1.1/dist/jlatexmath/TeXFormula.java:54: 错误: 程序包java.awt不存在
import java.awt.Image;
               ^
/Users/luolin/j2objc-2.1.1/dist/jlatexmath/TeXFormula.java:55: 错误: 程序包java.awt不存在
import java.awt.Insets;
               ^
/Users/luolin/j2objc-2.1.1/dist/jlatexmath/TeXFormula.java:56: 错误: 程序包java.awt不存在
import java.awt.Toolkit;
               ^
/Users/luolin/j2objc-2.1.1/dist/jlatexmath/TeXFormula.java:57: 错误: 程序包java.awt.image不存在
import java.awt.image.BufferedImage;
                     ^
/Users/luolin/j2objc-2.1.1/dist/jlatexmath/TeXFormula.java:68: 错误: 程序包javax.imageio不存在
import javax.imageio.ImageIO;
                    ^
/Users/luolin/j2objc-2.1.1/dist/jlatexmath/TeXFormula.java:69: 错误: 程序包javax.imageio.stream不存在
import javax.imageio.stream.FileImageOutputStream;
                           ^
/Users/luolin/j2objc-2.1.1/dist/jlatexmath/TeXEnvironment.java:51: 错误: 程序包java.awt不存在
import java.awt.Color;
               ^
/Users/luolin/j2objc-2.1.1/dist/jlatexmath/DefaultTeXFont.java:49: 错误: 程序包java.awt不存在
import java.awt.Font;
               ^
/Users/luolin/j2objc-2.1.1/dist/jlatexmath/TeXIcon.java:52: 错误: 程序包java.awt不存在
import java.awt.Color;
               ^
/Users/luolin/j2objc-2.1.1/dist/jlatexmath/TeXIcon.java:53: 错误: 程序包java.awt不存在
import java.awt.Component;
               ^
/Users/luolin/j2objc-2.1.1/dist/jlatexmath/TeXIcon.java:54: 错误: 程序包java.awt不存在
import java.awt.Graphics;
               ^
/Users/luolin/j2objc-2.1.1/dist/jlatexmath/TeXIcon.java:55: 错误: 程序包java.awt不存在
import java.awt.Graphics2D;
               ^
/Users/luolin/j2objc-2.1.1/dist/jlatexmath/TeXIcon.java:56: 错误: 程序包java.awt不存在
import java.awt.Insets;
               ^
/Users/luolin/j2objc-2.1.1/dist/jlatexmath/TeXIcon.java:57: 错误: 程序包java.awt不存在
import java.awt.RenderingHints;
               ^
/Users/luolin/j2objc-2.1.1/dist/jlatexmath/TeXIcon.java:58: 错误: 程序包java.awt.geom不存在
import java.awt.geom.AffineTransform;
                    ^
/Users/luolin/j2objc-2.1.1/dist/jlatexmath/TeXIcon.java:60: 错误: 程序包javax.swing不存在
import javax.swing.Icon;
                  ^
/Users/luolin/j2objc-2.1.1/dist/jlatexmath/TeXIcon.java:71: 错误: 找不到符号
public class TeXIcon implements Icon {
                                ^
  符号: 类 Icon
/Users/luolin/j2objc-2.1.1/dist/jlatexmath/TeXFormula.java:803: 错误: 找不到符号
    public TeXIcon createTeXIcon(int style, float size, int type, Color fgcolor) {
                                                                  ^
  符号:   类 Color
  位置: 类 org.scilab.forge.jlatexmath.TeXFormula
/Users/luolin/j2objc-2.1.1/dist/jlatexmath/TeXFormula.java:827: 错误: 找不到符号
    public void createImage(String format, int style, float size, String out, Color bg, Color fg, boolean transparency) {
                                                                              ^
  符号:   类 Color
  位置: 类 org.scilab.forge.jlatexmath.TeXFormula
/Users/luolin/j2objc-2.1.1/dist/jlatexmath/TeXFormula.java:827: 错误: 找不到符号
    public void createImage(String format, int style, float size, String out, Color bg, Color fg, boolean transparency) {
                                                                                        ^
  符号:   类 Color
  位置: 类 org.scilab.forge.jlatexmath.TeXFormula
/Users/luolin/j2objc-2.1.1/dist/jlatexmath/TeXFormula.java:853: 错误: 找不到符号
    public void createPNG(int style, float size, String out, Color bg, Color fg) {
                                                             ^
  符号:   类 Color
  位置: 类 org.scilab.forge.jlatexmath.TeXFormula
/Users/luolin/j2objc-2.1.1/dist/jlatexmath/TeXFormula.java:853: 错误: 找不到符号
    public void createPNG(int style, float size, String out, Color bg, Color fg) {
                                                                       ^
  符号:   类 Color
  位置: 类 org.scilab.forge.jlatexmath.TeXFormula
/Users/luolin/j2objc-2.1.1/dist/jlatexmath/TeXFormula.java:857: 错误: 找不到符号
    public void createGIF(int style, float size, String out, Color bg, Color fg) {
                                                             ^
  符号:   类 Color
  位置: 类 org.scilab.forge.jlatexmath.TeXFormula
/Users/luolin/j2objc-2.1.1/dist/jlatexmath/TeXFormula.java:857: 错误: 找不到符号
    public void createGIF(int style, float size, String out, Color bg, Color fg) {
                                                                       ^
  符号:   类 Color
  位置: 类 org.scilab.forge.jlatexmath.TeXFormula
/Users/luolin/j2objc-2.1.1/dist/jlatexmath/TeXFormula.java:861: 错误: 找不到符号
    public void createJPEG(int style, float size, String out, Color bg, Color fg) {
                                                              ^
  符号:   类 Color
  位置: 类 org.scilab.forge.jlatexmath.TeXFormula
/Users/luolin/j2objc-2.1.1/dist/jlatexmath/TeXFormula.java:861: 错误: 找不到符号
    public void createJPEG(int style, float size, String out, Color bg, Color fg) {
                                                                        ^
  符号:   类 Color
  位置: 类 org.scilab.forge.jlatexmath.TeXFormula
/Users/luolin/j2objc-2.1.1/dist/jlatexmath/TeXFormula.java:873: 错误: 找不到符号
    public static Image createBufferedImage(String formula, int style, float size, Color fg, Color bg) throws ParseException {
                                                                                   ^
  符号:   类 Color
  位置: 类 org.scilab.forge.jlatexmath.TeXFormula
/Users/luolin/j2objc-2.1.1/dist/jlatexmath/TeXFormula.java:873: 错误: 找不到符号
    public static Image createBufferedImage(String formula, int style, float size, Color fg, Color bg) throws ParseException {
                                                                                             ^
  符号:   类 Color
  位置: 类 org.scilab.forge.jlatexmath.TeXFormula
/Users/luolin/j2objc-2.1.1/dist/jlatexmath/TeXFormula.java:873: 错误: 找不到符号
    public static Image createBufferedImage(String formula, int style, float size, Color fg, Color bg) throws ParseException {
                  ^
  符号:   类 Image
  位置: 类 org.scilab.forge.jlatexmath.TeXFormula
/Users/luolin/j2objc-2.1.1/dist/jlatexmath/TeXFormula.java:900: 错误: 找不到符号
    public Image createBufferedImage(int style, float size, Color fg, Color bg) throws ParseException {
                                                            ^
  符号:   类 Color
  位置: 类 org.scilab.forge.jlatexmath.TeXFormula
/Users/luolin/j2objc-2.1.1/dist/jlatexmath/TeXFormula.java:900: 错误: 找不到符号
    public Image createBufferedImage(int style, float size, Color fg, Color bg) throws ParseException {
                                                                      ^
  符号:   类 Color
  位置: 类 org.scilab.forge.jlatexmath.TeXFormula
/Users/luolin/j2objc-2.1.1/dist/jlatexmath/TeXFormula.java:900: 错误: 找不到符号
    public Image createBufferedImage(int style, float size, Color fg, Color bg) throws ParseException {
           ^
  符号:   类 Image
  位置: 类 org.scilab.forge.jlatexmath.TeXFormula
/Users/luolin/j2objc-2.1.1/dist/jlatexmath/TeXFormula.java:934: 错误: 找不到符号
    public TeXFormula setBackground(Color c) {
                                    ^
  符号:   类 Color
  位置: 类 org.scilab.forge.jlatexmath.TeXFormula
/Users/luolin/j2objc-2.1.1/dist/jlatexmath/TeXFormula.java:956: 错误: 找不到符号
    public TeXFormula setColor(Color c) {
                               ^
  符号:   类 Color
  位置: 类 org.scilab.forge.jlatexmath.TeXFormula
/Users/luolin/j2objc-2.1.1/dist/jlatexmath/TeXEnvironment.java:61: 错误: 找不到符号
    private Color background = null, color = null;
            ^
  符号:   类 Color
  位置: 类 org.scilab.forge.jlatexmath.TeXEnvironment
/Users/luolin/j2objc-2.1.1/dist/jlatexmath/TeXEnvironment.java:91: 错误: 找不到符号
    private TeXEnvironment(int style, TeXFont tf, Color bg, Color c) {
                                                  ^
  符号:   类 Color
  位置: 类 org.scilab.forge.jlatexmath.TeXEnvironment
/Users/luolin/j2objc-2.1.1/dist/jlatexmath/TeXEnvironment.java:91: 错误: 找不到符号
    private TeXEnvironment(int style, TeXFont tf, Color bg, Color c) {
                                                            ^
  符号:   类 Color
  位置: 类 org.scilab.forge.jlatexmath.TeXEnvironment
/Users/luolin/j2objc-2.1.1/dist/jlatexmath/TeXEnvironment.java:99: 错误: 找不到符号
    private TeXEnvironment(int style, float scaleFactor, TeXFont tf, Color bg, Color c, String textStyle, boolean smallCap) {
                                                                     ^
  符号:   类 Color
  位置: 类 org.scilab.forge.jlatexmath.TeXEnvironment
/Users/luolin/j2objc-2.1.1/dist/jlatexmath/TeXEnvironment.java:99: 错误: 找不到符号
    private TeXEnvironment(int style, float scaleFactor, TeXFont tf, Color bg, Color c, String textStyle, boolean smallCap) {
                                                                               ^
  符号:   类 Color
  位置: 类 org.scilab.forge.jlatexmath.TeXEnvironment
/Users/luolin/j2objc-2.1.1/dist/jlatexmath/TeXEnvironment.java:170: 错误: 找不到符号
    public Color getBackground() {
           ^
  符号:   类 Color
  位置: 类 org.scilab.forge.jlatexmath.TeXEnvironment
/Users/luolin/j2objc-2.1.1/dist/jlatexmath/TeXEnvironment.java:178: 错误: 找不到符号
    public Color getColor() {
           ^
  符号:   类 Color
  位置: 类 org.scilab.forge.jlatexmath.TeXEnvironment
/Users/luolin/j2objc-2.1.1/dist/jlatexmath/TeXEnvironment.java:265: 错误: 找不到符号
    public void setBackground(Color c) {
                              ^
  符号:   类 Color
  位置: 类 org.scilab.forge.jlatexmath.TeXEnvironment
/Users/luolin/j2objc-2.1.1/dist/jlatexmath/TeXEnvironment.java:273: 错误: 找不到符号
    public void setColor(Color c) {
                         ^
  符号:   类 Color
  位置: 类 org.scilab.forge.jlatexmath.TeXEnvironment
/Users/luolin/j2objc-2.1.1/dist/jlatexmath/FontInfo.java:49: 错误: 程序包java.awt不存在
import java.awt.Font;
               ^
/Users/luolin/j2objc-2.1.1/dist/jlatexmath/Char.java:49: 错误: 程序包java.awt不存在
import java.awt.Font;
               ^
/Users/luolin/j2objc-2.1.1/dist/jlatexmath/TeXIcon.java:73: 错误: 找不到符号
    private static final Color defaultColor = new Color(0, 0, 0);
                         ^
  符号:   类 Color
  位置: 类 org.scilab.forge.jlatexmath.TeXIcon
/Users/luolin/j2objc-2.1.1/dist/jlatexmath/TeXIcon.java:82: 错误: 找不到符号
    private Insets insets = new Insets(0, 0, 0, 0);
            ^
  符号:   类 Insets
  位置: 类 org.scilab.forge.jlatexmath.TeXIcon
/Users/luolin/j2objc-2.1.1/dist/jlatexmath/TeXIcon.java:84: 错误: 找不到符号
    private Color fg = null;
            ^
  符号:   类 Color
  位置: 类 org.scilab.forge.jlatexmath.TeXIcon
/Users/luolin/j2objc-2.1.1/dist/jlatexmath/TeXIcon.java:122: 错误: 找不到符号
    public void setForeground(Color fg) {
                              ^
  符号:   类 Color
  位置: 类 org.scilab.forge.jlatexmath.TeXIcon
/Users/luolin/j2objc-2.1.1/dist/jlatexmath/TeXIcon.java:131: 错误: 找不到符号
    public Insets getInsets() {
           ^
  符号:   类 Insets
  位置: 类 org.scilab.forge.jlatexmath.TeXIcon
/Users/luolin/j2objc-2.1.1/dist/jlatexmath/TeXIcon.java:141: 错误: 找不到符号
    public void setInsets(Insets insets, boolean trueValues) {
                          ^
  符号:   类 Insets
  位置: 类 org.scilab.forge.jlatexmath.TeXIcon
/Users/luolin/j2objc-2.1.1/dist/jlatexmath/TeXIcon.java:156: 错误: 找不到符号
    public void setInsets(Insets insets) {
                          ^
  符号:   类 Insets
  位置: 类 org.scilab.forge.jlatexmath.TeXIcon
/Users/luolin/j2objc-2.1.1/dist/jlatexmath/TeXIcon.java:244: 错误: 找不到符号
    public void paintIcon(Component c, Graphics g, int x, int y) {
                          ^
  符号:   类 Component
  位置: 类 org.scilab.forge.jlatexmath.TeXIcon
/Users/luolin/j2objc-2.1.1/dist/jlatexmath/TeXIcon.java:244: 错误: 找不到符号
    public void paintIcon(Component c, Graphics g, int x, int y) {
                                       ^
  符号:   类 Graphics
  位置: 类 org.scilab.forge.jlatexmath.TeXIcon
/Users/luolin/j2objc-2.1.1/dist/jlatexmath/FontInfo.java:88: 错误: 找不到符号
    private Font font;
            ^
  符号:   类 Font
  位置: 类 org.scilab.forge.jlatexmath.FontInfo
/Users/luolin/j2objc-2.1.1/dist/jlatexmath/FontInfo.java:306: 错误: 找不到符号
    public Font getFont() {
           ^
  符号:   类 Font
  位置: 类 org.scilab.forge.jlatexmath.FontInfo
/Users/luolin/j2objc-2.1.1/dist/jlatexmath/FontInfo.java:317: 错误: 找不到符号
    public static Font getFont(int id) {
                  ^
  符号:   类 Font
  位置: 类 org.scilab.forge.jlatexmath.FontInfo
/Users/luolin/j2objc-2.1.1/dist/jlatexmath/Char.java:57: 错误: 找不到符号
    private final Font font;
                  ^
  符号:   类 Font
  位置: 类 org.scilab.forge.jlatexmath.Char
/Users/luolin/j2objc-2.1.1/dist/jlatexmath/Char.java:61: 错误: 找不到符号
    public Char(char c, Font f, int fc, Metrics m) {
                        ^
  符号:   类 Font
  位置: 类 org.scilab.forge.jlatexmath.Char
/Users/luolin/j2objc-2.1.1/dist/jlatexmath/Char.java:76: 错误: 找不到符号
    public Font getFont() {
           ^
  符号:   类 Font
  位置: 类 org.scilab.forge.jlatexmath.Char
/Users/luolin/j2objc-2.1.1/dist/jlatexmath/OverUnderBox.java:49: 错误: 程序包java.awt不存在
import java.awt.Graphics2D;
               ^
/Users/luolin/j2objc-2.1.1/dist/jlatexmath/OverUnderBox.java:50: 错误: 程序包java.awt.geom不存在
import java.awt.geom.AffineTransform;
                    ^
/Users/luolin/j2objc-2.1.1/dist/jlatexmath/OverUnderBox.java:99: 错误: 找不到符号
    public void draw(Graphics2D g2, float x, float y) {
                     ^
  符号:   类 Graphics2D
  位置: 类 org.scilab.forge.jlatexmath.OverUnderBox
/Users/luolin/j2objc-2.1.1/dist/jlatexmath/FramedBox.java:48: 错误: 程序包java.awt不存在
import java.awt.BasicStroke;
               ^
/Users/luolin/j2objc-2.1.1/dist/jlatexmath/FramedBox.java:49: 错误: 程序包java.awt不存在
import java.awt.Color;
               ^
/Users/luolin/j2objc-2.1.1/dist/jlatexmath/FramedBox.java:50: 错误: 程序包java.awt不存在
import java.awt.Graphics2D;
               ^
/Users/luolin/j2objc-2.1.1/dist/jlatexmath/FramedBox.java:51: 错误: 程序包java.awt不存在
import java.awt.Stroke;
               ^
/Users/luolin/j2objc-2.1.1/dist/jlatexmath/FramedBox.java:52: 错误: 程序包java.awt.geom不存在
import java.awt.geom.Rectangle2D;
                    ^
/Users/luolin/j2objc-2.1.1/dist/jlatexmath/FramedBox.java:62: 错误: 找不到符号
    private Color line;
            ^
  符号:   类 Color
  位置: 类 org.scilab.forge.jlatexmath.FramedBox
/Users/luolin/j2objc-2.1.1/dist/jlatexmath/FramedBox.java:63: 错误: 找不到符号
    private Color bg;
            ^
  符号:   类 Color
  位置: 类 org.scilab.forge.jlatexmath.FramedBox
/Users/luolin/j2objc-2.1.1/dist/jlatexmath/FramedBox.java:75: 错误: 找不到符号
    public FramedBox(Box box, float thickness, float space, Color line, Color bg) {
                                                            ^
  符号:   类 Color
  位置: 类 org.scilab.forge.jlatexmath.FramedBox
/Users/luolin/j2objc-2.1.1/dist/jlatexmath/FramedBox.java:75: 错误: 找不到符号
    public FramedBox(Box box, float thickness, float space, Color line, Color bg) {
                                                                        ^
  符号:   类 Color
  位置: 类 org.scilab.forge.jlatexmath.FramedBox
/Users/luolin/j2objc-2.1.1/dist/jlatexmath/FramedBox.java:81: 错误: 找不到符号
    public void draw(Graphics2D g2, float x, float y) {
                     ^
  符号:   类 Graphics2D
  位置: 类 org.scilab.forge.jlatexmath.FramedBox

**Comment by tomball** [comment]
j2objc does not support UI classes, as described on its [main page](https://j2objc.org/). This means there is no support for java.awt or java.awt.geom classes, just like there is [no support for them in Android](https://developer.android.com/reference/packages).

The good news is that if you are porting an Android app, it doesn't actually depend on any of these classes. Android apps are compiled using the normal JDK (which has these classes), and an app that depends on them will fail with a ClassNotFoundException. If you have Android code that uses this library and doesn't fail when run, then you can port the same subset of classes using j2objc.

To only translate the classes you need from a library, add it to the source path, then translate your app's Java sources with j2objc's --build-closure flag. This flag translates all the files you explicitly tell it too, plus any dependencies it finds on the source path. The command might look like this:
```
/Users/xx/j2objc-2.1.1/dist/j2objc \
   -sourcepath /Users/luolin/j2objc-2.1.1/dist/jlatexmath 
   -d /Users/xx/j2objc-2.1.1/my_app my_app/*.java
```
Note: only put libraries on the classpath if they are translated in separate build steps.
