### ISSUE TITLE
FileOutputStream memory leak

### ISSUE THREAD

**Issue by chenjin0624** [google/j2objc#977]
Memory increases as files are written, even if the last file is closed and memory is not released.            

demo code:

            NSUInteger offset = 0;
            NSInteger chunkSize = 65535;
            NSFileHandle *handle = [NSFileHandle fileHandleForReadingAtPath:localPath];
            NSData *data = [handle readDataOfLength:chunkSize];
            FileOutputStream* outStream = new FileOutputStream;//test code
            while ([data length] > 0) {
                
                IOSByteArray* byteArray = [IOSByteArray arrayWithNSData:data];
                
                [outStream writeWithByteArray:byteArray withInt:0 withInt:(int)[data length]];
                
                offset += [data length];
                
                [handle seekToFileOffset:offset];
                
                data = [handle readDataOfLength:chunkSize];
            }

            [handle closeFile];
            
            [outStream close];
            
            outStream = nil;

**Comment by tomball** [comment]
Are you converting a lot of files in a loop? j2objc uses an autorelease pool to free objects, so running this code in a loop may not fall out of scope of the current autorelease pool, and so it keeps increasing.  If this is the case, you should put the above code inside an autoreleasepool { ... } block, so autoreleased objects are deallocated after each file is processed. 

To do this in Java code, put this code into a separate method, then annotate it with [@AutoreleasePool](https://developers.google.com/j2objc/javadoc/annotations/reference/com/google/j2objc/annotations/AutoreleasePool). [Here's an example where we do this in the JRE.](https://github.com/google/j2objc/blob/master/jre_emul/android/platform/libcore/luni/src/main/java/java/util/concurrent/ThreadPoolExecutor.java#L853)
