### ISSUE TITLE
The resource [ org.apache.xml.serializer.XMLEntities ] could not load

### ISSUE THREAD

**Issue by ganeshmca** [google/j2objc#979]
This is the simple extraction of the code which fails. It works fine in Java but in iOS it generates org.apache.xml.serializer.utils.WrappedRuntimeException. In the last line of code the exception is thrown.
Along with other properties file, XMLEntities.properties is also added a Resource in the XCode project.

Exception
org.apache.xml.serializer.utils.WrappedRuntimeException: The resource [ org.apache.xml.serializer.XMLEntities ] could not load: java.lang.RuntimeException: The resource [ org.apache.xml.serializer.XMLEntities ] could not be found.
 org.apache.xml.serializer.XMLEntities 
 org.apache.xml.serializer.XMLEntities 	 java.lang.RuntimeException: The resource [ org.apache.xml.serializer.XMLEntities ] could not be found.
 org.apache.xml.serializer.XMLEntities
	at 0x000000010ec6ef11 org.apache.xml.serializer.utils.WrappedRuntimeException.<init>() + 97
	at 0x000000010ec16763 org.apache.xml.serializer.SerializerFactory.getSerializer() + 3155
	at 0x000000010eb568db org.apache.xalan.transformer.TransformerIdentityImpl.createResultContentHandler() + 2443
	at 0x000000010eb573a6 org.apache.xalan.transformer.TransformerIdentityImpl.transform() + 54

Java Code
DocumentBuilderFactory documentBuilderFactory =DocumentBuilderFactory.newInstance();
DocumentBuilder documentBuilder = documentBuilderFactory.newDocumentBuilder();
Document document = documentBuilder.newDocument();
Element rootElement = document.createElement("MedicalSystem");
document.appendChild(rootElement);
rootElement.setAttribute("Version", "2.2.0");

TransformerFactory transformerFactory = TransformerFactory.newInstance();
Transformer transformer = transformerFactory.newTransformer();
transformer.setOutputProperty(OutputKeys.METHOD, "xml");
transformer.setOutputProperty(OutputKeys.INDENT, "yes");
transformer.setOutputProperty("{http://xml.apache.org/xslt}indent-amount", "2");
transformer.setOutputProperty("{http://xml.apache.org/xalan}content-handler", "org.apache.xml.serializer.ToXMLStream");

DOMSource source = new DOMSource(document);
StreamResult result =  new StreamResult(output);
transformer.transform(source, result);

J2OBJC Code
JavaxXmlParsersDocumentBuilderFactory *documentBuilderFactory = JavaxXmlParsersDocumentBuilderFactory_newInstance();
    JavaxXmlParsersDocumentBuilder *documentBuilder = [((JavaxXmlParsersDocumentBuilderFactory *) nil_chk(documentBuilderFactory)) newDocumentBuilder];
    id<OrgW3cDomDocument> document = [((JavaxXmlParsersDocumentBuilder *) nil_chk(documentBuilder)) newDocument];
    id<OrgW3cDomElement> rootElement = [((id<OrgW3cDomDocument>) nil_chk(document)) createElementWithNSString:@"MedicalSystem"];
    (void) [document appendChildWithOrgW3cDomNode:rootElement];
    [((id<OrgW3cDomElement>) nil_chk(rootElement)) setAttributeWithNSString:@"Version" withNSString:@"2.2.0"];
    [rootElement setAttributeWithNSString:@"CreationDate" withNSString:xmlCreationTime];
    [rootElement setAttributeWithNSString:@"GUID" withNSString:[((JavaUtilUUID *) nil_chk(JavaUtilUUID_randomUUID())) description]];
    JavaxXmlTransformTransformerFactory *transformerFactory = JavaxXmlTransformTransformerFactory_newInstance();
    JavaxXmlTransformTransformer *transformer = [((JavaxXmlTransformTransformerFactory *) nil_chk(transformerFactory)) newTransformer];
    [((JavaxXmlTransformTransformer *) nil_chk(transformer)) setOutputPropertyWithNSString:JavaxXmlTransformOutputKeys_METHOD withNSString:@"xml"];
    [transformer setOutputPropertyWithNSString:JavaxXmlTransformOutputKeys_INDENT withNSString:@"yes"];
    [transformer setOutputPropertyWithNSString:@"{http://xml.apache.org/xslt}indent-amount" withNSString:@"2"];
    [transformer setOutputPropertyWithNSString:@"{http://xml.apache.org/xalan}content-handler" withNSString:@"org.apache.xml.serializer.ToXMLStream"];
    JavaxXmlTransformDomDOMSource *source = new_JavaxXmlTransformDomDOMSource_initWithOrgW3cDomNode_(document);
    JavaxXmlTransformStreamStreamResult *result = new_JavaxXmlTransformStreamStreamResult_initWithJavaIoOutputStream_(output);
    [transformer transformWithJavaxXmlTransformSource:source withJavaxXmlTransformResult:result];

**Comment by tomball** [comment]
As previously explained, *all* Xalan properties files in org/apache/xml/serializer/ need to be [copied into the Resources section of your app's bundle](https://developers.google.com/j2objc/guides/java-resources#adding_resources_to_an_ios_app). Here, your app hasn't included the [XMLEntities.properties file](https://github.com/google/j2objc/blob/master/xalan/third_party/android/platform/external/apache-xml/src/main/java/org/apache/xml/serializer/XMLEntities.properties). There are 7 properties file in that directory, so add each of them to the Copy Files build phase, and check that the copy files Destination is Resources and the subpath is org/apache/xml/serializer/.

**Comment by ganeshmca** [comment]
As mentioned in the description all the 7 properties file were added as Resource with subpath org/apache/xml/serializer/.
