### ISSUE TITLE
Conflicting when 2 library is installed j2objc  on IOS Platform

### ISSUE THREAD

**Issue by thong91ptit** [google/j2objc#982]
Application of my install 2 library: GetSocial SDK and Deepstream.
when  running an error:
objc[3682]: Class JavaUtilRandom is implemented in both /Users/thongpro/Library/Developer/CoreSimulator/Devices/143E3C1D-4F14-45F5-8E0A-3E9A7D9C707E/data/Containers/Bundle/Application/AE0ECEFE-384D-4ADF-A38E-D041C8825A30/testGetsocial.app/Frameworks/GetSocial.framework/GetSocial (0x102b5fb00) and /Users/thongpro/Library/Developer/CoreSimulator/Devices/143E3C1D-4F14-45F5-8E0A-3E9A7D9C707E/data/Containers/Bundle/Application/AE0ECEFE-384D-4ADF-A38E-D041C8825A30/testGetsocial.app/testGetsocial (0x101674290). One of the two will be used. Which one is undefined.
objc[3682]: Class JavaUtilRandomAccess is implemented in both /Users/thongpro/Library/Developer/CoreSimulator/Devices/143E3C1D-4F14-45F5-8E0A-3E9A7D9C707E/data/Containers/Bundle/Application/AE0ECEFE-384D-4ADF-A38E-D041C8825A30/testGetsocial.app/Frameworks/GetSocial.framework/GetSocial (0x102b5fc68) and /Users/thongpro/Library/Developer/CoreSimulator/Devices/143E3C1D-4F14-45F5-8E0A-3E9A7D9C707E/data/Containers/Bundle/Application/AE0ECEFE-384D-4ADF-A38E-D041C8825A30/testGetsocial.app/testGetsocial (0x1016742e0). One of the two will be used. Which one is undefined.
objc[3682]: Class JavaUtilResourceBundle is implemented in both /Users/thongpro/Library/Developer/CoreSimulator/Devices/143E3C1D-4F14-45F5-8E0A-3E9A7D9C707E/data/Containers/Bundle/Application/AE0ECEFE-384D-4ADF-A38E-D041C8825A30/testGetsocial.app/Frameworks/GetSocial.framework/GetSocial (0x102b5fc90) and /Users/thongpro/Library/Developer/CoreSimulator/Devices/143E3C1D-4F14-45F5-8E0A-3E9A7D9C707E/data/Containers/Bundle/Application/AE0ECEFE-384D-4ADF-A38E-D041C8825A30/testGetsocial.app/testGetsocial (0x101674308). One of the two will be used. Which one is undefined.
objc[3682]: Class JavaUtilResourceBundle_MissingBundle is implemented in both /Users/thongpro/Library/Developer/CoreSimulator/Devices/143E3C1D-4F14-45F5-8E0A-3E9A7D9C707E/data/Containers/Bundle/Application/AE0ECEFE-384D-4ADF-A38E-D041C8825A30/testGetsocial.app/Frameworks/GetSocial.framework/GetSocial (0x102b5fd08) and /Users/thongpro/Library/Developer/CoreSimulator/Devices/143E3C1D-4F14-45F5-8E0A-3E9A7D9C707E/data/Containers/Bundle/Application/AE0ECEFE-384D-4ADF-A38E-D041C8825A30/testGetsocial.app/testGetsocial (0x101674380). One of the two will be used. Which one is undefined.
objc[3682]: Class JavaUtilResourceBundle_Control is implemented in both /Users/thongpro/Library/Developer/CoreSimulator/Devices/143E3C1D-4F14-45F5-8E0A-3E9A7D9C707E/data/Containers/Bundle/Application/AE0ECEFE-384D-4ADF-A38E-D041C8825A30/testGetsocial.app/Frameworks/GetSocial.framework/GetSocial (0x102b5fd30) and /Users/thongpro/Library/Developer/CoreSimulator/Devices/143E3C1D-4F14-45F5-8E0A-3E9A7D9C707E/data/Containers/Bundle/Application/AE0ECEFE-384D-4ADF-A38E-D041C8825A30/testGetsocial.app/testGetsocial (0x1016743a8). One of the two will be used. Which one is undefined.
...
How do fix it?

**Comment by tomball** [comment]
This is not a j2objc-specific problem. Your log shows that there appear to be two copies of the GetSocial library being linked together, one in the GetSocial.framework, and one in the testGetsocial.app. Recheck your linker flags, maybe remove any -ObjC flag (I don't know, as I've never worked with GetSocial). 

If you continue to have problems, use [GetSocial's support contact page](https://www.getsocial.im/contact-us/).
