### ISSUE TITLE
Morph NSException into a Throwable

### ISSUE THREAD

**Issue by tux-mind** [google/j2objc#986]
Hello there, as always thank you for this great project!

I have a logger that is shared between Java and Objective-C.
Sadly I am not able to use it to log native exceptions, as explained in #897 .

I was trying to create a `JavaLangThrowable` and assigning to it a `null` value to `stackTrace` and the `NSException` backtrace to `backtrace`.  This, according to [Throwable.java](https://github.com/google/j2objc/blob/2.0.4.1/jre_emul/android/platform/libcore/ojluni/src/main/java/java/lang/Throwable.java#L832) shall make it works.

Sadly I'm not able to find out hot to get the native stacktrace out of the current `NSException`, do you have any clue? is my idea feasible?

All the best, tuxmind.

**Comment by tomball** [comment]
You might try [NSException callStackReturnAddresses] ([doc](https://developer.apple.com/documentation/foundation/nsexception/1412165-callstackreturnaddresses?language=objc)), and then call [StackTraceElement(long address)](https://github.com/google/j2objc/blob/master/jre_emul/Classes/java/lang/StackTraceElement.java#L69) for each return address.

**Comment by tomball** [comment]
Or add the NSException's stack trace to its description when logging it, using [NSException callStackSymbols]. It won't create an identical log message, but will give you the diagnostic information you need.

**Comment by tux-mind** [comment]
Thank you for your help. 
I'm sharing what I've done, it might be useful to someone, cheers!

```objc
#include <Foundation/Foundation.h>

#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "java/lang/Boolean.h"
#include "java/lang/ThreadLocal.h"
#include "java/lang/Throwable.h"
#include "java/lang/StackTraceElement.h"

extern jarray Java_java_lang_Throwable_nativeGetStackTrace(JNIEnv *_env_, jclass _cls_, jobject stackState);

@interface RawStack : NSObject {
@public
    void **frames_;
    unsigned count_;
}
@end

@implementation RawStack (NSException)

- (instancetype)initWithBacktrace: (NSArray<NSNumber *> *)backtrace {
    NSObject_init(self);
    
    self->count_ = (unsigned int) backtrace.count;
    unsigned nBytes = self->count_ * sizeof(void *);
    self->frames_ = (void **)malloc(nBytes);
    
    for (unsigned i = 0; i < backtrace.count; i++) {
        self->frames_[i] = (void *) [backtrace[i] unsignedIntegerValue];
    }
    
    return self;
}

- (instancetype)initWithException: (NSException *)ex {
    return [self initWithBacktrace:[ex callStackReturnAddresses]];
}

@end

@interface JavaLangThrowableAdapter : JavaLangThrowable {
@public
    NSString *nativeExceptionName_;
}
@end

@implementation JavaLangThrowableAdapter

-(NSString *)description {
    /* Original code
     String s = getClass().getName();
     String message = getLocalizedMessage();
     return (message != null) ? (s + ": " + message) : s;
     */
    NSString *s = self->nativeExceptionName_;
    NSString *message = [self getLocalizedMessage];
    return (message != nil) ? [NSString stringWithFormat:@"%@: %@", s, message] : s;
}

@end

JavaLangThrowable *convertNativeException(NSException *e) {
    RawStack *rawStack = [[RawStack alloc] initWithException:e];
    jarray stackTrace = Java_java_lang_Throwable_nativeGetStackTrace(nil, nil, rawStack);
    
    JavaLangThrowableAdapter *throwable = [[JavaLangThrowableAdapter alloc] initWithNSString:[e description]];
    
    throwable->nativeExceptionName_ = [e name];
    
    [throwable setStackTraceWithJavaLangStackTraceElementArray:(IOSObjectArray *) stackTrace];
    
    return (JavaLangThrowable *)throwable;
}
```
