### ISSUE TITLE
Externalization support [moved]

### ISSUE THREAD

**Issue by kstanger** [google/j2objc#99]
This is [Issue 99](https://code.google.com/p/j2objc/issues/detail?id=99) moved from a Google Code project.
Added on 2012-11-22T22:17:24.000Z by [j...@h-code.com](http://code.google.comhttps://code.google.com/u/117032527489985545520/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Low

**Comment by tomball** [comment]
Implemented.
